### ISSUE TITLE
Icon for Scilab

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#1012]
Hi, there is no numix-circle icon for Scilab (open source scientific package for numerical computations).
[http://www.scilab.org/](http://www.scilab.org/)

The icon is hardcoded to:
Icon=/usr/share/scilab/icons/scilab.xpm

Original icon, quite low resolution:
![scilab](https://cloud.githubusercontent.com/assets/7050624/3717832/9fdd27a6-162c-11e4-908d-c93c0c3ebf4b.png)

There are additional launchers for "Scilab CLI" (Exec=scilab-cli) and "Scilab advanced CLI" (Exec=scilab-adv-cli) which also refer to:

Icon=/usr/share/scilab-cli/icons/scilab.xpm

**Comment by gusbemacbr** [comment]
Scilab doesn't appear in the last version of Numix Circle Icons Theme in Ubuntu 14.04 with Trenta-theme installed.

**Comment by palob** [comment]
@gusbemacbr How did you install the Numix Circle icons?
Can you look up the icon line (Icon=...) in the .desktop file (located in /usr/share/applications)?

**Comment by gusbemacbr** [comment]
Hello, sory, I was busy with the university

I added Numix-Circle's PPA. It's hosted in /usr/share/icon. 

Follow:

` ` ` [Desktop Entry]
....
Icon=scilab
MimeType=application/x-scilab-sci;application/x-scilab-sce;application/x-scilab-tst;application/x-scilab-dem;application/x-scilab-sod;application/x-scilab-xcos;application/x-scilab-zcos;application/x-scilab-bin;application/x-scilab-cosf;application/x-scilab-cos;
Name=Scilab
StartupNotify=false
Terminal=false
Type=Application
Categories=Science;Math;

` ` `

**Comment by palob** [comment]
That's strange. As far as I know, the PPA is up to date so that there should be the *scilab.svg* file.

**Comment by bil-elmoussaoui** [comment]
@palob i dont think that the ppa is up to date, i didnt receive to many icons that have been added days ago

**Comment by Foggalong** [comment]
Easy way to check - go to `/usr/share/icons/Numix-Circle/48x48/apps/` and look for `scilab.svg`. If it's not there, you're not running the latest version.
