### ISSUE TITLE
Icon for Stargunner

### ISSUE THREAD

**Issue by rstreeter** [numixproject/numix-core#1029]
The icon name in the desktop file is gog-stargunner
![screenshot at 14-23-11](https://cloud.githubusercontent.com/assets/500779/3770229/26cb38da-18e8-11e4-80c6-eca74a19530d.png) This is what the icon looks like 

Thank you
##

**Comment by hlechner** [comment]
Hello @rstreeter, could you please give us the full content of the **gog-stargunner.desktop** or **gog-stargunner-primary.desktop**?

I've tried to find it on my own, but I don't have the gog file to check it.
Thanks!

**Comment by rstreeter** [comment]
[Desktop Entry]
Version=1.0
Name=Stargunner
Comment=Stargunner (GOG.com)
Exec=gog-stargunner
Icon=gog-stargunner
Terminal=false
Type=Application
Categories=Game;
X-Desktop-File-Install-Version=0.22


This is from the desktop file.
