### ISSUE TITLE
Icon for Trello (Chrome App)(Draft included)

### ISSUE THREAD

**Issue by jhrdina** [numixproject/numix-core#1139]
**Name:** Trello
**Web:** https://trello.com/
**Chrome Store:** https://chrome.google.com/webstore/detail/trello/oflhioojkbelepjlnafgmgkkjhojphcg
**My circle icon draft** (feel free to use it): https://mediacru.sh/i4zpU3vTNeDH

**Original icon:**
![icon](https://cloud.githubusercontent.com/assets/1280734/4232590/d914da2e-399e-11e4-8442-c960f5c2286b.png)

**Comment by simondubois** [comment]
@jhrdina Thank you for your nice circle icon. I have used it for months and find it really nice.
However, I have just moved to the numix-icon-square but it does not include any Trello icon.
Is there any chance for you to share a square icon in the same shape tone than the circle one ?
Thank you for your sharing,
Simon
