### ISSUE TITLE
Icon for Syncthing-GTK

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#1369]
Syncthing-GTK, a desktop GUI for the Open Source sync/cloud service.
https://github.com/syncthing/syncthing-gtk

AUR Build:
Icon=/usr/share/syncthing-gtk/icons/st-logo-128.png
![st-logo-128](https://cloud.githubusercontent.com/assets/7050624/5349534/f0101d7a-7f39-11e4-8b68-c522326f42c5.png)

**Comment by allanbreyes** [comment]
Looks like Syncthing-GTK fixed the hardcoded issue, and this can be reopened.

https://github.com/syncthing/syncthing-gtk/issues/119

Would love a fix for this, especially the nautilus integration icons:

![image](https://cloud.githubusercontent.com/assets/7947900/8635952/64c6a3f0-2809-11e5-8e37-6f5f9114f9b6.png)

and the appindicator icons.

**Comment by palob** [comment]
@allanbreyes So what you're asking for is a Numix icon for the folder emblem?
Actually this would be an issue for the base theme?

Could you try to find the original icon name?
It might be stored in ``/usr/share/icons/hicolor/"size"/emblems``.
Otherwise just search for all files named ``syncthing`` and watch out for icon files.

**Comment by allanbreyes** [comment]
Ah, it's actually in `/usr/share/pixmaps`.  Thanks for clarifying!

No idea about the app indicator icons in the panel.

**Comment by palob** [comment]
The [elementary plus](https://github.com/mank319/elementaryPlus) icon set has got panel icons for Syncthing called ``si-idle``, ``si-syncing-...`` and ``si-unknown``.

Could you try to locate them on your machine and file an issue against the [Numix base theme](https://github.com/numixproject/numix-icon-theme)?

**Comment by allanbreyes** [comment]
Will do.  Thanks @palob !
