### ISSUE TITLE
Icon for Hearthstone

### ISSUE THREAD

**Issue by SM83** [numixproject/numix-core#2137]
Hearthstone needs an icon - the 64x64 one looks pretty bad in the icon switcher. It runs through wine, so no desktop file.

Icon:
![hearthstone](https://cloud.githubusercontent.com/assets/11599280/7671770/dc29cf34-fca9-11e4-8bb1-65fcb2640d2e.png)
##

**Comment by Foggalong** [comment]
Same was with LoL [here](https://github.com/numixproject/numix-icon-theme-circle/issues/1086) we only do WINE stuff if it's a popular request. Get 5 "+1"s and we'll switch it to a request.

**Comment by Eleuin** [comment]
ill +1 this

**Comment by mralext20** [comment]
add another +1

**Comment by mralext20** [comment]
@Foggalong if someone makes an icon that follows the guidelines, can it be added even without 5 "+1"s?

**Comment by asdrubalsantander** [comment]
+1!!!!

**Comment by Rolandocmr** [comment]
aigth +1

**Comment by DanielRS** [comment]
We need this! +1

**Comment by Foggalong** [comment]
Congrats guys, you got enough to turn this into a request :D

**Comment by rickinbsb** [comment]
this vectored version could be used as reference if wanted http://uxrepo.com/icon/hearthstone-by-dr-slash

**Comment by Foggalong** [comment]
We can use it as a reference, but can't use any code/shapes/etc from that icon since its license doesn't allow for commercial usage.

**Comment by W-Floyd** [comment]
Here's what I've got so far, just need someone to get the correct icon name for the data entry.

![iconified_hearthstone](https://user-images.githubusercontent.com/11786132/34103668-5323dee4-e439-11e7-8d4d-4e3ada61f7e3.png)

**Comment by Foggalong** [comment]
@W-Floyd Just go with `hearthstone.svg` :)
