### ISSUE TITLE
Icon for Android Studio

### ISSUE THREAD

**Issue by markojic** [numixproject/numix-core#214]
There's no icon for android studio in numix-circle.
The icon line says "icon.png" and the original icon is attached.
![icon](https://f.cloud.github.com/assets/5999694/1930368/5a55f16e-7eaa-11e3-8360-a2b02a776ce9.png)

**Comment by domdomegg** [comment]
@me4oslav It's "Icon=androidstudio", no extra 't'

My .desktop file on Ubuntu:

`
[Desktop Entry]
Version=1.0
Name=Android Studio
X-GNOME-FullName=Android Studio
Comment=Android Studio IDE
Type=Application
Categories=Development;IDE;
Exec="/home/adam/Applications/android-studio/bin/studio.sh" %f
Terminal=false
StartupNotify=true
Icon=androidstudio
StartupWMClass=jetbrains-android-studio
`
