### ISSUE TITLE
Icon for fcitx

### ISSUE THREAD

**Issue by gzjjrp** [numixproject/numix-core#2166]
Icon=fcitx
![fcitx](https://cloud.githubusercontent.com/assets/9773849/7786713/545fdd00-0212-11e5-9fef-a49fec7b6fc7.png)

**Comment by Foggalong** [comment]
We have an icon which was created to a similar specification as this, so I'll see if I can find it and symlink it up.

**Comment by wa4557** [comment]
`distributor-logo-lfs`?

**Comment by Foggalong** [comment]
Couldn't remember what it was so just hooked it up to the generic paint icon :)

**Comment by palob** [comment]
Isn't it an input method for Asian languages?
https://fcitx-im.org/wiki/Fcitx
https://en.wikipedia.org/wiki/Fcitx

**Comment by Foggalong** [comment]
Wtf app creators. Wtf.

**Comment by Foggalong** [comment]
This issue got closed when we were trying to sort the PPA which is why #2781 was posted. Reopening this one :)

**Comment by palob** [comment]
In the [deepin icon theme](https://github.com/linuxdeepin/deepin-icon-theme) the icon looks like this:
![fcitx](https://cloud.githubusercontent.com/assets/7050624/12432979/b0840256-befe-11e5-8da7-682ce9318a68.png)

**Comment by Foggalong** [comment]
I like that idea :+1:
