### ISSUE TITLE
More Distributor Logos

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#2183]
I use our distributor logos for users flairs over in [/r/unixporn](https://www.reddit.com/r/unixporn). For that reason I'll probably be adding these new icons in the near future. Note that there are some flairs that aren't currently logos and vis versa so I'll make things equal before I start off on this.
- [x] Aix
- [x] Android
- [x] Antergos
- [x] Antix
- [x] Arch
- [x] Arya
- [x] Archbang
- [x] Backbox
- [x] Bodhi
- [x] BSD
- [x] CentOS
- [x] Chakra
- [x] Chalet OS
- [x] ConnochaetOS
- ~~[ ] CrunchBang~~
- [x] Crux
- [x] Cub Linux
- [x] Debian
- [x] Deepin
- [x] DragonFly BSD
- [x] elementary OS
- [x] Endless OS
- [x] Exherbo
- [x] Fedora
- [x] FreeBSD
- [x] Funtoo
- [x] Gentoo
- [x] GhostBSD
- [x] GNU
- [x] GuixSD
- [x] HandyLinux
- [x] Illumos
- [x] Kali
- [x] KaOS
- [x] KDE Neon
- [x] Korora
- [x] Kubuntu
- [x] LFS
- [x] Lite
- [x] Linux
- [x] LMDE
- [x] Lubuntu
- [x] LXLE
- [x] Mageia
- [x] Manjaro
- [x] Maui
- [x] Mint
- [x] MS-DOS
- [x] MX Linux
- [x] NetBSD
- [x] NixOS
- [x] OpenBSD
- [x] OpenIndiana
- [x] OpenMandriva
- ~~[ ] Open Solaris~~
- [x] openSUSE
- [x] OSX
- [x] Parabola
- [x] Parsix
- [x] PC-BSD
- [x] PCLinuxOS
- [x] Peppermint
- ~~[ ] PiBang~~
- [x] Plan 9
- [x] Puppy
- [x] Qubes
- [x] Raspbian
- [x] Red Hat
- [x] Rosa
- [x] Sabayon
- [x] Salix
- [x] Scientific Linux
- [x] Siduction
- ~~[ ] Simplicity~~
- [x] Slackware
- [x] SmartOS
- [x] Solaris (Oracle)
- [x] Solaris (Sun)
- [x] Solus
- [x] SparkyLinux
- [x] Tails
- [x] Tanglu
- [x] Trisquel
- [x] TrueOS
- [x] Ubuntu
- [x] Ubuntu Budgie
- [x] Ubuntu GNOME
- [x] Ubuntu MATE
- [x] Ultimate
- [x] Void
- [x] Voyager
- [x] Windows
- [x] Xubuntu
- [x] Zorin
##

**Comment by gregorydk** [comment]
Can you add Solus (https://solus-project.com/) and Papyros (http://papyros.io/)?

**Comment by Foggalong** [comment]
Maybe after they've actually released OSs and finalised their branding, yeah. Up to now they've both undergone multiple rebrandings which would make me reluctant to invest time into an icon that might change 

Obviously, if you want to stick a bounty on this issue then I'd be more than happy to change my mind ;)

**Comment by bil-elmoussaoui** [comment]
[Solus 1.0 released](https://solus-project.com/2015/12/27/solus-1-0-released/)

**Comment by W-Floyd** [comment]
Crux may be marked off as of #3968

[Funtoo has no set logo.](https://www.funtoo.org/Artwork) - I'd rather let them settle first, I don't think their current one is very striking.

**Comment by W-Floyd** [comment]
What should we do about the "Linux" entry, symlink with LFS?

Same with LMDE, they have no specific logo, so I say symlink to the Mint icon.

**Comment by W-Floyd** [comment]
OpenSolaris has been discontinued, as of 8 years ago. Not really going to happen.

As for OSX, are we going to make a distinction between Mac OSX / OSX / macOS? So far as I can tell, the [current High Sierra icon](https://pbs.twimg.com/profile_images/879699604907765760/NYFOQkDV.jpg) is more of a picture than a logo, the general macOS logo is pretty much just [text on a circle](https://upload.wikimedia.org/wikipedia/commons/2/22/MacOS_logo_%282017%29.svg), while their [official branding guide](https://developer.apple.com/softwarelicensing/agreements/maclogo.php) is out of date, still refering to OSX. Clearly something needs to be made, but guidance would be appreciated.

**Comment by W-Floyd** [comment]
[Pibang's domain](http://pibanglinux.com/) has been parked, [latest files](https://sourceforge.net/projects/pibang/files/) are 4 years old. Not going to happen.

As for Pibean, do you mean Raspbian? The only places I see Pibean referenced is this list.

**Comment by W-Floyd** [comment]
Simplicity seems inactive since July last year. Not quite sure, so I wouldn't discount it yet, but all the same, I'm skipping it for now.

**Comment by W-Floyd** [comment]
All PR'ed, minus:
* Funtoo (No set logo yet)
* Linux (Symlink with LFS perhaps?)
* LMDE (Symlink with Mint perhaps?)
* Open Solaris (Well and truly 8 years dead)
* OSX (No set logo? Should we do Mac OSX / OSX / macOS?).
* Pibang (Domain is parked, last update 4 years ago)
* Pibean (I think Raspbian was meant)
* Simplicity (Seems inactive)

**Comment by bilelmoussaoui** [comment]
@Foggalong What do you think about this?

**Comment by Foggalong** [comment]
* For Funtoo, maybe just do the Gentoo logo in the Funtoo colours
* Yeah that'd be fine
* Mint logo in Debian colours
* Cool, removed it
* Use [the Mac logo](https://developer.apple.com/softwarelicensing/agreements/maclogo.php)
* Removed Pibang
* Switched to Raspbian
* Removed Simplicity

**Comment by W-Floyd** [comment]
If those are merged, this should be done :+1:

**Comment by Foggalong** [comment]
:heart: :christmas_tree:
