### ISSUE TITLE
Icon for StarUML

### ISSUE THREAD

**Issue by delacruzbordajn** [numixproject/numix-core#2185]
A Numix-Circle Icon for StarUML is missing 

[Desktop Entry]
Name=StarUML
Type=Application
Categories=Development
Exec=/opt/staruml/staruml %U
Icon=staruml
MimeType=text/html;
Keywords=Design;Modeling;Development;UML;
![staruml_icon_by_funkmasterta-d2xh4wo](https://cloud.githubusercontent.com/assets/3194614/7852575/1c38abfc-04d6-11e5-8907-3803e9a142b7.png)
##

**Comment by delacruzbordajn** [comment]
any notice?

**Comment by Foggalong** [comment]
@delacruzbordajn Sorry for the big delay in replying! What sort of collaboration did you have in mind?

**Comment by delacruzbordajn** [comment]
Any news about this?

**Comment by Foggalong** [comment]
Issues take a while to fix these days, and there are ones older than yours still in line. Sorry

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by Foggalong** [comment]
Please convert that +1 to a reaction on the original issue, then I will delete both your comment and this one. This prevents the issue tracker being clogged up with +1s

**Comment by bil-elmoussaoui** [comment]
Done

**Comment by nico-dela** [comment]
News?

**Comment by palob** [comment]
Can you please open a pull request, @boosterdev?
