### ISSUE TITLE
Icon for Torchlight II (steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-core#2255]
Game: **Torchlight II**
Game ID: [200710](https://steamdb.info/app/200710/)
Description: **RPG game**
Icon:
![image](https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/200710/178d0b01acdae4a1a68e5b2b40d61903e5075092.ico)

```
Icon=steam_icon_200710
```
##

**Comment by Foggalong** [comment]
The icon at a more reasonable size :P

![images duckdu2ckgo com](https://cloud.githubusercontent.com/assets/5920259/8890038/dd54383e-32e8-11e5-99d2-7e4d80c404fb.jpeg) ![images duckduckgo com](https://cloud.githubusercontent.com/assets/5920259/8890039/dd5eef2c-32e8-11e5-94cf-84e90bb09eed.jpeg)
