### ISSUE TITLE
Tray icon for qBittorrent

### ISSUE THREAD

**Issue by anthonyhuben** [numixproject/numix-core#233]
A numix-circle icon for the tray icon for qbittorrent is missing.
I don't know if you can change the tray icon, but if you can that would be amazing!

(It uses the numix-circle icon for it, but it would be nice to have a separate icon that matches the design characteristics of Transmission's tray icon.)

**Comment by sl-codenine** [comment]
On gnome 3.14 qBitTorrent icon works a bit strange (just in the applications notification bar). It sometimes work ok - i mean the size is ok and actual icon too. But sometimes it's not. In most cases it shows a small, original qBT icon, and sometimes just nothing, empty space.

In any different scenario i would say it's probably some problem on my side, but i have totally fresh (from yesterday) install.

Ubuntu 14.10 / gnome 3.14 from gnome-team.

(this highlighted area is qBitTorrent icon)

![screenshot from 2015-04-04 23 00 10](https://cloud.githubusercontent.com/assets/6673789/6994575/a9aadaf0-db1e-11e4-8dd0-cbd66612214c.png)

**Comment by bil-elmoussaoui** [comment]
This should be fixed soon as the monochrome icons are now in Numix base instead of Numix-Circle Icon theme.

**Comment by sl-codenine** [comment]
I see, so in fact icons for copy and rythmbox are incorrect too, and there should be monochrome icons in notifications bar?

Anyway - great. Looking forward for this fix :)

**Comment by bil-elmoussaoui** [comment]
qBittorrent has already a monochrome icon as its used in other linux desktops (Unity for ex). For Rhythmbox and copy its normal as its only a notification and not a tray icon.
