### ISSUE TITLE
Icon for "This War of Mine" (Steam)

### ISSUE THREAD

**Issue by zipainz** [numixproject/numix-core#2345]
Game: This War of Mine
AppID: 282070
Icon: http://www.loadthegame.com/wp-content/uploads/2014/11/This_war_of_mine_header-620x330.jpg

Though the text might be to boring for a designer to work with. There was no icon in the steam folder, so I just found a picture with the text and a bit of enviorment on.

Notes: It's a game about surviving in the war. You control a few charracters in a abandoned and ruined house and you have to make sure to keep them alive by gathering and crafting.
##

**Comment by Foggalong** [comment]
I love this game, but it's suddenly stopped working for me after an update a few months ago :(

**Comment by zipainz** [comment]
I just bought it yesterday during the steam summersale to have something to kill time with at work when things are calm. Plays perfectly fine in ubuntu 14.04

**Comment by ChuckDaniels87** [comment]
This is an interesting icon to design. I'll buy this game as soon is on a nice steam sale. :smile:

**Comment by maxtron95** [comment]
@palob What do you think of this icon draft? I based the icon off of the handprint that is found on the logo.
![this-war-of-mine-sq svg](https://user-images.githubusercontent.com/53346722/72486902-e6e9dc80-37d1-11ea-94fd-f322fec092f6.png)
![this-war-of-mine-ci svg](https://user-images.githubusercontent.com/53346722/72486881-d89bc080-37d1-11ea-8d77-419a4dce7b1d.png)

[this-war-of-mine-draft.tar.gz](https://github.com/numixproject/numix-core/files/4068958/this-war-of-mine-draft.tar.gz)

![This_war_of_mine_header-620x330](https://user-images.githubusercontent.com/53346722/72486968-1d275c00-37d2-11ea-8b59-14114742db7e.jpg)

**Comment by palob** [comment]
Thanks, looking forward to a PR. For both icons the symbol should be moved 1px to the left.

**Comment by palob** [comment]
@creepertron95 Still interested?

**Comment by maxtron95** [comment]
@palob I am still interested but I have to wait until #5009 is merged as I have pushed that icon into the master branch of my fork. Meanwhile, I made more icons for Numix.
![numix-did](https://user-images.githubusercontent.com/53346722/76705650-9f87ab80-66af-11ea-8262-37ae8b862a7b.png)

**Comment by palob** [comment]
Wow, thank you, looking forward to having those merged.

**Comment by Foggalong** [comment]
@creepertron95 Yes! Would love to see all these in the theme :heart:

**Comment by maxtron95** [comment]
@Foggalong Well I already have pull requests up for most of the icons.

**Comment by Foggalong** [comment]
@creepertron95 I've seen! I'm going through and reviewing PRs now :)
