### ISSUE TITLE
Missing icons in elementary OS

### ISSUE THREAD

**Issue by Gabriel-p** [numixproject/numix-core#235]
The _Tweaks_ app in elementary looks like this in my system with the _Numix Circle_ icon theme:

![captura de pantalla de 2014-01-22 22 01 36](https://f.cloud.github.com/assets/6054951/1980838/ecf17de4-83c9-11e3-8abb-8887a9fa937b.png)

Notice there are several icons missing:
- Animations
- Shadows
- Miscellaneous
- Slingshot
- Cerbere

**Comment by nupole** [comment]
Has this actually been fixed? I am still running into this issue now.

I have located the specific icons in the elementary os, is there a location that they can be moved to within the Numix Circle directory to fix this?

**Comment by Foggalong** [comment]
If you've found the icon names, just list them and then we can properly fix the issue :)

**Comment by nupole** [comment]
Of the above listed icons, only one resides in the /usr/share/applications/ directory, which is Cerebra. The icon name for Cerbere in the cerbere.desktop file is view-refresh. The actual icon is found in the /usr/share/icons/elementary/categories/24 directory. Here you will find preferences-tweaks-cerbere.svg as well as preferences-tweaks-anim.svg, preferences-tweaks-shadows.svg, and preferences-tweaks-slingshot.svg.

Unfortunately, this is as good of information as I can get to you at this point. I will search around and see if I can find anything else useful for you.

**Comment by Foggalong** [comment]
Thanks :+1: By the sounds of it these will be base icons so report them [here](https://github.com/numixproject/numix-icon-theme) if you find anything :)

**Comment by nupole** [comment]
I believe ghost already linked to an issue that was posted under here. I will post to that issue if I find anything more regarding them.

https://github.com/numixproject/numix-icon-theme/issues/64
