### ISSUE TITLE
Guns of Icarus Online

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#2431]
Steam ID: 209080

![images duckduckgo com](https://cloud.githubusercontent.com/assets/5920259/8910035/7edc86a4-347c-11e5-89eb-928d12edaa2f.jpeg)
##

**Comment by walker-dev** [comment]
![screenshot from 2017-02-04 15-58-29](https://cloud.githubusercontent.com/assets/25176087/22619337/1a073600-eaf3-11e6-9b26-25948da7fc31.png)
any good?

**Comment by palob** [comment]
Much too detailed I'm afraid.
