### ISSUE TITLE
Icon for Postman 3.0 (Chrome Web App)

### ISSUE THREAD

**Issue by krzysieki** [numixproject/numix-core#2443]
Icon for Postman has changed. Please update. Thanks for great work!

Application: Postman
Icon: https://www.getpostman.com/img-rebrand/logo.png

Desktop file (~/.local/share/applications/chrome-fhbjgbiflinjbdggehcddcbncdddomop-Profile_1.desktop):
# !/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Postman 
Exec=/opt/google/chrome/google-chrome "--profile-directory=Profile 1" --app-id=fhbjgbiflinjbdggehcddcbncdddomop
Icon=chrome-fhbjgbiflinjbdggehcddcbncdddomop-Profile_1
StartupWMClass=crx_fhbjgbiflinjbdggehcddcbncdddomop
##

**Comment by bilelmoussaoui** [comment]
There's now a postman application for linux, the icon name is `postman`

**Comment by bilelmoussaoui** [comment]
@Foggalong I have added a symlink to `postman` in master. So this is now just a enhancement request :)

**Comment by bkanuka** [comment]
here is an svg of the new postman logo: https://cdn.svgporn.com/logos/postman.svg
credit to https://github.com/gilbarbara/logos

Probably a reasonable icon to just put the jet man on an orange background!

**Comment by bkanuka** [comment]
FYI this is the icon Postman uses on Facebook. 
![postman](https://user-images.githubusercontent.com/2676579/34940598-17cc20f0-f9be-11e7-8c6d-f0190d502d64.png)

**Comment by Chinney** [comment]
I made one:

http://svgur.com/s/5xY

Use it if you want to.
