### ISSUE TITLE
Icon for Wyrmsun

### ISSUE THREAD

**Issue by jasonmacduffie** [numixproject/numix-core#2489]
Name=Wyrmsun
Icon=wyrmsun
![wyrmsun](https://cloud.githubusercontent.com/assets/6655349/9362866/02de7b82-4671-11e5-9061-180c31580c50.png)
##

**Comment by Taknamay** [comment]
Here is a higher resolution image of the full logo, the icon is just the "W" from here.

![wyrmsun_logo_1080](https://cloud.githubusercontent.com/assets/6655349/9386195/6d028550-4728-11e5-86c1-191eec2bca91.png)

**Comment by Foggalong** [comment]
Thanks, that'll be helpful :)

**Comment by palob** [comment]
[Fixed](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/wyrmsun.svg).
