### ISSUE TITLE
Icon for Mudlet

### ISSUE THREAD

**Issue by jasonmacduffie** [numixproject/numix-core#2494]
Name=Mudlet
Icon=mudlet

![mudlet](https://cloud.githubusercontent.com/assets/6655349/9420006/fd05d0b0-482e-11e5-9ef1-c52d7f64641b.png)
##

**Comment by palob** [comment]
Fixed in https://github.com/numixproject/numix-core/pull/4281/commits/ca234192ac21f44e809949678436f7234e1f7791
