### ISSUE TITLE
Icon for Nuntius

### ISSUE THREAD

**Issue by vodik** [numixproject/numix-core#2522]
https://github.com/holylobster/nuntius-linux

Name=Nuntius
Icon=nuntius

![hicolor_apps_512x512_nuntius](https://cloud.githubusercontent.com/assets/216803/9623729/be65ba04-5112-11e5-9049-4341def43a91.png)
##

**Comment by Foggalong** [comment]
I think we have a new winner for worst icon ever.

**Comment by gregorydk** [comment]
Yeah, but it's a funny one, an archbishop lobster. :-)

**Comment by wa4557** [comment]
https://github.com/holylobster/nuntius-linux#the-icon

**Comment by Eleuin** [comment]
If they are really spending the majority of their time on the icon, they are spending it wrong. This icon is seriously god awful. Shamfur dispray

**Comment by ChuckDaniels87** [comment]
Pure dadaism.
