### ISSUE TITLE
Icon for Freedoom: Phase 1

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#2527]
https://en.wikipedia.org/wiki/Freedoom#Gameplay

Icon=freedoom1

![freedoom1](https://cloud.githubusercontent.com/assets/7804464/9698412/527ddb5a-53b5-11e5-9ae7-92b7eca551a8.png)
##

**Comment by BlueManCZ** [comment]
@palob Should we symlink it to the same [icon](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/freedoom.svg) as Phase 2 or is it better to clone the icon and change the baseplate color?

![Snímek z 2021-08-12 18-20-36](https://user-images.githubusercontent.com/17854950/129232233-7f4bfc67-b446-4cae-b6f2-37293e38ad38.png)

![Snímek z 2021-08-12 18-23-59](https://user-images.githubusercontent.com/17854950/129232739-990bfa35-3029-4207-b5a9-2858441ebaa0.png)


https://github.com/numixproject/numix-core/blob/0de3e8d51eb8d02c6f33be5cc4777bc729446c34/data.json#L8233-L8242

**Comment by palob** [comment]
Ideally there should be a visual difference.
Do you know if that ``freedom`` icon name is really used by Freedom Phase 2?

**Comment by BlueManCZ** [comment]
I know that Freedoom Phase 2 uses `Icon=freedoom2`, so `freedoom` without any number seems to be redundant here.

**Comment by palob** [comment]
There's #1906 with the icon name ``freedoom`` showing the Phase 2 icon.

**Comment by BlueManCZ** [comment]
Well, to make everything clear, here are current original icons:

![Snímek z 2021-08-12 22-57-45](https://user-images.githubusercontent.com/17854950/129269075-65d9b6cc-39bf-4269-8dd9-ee933c97a028.png)

And here my .desktop files:

```
cat /usr/share/applications/io.github.freedoom.Phase1.desktop

[Desktop Entry]
Name=Phase 1
Name[he]=מופע 1
Comment=Battle monsters in four 9-level chapters
Comment[he]=הילחם במפלצות בארבעה פרקים בעלי 9 שלבים
GenericName=First Person Shooter Game
GenericName[he]=משחק יריות בגוף ראשון
Type=Application
Icon=freedoom1
Keywords=first;person;shooter;doom;
Categories=Game;ActionGame;
Exec=freedoom1
```

```
cat /usr/share/applications/io.github.freedoom.Phase2.desktop

[Desktop Entry]
Name=Phase 2
Name[he]=מופע 2
Comment=Battle monsters in one massive 32-level chapter
Comment[he]=הילחם במפלצות בפרק אדיר אחד בעל 32 שלבים
GenericName=First Person Shooter Game
GenericName[he]=משחק יריות בגוף ראשון
Type=Application
Icon=freedoom2
Keywords=first;person;shooter;doom;
Categories=Game;ActionGame;
Exec=freedoom2
```

> There's #1906 with the icon name `freedoom` showing the Phase 2 icon.

Alright, I think we create a new icon and name it freedom1. That should do it.

**Comment by palob** [comment]
Thanks for investigating.

**Comment by BlueManCZ** [comment]
And interestingly their .desktop files in the GitHub repo have different icon filenames than in the latest release archive. So maybe it will change in the next release.
https://github.com/freedoom/freedoom/blob/master/dist/io.github.freedoom.Phase1.desktop
https://github.com/freedoom/freedoom/blob/master/dist/io.github.freedoom.Phase2.desktop
