### ISSUE TITLE
Icon for FreeDM

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#2529]
https://en.wikipedia.org/wiki/Freedoom#Gameplay

Icon=freedm

![freedm](https://cloud.githubusercontent.com/assets/7804464/9698436/7dbfa202-53b6-11e5-8fce-61dc17d0b6e7.png)
##

**Comment by BlueManCZ** [comment]
Current Linux icon:

![freedm](https://user-images.githubusercontent.com/17854950/146243508-f9bc72c0-9294-4a9e-bd92-78eb61a86433.png)

**Comment by palob** [comment]
Next release will have it. At last.
