### ISSUE TITLE
Icon for IntelliJ IDEA Community Edition

### ISSUE THREAD

**Issue by markojic** [numixproject/numix-core#253]
There's no icon for IntelliJ IDEA Community Edition numix-circle.
The icon line says "/opt/idea-IC/bin/idea.png" and the original icon is attached.
![idea](https://f.cloud.github.com/assets/5999694/2047153/77eb18aa-8a15-11e3-9f23-7a4aead449fc.png)

**Comment by lightradius** [comment]
I keep seeing these threads for the Idea icon but I can't seem to find how to change this "icon line" everyone speaks of. Where do I change it? Is there a tutorial or additional information anywhere?

**Comment by Foggalong** [comment]
Check out the README :) for hardcoded icons and icon requests, it should give you the info you need

**Comment by LoLei** [comment]
The script did not work for me, what I did was:
- Open IntelliJ IDEA and select Tools > Create Desktop Entry (Close IntelliJ IDEA)
- Edit the `jetbrains-idea.desktop` file in `/usr/share/applications`, change the line which says `Icon` to equal `idea`.
- Restart IntelliJ IDEA

Sources:
http://nufailm.blogspot.co.at/2012/05/custom-launcher-for-intellij-idea-in.html
https://www.reddit.com/r/elementaryos/comments/2f9qms/how_to_change_application_icon_in_eos/

**Comment by Foggalong** [comment]
@LoLei Yeah, that's just what the script does only automated, so you only have to rerun the script every time the software gets updated rather than go through the whole process. If it didn't work for you file an issue with the script and we'll fix it asap :+1:
