### ISSUE TITLE
Icon for Trackma 

### ISSUE THREAD

**Issue by AlejandroC90** [numixproject/numix-core#2538]
A numix-circle icon for trackma is missing 
The icon line says "trackma"
![trackmaicon](https://cloud.githubusercontent.com/assets/5132907/9723848/15cd4e42-5591-11e5-8339-c5d76e4703b7.png)
##

**Comment by bil-elmoussaoui** [comment]
PS: the telegram icon is not a Numix Circle icon; you can try [hardcode-fixer](https://github.com/Foggalong/hardcode-fixer) to fix that

**Comment by AlejandroC90** [comment]
I know that, because it's the "portable" version.

**Comment by AlejandroC90** [comment]
Now that you mention it, I already fixed it, jeje 
![telegramiconrepaired](https://cloud.githubusercontent.com/assets/5132907/9723918/f09912bc-5592-11e5-99a6-ce2022765fa3.png)
