### ISSUE TITLE
Icon request for Wiznote

### ISSUE THREAD

**Issue by alim0x** [numixproject/numix-core#2571]
Website: [Wiznote](http://www.wiz.cn/)

```
[Desktop Entry]
Name=WizNote
Name[zh_CN]=为知笔记
Name[zh_TW]=为知笔记
Comment=cloud based note-taking application
Comment[zh_CN]=开源云笔记
Comment[zh_TW]=开源云笔记
Exec=WizNote
Terminal=false
Type=Application
StartupNotify=true
Icon=wiznote
Categories=KDE;Qt;Utility;
```

![screenshot from 2015-09-27 12 04 48](https://cloud.githubusercontent.com/assets/4954007/10121143/94ab7d68-6510-11e5-8722-d402cf66c960.png)
##

**Comment by alim0x** [comment]
![screenshot from 2015-11-06 18-15-30](https://cloud.githubusercontent.com/assets/4954007/10994601/64512a5c-84b2-11e5-8bb9-be3c583bbf62.png)

update: need tray style icon too

**Comment by bil-elmoussaoui** [comment]
Can you report that on Numix base ? The icon is hardcoded but it's already supportes by Hardcode-Tray

**Comment by alim0x** [comment]
ok, thx

**Comment by really-need-an-api-key** [comment]
Working on this one, but have to clean up the bevels a bit before making a PR.
![wiznote svg](https://user-images.githubusercontent.com/11636003/57183988-bae13200-6eb4-11e9-8e65-834523d7c21a.png)
