### ISSUE TITLE
Icon for Wildguppy

### ISSUE THREAD

**Issue by elridion** [numixproject/numix-core#2588]
A numix-circle icon for Wildguppy is missing.
The Icon line says "/opt/wildguppy/icon/fish_large.png"
The Icon file is attached.

![fish_large](https://cloud.githubusercontent.com/assets/14920272/10267083/251dd6fc-6a84-11e5-8e28-610210be983e.png)
##

**Comment by palob** [comment]
Last release dates back 10 years. Probably isn't needed anymore on modern systems.
