### ISSUE TITLE
Icon for slack

### ISSUE THREAD

**Issue by takayukioda** [numixproject/numix-core#2604]
A numix-circle icon for slack is missing
The icon line says, `Icon=slack` and original icon is attached.

![slack](https://cloud.githubusercontent.com/assets/1546410/10502123/9eaa45ee-7323-11e5-8915-8db39cfdd3d5.png)

Thanks!
##

**Comment by TamasBarta** [comment]
It isn't missing, it's doesn't look like Slack. It uses the "hash mark" logo of Slack. (Which is great for the panel, but not appropriate as a launcher icon, I believe)
I'd also love to see this icon's numixified version as Slack's launcher icon.

**Comment by ediTLJ** [comment]
Any hopes of seeing this done?

**Comment by bilelmoussaoui** [comment]
Fixed
