### ISSUE TITLE
STAR WARS: KOTOR2 (Steam)

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#2610]
Game: STAR WARS™ Knights of the Old Republic™ II: The Sith Lords™
AppID: 208580
Icon: ![512x512bb-85](https://cloud.githubusercontent.com/assets/1087450/10543086/b6a9558c-741c-11e5-8e53-d86cd772de2b.png)
##

**Comment by maxtron95** [comment]
Here is an icon I propose for the game:
![star-wars-kotor2-ci svg](https://user-images.githubusercontent.com/53346722/72487165-b6ef0900-37d2-11ea-9cb9-85cd7ed1cf30.png)
![star-wars-kotor2-sq svg](https://user-images.githubusercontent.com/53346722/72487174-bc4c5380-37d2-11ea-997a-2bbdbe67b8f1.png)
[star-wars-kotor2-draft.tar.gz](https://github.com/numixproject/numix-core/files/4068970/star-wars-kotor2-draft.tar.gz)

**Comment by palob** [comment]
Thank you, feel free to open a PR.
There is some strange stacking. The black and greyish parts should be on top of the white path rather than be cut out from the white path.
All elements should overlap rather than share common outlines in order to avoid fine contour lines.

**Comment by palob** [comment]
@creepertron95 Still interested?
