### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#2620]
Please, I need new beautifull icons for SchematicEditor and PcbNew. The first 2 are hardcoded, I will will make an issue on hardcode-fixer.

**Icon 2** (Can be different from the 1)

```
/usr/local/share/applications/schematic.desktop
Icon=layout.png
```

**Icon 3**

```
/usr/share/applications/pcbnew.desktop
Icon=pcbnew
```

![layout](https://cloud.githubusercontent.com/assets/1277920/10623180/6c0eeb52-776b-11e5-8569-458c89923ed2.png)
##

**Comment by leoheck** [comment]
The issue on hardcode-fixer [#185](https://github.com/Foggalong/hardcode-fixer/issues/185)

They named the icons as (1) ```layout``` and (2) ```schematic```

**Comment by bilelmoussaoui** [comment]
Already on master :)
