### ISSUE TITLE
Icon for Nixnote

### ISSUE THREAD

**Issue by WolfangAukang** [numixproject/numix-core#2629]
An icon for Nixnote is missing.

Icon line says "/usr/share/nixnote/nixnote.png" and the icon is attached:
![nixnote](https://cloud.githubusercontent.com/assets/8378365/10722018/6336a86c-7b71-11e5-8afb-4d6a875bd7d5.png)

Shortcut file named as "nixnote.desktop".
##

**Comment by palob** [comment]
We've actually got a symlink.
