### ISSUE TITLE
Icon for Aurous

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-core#2631]
Aurous is PopcornTime for Music, more info [here](https://aurous.me/)
The application does not have any default desktop file neither an icon name. I think `aurous` would be a good icon name, if there's any new updates on this we can create a symlink later!

The default icon 
![logo](https://cloud.githubusercontent.com/assets/7660997/10761886/b1d12454-7cc3-11e5-9fa1-e08fe1753389.png)
##

**Comment by Foggalong** [comment]
I'd not realised but within a few months of this issue being posted [Aurous shutdown](https://web.archive.org/web/20160301071503/http://aurous.me:80/). Given that it actually never got a launcher I'm just gonna close this :man_shrugging:
