### ISSUE TITLE
Icon for TopCoder

### ISSUE THREAD

**Issue by HandIeNeeded** [numixproject/numix-core#2632]
Icon for TopCoder.
Icon:
![topcoder](https://cloud.githubusercontent.com/assets/6835974/10811015/32737fa6-7e42-11e5-939f-9fd6c7b873de.png)
Notes: Algorithm competitions. Java webstart applications.

Icon name: TopCoder
##

**Comment by Foggalong** [comment]
We need the icon name too. See tuesday readme for more details

**Comment by yuzhou627** [comment]
Icon for TopCoder.
Icon:
![topcoder](https://cloud.githubusercontent.com/assets/6835974/10938010/ed8d2dca-8331-11e5-8af9-bcbdf854f3cd.png)

Notes: Algorithm competitions. Java webstart applications.

Icon name: TopCoder

**Comment by palob** [comment]
defunct in this form as far as I can see.
