### ISSUE TITLE
Icon for Stremio

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#2674]
Stremio is the new PopcornTime
The application does not have a desktop file, you can name the icon as `stremio`
The default icon is 
![stremio-white-small](https://cloud.githubusercontent.com/assets/7660997/11165169/145d7d96-8b08-11e5-9056-06bedb20f2b0.png)
##

**Comment by Foggalong** [comment]
What happened to the old popcorn time?

**Comment by bil-elmoussaoui** [comment]
@Foggalong Not maintained anymore, website not working too (In Belgium) :/

**Comment by Foggalong** [comment]
Ah, [just seen this](https://medium.com/@getpopcornapp/goodbye-popcorn-time-93f890b8c9f4)

**Comment by natanfelles** [comment]
Look: https://github.com/numixproject/numix-icon-theme-circle/pull/2886

**Comment by rickinbsb** [comment]
@Foggalong @bil-elmoussaoui Popcorntime is back, there is a community maintained version now. [you can find it here](http://popcorntimece.tk/)

**Comment by KSXGitHub** [comment]
anyone working on this?
