### ISSUE TITLE
Icon for gcdemu

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#2687]
**Original icon:**
![screenshot from 2015-11-17 21-17-39](https://cloud.githubusercontent.com/assets/1087450/11223607/18b937e8-8d71-11e5-82aa-20d276ddb3d7.png)

**Icon name:** gcdemu

**Notes:** It's a software for mounting disk images, much like Daemon Tools on Windows.

**Additional info:** It has a tray icon, so a monochromatic panel icon is needed, too.
##

**Comment by palob** [comment]
Already [fixed](https://github.com/numixproject/numix-core/blob/c97ddcde5eddc6d51c75cccfbc93fecb8adbdfaa/data.json#L2197).
