### ISSUE TITLE
Icon for soundnode

### ISSUE THREAD

**Issue by artur9010** [numixproject/numix-core#2765]
[Desktop Entry]
Name=Soundnode App
GenericName=Soundcloud client
Comment=Soundnode App is the Soundcloud for desktop.
Exec=/opt/soundnode-app-bin/Soundnode-App
Icon=/opt/soundnode-app-bin/soundnode.png
Terminal=false
Type=Application

Orginal icon:
![soundnode](https://cloud.githubusercontent.com/assets/4835677/12075412/6183fc0a-b180-11e5-8167-829d1e8a2b9a.png)

**Comment by bil-elmoussaoui** [comment]
The icon is hardcoded, can you give us the destkop file name too?

**Comment by artur9010** [comment]
soundnode-app.desktop

**Comment by bilelmoussaoui** [comment]
@artur9010 already fixed in https://github.com/numixproject/numix-core/pull/3404
