### ISSUE TITLE
Icon for Blockstorm Steam

### ISSUE THREAD

**Issue by artur9010** [numixproject/numix-core#2774]
App: Blockstorm
AppID: 263060

**Comment by Foggalong** [comment]
@artur9010 can you add the original icons? It makes it easier for us to file them :)

**Comment by artur9010** [comment]
It uses steam icon.

**Comment by Foggalong** [comment]
Yeah, but the original games have icons even those that use the Steam one by default

**Comment by Hori873** [comment]
This is the icon: ![883b2cee32047782e366da6c1cad39e87a4b630f](https://cloud.githubusercontent.com/assets/10261133/16709506/463564ae-461b-11e6-9193-90fc77a4f1e0.jpg)
