### ISSUE TITLE
Icon for Cockatrice, Cockatrice Oracle, and Servatrice

### ISSUE THREAD

**Issue by jasonmacduffie** [numixproject/numix-core#2776]
This is a request for 3 related applications:

Name=Cockatrice
Icon=cockatrice

![cockatrice](https://cloud.githubusercontent.com/assets/6655349/12154744/52c4bbd4-b48f-11e5-9c95-5f2916e12f67.png)

Name=Cockatrice Oracle downloader
Icon=oracle

![oracle](https://cloud.githubusercontent.com/assets/6655349/12154749/57a75fbc-b48f-11e5-854f-6cfdf012187a.png)

Name=Servatrice
Icon=servatrice

![servatrice](https://cloud.githubusercontent.com/assets/6655349/12154751/5a52887c-b48f-11e5-96f4-c5e3c9cd440d.png)

**Comment by palob** [comment]
It's this https://github.com/Cockatrice/Cockatrice I suppose.
Can you tell us what the 3 launchers are for?

**Comment by Taknamay** [comment]
That link is correct. Yes of course, I will explain each launcher.

**Cockatrice** is the main program, used to actually build Magic the Gathering decks and join matches with other people.

**Oracle downloader** downloads the card data for Magic the Gathering from an online database.

**Servatrice** is a server program used to host Magic the Gathering matches.

**Comment by Foggalong** [comment]
So three related icons on the themes of "main", "downloader", "server" would be well suited.
