### ISSUE TITLE
Icon for Rocket League

### ISSUE THREAD

**Issue by scottwillmoore** [numixproject/numix-core#2784]
Game: Rocket League
AppID: 252950

Icon (inspiration):

![image](https://cloud.githubusercontent.com/assets/9512557/12220086/848b5368-b7b3-11e5-910b-04b79c937238.png)

![image](https://cloud.githubusercontent.com/assets/9512557/12220087/8d5f6498-b7b3-11e5-8951-ef4b6251ce1a.png)

**Comment by W-Floyd** [comment]
I'm having a go at this now.

**Comment by scottwillmoore** [comment]
Looks great, thanks!
