### ISSUE TITLE
Icon for TraGtor video converter

### ISSUE THREAD

**Issue by Tracinha** [numixproject/numix-core#2799]
If can, please, add a icon for traGtor video converter.

**Comment by palob** [comment]
Hi, could you please add the information set out in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests)?

**Comment by Tracinha** [comment]
A numix-circle icon for traGtor os missing.
The icons line says "tragtor"  and the original icon is attached.
![tragtor](https://cloud.githubusercontent.com/assets/12475564/12516814/53123798-c10e-11e5-9fdf-b393f37930ae.png)

Now is all ok?!

**Comment by palob** [comment]
@Tracinha Yep, thanks.

**Comment by palob** [comment]
upstream defunct.
