### ISSUE TITLE
Shrew Soft VPN Access Manager icon missing

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#2802]
Hello, I'd like to make a request for a Cisco compatible VPN alternative app. The package itself is called  "ike" and "ike-qtgui", the icon line of the /usr/share/appdata file is "Icon=ikea". The app icon lookes like this:

![](http://techedemic.com/wp-content/uploads/2015/10/shrewsoft.png)

source: http://techedemic.com/2015/10/14/installing-shrewsoft-vpn-on-ubuntu-14-04/

**Comment by palob** [comment]
Last release looks to be from 2013.
