### ISSUE TITLE
Icon for Crypt of the NecroDancer (Steam)

### ISSUE THREAD

**Issue by marcobenoit90** [numixproject/numix-core#2809]
Game: Crypt of the NecroDancer
AppID: 247080
Icon: ![icon](https://cloud.githubusercontent.com/assets/16888391/12567426/4f77309e-c3bf-11e5-8a36-f7e58b85dd2e.png)
Notes: -

**Comment by marcobenoit90** [comment]
still nothing? ;(

**Comment by Foggalong** [comment]
We have requests [a lot older than yours](https://github.com/numixproject/circle-core/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3Arequest) still waiting. We'll hopefully get around to it soon but there's a lot to cover
