### ISSUE TITLE
Icon for YubiKey NEO Manager

### ISSUE THREAD

**Issue by drohm** [numixproject/numix-core#2813]
I'd like to request an icon for YubiKey NEO Manager - application info [here](https://developers.yubico.com/yubikey-neo-manager/).

![yubikey-neo-manager](https://cloud.githubusercontent.com/assets/184959/12688541/e55e6ad6-c6a4-11e5-910c-2615e618aea3.png)

The /usr/share/applications/neoman.desktop Icon line:

```
Icon=neoman
```

If there is any other information needed let me know, happy to get it.

**Comment by microraptor** [comment]
This application is deprecated and superseded by the YubiKey Manager, which is requested in #4664

**Comment by Foggalong** [comment]
@microraptor Thanks for the update on this! Going to close this issue and just track using #4664
