### ISSUE TITLE
Icon for mednafen and its GUI's

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-core#2819]
Albeit this is a command-line program, there are a couple of GUI's for it. A pretty good one is https://github.com/AmatCoder/mednaffe whose desktop file is:

```
[Desktop Entry]
Type=Application
Version=1.0
Name=Mednaffe
Comment=A front-end (GUI) for mednafen emulator
Exec=mednaffe
Terminal=false
Icon=mednaffe
Categories=GTK;Game;Emulator;
```

So I guess one icon with this little bug:

![256px-mednafen_logosvg](https://cloud.githubusercontent.com/assets/7532854/12706190/85a2234e-c866-11e5-8558-a3a455597b1c.png)

and symlinks to mednaffe and any other GUI's would suffice

**Comment by palob** [comment]
Fixed.
