### ISSUE TITLE
Icon for Cisco AnyConnect

### ISSUE THREAD

**Issue by thimslugga** [numixproject/numix-core#2820]
Hi,

I wanted to submit an icon request for the Cisco AnyConnect client.  I've included the desktop file and default image. Let me know if you need anything else!

`/usr/share/applications/cisco-anyconnect.desktop`

```
[Desktop Entry]
Type=Application
Name=Cisco Anyconnect Secure Mobility Client
Comment=Connect to a private network using the Cisco Anyconnect Secure Mobility Client
Exec=/opt/cisco/anyconnect/bin/vpnui
Icon=/opt/cisco/anyconnect/pixmaps/vpnui48.png
Terminal=false
Encoding=UTF-8
```

![vpnui48](https://cloud.githubusercontent.com/assets/285055/12709240/b3de9b96-c877-11e5-9434-7a095f7c7840.png)

**Comment by mnapp** [comment]
+1 

This it's the only thing in my launcher that is not Numix styled.

**Comment by mnapp** [comment]
I created this one just now. Totally new to Inkscape so I don't know if I did it right.

![cisco-anyconnect](https://cloud.githubusercontent.com/assets/4920542/13017126/ffde9f42-d1c2-11e5-8ccd-b1687bb7339c.png)

**Comment by kmyid** [comment]
This is the only icon that is left in my launcher without numix icon support as well :-(
It would be nice if it is supported. I also had a look at PR #2854, but it seems deleted...

**Comment by r0ckarong** [comment]
The icon I created wasn't up to standard for the project and I don't have the time right now to learn the techniques to do it properly so I closed the PR. Maybe I'll get around to do that eventually.

**Comment by palob** [comment]
Doesn't seem to be a thing no more.
