### ISSUE TITLE
Icon for gigolo

### ISSUE THREAD

**Issue by truggleswick** [numixproject/numix-core#2821]
A numix-circle icon for gigolo for missing.
The icon says "gigolo" and please see attached.
THANK YOU.
Ps. The creator of gigolo said he name it that way, because it mounts whatever you tell it to - HTH

![screenshot from 2016-02-01 12-35-46](https://cloud.githubusercontent.com/assets/8123711/12717622/ef185a08-c8e0-11e5-81a0-c3bc5b8f2fdd.png)

**Comment by palob** [comment]
Hi, it's a bit late but I'm not sure the icon line insinde the ``.desktop`` launcher really is "gigolo" given the fact a Numix folder icon is shown.

With a Numix folder being show it's probable we can't fix this. But you could edit the ``.desktop`` launcher.

**Comment by Foggalong** [comment]
I just installed it on Ubuntu (I think the screenshot is taken from USC) and the icon line is `Icon=gtk-ntwork` which [in base](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/48/places/gtk-network.svg) which is a symlink indeed leading to [the shown icon](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/48/places/default-network.svg). So yeah, hardcoded but we can add one and then a fix for it :+1:

**Comment by palob** [comment]
Fixed a while ago.
