### ISSUE TITLE
Support for bumblebee

### ISSUE THREAD

**Issue by amlankar** [numixproject/numix-core#2823]
Could you add support for icons to show up when the program is run with 'optirun program' instead of just 'program'. I just installed bumblebee and am now running basic applications (Chrome etc.) using optirun but the icons have broken.

**Comment by palob** [comment]
I don't know what's the issue. Can you post a screenshot of the broken issue? What's that ``optirun`` thing?

**Comment by amlankar** [comment]
Optirun is the function provided by bumblebee. It allows the user to run programs on the discrete GPU or the integrated GPU as required. I don't really understand the issue though.

In the screenshot, chrome doesn't show its icon now on my dock(the icon runs optirun google-chrome-stable). 
![screenshot from 2016-02-02 15 37 37](https://cloud.githubusercontent.com/assets/7633212/12746079/e89730a4-c9c2-11e5-98e9-36aadafe8afd.png)

**Comment by palob** [comment]
Is it only about Chrome?

**Comment by amlankar** [comment]
It seems it's general. I've tried chrome, skype, lollypop and vlc. In case of Skype pressing Alt+Tab indicates Skype as Bumblebee indicator, while all other programs are identified correctly.

**Comment by bil-elmoussaoui** [comment]
Do you have the same issue with the default theme?

**Comment by amlankar** [comment]
You're right, the issue is there for every theme I have! I guess the issue is then with how the classes are handled

**Comment by Foggalong** [comment]
@bil-elmoussaoui Is this a [StartupWMClassFixer](https://github.com/bil-elmoussaoui/StartupWMClassFixer) thing

**Comment by palob** [comment]
Since @amlankar told *"the icon runs optirun google-chrome-stable"* to me it seems like those optirun launchers are seperate launchers with probably hardocded icon paths.

**Comment by bil-elmoussaoui** [comment]
I have no idea, maybe someone should test it out and paste the content of the desktop file

**Comment by Foggalong** [comment]
Closing due to lack of info from OP
