### ISSUE TITLE
Icon Request for CPU-G

### ISSUE THREAD

**Issue by bongochong** [numixproject/numix-core#2830]
- CPU-G (https://launchpad.net/cpug)
  ![cpug](https://cloud.githubusercontent.com/assets/10101120/12800025/9ceeb014-ca8f-11e5-845d-44850c9b987b.png)

Icon=/usr/share/pixmaps/cpu-g_128.png
/usr/share/applications/cpu-g.desktop

**Comment by palob** [comment]
Hi, any particular reason for closing this? Application got obsolete?

**Comment by bongochong** [comment]
Slipped my mind to mention why, but you're right on the money. CPU-G is no longer in the repos for recent releases of many widely used distros, and the program itself has not been updated since 2013 now, so it seems to be obsolete.
