### ISSUE TITLE
Icon Request for UPnP Router Control

### ISSUE THREAD

**Issue by bongochong** [numixproject/numix-core#2837]
- UPnP Router Control (https://launchpad.net/upnp-router-control)
  ![upnp](https://cloud.githubusercontent.com/assets/10101120/12800029/9d0358ac-ca8f-11e5-8572-5cc69728ea60.png)

Icon=upnp-router-control
/usr/share/applications/upnp-router-control.desktop

**Comment by bilelmoussaoui** [comment]
Fixed
