### ISSUE TITLE
Unturned (steam)

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#2841]
Description : You become a survivor in the zombie infested ruins of society, and team up with your friends to remain among the living. [More details](http://store.steampowered.com/app/304930/?l=french)
The default icon: it's not really the default icon as the game comes with the steam icon by default and i couldn't find the the logo anywhere on the internet, neither in the game local files.
![ss_add79e7502a5d4f0ff2384d3798d74529f7ddb92 600x338](https://cloud.githubusercontent.com/assets/7660997/12876679/3be0822e-ce05-11e5-8d2d-654180928dec.jpg)

The icon name: `steam` (hardcoded)
The desktop file name:  `Unturned.desktop`
Steam id : 304930

**Comment by Foggalong** [comment]
We need the app ID for Steam requests. See the README for a video tutorial

**Comment by bil-elmoussaoui** [comment]
I've completely forgot that! updated!
