### ISSUE TITLE
Original terminator icon shown instead of numix circle icon

### ISSUE THREAD

**Issue by ggirelli** [numixproject/numix-core#2853]
Hello, I don't get why but the terminator icon from this theme is not shown, instead I see the ugly terminator icon (the one with 4 red terminals)... even if I removed the _ugly_ terminator icon from /usr/share/pixmaps/ and the numix icon is present in /usr/share/icons/Numix-Circle/scalable/apps/... any idea why this might be happening?

Thanks in advance :D

**Comment by Foggalong** [comment]
Please fill out the information from the README so we can better work out this problem :)

**Comment by ggirelli** [comment]
Sorry, here it is.
Still, the icon is already there... it's just not showing up in the Ubuntu Unity 7 Launcher... :/

The icon line says 'terminator', and the original and current numix icons are attached.
![terminator](https://cloud.githubusercontent.com/assets/1636105/12949428/0b5f015c-d008-11e5-95c9-a315520393cb.png)
![terminator](https://cloud.githubusercontent.com/assets/1636105/12949437/19d07bda-d008-11e5-8317-09a38b6970a8.png)

**Comment by Foggalong** [comment]
Huh, that's weird. What Ubuntu are you using?

**Comment by ggirelli** [comment]
15.10. On another pc with the same version of Ubuntu everything works like a charm... Please et me know if I can provide any information that you might need to help me with this issue 😀

**Comment by bil-elmoussaoui** [comment]
Where exactly the ugly icon is shown? :+1:  can you paste the content of the desktop file too ?

**Comment by ggirelli** [comment]
Here is the content of the desktop file:
```
[Desktop Entry]
Name=Terminator
Comment=Multiple terminals in one window
TryExec=terminator
Exec=terminator
Icon=terminator
Type=Application
Categories=GNOME;GTK;Utility;TerminalEmulator;System;
StartupNotify=true
X-Ubuntu-Gettext-Domain=terminator
X-Ayatana-Desktop-Shortcuts=NewWindow;
Keywords=terminal;shell;prompt;command;commandline;
[NewWindow Shortcut Group]
Name=Open a New Window
Exec=terminator
TargetEnvironment=Unity
```

And I attach how the desktop file looks (i.e., it looks correct), it's located in `/usr/share/applications/`.

![screenshot from 2016-02-10 19-14-54](https://cloud.githubusercontent.com/assets/1636105/12957499/3de13dc8-d02d-11e5-9652-88053c991a24.png)

And the screenshot of the icon in the unity launcher (follow that *fancy* and big black arrow).

![screenshot from 2016-02-10 19-13-41](https://cloud.githubusercontent.com/assets/1636105/12957502/3f1e28c2-d02d-11e5-937f-f598678b2bda.png)

**Comment by dirtydancing** [comment]
Not reproducible on Arch/GNOME, all Terminator icons are showing fine.

@ggirelli Just in case, could you try a forced icon cache update:

`sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle`

**Comment by ggirelli** [comment]
@dirtydancing Nothing changes :/

**Comment by ggirelli** [comment]
I know that it's not the most suitable solution, but I fixed this behavior by replacing terminator default icon (24x24, 32x32, 48x48) in the hicolor theme, and then updating the cache for both the hicolor and the Numix-Circle themes.

It does not surprise me that in Arch/GNOME the bug cannot be reproduced since it affected mainly the Unity launcher. Right? Anyway I forgot to mention that the size of the icons in my Unity launcher is 32 pixel (not the default 48).

Thanks everyone for the support! :D

**Comment by dirtydancing** [comment]
Still strange, because also Ubuntu/Unity should pick up the Terminator icon from Numix-Circle, as Numix-Circle inherits hicolor and thus hicolor comes after Numix-Circle in the icon theme inheritance line.

Maybe this a bug in Ubuntu/Unity, e.g. that a specific size of an icon is looked for down the entire inheritance line? But then again, normally the Numix-Circle icon should cover all sizes. Oh well :)

@wa4557 As you are running Ubuntu: Any chance that you know what might be going on here?

**Comment by Foggalong** [comment]
@ggirelli I've been unable to replicate this issue with a fresh install of Ubuntu and Terminator, settings switched to the 32px panel. Has anyone else been able to replicate it?
![screenshot_2016-09-02_12-23-33](https://cloud.githubusercontent.com/assets/5920259/18202493/29dc7424-7108-11e6-89a4-f0c941eb9f49.png)

**Comment by ggirelli** [comment]
I replicated the issue in a clean install of Ubuntu 14.04 on a new laptop a couple of days ago.

When installing `numix-gtk-theme` and `numix-icon-theme-circle` for the first time and applying them to the system via `unity-tweak-tool` using `terminator`, the `terminator` icon did not change. At the same time, if the same steps are performed via the usual `gnome-terminal` and `terminator` is installed afterwards, everything behaves properly.

**Comment by Foggalong** [comment]
Oh, it's with 14.04? I'll try again with that but it's possible this is a Unity bug. The version included there has a lot of problems which weren't fixed until 16.04.

**Comment by ggirelli** [comment]
The original issue was on 15.10. I reproduced it on 14.04. Did not check with 16.04...

**Comment by Foggalong** [comment]
Yeah, iirc 16.04 is the one with the significantly less buggy Unity.  However 14.04 is still a supported LTS so I'll try and reproduce this and fix the issue. Downloading the ISO as we speak.

**Comment by Foggalong** [comment]
I've not been able to reproduce this in a fresh install of 14.04 either - are you sure there's nothing else in the steps you took that weren't stated above?
![screenshot_2016-09-02_20-02-35](https://cloud.githubusercontent.com/assets/5920259/18215260/43464d82-7148-11e6-95cc-cac1bd04100a.png)

**Comment by ggirelli** [comment]
Hej guys, on a new computer, clean installation of Ubuntu 16.04.
I installed `unity-tweak-tool`, `terminator`, `numix-gtk-theme` and `numix-icon-theme-circle`.
Then I open `unity-tweak-tool` and change a few settings and then the icon and theme to the numix and numix-circle ones. Still, terminator has the original icon, not numix's one.

I tried to purge them, reboot, re-install but nothing worked... I guess I will manually change the icons again...

Also, I don't know if this might matter but I changed the size of the panel icons to 32px.

**Comment by ggirelli** [comment]
This is even more weird, the panel has the original icon while terminator is showed with numix's one when looking for it...

![screenshot from 2016-11-15 16-15-11](https://cloud.githubusercontent.com/assets/1636105/20308958/60ff942c-ab46-11e6-9ad2-3d5c9b502ab0.png)

**Comment by ggirelli** [comment]
Last news: if I open `terminator` using `Ctr+Alt+T` I get the old icon, if I open it by searching it or by running `terminator` on `gnome-terminal` I get numix icon! Any idea why that happens?

![screenshot from 2016-11-15 16-24-17](https://cloud.githubusercontent.com/assets/1636105/20309263/950955c2-ab47-11e6-912d-397ad634f796.png)

**Comment by Foggalong** [comment]
I honestly have no idea what's causing this :cry:

**Comment by dirtydancing** [comment]
The Numix-Circle icons are showing correctly in my Ubuntu 16.04 LTS installation. However, with Terminator there seems to be s.th. special going on with CTRL + ALT + T, cf.

https://askubuntu.com/questions/561127/ctrl-alt-t-opens-root-terminal-instead-of-normal-terminal
https://bugs.launchpad.net/terminator/+bug/1447580

This opens "Root Terminal", but it is a normal user Terminal. Anyways, also for this, on my machine Ubuntu 16.04 LTS is displaying the "Root Terminal" Numix-Circle icon. Screenshot:

![root_terminal](https://cloud.githubusercontent.com/assets/7164227/20342789/19b19b6e-abec-11e6-9083-b88dbaea40c5.png)

I figure then that this is not a Numix-Circle issue, but rather an issue/feature with Ubuntu/Terminator.

**Comment by ggirelli** [comment]
@dirtydancing Interesting but unrelated :(

I also tried to change the keyboard shortcut behaviour with `sudo update-alternatives --config x-terminal-emulator`, to set `terminator` or other options both as automatic or manual, with no results.

**Comment by bilelmoussaoui** [comment]
@ggirelli Try using this script, https://github.com/bil-elmoussaoui/StartupWMClassFixer this should fix your issue!

**Comment by ggirelli** [comment]
@bil-elmoussaoui tried, rebooted, but did not fix it :/

**Comment by ggirelli** [comment]
Yay! Fixed it :)

Basically, in `~/.local/share/icons/` there was a `x-terminal-emulator.png` icon with the old terminator one. Once I deleted that file, everything got fixed.

Sorry for the headache, it never occurred to me to check if an icon got generated for x-terminal-emulator in my home... :/

**Comment by Foggalong** [comment]
No worries!
