### ISSUE TITLE
Issue and Pull Request Template

### ISSUE THREAD

**Issue by ChuckDaniels87** [numixproject/numix-core#2861]
I'm not sure if this is the best way to communicate this but take a look:
https://github.com/blog/2111-issue-and-pull-request-templates

This can make developing workflow a bit better. :smile: 

@Foggalong @palob 

Edit: Even better -> https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by Foggalong** [comment]
Yeah, it's in the works :)

**Comment by palob** [comment]
Oh yes!

So something like
*Name of the .desktop file:*
*Icon line: Icon=*
*Original icon:*

?

Is there an easy way to get rid of this if the issue isn't going to be an icon request?

**Comment by Foggalong** [comment]
You have to erase the template every time, which is on of the issues with this

**Comment by ChuckDaniels87** [comment]
Considering that 90% of the issues in `numix-icon-theme-circle` are icon requests, I think that erasing the template won't be a relevant problem. However, using the template will reduce  the number of wrong icon requests.

**Comment by bil-elmoussaoui** [comment]
I think something like this will be a good way to go https://github.com/mank319/elementaryPlus/issues/380

**Comment by cybre** [comment]
@bil-elmoussaoui 
Note: Our new configurator<sup>[1]</sup> generates the table you see in that.


[1] It's not available, yet.
