### ISSUE TITLE
Icon for Google Flights (Chrome Web App)

### ISSUE THREAD

**Issue by edufrojo** [numixproject/numix-core#2862]
A numix-circle icon for Google Flights is missing.
Thanks for great work!

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Google Flights
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=epionbmgciknkbdibokmpmcfllkdfeeo
Icon=chrome-epionbmgciknkbdibokmpmcfllkdfeeo-Default
StartupWMClass=crx_epionbmgciknkbdibokmpmcfllkdfeeo

![google flights](https://cloud.githubusercontent.com/assets/10981413/13181074/880ada94-d72b-11e5-80e3-6c648f904774.png)

**Comment by Jacajack** [comment]
![selection_530](https://cloud.githubusercontent.com/assets/6173262/13320543/0a42bd7c-dbca-11e5-955d-f7c2e4d2f6a7.png)

I created this one myself, probably it's to simple. Anyway, what do You think?

**Comment by palob** [comment]
Not too simple. feel free to submit a pull request so @Foggalong can review it :)

**Comment by Jacajack** [comment]
Ok, I'm forming pull request then :)

**Comment by bilelmoussaoui** [comment]
@Foggalong this can be closed ;)
