### ISSUE TITLE
Icon for Jack Rack

### ISSUE THREAD

**Issue by eduardomezencio** [numixproject/numix-core#2881]
Icon missing for Jack Rack. Icon name is "jack-rack-icon.png". Here's the default icon
![jack-rack-icon](https://cloud.githubusercontent.com/assets/4137750/13558143/c5ad4668-e3db-11e5-90ed-2e5be082052e.png)

**Comment by palob** [comment]
Latest release is from 2010 so this isn't part of distros anymore. If people are still using this via Flatpak, Snap or whatever, feel free to reopen.
