### ISSUE TITLE
Icon for Non DAW

### ISSUE THREAD

**Issue by eduardomezencio** [numixproject/numix-core#2882]
Icon missing for the Non DAW. The Non DAW consists of 4 pieces of software with different icons. Icon names are "non-mixer", "non-sequencer", "non-session-manager" and "non-timeline". Here are the default icons 
![non](https://cloud.githubusercontent.com/assets/4137750/13558182/da70009e-e3dc-11e5-886d-03d8da53919f.png)

**Comment by W-Floyd** [comment]
I would propose icons like so:

![iconified_non-mixer](https://user-images.githubusercontent.com/11786132/34327354-c5747ce6-e90d-11e7-9eee-d6bd460a0db7.png)

Assuming the user knows the colour correspondence, they're okay, but for us to signify "mixer", or "session manager" might be hard. Any ideas?

**Comment by palob** [comment]
And those aren't words which are essy to depict so I'd say it's fine to go with the colours only.
