### ISSUE TITLE
Icon for Private Internet Access 

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#2890]
There is no Icon for PIA. The default one is way out of place with numix circle and it looks terrible.

![screenshot from 2016-03-17 00-50-06](https://cloud.githubusercontent.com/assets/16209272/13836712/781822b8-ebda-11e5-98c8-ae8031abf506.png)

Icon=/home/"user"/.pia_manager/pia_tray.32/Resources/default_app_logo.png

**Comment by maxtron95** [comment]
But there is an icon for [Private Internet Access](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/pia-manager.svg)

**Comment by palob** [comment]
Fixed in #3676.
