### ISSUE TITLE
Icon for ISQ client

### ISSUE THREAD

**Issue by ewgenius** [numixproject/numix-core#2914]
There is an official open source client [https://icq.com/linux/en](https://icq.com/linux/en)

isq.desktop

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=ICQ
Icon=icq
Path=/home/ewgenius/Applications/ISQ
Exec=/home/ewgenius/Applications/ISQ/icq
StartupNotify=false
OnlyShowIn=Unity;
X-UnityGenerated=true
```

default icon is ![github](https://raw.githubusercontent.com/mailru/icqdesktop/master/installer/resources/images/appicon.png)

**Comment by ewgenius** [comment]
default icon is here [github](https://github.com/mailru/icqdesktop/blob/master/installer%2Fresources%2Fimages%2Fappicon.png)

**Comment by ElvisPresly** [comment]
Its no new client
He is already a grandfather)))

**Comment by palob** [comment]
Closing because icq is now defunct.
