### ISSUE TITLE
Icon for XHydra

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-core#2939]
A icon for XHydra is missing in Numix Circle.

The icon line in the `.desktop` file says `xhydra`

Can't take screenshot or find the file (I think it is a bug with elementary OS)

**Comment by palob** [comment]
Please add the information [asked for](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

**Comment by maxtron95** [comment]
Original Icon:
![xhydra](https://user-images.githubusercontent.com/53346722/78075800-d37af600-736a-11ea-8b43-50ea99566a66.png)
