### ISSUE TITLE
Icon for XSensors

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-core#2940]
A icon for XSensors is missing in Numix Circle.

The icon line in the `.desktop` file says `/usr/share/pixmaps/xsensors/default.xpm`

![xsensors](https://cloud.githubusercontent.com/assets/13938848/14317854/d349599c-fc27-11e5-8d94-21b68eaaf6ec.png)

**Comment by SuicSoft** [comment]
@Foggalong How can I create a Numix Circle icon in GIMP

**Comment by Foggalong** [comment]
@SuicSoft We don't use GIMP, we use Inkscape to make vector graphics. If you're trying to get started just open an existing icon and have a play around with it.

**Comment by SuicSoft** [comment]
@Foggalong I will try InkScape . A C and F should be good

**Comment by ChuckDaniels87** [comment]
A meta-issue: the `bounty` label from BountySource is not applied anymore in the issues.

**Comment by SuicSoft** [comment]
@Foggalong I have made

![newxsensors](https://cloud.githubusercontent.com/assets/13938848/14761097/f21fe33c-0973-11e6-8f0d-cea611010217.png)

Do I get the bounty ?

**Comment by Foggalong** [comment]
No, the icon had to adhear to our design guidelines. That means symbol in the middle somewhere between 24px^2 and 30px^2 depending whether the shape is closer to a circle or square, and a drop shadow which for circle is 1px to the right and 1px down.

**Comment by Foggalong** [comment]
@ChuckDaniels87 Yeah, I'm not sure why that is. I might have to contact them

**Comment by ChuckDaniels87** [comment]
You can check the guidelines [here](https://github.com/numixproject/numix-wiki/wiki/Guidelines).

**Comment by W-Floyd** [comment]
This icon [already exists](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/xsensors.svg), has done for at least 3+ years (so far as I could tell).
