### ISSUE TITLE
Icon for Flappy Bird

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-core#2941]
Shashlik is an Android simulated enviorment : shashlik.io

A icon for Flappy Bird is missing in Numix Circle.

The icon line in the `.desktop` file says `/home/suici/.local/share/shashlik//com.dotgears.flappybird.png`

![com dotgears flappybird](https://cloud.githubusercontent.com/assets/13938848/14317800/8f1202c4-fc27-11e5-85b5-5de8813c4146.png)

**Comment by Foggalong** [comment]
We generally don't fix emulated applications unless it's a popular request. For now I've tagged the issue as wontfix but if at least 5 people +1 the request (using [GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) only please) then we'll do it.

**Comment by bilelmoussaoui** [comment]
@Foggalong What are we going to do with those kind of icon requests when the android icons will get merged with the core ones ?

**Comment by Foggalong** [comment]
They Android ones will be reopened: gonna have two request labels, one for Linux and one for Android :)
