### ISSUE TITLE
Icon for Chess Free

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-core#2942]
Shashlik is an Android simulated enviorment : shashlik.io

A icon for Chess Free is missing in Numix Circle.

The icon line in the `.desktop` file says `/home/suici/.local/share/shashlik//uk.co.aifactory.chessfree.png`

![uk co aifactory chessfree](https://cloud.githubusercontent.com/assets/13938848/14317822/9f0d8be4-fc27-11e5-8b94-d25b8acec381.png)

**Comment by palob** [comment]
Is that Shashlik thing something like Wine for Android?

**Comment by Foggalong** [comment]
Yeah, gonna rephrase the WINE policy to more generally talk about apps running through emulators.

**Comment by Foggalong** [comment]
We generally don't fix emulated applications unless it's a popular request. For now I've tagged the issue as wontfix but if at least 5 people +1 the request (using [GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) only please) then we'll do it.

**Comment by palob** [comment]
Closing due to lack of popularity.
