### ISSUE TITLE
Icon for Driftnet

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-core#2943]
A icon for Driftnet is missing in Numix Circle.

The icon line in the `.desktop` file says `driftnet`

The app doesn't have a default icon

**Comment by palob** [comment]
Please add the information [asked for](https://github.com/numixproject/numix-icon-theme-circle#icon-requests) to all of your request.

**Comment by SuicSoft** [comment]
@palob Done adding the information.

I think that this should be added to the GitHub issue template
