### ISSUE TITLE
Firewatch (Steam)

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#2991]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| Firewatch | `steam_icon_383870` | `Firewatch.desktop` | ![steam_icon_383870](https://cloud.githubusercontent.com/assets/7660997/14601009/f06272a2-055f-11e6-92d0-323674204b12.png) |

**Comment by Foggalong** [comment]
ngl, that formatting is really nice (cc: #2861)

**Comment by really-need-an-api-key** [comment]
Realized after exporting I forgot the shadows, but any of those colour combinations okay?
![firewatch svg](https://user-images.githubusercontent.com/11636003/56854679-b3f97300-693a-11e9-9255-48d1c1226491.png)
![firewatch2 svg](https://user-images.githubusercontent.com/11636003/56854680-b65bcd00-693a-11e9-9802-71f963516ab7.png)
The second one is based off https://blog.camposanto.com/post/166854367439

**Comment by palob** [comment]
Both look nice :+1:
