### ISSUE TITLE
Icon for Signal Private Messenger (Chrome Web App)

### ISSUE THREAD

**Issue by Ivan0xFF** [numixproject/numix-core#2997]
It'd be great to have an icon for the new Signal Desktop app.

Chrome Web Store: https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=en

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Signal Private Messenger
Exec=/usr/bin/chromium --profile-directory=Default --app-id=bikioccmkafdpakkkcpdbppfkghcmihk
Icon=chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default
StartupWMClass=crx_bikioccmkafdpakkkcpdbppfkghcmihk
```

**Comment by kpuljek** [comment]
This would be really sweet!

**Comment by kpuljek** [comment]
I made two, maybe these could help? Made by modifying the existing circle icons, so they should fit perfectly. One is based on the android icon, the other on the ios/chrome app.
[signal icons.zip](https://github.com/numixproject/numix-core/files/538939/signal.icons.zip)

**Comment by kpuljek** [comment]
[signal icons 2.zip](https://github.com/numixproject/numix-core/files/538963/signal.icons.2.zip)
 Fixed centering on one of the icons, sorry

**Comment by Foggalong** [comment]
@kpuljek Please submit proposed icons as pull requests, it makes it much easier to give feedback :)

**Comment by kpuljek** [comment]
Never did that before, I'll try! :) Bear with me
