### ISSUE TITLE
Icon for Cronopete

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-core#3001]
http://www.rastersoft.com/programas/cronopete.html

Icon=cronopete_preferences.svg
![1](https://cloud.githubusercontent.com/assets/18265958/14675321/1f7e21c8-0711-11e6-9e7c-5703ac36cb8c.png)

Icon=cronopete_restore.svg
![default](https://cloud.githubusercontent.com/assets/18265958/14675325/268879aa-0711-11e6-82cb-b2219fbcd470.png)

Thx

**Comment by ghost** [comment]
7 years :) 7 Karl
