### ISSUE TITLE
Icon for Simplenote

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-core#3005]
![simplenote](https://cloud.githubusercontent.com/assets/11137173/14702942/86372f30-07ad-11e6-9785-eb37d6cde04f.png)

```
[Desktop Entry]
Name=Simplenote
Comment=Simplenote for Linux
Exec=/usr/share/simplenote/simplenote
Icon=simplenote
Type=Application
StartupNotify=true
```

**Comment by Corsseir** [comment]
When are you going to add this icon to icon theme?

**Comment by Foggalong** [comment]
As soon as we can. There are icons [way older than yours](https://github.com/numixproject/numix-icon-theme-circle/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc) still waiting on being added.
