### ISSUE TITLE
Tomb Raider [2013] (Steam)

### ISSUE THREAD

**Issue by fusionlightcat** [numixproject/numix-core#3165]
Game: Tomb Raider (2013)
AppID: 203160

Icon: ![4e5d7f3492149b8f06343ce670a0432e4f8c108d](https://cloud.githubusercontent.com/assets/1558185/15322331/6d36661a-1c3c-11e6-8f07-b5109869e696.png)

Note: This game is now officially supporting Linux.

**Comment by bilelmoussaoui** [comment]
Fixed
