### ISSUE TITLE
Icon for Portal Stories: Mel (Steam)

### ISSUE THREAD

**Issue by tkdberger** [numixproject/numix-core#3170]
Game: Portal Stories: Mel
AppID: 317400
Current icon: 
![portal2](https://cloud.githubusercontent.com/assets/8628974/15440771/495df97c-1ea5-11e6-8d5d-2dd912138f68.png)

Notes: It _is_ a Portal 2 mod, however it has its own launcher/game data so I believe that shouldn't be an issue.

**Comment by tkdberger** [comment]
I decided to start playing with this one on my own while I wait.
Found an Aperture logo on Wikipedia, have begun hacking at it in Inkscape.

Progress:
![aperture_science svg](https://cloud.githubusercontent.com/assets/8628974/15441359/67e38274-1ea8-11e6-8782-59537b101358.png)

**Comment by tkdberger** [comment]
Welp, I have no idea what I'm doing.

**Comment by tkdberger** [comment]
Reccomending @Foggalong unsubcribes from this thread, as I'll probably be posting a lot of useless stuff on it as I work.

**Comment by bil-elmoussaoui** [comment]
@tkdberger you can fork the repo and work on it until the icon is ready & btw you can use portal 1 or portal 2 icon as base for your icon ;)

**Comment by tkdberger** [comment]
I would use the portal 1 or 2 icons, but they aren't even close to the icon I want.

I really don't have the skill to make anything of decent quality, just something to work off of besides the normal icon.

**Comment by tkdberger** [comment]
Potato quality icon:
![portal2](https://cloud.githubusercontent.com/assets/8628974/15442237/cceef0ea-1ead-11e6-8157-fff2d907b926.png)
