### ISSUE TITLE
Icon for Zeegaree Pomodoro-Indicator

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-core#3173]
A Numix-circle-icon for **Zeegaree Pomodoro-Indicator** is missing.

The icon says "zeegaree" and original is attached.

![zeegaree pomodoro-indicator](https://cloud.githubusercontent.com/assets/11943860/15449352/75361898-1f51-11e6-9e13-5dfda124f3f7.png)

**Comment by Foggalong** [comment]
I know we already have a symlink for this, but I'm leaving it open because I could have sworn that we had an actual stand alone icon for this. Could have sworn as in, I distinctly remember having the SVG for it on my desktop.

**Comment by bil-elmoussaoui** [comment]
@Foggalong Yes, Numix has already an [icon](https://github.com/bil-elmoussaoui/core-demo/blob/29567c2296e6f684855d08eb5f5099b0a9090851/data.json#L6877)

**Comment by Foggalong** [comment]
@bil-elmoussaoui That's a symlink, I'm talking about an actual SVG icon

**Comment by palob** [comment]
Seems defunct, can't find the app.

**Comment by Foggalong** [comment]
Definitely defunct https://github.com/mivoligo/Zeegaree

**Comment by palob** [comment]
Thanks for dropping by!
