### ISSUE TITLE
Icon for Unity Launcher Folders

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-core#3175]
A Numix-circle-icon for **Unity Launcher Folders** is missing.

Icon=/usr/share/unity-launcher-folders/media/unity-launcher-folders.png

Website Project: http://unity-folders.exceptionfound.com/

![unity-laucher-folders](https://cloud.githubusercontent.com/assets/11943860/15455749/391e4928-2034-11e6-93a7-e4783eb36c24.png)

**Comment by palob** [comment]
project defunct.
