### ISSUE TITLE
Icon For - Forticlient SSL VPN

### ISSUE THREAD

**Issue by praveenpuglia** [numixproject/numix-core#3201]
This one is missing and the original icon is ugly. Here are the details.

Original Icon - 
![image](https://cloud.githubusercontent.com/assets/313363/15742077/6e664c3a-28da-11e6-9e84-13ee2591f0f1.png)

`Icon=/opt/forticlient-sslvpn/forticlientsslvpn.gif`

**Comment by palob** [comment]
Got, renamed a bit which means icon name and icon design also got changed.
