### ISSUE TITLE
Turtl icon

### ISSUE THREAD

**Issue by ismaelgv** [numixproject/numix-core#3203]
**App:** Turtl
**Description:** Turtl lets you take notes, bookmark websites, and store documents for sensitive projects.
**Website:** https://turtl.it/
**Icon name:** turtl

![com lyonbros turtl-w250](https://cloud.githubusercontent.com/assets/8478202/15789543/1ba40534-29cd-11e6-8ea2-8baaa8329638.png)

**Comment by palob** [comment]
Are you going to give this a shot?

**Comment by ChuckDaniels87** [comment]
@palob I've got a lot of work lately and I won't be able to make the icon soon, so it is yours if you want it. :+1:

**Comment by palob** [comment]
Closing because turtl has been unmaintained for 5+ years.
