### ISSUE TITLE
Icon for JetBrains Project Rider C# IDE

### ISSUE THREAD

**Issue by Bulmanator** [numixproject/numix-core#3226]
This IDE is currently still in development so that is probably why it currently doesn't have an icon
Also unfortunately, like all other JetBrains IDEs (IntelliJ, PyCharm etc..), its icon is hardcoded. However I really like the new ones you have made for both IntelliJ and PyCharm so one for this would be a nice addition

![rider_128](https://cloud.githubusercontent.com/assets/8584482/16063380/c5e1cd1c-3290-11e6-9a73-bb3d8f4a09f5.png)

This is the current Project Rider Icon. The name of the IDE is probably subject to change as well due to it being in early development

Desktop file: `jetbrains-rider.desktop`
Icon line: `/opt/JetBrains Project Rider/bin/Rider_128.png`

However as the image path is not set. The /opt/JetBrains Project Rider/ is relative to where the user has chosen to install the application. So the **bin/Rider_128.png** would be the important part.

I think that Issue #2730 covers JetBrains products however this one didn't get done because they are still developing it

**Comment by RicardoEPRodrigues** [comment]
Instead of doing a single issue for each of JetBrains icons why not just do for all? 😀

**Comment by palob** [comment]
Could you please post the hardcoded icon path and the name of the ``.desktop`` file?

**Comment by Bulmanator** [comment]
Sorry for not providing this in my initial post
The  <code>.desktop</code> is called **jetbrains-rider.desktop**
and the icon path is currently **/opt/JetBrains Project Rider/bin/Rider_128.png**, however as the image path is not set. The /opt/JetBrains Project Rider/ is relative to where the user has chosen to install the application. So the **bin/Rider_128.png** would be the important part

I think that Issue #2730 covers JetBrains products however this one didn't get done because they are still developing it
