### ISSUE TITLE
Icon for FORCED (Steam)

### ISSUE THREAD

**Issue by Wintro** [numixproject/numix-core#3233]
**Game:** FORCED
**AppID:** 249990
**Icon:**
![FORCED](https://cloud.githubusercontent.com/assets/16349988/16133129/f539a640-341e-11e6-94c3-1fe3f5880e92.jpg)
**Banner:**
![FORCED](https://cloud.githubusercontent.com/assets/16349988/16133134/fb913f80-341e-11e6-943a-4efda641295b.jpg)
**Notes:** The icon here is very low resolution, but it seems like a down-scaled version of the glowing orb in the center of the "O" letter in the banner. Maybe keeping the same style of the single orb being the icon but basing it off the banner orb would be a good course of action.

**Comment by really-need-an-api-key** [comment]
I was actually thinking of doing a thing with this layout and started a while ago but forgot about it.
![forced](https://cloud.githubusercontent.com/assets/11636003/19071306/a9864f34-8a2f-11e6-8744-3fd5f4a7ffe8.png)
Still have to decide on line weights and elements scale and whatnot, fill the circle and add some bells and whistles, and I think I should remove the highlights on the bars to make it look flatter.

**Comment by really-need-an-api-key** [comment]
Would something like this be acceptable?
![forced 48 svg](https://cloud.githubusercontent.com/assets/11636003/19108641/e16a3dc6-8af1-11e6-8592-9636fe0f74b8.png)
![forced 192 svg](https://cloud.githubusercontent.com/assets/11636003/19108646/e5690eb6-8af1-11e6-9d73-914bbef92913.png)

**Comment by Foggalong** [comment]
I think so yeah, but it's difficult to tell based on the png alone. If you open a pull request we can give you some proper feedback :)
