### ISSUE TITLE
Icon for Emojione Picker for Ubuntu (emojione-picker)

### ISSUE THREAD

**Issue by sagarpanchal** [numixproject/numix-core#3255]
An icon for [Emojione Picker for Ubuntu](https://github.com/gentakojima/emojione-picker-ubuntu) is missing.
The icons line says "emojione-picker".

![raw](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon.svg)

[icon-mono-dark-16](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-dark-16.png)
[icon-mono-dark-22](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-dark-22.png)
[icon-mono-dark-24](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-dark-24.png)
[icon-mono-dark-32](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-dark-32.png)
[icon-mono-dark-48](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-dark-48.png)
[icon-mono-dark-64](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-dark-64.png)
[icon-mono-light-16](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-light-16.png)
[icon-mono-light-22](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-light-22.png)
[icon-mono-light-24](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-light-24.png)
[icon-mono-light-32](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-light-32.png)
[icon-mono-light-48](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-light-48.png)
[icon-mono-light-64](https://github.com/gentakojima/emojione-picker-ubuntu/blob/master/assets/icon-mono-light-64.png)

**Comment by Foggalong** [comment]
@sagarpanchal Please report panel icons in the base theme (numix-icon-theme) :)
