### ISSUE TITLE
Kicad Icons Request

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#3265]
I am just starting this issue. [Kicad](http://kicad-pcb.org/) is composed by a set of tools. Kicad itself already has an icon (`kicad`) but related tools don't. Though the default **kicad** numix icon is pretty different than the original. I think it should have some elements that match with the original. 

Here are the icons and their names:

![images](https://cloud.githubusercontent.com/assets/1277920/17199913/333ef884-5457-11e6-807f-fc20f21f6509.png)
- [x] kicad (already has an numix icon, but it should be iproved)
- [x] eeschema
- [x] pcbnew
- [x] pcbcalculator
- [x] bitmap2component
- [x] gerbview
- [ ] ~~cvpcb~~ removed on kicad 4.1+ ?
- [ ] pl_editor

**Comment by Foggalong** [comment]
Please add the information set out in the readme. Mimetypes need reporting [here](https://github.com/numixproject/numix-icon-theme)

**Comment by nupole** [comment]
Eeschema is a particular Kicad program that needs a numix circle icon.

The icon line reads "Icon=eeschema" and the icon is attached below.

![screenshot from 2016-07-04 15 37 04](https://cloud.githubusercontent.com/assets/19938589/16569540/4bf0d102-41fd-11e6-8d92-fa58dc4dc85e.png)

**Comment by leoheck** [comment]
Good, thank you @nupole but I think there are more. There are mime types missing too, I will post whenever I have time.

**Comment by leoheck** [comment]
Actually, all icons are:

![images](https://cloud.githubusercontent.com/assets/1277920/17199913/333ef884-5457-11e6-807f-fc20f21f6509.png)

By the way, the default **kicad** numix icon is pretty different than the original. I think it should have some elements that match with the original. 

- **/usr/share/applications/kicad.desktop**
```
[Desktop Entry]
Icon=kicad
MimeType=application/x-kicad-project;
```

- **/usr/share/applications/eeschema.desktop**
```
[Desktop Entry]
Icon=eeschema
MimeType=application/x-eeschema-schematic;
```

- **/usr/share/applications/pcbnew.desktop**
```
[Desktop Entry]
Icon=pcbnew
MimeType=application/x-pcbnew-pcb;
```

- **/usr/share/applications/pcbcalculator.desktop**
```
[Desktop Entry]
Icon=pcbcalculator
MimeType=application/x-pcbcalculator-project;
```

- **/usr/share/applications/bitmap2component.desktop**
```
[Desktop Entry]
Icon=bitmap2component
MimeType=application/x-bitmap2component-project;
```

- **/usr/share/applications/gerbview.desktop**
```
[Desktop Entry]
Icon=gerbview
MimeType=application/x-gerbview-project;
```

- **/usr/share/applications/cvpcb.desktop**
```
[Desktop Entry]
Icon=cvpcb
MimeType=application/x-cvpcb-project;
```

**Comment by Foggalong** [comment]
I moved the content of the previous comment to the original description so that we can utilise GitHub lists, and I've moved your mimetype requests to the base theme so they can be properly addressed there.

**Comment by Jacajack** [comment]
Some time ago, I started creating Kicad/Eeschema icon, and this is what I've got:

![selection_829](https://cloud.githubusercontent.com/assets/6173262/17948532/7e8ae946-6a51-11e6-87b3-480b821cf0fc.png)

I think this might be icon for either Eeschema, or for Kicad, after some little adjustments.
What's your opinion about it?

**Comment by leoheck** [comment]
Ideas. From left to right: kicad, eeschema, pcbnew

The icon on pcbnew represents a layout of the circuit in eeschema icon. And the first one (kicad), is the mix of both. I know the icons has lot of info and are bad for icons but this some ideas to start with.
The pcbnew icon can be further improved to place commponents on the same place of eeschema. 

![selection_022](https://cloud.githubusercontent.com/assets/1277920/18030697/bba4b5d6-6c96-11e6-98fe-ead49818a1e0.png)

The sources... 
https://www.dropbox.com/s/u9mb4kqmk7phbmd/kicad.svg?dl=0
https://www.dropbox.com/s/5n93g2ypuzdq09s/eeschema.svg?dl=0
https://www.dropbox.com/s/92fardfic65q665/pcbnew.svg?dl=0

**Comment by Jacajack** [comment]
What about something like this for `pcbnew`?
![selection_842](https://cloud.githubusercontent.com/assets/6173262/18038298/865632f0-6d96-11e6-9325-cefd7edcaebe.png)

I'm not sure if it looks right, though :confused:

**Comment by Foggalong** [comment]
@leoheck Those icons are way too detailed - even at 48px (which is the size of icon we provide) you'll end up loosing massive amounts of detail to blur. I like the idea of the circuit diagrams though 

@Jacajack Those icons for pcbnew look good, but make the lines leading to the boxes thinner and the boxes smaller and more central. Possibly experiment with using different shades of green/purple with one for the box and one for the wire?

**Comment by leoheck** [comment]
I agree @Foggalong I can make them with less details.. let me see.

**Comment by Jacajack** [comment]
@Foggalong I will see what I can do today. I'm only afraid about those diagonal paths, because they look blurry when you look at the icon in its original size.

**Comment by leoheck** [comment]
@Jacajack, do you like the icons? I think we can think together here..

**Comment by Jacajack** [comment]
@leoheck Of course! :+1: They are great in my opinion, but I'm afraid that symbols are little bit too big, though.

Anyway, we still have PCB calculator, bmp2component, gerber view (we already have an icon for `gerbv`, so I guess this one should be somewhat similar) and cvpcb left.

**Comment by Foggalong** [comment]
@leoheck Those are definitely along the right lines, and I especially like the Kicad one. @Jacajack is right that the symbols are a bit too big, and there's possibly some alignment issues too but those can both wait til pull request review.

@Jacajack Diagonal paths are impossible to avoid completely and are okay to have here and there, so don't worry too much about them

**Comment by Jacajack** [comment]
@Foggalong Alright, so I made the tracks thinner, changed color of the pads and this is what I've got:
![selection_853](https://cloud.githubusercontent.com/assets/6173262/18145846/3d40ae86-6fcd-11e6-87e3-3589fca2c9fc.png)

I used same colors as @leoheck, to make icons look more compatible. I thought about adding more paths, to make the icon look more like PCB editor rather than footprint editor. I can open pull request if you want, but to be honest, I think that Leo's icon is better :)

**Comment by Foggalong** [comment]
@leoheck Which of your icons corresponds to @Jacajack's? Sorry for the ignorance, I'm not familiar with the software

**Comment by Jacajack** [comment]
@Foggalong Judging from filenames, it's the right one

**Comment by Foggalong** [comment]
Yeah, looking at the footprint editor I'd say yours was more appropriate for that and then @leoheck's for the PCB editor.

**Comment by Jacajack** [comment]
@Foggalong, actually, I thought other way around, because @leoheck's icon shows single footprint (which is basically the pattern of copper on the PCB that you solder your element to), and mine has footprint and some tracks (you don't do that in footprint editor).

Anyway, if we need only one icon, I'd pick his one :)

**Comment by leoheck** [comment]
Sorry, I forget to name icons... from left to right: ``kicad, eeschema and pcbnew``

I agree with @Jacajack we have to improve my ``pcbnew``. However, ``eeschama`` shows a transistor, so what about to make the same component for ``pcbnew``, like I did? This makes the design more connected, I think. So, it is possible to choose an SMD transistor instead of my choice that uses a thru-hole. I agree to add some tracks on the pads to simulate the connections making it seems more layout editor, as you said. 

I will improve all of them. There are some guidelines I should follow? I have been following my feelings only.

Someone has any idea for the other icons? I also think ``cvpcb``, in kicad 4.1 (beta) was removed.

**Comment by leoheck** [comment]
![selection_026](https://cloud.githubusercontent.com/assets/1277920/18154789/1597c53e-6fde-11e6-91c7-f6fbece37f72.png)
![selection_025](https://cloud.githubusercontent.com/assets/1277920/18154536/ee7404ec-6fdb-11e6-93ac-4a97ac8f8e84.png)

- Kicad reduced, with the orange ball increased and alignment improved
- Esschema reduced, with Kicad light blue and alignment improved
- Pcbnew reduced with tracks in Kicad-orange

**Comment by Jacajack** [comment]
@leoheck Nice! :+1:

Don't get me wrong, I meant to say that If we had to make two icons (one for footprint editor, and one for pcbnew) the track would possibly be useful hint. In this case, in my opinion, the version of icon without tracks looks even a bit better (and because you added tracks symbol is still too big, but maybe if they were thinner and would lead outside the icon base (like mine do) it would be alright).

SMD transistors are boring, by the way, I think that TO-92-like footprint is fine. Every electronics beginner will assume it's a transistor, and seeing for example SOT-23 may not be so obvious.
![selection_855](https://cloud.githubusercontent.com/assets/6173262/18163191/13376a86-703a-11e6-9b27-12ad3be1347f.png)


`cvpcb` is still here, but not available through desktop file, so I guess we don't need icon for it.

**Comment by Jacajack** [comment]
Ok, I have prototype of icon for bmp2component

![selection_862](https://cloud.githubusercontent.com/assets/6173262/18164920/d5008096-7042-11e6-9702-ba449a0cba7f.png)

Color can be changed of course. What do you think about this?

**Comment by leoheck** [comment]
Thank you for the guidelines and comments. My icons are just a good draft for numix team/community since I am not a designer but I can try to improve them with your tips.

I think all tools should have an icon, because they will appear in dash/dock if the application is opened. Look, the last one is the default ``bmp2component``
![screenshot from 2016-09-01 08-14-19](https://cloud.githubusercontent.com/assets/1277920/18165539/2d8bf640-701c-11e6-9eec-9b1175f47cfa.png)
 

- ``Kicad`` is very good for me
- ``Eeschema`` is almost there
- I actually do not like ``pcbnew`` yet and do not have any ideas to improve it. 
- ``footprint`` editor can be like pcbnew without the tracks, but it could have any other device, I think.
- I like your ``bmp2component`` 
- ``pcbcalculator`` can use this image as a reference.  It shows a track over the FR4 substrate over a copper plane. Sure, FR4 should be green :) 

![pcb_calculator](https://cloud.githubusercontent.com/assets/1277920/18165756/81398fcc-701d-11e6-8b0b-40bc5e1ee03c.png)

- ``gerberview`` can have a green square to represent the pcb (as in pcbcalculator) with a  magnifying glass. 

Toughts?

**Comment by Jacajack** [comment]
@leoheck Hey, wait.... are we going to make icons for things not listed in Ubuntu launcher too, or not?

**Comment by Jacajack** [comment]
@leoheck, that sounds right.
Though if we are lazy, we can link `gerberview` to `gerbv` icon. 

If you want I can modify your icons to meet guideline.
I can also try to modify your `eeschema` icon in order to get Footprint Editor icon.

**Comment by leoheck** [comment]
Yeah, I am fine with that.

**Comment by Jacajack** [comment]
Ok, so here's what we've got so far:

 - Kicad: 

![selection_869](https://cloud.githubusercontent.com/assets/6173262/18173031/4fb9dd08-7068-11e6-9255-bb6fd597ec68.png)![selection_870](https://cloud.githubusercontent.com/assets/6173262/18173032/5161c9d6-7068-11e6-8f0f-4f371c713087.png)

- Eeschema:

![selection_871](https://cloud.githubusercontent.com/assets/6173262/18173053/6ffa40f8-7068-11e6-9856-72f728a2cf19.png)![selection_872](https://cloud.githubusercontent.com/assets/6173262/18173058/734bff58-7068-11e6-999d-f51c8b7f5d38.png)

- PCBnew or Footprint editor (I'm going to create second version of this icon, and then see what it matches better)

![image](https://cloud.githubusercontent.com/assets/6173262/18173140/c2ccdfde-7068-11e6-8ff6-46e8d4e93f24.png)![selection_873](https://cloud.githubusercontent.com/assets/6173262/18173143/c644427e-7068-11e6-8ffd-ac4584652709.png)

- Bitmap 2 component:

![selection_875](https://cloud.githubusercontent.com/assets/6173262/18173217/1ae31512-7069-11e6-841a-109cf73689a6.png)![selection_876](https://cloud.githubusercontent.com/assets/6173262/18173224/1e830844-7069-11e6-84df-378f743398d3.png)

https://drive.google.com/folderview?id=0B6I7tshTB6Z2a19GY1J0dkF1a1k&usp=sharing
*I left the icons in looking ok, but not ready to be committed state, just in case I had to edit them afterwards*

What do you think about it?

**Comment by leoheck** [comment]
Nice! I will make some drafts for other icons too.

**Comment by leoheck** [comment]
An idea for pcbcalculator. I think a ruler or  set-square is missing..
![selection_027](https://cloud.githubusercontent.com/assets/1277920/18188061/2f75600e-7085-11e6-9dc2-47e902d3daf4.png)

Maybe a yellow version of this:
![2000px-reglas svg](https://cloud.githubusercontent.com/assets/1277920/18188110/957612c2-7085-11e6-9c28-e1a6930e8d83.png)

**Comment by leoheck** [comment]
@Jacajack, rename the bmp2component.svg to bitmap2component.svg

**Comment by Foggalong** [comment]
@leoheck If you want a set square to use have a look at the glade icons :)

**Comment by Jacajack** [comment]
@leoheck, I'm not working on git repository yet, I was going to change it before committing. Thanks for reminding me anyway :)

**Comment by Jacajack** [comment]
@leoheck What about this?
![selection_881](https://cloud.githubusercontent.com/assets/6173262/18207621/31f0b368-712c-11e6-9959-46214e2c6558.png)

**Comment by leoheck** [comment]
@Jacajack can you puty it in your shared folder.. I would like to try some rotations.

**Comment by Jacajack** [comment]
@leoheck I'm away from home this weekend. I can upload it on Sunday
evening. Sorry...

2 wrz 2016 20:07 "Leandro Heck" <notifications@github.com> napisał(a):

@Jacajack <https://github.com/Jacajack> can you puty it in your shared
folder.. I would like to try some rotations.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/numixproject/circle-core/issues/3265#issuecomment-244447813>,
or mute the thread

**Comment by Jacajack** [comment]
@leoheck, I uploaded it. Of course it's development version, so you might find some rubbish around. I'm going to play around with it more tomorrow :)

**Comment by Jacajack** [comment]
@leoheck, alright, so here are 2 variants you probably wanted to try.
Personally, I prefer the first one below:
![selection_885](https://cloud.githubusercontent.com/assets/6173262/18248538/1a7be56e-7379-11e6-8403-4f0b63aea19b.png)![selection_884](https://cloud.githubusercontent.com/assets/6173262/18248540/1c712898-7379-11e6-8497-db784eea04e5.png)

**Comment by leoheck** [comment]
Personally, I like the ones which have the yellow set-square and the thick tracks. @Foggalong which one do you like most?

**Comment by Jacajack** [comment]
@leoheck, it's alright, otherwise I wouldn't many different variations of the icon :)

**Comment by Foggalong** [comment]
@Jacajack What does [this one](https://cloud.githubusercontent.com/assets/6173262/18248634/c3f975ca-7379-11e6-96a3-6860d6ca9bff.png) look like rotated a quarter turn clockwise and then flipped through the Y-axis?

**Comment by Jacajack** [comment]
@Foggalong 
![image](https://cloud.githubusercontent.com/assets/6173262/18366840/889dd54c-7618-11e6-8b27-5506172b1909.png)

So I guess now the question is "which rotation of the same thing do we like best?"

**Comment by Foggalong** [comment]
That one, definitely :+1:

**Comment by Jacajack** [comment]
@Foggalong, alright :)
We have still 3 more to go - I will try to make some drafts tomorrow.

**Comment by leoheck** [comment]
cvpcb can be a mix from eeschema and pcbnew... maybe one overlapping the other.

**Comment by Jacajack** [comment]
@Foggalong, @leoheck, `cvpcb` is a utility to edit netlists (files that define how components are connected).
Later, the information is displayed by `pcbnew` as so caled *ratnet*. It looks somewhat like [weird spider web](http://audio.engineeringvista.com/AudioKits/Phono-1/Design/Images/ImportedNetlist.gif).

![selection_915](https://cloud.githubusercontent.com/assets/6173262/18395055/0dc2d9c6-76bd-11e6-9043-b3a321fc3dc6.png)
*Just a draft to show you my idea.*

And this is basically where my idea comes from. I'm also thinking about simpler design with only few connected nodes, marked as little circles. Unfortunately, I'm afraid that I may have seen similar Numix icon somewhere already, I'm not sure though.

Also, this symbol could be used on netlist mimetype.

**Comment by Foggalong** [comment]
@leoheck overlapping symbols only really works if there's a significant size difference between the two and if the colours match - where possible, a unique symbol would be preferable.

**Comment by Jacajack** [comment]
@Foggalong, something like this maybe?

![image](https://cloud.githubusercontent.com/assets/6173262/18403210/b94cd0f0-76e3-11e6-9dfd-719936a27d95.png)

**Comment by Foggalong** [comment]
I have no idea what these programs do so I can only compare them to their original iconography, but this is a well design icon yes :)

**Comment by Jacajack** [comment]
@Foggalong, no problem. Anyway, I'm glad to hear you like it :)

**Comment by Jacajack** [comment]
I've been lazy for almost two weeks now. It's definitely time to get back to work...

One thing I'm still unsure about are icons for `cvpcb`, `pl_editor` and footprint editor. I can't [find them](http://pastebin.com/ZW56qQ8S) anywhere (apart from `/usr/share/doc/kicad/help/en/images/icons`, but apparently modifying them doesn't change anything), so I suppose they are some kind of hardcoded into Kicad itself. (I use Kicad 4.10-alpha)

Also, `cvpcb` and footprint editor icons are not visible on launcher while programs are running.
Though, PL editor's icon appears in launcher when it's running, it cannot be ran from launcher menu and the icon is really kind of... well... missing.

*Eeschema and `cvpcb` stack up:*
![image](https://cloud.githubusercontent.com/assets/6173262/18673565/85af3bea-7f4c-11e6-89b8-48e7a3229aa1.png)

In this case we only have `gerbview` icon left to do, and I think all those tiny icons that appear **in** Kicad (if they can be changed) should be treated as yet another issue.

**Comment by leoheck** [comment]
Good work @Jacajack, we have to report a bug in kicad telling them to use system icons.

**Comment by Jacajack** [comment]
@leoheck, ok, I guess I'll start setting up new branch on my fork to prepare pull request.

**Comment by leoheck** [comment]
Good, I've created a kicad bug report.
https://bugs.launchpad.net/kicad/+bug/1625865

The next step is to improve kicad mimetypes, https://github.com/numixproject/numix-icon-theme/issues/1111#issuecomment-237663961

**Comment by Jacajack** [comment]
@leoheck, marvelous. :+1:

I'm creating pull request right now. I'm going to help you with mimetypes too, just as soon as we finish this.

**Comment by Jacajack** [comment]
@leoheck Since we're done here, I think you can close this issue :)

**Comment by leoheck** [comment]
Sure! Good work @Jacajack

**Comment by Foggalong** [comment]
@Jacajack Are you not wanting fixes for the remaining two icons?

**Comment by leoheck** [comment]
I thought all was done, forgot that.

**Comment by Jacajack** [comment]
@Foggalong @leoheck 

I described problem with them in this post: https://github.com/numixproject/numix-core/issues/3265#issuecomment-248314730. If I only knew how to change them, I would have added them too. I asked question about them at Kicad's launchpad page - https://answers.launchpad.net/kicad/+question/403823.

Obviously, we can add them now for future use if you want.

**Comment by Foggalong** [comment]
Ah okay, I'll close this until the situation upstream changes then :)
