### ISSUE TITLE
Icon for RationalPlan

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-core#3270]
A Numix-circle-icon for RationalPlan is missing.

This software cointains 3 versions: Project, Single, Multi.

![captura de tela de 2016-07-06 01-17-08](https://cloud.githubusercontent.com/assets/11943860/16607449/658fc788-4317-11e6-979e-d38b9a49747a.png)

**The background color is related to your version.**

![captura de tela de 2016-07-06 01-20-23](https://cloud.githubusercontent.com/assets/11943860/16607485/d8d3efb2-4317-11e6-8144-b467bce6e917.png)

Icon=rationalplan-single
Icon=rationalplan-multi
Icon=rationalplan-project

Website Project: http://www.rationalplan.com/index.php

**Comment by Jacajack** [comment]
@Foggalong I think this can be closed :)

**Comment by Foggalong** [comment]
Indeed it can :)
