### ISSUE TITLE
When starting most apps: Invalid Context= "Panel" line for icon theme

### ISSUE THREAD

**Issue by goetzc** [numixproject/numix-core#3277]
I get this output, it seems when starting Qt apps, GTK+ apps don't show this.
Qt 5.7.0, GTK+ 2.24.30, GTK+ 3.20.6

```
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16x16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/22x22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/24x24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48/notifications/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48@2x/notifications/"
```

**Comment by palob** [comment]
Can confirm for Miunet (KDE KF5 app) but it's just warnings. Doesn't hurt.

**Comment by goetzc** [comment]
> but it's just warnings. Doesn't hurt.

It hurts my eyes :)  
No, seriously, it clutters the terminal, and other data sent to stdout or stderr is buried alive.

Imagine all apps with small warnings here and there, all filling the terminal output with uninteresting text mixed with useful data.

**Comment by palob** [comment]
I think it is an issue for the [base theme](https://github.com/numixproject/numix-icon-theme).

I'm no panel icons expert but i don't think we could do without the ``panel`` context.

**Comment by Foggalong** [comment]
By the looks of things it's an issue with both :(

**Comment by Foggalong** [comment]
Is this because panel is a non-standard context?

**Comment by hirschmann** [comment]
You are right, KDE complains when it finds non-standard contexts, see

- https://github.com/KDE/kiconthemes/blob/master/src/kicontheme.cpp#L672
- [Icon Theme Specification](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#context)
- [Icon Naming Specification](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)

This warning can be fixed by replacing all occurrences of `Context=Panel` and `Context=Notifications` in _index.theme_ with valid contexts (e.g. `Context=Status`).

**Comment by Foggalong** [comment]
@wa4557 @palob Would changing these mess with the workaround at all?

**Comment by palob** [comment]
IIRC we somewhat rely on those invalid contexts. Not sure.

**Comment by arthurflor23** [comment]
I get this output too and some softwares "can't find some icons", like this:
![image](https://cloud.githubusercontent.com/assets/11759042/25555995/895f91fa-2cca-11e7-878b-cdb16a8c96d0.png)
 
> This warning can be fixed by replacing all occurrences of Context=Panel and Context=Notifications in index.theme with valid contexts (e.g. Context=Status).

Doesn't worked to me.. btw, this package "menda-circle" works fine here (but was depreciated):
https://github.com/manjaro/menda-icon-themes

I'm using Arch Linux with KDE.

**Comment by palob** [comment]
Please open a seperate issue for the missing icons. We can't however fix this without knowing the icon names.

Menda is an outdated downstream distribution of our theme which we have no leverage on.

**Comment by palob** [comment]
@arthurflor The missing icons are most probably part of this list https://github.com/numixproject/numix-icon-theme/issues/580.

Can you please navigate to ``/usr/share/icons/Numix`` (or whereever your Numix theme is installed to), open ``index.theme`` in a text editor and add ``,breeze`` or ``,Breeze`` (don't know which one's correct) to the end of the ``Inherits= ...`` line and see if something chnages?

**Comment by andia89** [comment]
Changing the context doesn't change anything for the icon lookup btw. So maybe we should change it to "status"

**Comment by arthurflor23** [comment]
> Can you please navigate to /usr/share/icons/Numix (or whereever your Numix theme is installed to), open index.theme in a text editor and add ,breeze or ,Breeze (don't know which one's correct) to the end of the Inherits= ... line and see if something chnages?

It works, I put "breeze".
All the icons that were missing on system, came back:
![image](https://cloud.githubusercontent.com/assets/11759042/25557068/babd1816-2cdf-11e7-95a1-83d26d81f2a9.png)

**Comment by palob** [comment]
@arthurflor This is related to https://github.com/numixproject/numix-icon-theme/issues/1042.

**Comment by Foggalong** [comment]
Sam uses `Context=Status` for [panel/](https://github.com/snwh/faba-icon-theme/blob/master/Faba/index.theme#L345-L355) and [notifications/](https://github.com/snwh/faba-icon-theme/blob/master/Faba/index.theme#L337-L342) in Faba and Faba-Mono so it would seem it doesn't cause any problems to match up non-standard folders with standard contexts :+1:

**Comment by bilelmoussaoui** [comment]
@Foggalong This should be moved to the packaging repo, as we don't have any index.theme file here to deal with it.

**Comment by Foggalong** [comment]
Aye
