### ISSUE TITLE
Monogame Pipeline icon

### ISSUE THREAD

**Issue by HoratiuMl** [numixproject/numix-core#3284]
Icon for monogame pipeline

Original icon:
<img width="512" alt="monogame" src="https://cloud.githubusercontent.com/assets/10261133/16708082/2a0a6792-45ef-11e6-8a3b-f16f7a1b5292.png">

Desktop file: /usr/share/applications/Monogame\ Pipeline.desktop
Icon line: Icon=monogame

------------

![monogame](https://cloud.githubusercontent.com/assets/10261133/16708099/aea5580e-45ef-11e6-94a0-8d62cf82a777.png)
I've created this one, based on the original svg icon. What do you guys think, is it ok like that or should we make it more fancy? I'm not very sure if I put the objects at the right coordinates tho

Edit: How do I upload the original SVG instead of PNG?

**Comment by bil-elmoussaoui** [comment]
Sadly you can only upload binary files (png, jpg...). If you want to upload the SVG file of the icon you've designed, feel free to open a PR

**Comment by palob** [comment]
@Hori873 Can you please open a PR so we can review your icon draft?

**Comment by Hori873** [comment]
Yes, I will do that as soon as I repair my laptop. Unfortunately it broke a few days ago :(

**Comment by palob** [comment]
Could you retrieve your draft?

**Comment by Hori873** [comment]
I'm gonna try putting the disk into another computer to retreive it.
Unfortunately I don't have a PC anymore (for a while) as the laptop broke
really bad and it's too expensive to repair.

**Comment by palob** [comment]
Alright, if it is too much hassle just let me know, I could do the icon then.

**Comment by Hori873** [comment]
I just created the PR. Hope it's ok.

**Comment by Foggalong** [comment]
This is now fixed in master :+1:
