### ISSUE TITLE
QGIS Browser: dedicated icon

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3333]
After a recent update of Quantum GIS the QGIS Browser have no longer has a numix circle icon. The "**/usr/share/applications/qbrowser.desktop**" icon has the icon line changed to "**Icon=qbrowser**". I suppose it only needs a symbiotic link to fix this, since the QGIS Desktop icon is not affected by the update. The new icon after the update looks like this:
![qbrowser](https://cloud.githubusercontent.com/assets/20751590/17277961/04cd605c-5750-11e6-8c1e-7992e9cf68cc.png)

**Comment by palob** [comment]
Hmm, not easy to find a fitting metaphor here. As far as I can see a globe isn't very precise.

**Comment by szekeres2016** [comment]
How about a light and dark green version of the browser globe icon you guys already have? Like this:

https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/browser-tor.svg

**Comment by palob** [comment]
Sure, I could do it. But as far as I can see it's actually a database browser http://docs.qgis.org/2.0/en/docs/user_manual/qgis_browser/qgis_browser.html.

**Comment by szekeres2016** [comment]
Or since it used the same qgis icon before the update a symlink that points qbrowser to qgis would the trick as well.

**Comment by palob** [comment]
Probably the best until someone comes up with a better idea.

**Comment by msevilla00** [comment]
What about something like this:

![QGIS Browser icon](https://i.imgur.com/Q0On46F.png)

[qbrowser.svg.zip](https://github.com/numixproject/numix-core/files/1759014/qbrowser.svg.zip)

**Comment by msevilla00** [comment]
"Q" could be without color gradients like in this proposal: https://github.com/numixproject/numix-core/issues/4227#issuecomment-368532700

**Comment by palob** [comment]
Don't like the white and I think it is a bit too busy.
What does this browser anyway? Is it a file browser?

**Comment by msevilla00** [comment]
Yes, its a kind of file browser: an spatial data/files browser and viewer.
It could be a earth icon with a monochrome "Q" on it... I'll try an example later.

**Comment by msevilla00** [comment]
What about something like next image?

![qbrowser2 svg](https://user-images.githubusercontent.com/1491985/36722313-7b356776-1bad-11e8-999a-372f9125fd39.png)

Here it is the svg file: 
[qbrowser2.svg.zip](https://github.com/numixproject/numix-core/files/1762116/qbrowser2.svg.zip)
