### ISSUE TITLE
Request: Better OCZ SSD Utility icon

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-core#3418]
Like the title says, OCZ's SSD GURU program has been renamed and rebranded upstream as OCZ SSD Utility.

In the .desktop file, the icon being requested is now "ocz-ssd-utility"

I believe we had a fancy icon for OCZ SSD GURU, can we switch that over to the new branding?

**Comment by Foggalong** [comment]
@brittyazel Can we have a screenshot of the new design and the old icon name? :)

**Comment by brittyazel** [comment]
Oh weird, I guess we didn't have one before. It was just that the old icon actually looked good, so I always attributed it to being Numix. Unfortunately, I don't know how to find the old icon anywhere. Anywho, here is the new icon, and it is aweful. I guess this is actually now an icon request for a better OCZ icon.

![oczssdutility](https://cloud.githubusercontent.com/assets/3747347/18419210/64a40032-780a-11e6-86fd-d3655ed6fbb2.png)


Perhaps a new icon could take cues from any of the icons on this info page: https://ocz.com/us/download/ssd-utility

or something like this:
https://ocz.com/images/feature_icon_lasting_performance.03152016.png
 
and making use of colors or parts of their official logo:
https://elchapuzasinformatico.com/wp-content/uploads/2013/11/ocz-logo.jpg
