### ISSUE TITLE
Icon for Code Composer Studio (CSS)  by Texas Instruments

### ISSUE THREAD

**Issue by gcerretani** [numixproject/numix-core#3425]
Code Composer Studio is an IDE that supports TI's Microcontroller and Embedded Processors portfolio. This is the webpage:

http://www.ti.com/tool/ccstudio

**Comment by Foggalong** [comment]
Please add the information set out in the readme.

**Comment by gcerretani** [comment]
Name=Code Composer Studio
Icon=~/ti/ccsv6/doc/eclipse-css-2.ico

![eclipse-css-2](https://cloud.githubusercontent.com/assets/22291296/18867406/5d8468ae-84a4-11e6-9bc7-ba8d82bb5d0a.png)

**Comment by palob** [comment]
Closing in favour of #4690
