### ISSUE TITLE
Implement Full Android Support

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#3452]
_This issue was originally core-demo#3. It has been transferred here for archiving._

---

Foggalong, 14 Feb 2016

> To properly theme Android icons you need both the icon name and the activity name. We'd hoped to automate the lookup of the activity name but it seems there's no easy way to do this. Instead we'll have to make us of [this website](http://activities.tundem.com/) and then add them manually to the database file.

bil-elmoussaoui, 15 May 2016

> What do you mean by the icon name and the activity name? The android icons uses the activity name or i'm mistaken ?

Foggalong, 15 May 2016

> Icon name ≠ activity name on Android. Multiple activities can use the same icon name, so the system of using the same for both doesn't work perfectly. Android also doesn't support symlinks for icon themes so it requires carbon copies of the same file to be used.

bil-elmoussaoui, 8 Aug 2016 

> Maybe talking to the dev of the website if it's possible to provide an API so we can fix this easily?:) Or if he use Github Pages, this way we can use his database file

**Comment by bilelmoussaoui** [comment]
@Foggalong I have some free time this evening, and i would like to get this done. What should i do? I think we have to move no-existing icons from Android theme to Circle/Square too (might need some updates/modifications)

**Comment by mueller-ma** [comment]
https://github.com/numixproject/com.numix.icons_circle/issues/46

**Comment by mueller-ma** [comment]
Any updates?

**Comment by bilelmoussaoui** [comment]
It might take a lot of time :(, but we have already started working on this see https://github.com/numixproject/numix-core/pull/3634
https://github.com/numixproject/numix-core/pull/3895
The icons should be cleaned, and a lot redesigned/updated. I will take care of this once i have some free time 👍
