### ISSUE TITLE
Icon Categories

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#3453]
_This issue was originally core-demo#5. It has been transferred here for archiving._

---

Foggalong, 9 Apr 2016

> Wondering if it might be advantageous to split apps based on the category they fall into? Like within each size have folders for `games`, `web-sapps`, `text-editors`, `browsers`, etc.

bil-elmoussaoui, 1 Aug 2016

> I think it's a great idea and we should add this to the database file asap. But will this work on all OS's or only linux?

**Comment by bilelmoussaoui** [comment]
Do you have a list of categories that we must implement ? Do we need sub-categories? 
I think this, will only work on Linux for now, some Android themes has categories for icons too! We have to contact the linux theme maintainer first :P and also add android keys to each icons..

**Comment by Foggalong** [comment]
This shouldn't make a big difference to the way the script works, it's just categorised sorting of the icons. The script then goes through all of the category folders in turn for generating rather than just the single icon folder like it does now.

**Comment by bilelmoussaoui** [comment]
We have two ways to implement categories, etiher we do that in the json file (thing i prefer) or in the icons folder. What do you propose ?

**Comment by Foggalong** [comment]
The folder system was the idea behind it to make finding a certain icon easier. This is something that's come up when making icons and wanting to find a similar icon to copy elements from. Under the current system this is quite difficult with several thousand icons to sift through, which isn't especially convenient.

**Comment by bilelmoussaoui** [comment]
Well, i think you still can just generate the theme for linux and you will have the icons categorized! if we do put each icon in the correct category folder, this will complicate the work...As we only have to add a new key to each icon with something like this `"category" : "browsers"` and i will add something to the script to detect if there's a cateogry key and create a folder and put the icon in there instead.
We can do the same for Android, we add a category key to the android icons and things will be fixed easily! :+1:

**Comment by Foggalong** [comment]
I'm not sure you've understood - the categorisation isn't in the Linux theme, it's in the icon resource directory. Either that or I've misunderstood what you mean :stuck_out_tongue_winking_eye:

**Comment by bilelmoussaoui** [comment]
Ah okey! i thought you wanted to categorize the linux theme :P well, this is a hard task to do...

**Comment by Foggalong** [comment]
I've got some other ideas for possibly addressing the problem in a simpler way, but I'm gonna leave it until we know what's happening with square before I do anything :+1:
