### ISSUE TITLE
What to do with the BFB icons?

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#3455]
_This issue was originally core-demo#13. It has been transferred here for archiving._

---

Foggalong, 3 Aug 2016

> They're required to be PNG while the rest of the Linux theme is SVG as afaik they're not even applied automatically, though I could be wrong on that one. To implement them in this script would require a special case for just those three icons. To leave them out though would mean readding them back each time.
> 
> hexcube: am I right in thinking this is your area of expertise? If so, what's the current status on BFB launcher icons?

bil-elmoussaoui, 3 Aug 2016

> Shouldn't be that hard to implement. We can rename those icons from `launcher_bfb_*` to something else like `numix_logo` and so on for the two other icons. And add a new JSON key with png instead of root. With a condition in the script, we will convert those icons to png instead of keeping them `svg`. And as far as i know, those icons are applied automatically (the `launcher_bfb.png`)

Foggalong, 3 Aug 2016

> I'm gonna download a Unity 7 iso and test this out. If they are applied automatically we'll add them as a special case. :+1:

HEXcube, 3 Aug 2016

> Thanx 4 notifying me Foggalong , this is my area of interest!:grin: And the good news is: From **Ubuntu 16.04LTS**'s _Unity 7.4_ onwards, Dash Button icon can be SVG and themeable too!:smiley:  See [Unity Theming documentation](https://wiki.ubuntu.com/Unity/Theming#Launcher.2FSwitcher_Icons).
> 
> However, if there's a need to keep compatibility with **Ubuntu 14.04LTS**'s _Unity 7.2_, PNG icons'll have to be provided. Note that _Unity 7.2_'s Dash Button icon isn't themeable though. Can be changed only when manually modded :open_mouth:

Foggalong, 3 Aug 2016

> Am I right in thinking the 7.4+ implementation has to be handled from the GTK theme rather than the icon theme? I've tried playing around with it in a VM and can't to get it to work within Numix Circle/

HEXcube, 4 Aug 2016

> Yep, it's the GTK theme which bundles Unity Theme. Forgot to mention that. :sweat_smile:

bil-elmoussaoui, 5 Aug 2016

> What shall we do?

Foggalong, 10 Aug 2016

> Given we're only half way through 14.04's support period it's probably worth adding support for them here

bil-elmoussaoui, 10 Aug 2016
Alright, what should i exaclty do ? :) 

Foggalong, 13 Aug 2016

> This is the fix we'll go with: add another key along with `root` & `symlink` called `bfb`. Then the script exports these icons as 144×144 png files which can be manually switched in by users.

bil-elmoussaoui, 19 Aug 2016

> I will do that once the two other PR are merged :+1:

**Comment by bilelmoussaoui** [comment]
Is there anything else should i implement to get this closed? :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui Yeah, I'm just gonna add the actual bfb lines :)
