### ISSUE TITLE
Language indicator showing icon instead language - Numix icon circle

### ISSUE THREAD

**Issue by jacoborus** [numixproject/numix-core#3464]
I noticed numix icon theme shows the actual language code in the language indicator of the top panel, but numix circle just shows an icon with a keyboard.

Numix circle:
![selection_086](https://cloud.githubusercontent.com/assets/829859/19604409/6e02eca4-97b5-11e6-8d3e-36089ab2e4fb.png)

Numix:
![selection_087](https://cloud.githubusercontent.com/assets/829859/19604433/8853b2be-97b5-11e6-9f2e-833020d43bc4.png)

**Comment by melmi** [comment]
Same problem here.

**Comment by lamka02sk** [comment]
Same here.

**Comment by svirschevskiy** [comment]
Issue appeared after upgrade on Ubuntu 16.10

**Comment by nekofar** [comment]
Same here, But as I noticed it's just for numix circle icons and work on other ones.

**Comment by bilelmoussaoui** [comment]
@Foggalong Fixed in the latest commit you've merged :)

**Comment by andia89** [comment]
@jacoborus @nekofar @rezzzet @melmi @lamka02sk Can you confirm that this is fixed?

**Comment by svirschevskiy** [comment]
@wa4557  Yep, it works after reinstall numix-icon-theme package. Thank you!!!

**Comment by lamka02sk** [comment]
@rezzzet Oh, thanks, it works after reinstall!
