### ISSUE TITLE
Add support for GIMP

### ISSUE THREAD

**Issue by heyhippari** [numixproject/numix-core#3471]
I haven't seen this mentioned anywhere, so I figured I'd make a list to keep track of what is still needed in GIMP for a fully themed interface.

This list is by no means exhaustive, these are what I could easilly find using gtkparasite.

# Toolbox
- [ ] gimp-tool-rect-select
- [ ] gimp-tool-ellipse-select
- [ ] gimp-tool-free-select
- [ ] gimp-tool-fuzzy-select
- [ ] gimp-tool-by-color-select
- [ ] gimp-tool-iscissors
- [ ] gimp-tool-foregound-select
- [ ] gimp-tool-path
- [ ] gimp-tool-color-picker
- [ ] gimp-tool-zoom
- [ ] gimp-tool-measure
- [ ] gimp-tool-move
- [ ] gimp-tool-align
- [ ] gimp-tool-crop
- [ ] gimp-tool-rotate
- [ ] gimp-tool-scale
- [ ] gimp-tool-shear
- [ ] gimp-tool-perspective
- [ ] gimp-tool-flip
- [ ] gimp-tool-cage
- [ ] gimp-tool-text
- [ ] gimp-tool-bucket-fill
- [ ] gimp-tool-blend
- [ ] gimp-tool-pencil
- [ ] gimp-tool-paintbrush
- [ ] gimp-tool-eraser
- [ ] gimp-tool-airbrush
- [ ] gimp-tool-ink
- [ ] gimp-tool-clone
- [ ] gimp-tool-heal
- [ ] gimp-tool-perspective-clone
- [ ] gimp-tool-blur
- [ ] gimp-tool-smudge
- [ ] gimp-tool-dodge

# Tool Options
- [ ] gimp-tool-options
- [ ] gimp-menu-left
- [ ] gimp-edit
- [ ] gimp-reset

# Misc
- [ ] gimp-layers
- [ ] gimp-channels
- [ ] gimp-paths
- [ ] gimp-undo-history
- [ ] gimp-duplicate
- [ ] gimp-anchor

**Comment by Foggalong** [comment]
Thanks for reporting, but I believe this is an issue for [Numix based](https://github.com/numixproject/numix-icon-theme). That's the package which deals with things like action icons :)

**Comment by heyhippari** [comment]
Ah, sorry for that :p

I'll repost there :)
