### ISSUE TITLE
Icon for Quaternion

### ISSUE THREAD

**Issue by PureTryOut** [numixproject/numix-core#3474]
I would love to see an icon for [Quaternion](https://github.com/fxrh/quaternion). It's a Qt-based client for [Matrix](https://matrix.org), which is an upcoming, decentralized, FOSS, encrypted chat/voip protocol. It's current logo is available [here](https://github.com/Fxrh/Quaternion/blob/master/icons/quaternion/sources/quaternion.svg).

**Comment by Foggalong** [comment]
Please add the information set out in the readme. In particular we can't fix the icon without knowing the icon line of the launcher file

**Comment by PureTryOut** [comment]
Woops, sorry, I should read more...

Icon line:

```
Icon=quaternion
```

The makefile of the application installs it's own icons to `/usr/local/share/icons/hicolor/.../apps/quaternion.png`.

**Comment by palob** [comment]
Here's a draft
![quaternion](https://cloud.githubusercontent.com/assets/7050624/20029885/f2ceb630-a358-11e6-9bcf-1fe924114d07.png)

**Comment by Foggalong** [comment]
@palob Possibly a slightly bluer blue for the background?

**Comment by palob** [comment]
One of these?
![quaternion2](https://cloud.githubusercontent.com/assets/7050624/20029945/d8a3e530-a35a-11e6-93b3-ef828b513b44.png)
![quaternion3](https://cloud.githubusercontent.com/assets/7050624/20029946/d8a62354-a35a-11e6-9e15-065ad179917e.png)

**Comment by Foggalong** [comment]
Go with the second one. Love those colours :heart_eyes:
