### ISSUE TITLE
Outdated Icons in Square

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#3484]
There are some icons in the Square section which have been removed from Circle because they caused bugs or were just very outdated (think alternative versions of icons). I came across a few while getting the merge ready and no doubt more will be found as #3481 and #3482 are addressed.

**Comment by andia89** [comment]
These are all the icons that are in square and not in circle. Not all of them are useless I would say
- [ ] 56B4_Battle.net Launcher.0.svg
- [ ] 5C12_World of Warcraft Launcher.0.svg
- [ ] aim.svg
- [ ] apport-old.svg
- [ ] battery.svg
- [ ] beatbox.svg
- [ ] bless-48x48.svg
- [ ] bluefish-alt.svg
- [ ] boot-repair.svg
- [ ] bt-logo.svg
- [ ] calc-alt.svg
- [ ] calc-old.svg
- [ ] calendar.svg
- [ ] celestia.svg
- [ ] chrome-namljbfbglehfnlonjmebceimaalofei-Default.svg
- [ ] chrome-oflhioojkbelepjlnafgmgkkjhojphcg-Default.svg
- [ ] chrome-onlgmecjpnejhfeofkgbfgnmdlipdejb-Default.svg
- [ ] config-users.svg
- [ ] cs-desklets.svg
- [ ] cs-overview.svg
- [ ] desktop-enviroment-gnome.svg
- [ ] desktop-enviroment-kde.svg
- [ ] desktop-enviroment-mate.svg
- [ ] desktop-enviroment-unity.svg
- [ ] distributor-logo-magiea.svg
- [ ] distributor-logo.svg
- [ ] filelight.svg
- [ ] file-manager-old.svg
- [ ] folder-sparkleshare.svg
- [ ] footnote.svg
- [ ] gnome-shell-extension-prefs.svg
- [ ] goa-account-facebook.svg
- [ ] goa-account-flickr.svg
- [ ] goa-account-google.svg
- [ ] goa-account-kerberos.svg
- [ ] goa-account-live.svg
- [ ] goa-account-owncloud.svg
- [ ] goa-account-pocket.svg
- [ ] goa-account-twitter.svg
- [ ] goa-account-yahoo.svg
- [ ] google-calendar.svg
- [ ] help.svg
- [ ] info.svg
- [ ] jabber.svg
- [ ] josm.svg
- [ ] krita.svg
- [ ] live.svg
- [ ] mahjongg.svg
- [ ] mathematica.svg
- [ ] mixxx.svg
- [ ] multimedia-audio-player-old.svg
- [ ] office-calendar.svg
- [ ] online-accounts.svg
- [ ] pithos.svg
- [ ] preferences-calendar-and-tasks.svg
- [ ] preferences-desktop-theme.svg
- [ ] preferences-system-bluetooth-inactive.svg.svg
- [ ] preferences-system-old.svg
- [ ] preferences-system-windows.svg
- [ ] preferences-theme.svg
- [ ] preferences-web-browser-stylesheets.svg
- [ ] salut.svg
- [ ] shortcuts.svg
- [ ] show-desktop.svg
- [ ] sigram.svg
- [ ] snap.svg
- [ ] softwarecenter-old.svg
- [ ] spacefm-blue.svg
- [ ] spacefm-green.svg
- [ ] spacefm-red.svg
- [ ] steam_icon_35720.svg
- [ ] stock_notes.svg
- [ ] system-users.svg
- [ ] text-editor-old.svg
- [ ] thunderbird-old.svg
- [ ] ubuntuone-client.svg
- [ ] unity-webapps-hotmail.svg
- [ ] webide.svg
- [ ] web-microsoft-onedrive.svg
- [ ] web-wordpress.svg
- [ ] wesnoth-1.10_editor-icon.svg
- [ ] wesnoth-1.10-icon.svg
- [ ] Yahoo Mail-mail.yahoo.com.svg

**Comment by palob** [comment]
Many continue to exist as symlinks in Circle.

We did some base SVG / symlink changes in Circle.

**Comment by Foggalong** [comment]
Aye, they need checking against [the packaging repo](https://github.com/numixproject/numix-icon-theme-circle) not the icons here.

**Comment by bilelmoussaoui** [comment]
@wa4557 A lot of icons were removed recently, especially the goa-* ones. As they were no square ( we did the same for circle few months ago)
