### ISSUE TITLE
Museeks

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3487]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| Museeks | `museeks` | `museeks.desktop` | ![museeks-48](https://cloud.githubusercontent.com/assets/7660997/20075435/68d21bc4-a534-11e6-86da-2ecacb131962.png)|

**Comment by palob** [comment]
Isn't it [hardcoded upstream](https://github.com/KeitIG/museeks/blob/f7f40b4d1f1b76c800535be9f0a99edb7813efb9/build/museeks.desktop)?

**Comment by bilelmoussaoui** [comment]
Yeah, i was going to report that to hardcode-fixer :+1:

**Comment by palob** [comment]
Which design do you prefer?
![museeks0](https://cloud.githubusercontent.com/assets/7050624/20238920/d1e822ce-a8f5-11e6-9249-b93889cd36fe.png)
![museeks1](https://cloud.githubusercontent.com/assets/7050624/20238919/d1e57d44-a8f5-11e6-9852-60925f1db058.png)

**Comment by bilelmoussaoui** [comment]
First one is a great one!
