### ISSUE TITLE
Some ideas about ubuntu hard-coded icons

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3490]
Good day, I have an idea how to handle the hard-coded icons like the 'Shutdown', 'Logout' and 'Reboot' icons along with the 'launcher_bfb.png'. Fortunately we can make local copies of the first 3 desktop files to '~/.local/share/applications' and the icon line can be fixed to use theme icons. That way any update to ubuntu will not revert the fix back, and since its not fixed globally it would look the same for other users on the machine without custom themes. The other one is the 'lanucher_bfb.png', I simply use a simlink like these:

ln -s /usr/share/icons/Numix-Circle/48/apps/launcher_bfb_ubuntu.png /usr/share/themes/Arc/unity/launcher_bfb.png
ln -s /usr/share/icons/Numix-Circle/48/apps/launcher_bfb_ubuntu.png /usr/share/themes/Arc-Dark/unity/launcher_bfb.png
ln -s /usr/share/icons/Numix-Circle/48/apps/launcher_bfb_ubuntu.png /usr/share/themes/Arc-Darker/unity/launcher_bfb.png
ln -s /usr/share/icons/Numix-Circle/48/apps/launcher_bfb_ubuntu.png /usr/share/themes/Numix/unity/launcher_bfb.png

I use these commands to patch my most favorite themes to use the Numix launcher icon locally.
A script could be made to make local copies of 'shutdown.desktop' etc. that could in the same time detect currently used GTK theme and place the numix circle launcher png file symlink in the local folder, so our changes to out themes will not affect other users on the machine. What do you guys think?

**Comment by palob** [comment]
That's actually what the [hardcode-fixer](https://github.com/Foggalong/hardcode-fixer) will do after https://github.com/Foggalong/hardcode-fixer/issues/178 has been adressed.
