### ISSUE TITLE
Icon for fs-uae-launcher

### ISSUE THREAD

**Issue by ml2mst** [numixproject/numix-core#3492]
Hi,

Could you please add an icon for the fs-uae Amiga emulator to the Numix-Circle icon set?

TIA.
![fs-uae-launcher](https://cloud.githubusercontent.com/assets/15306999/20207372/0675b714-a7e7-11e6-9c50-a5cb75385c56.png)

**Comment by palob** [comment]
Duplicate of #2913. Could you please add the information set out in the readme so we can see why the icon isn't applied?
