### ISSUE TITLE
Icon for Day of the Tentacle Remastered (Steam)

### ISSUE THREAD

**Issue by fabiomargarido** [numixproject/numix-core#3493]
```
[Desktop Entry]
Name=Day of the Tentacle Remastered
Comment=Play this game on Steam
Exec=steam steam://rungameid/388210
Icon=steam_icon_388210
Terminal=false
Type=Application
Categories=Game;
```

![steam_icon_388210](https://cloud.githubusercontent.com/assets/649114/20214088/203624d4-a7f3-11e6-824e-155b1c859fb6.png)

Thanks!

**Comment by palob** [comment]
@fabiomargarido What's the reason you closed this?

**Comment by fabiomargarido** [comment]
3+ years and not one update, guessed it counted as abandoned... :)

**Comment by palob** [comment]
The game? Well if it is feature-complete and still runs fine...

**Comment by fabiomargarido** [comment]
Not the game, the issue.

**Comment by palob** [comment]
Numix is a spare time project of a limited number of contributors. So far this issue hasn't scratched a personal itch of any of us. As you can see the repo is still very active and there are many other open issues. If you close this issue chances that it will ever come to fruition are even lower.

**Comment by maxtron95** [comment]
I will see if I can do this in the future.
