### ISSUE TITLE
Icon for Visual Studio Code

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3504]
Could we have Visual Studio Code default icon instead of the pink one?

**Comment by palob** [comment]
Are you referring to this icon?
![code](https://cloud.githubusercontent.com/assets/7050624/20458765/1c0ee708-aeae-11e6-80b5-0c3dac290e73.png)

**Comment by Foggalong** [comment]
We won't be providing a VSCode icon with the name `code.svg` it for the reasons mentioned in #2964

**Comment by palob** [comment]
@lzbthlsn In order to get a specific icon, copy the `.desktop` file over to `~/.local/share/applications` (if that isn't where it is) and edit it so that the icon line reads `Icon=vscode`.

**Comment by ghost** [comment]
@palob This workaround does not carry over to using the Square icon theme, any ideas?

**Comment by palob** [comment]
It can't since there is no vscode icon in Square yet.

**Comment by ghost** [comment]
@palob Can I manually add it somehow? :D

**Comment by palob** [comment]
Pull requests against numix-core are always welcome. Have you ever worked with Inkscape before?

**Comment by ghost** [comment]
Afraid not, as it were. Where are the icons stored? I don't really ever mess with icons in Linux. I was thinking I could just throw one in there to satisfy it so that it makes VSCode stand out from Gedit. Not sure it'd be worth PRing.

**Comment by palob** [comment]
Well you can fire up your file manager and browse ``/usr/share/icons/Numix-Square/48/apps`` (that's probably where the theme is located). Look up for an icon you want to have shown instead of the gedit one change the icon line to ``Icon=name`` where ``name`` is the filename of your icon of choice minus ``.svg``.

**Comment by ghost** [comment]
@palob I made a square vscode icon and mimicked the file structure of how Numix Circle has it laid out.

visualstudiocode.svg (the original file) with symbolic links vscode.svg and visual-studio.code.svg

Though it does not appear to be working in the same capacity.

`/usr/share/icons/Numix-Square/48/apps/`
```
lrwxrwxrwx 1 root root   20 Apr 18 16:38 visual-studio-code.svg -> visualstudiocode.svg
-rw-r--r-- 1 root root 6595 Apr 18 16:31 visualstudiocode.svg
lrwxrwxrwx 1 root root   20 Apr 18 16:36 vscode.svg -> visualstudiocode.svg

```

`/usr/share/icons/Numix-Circle/48/apps/`

```
lrwxrwxrwx 1 root root   20 Apr  5 09:31 visual-studio-code.svg -> visualstudiocode.svg
-rw-r--r-- 1 root root 3431 Apr  5 09:31 visualstudiocode.svg
lrwxrwxrwx 1 root root   20 Apr  5 09:31 vscode.svg -> visualstudiocode.svg

```
Uploaded the icon I made here:
[vscode-square.svg.zip](https://github.com/numixproject/numix-core/files/931395/vscode-square.svg.zip)

**Comment by palob** [comment]
What is this ``visualstudiocode.svg`` in your Square installation? Did you create it (happy to merge it)?
What doesn't work?

**Comment by ghost** [comment]
@palob Yeah I created it. Took an existing square icon in inkscape, removed the icon part, pasted over the vscode icon from the circle version (and resized it a smidge) and saved as a new copy.

EDIT: looks like the issue was I needed to clear the icon cache. Works now.

**Comment by palob** [comment]
That's actually how we do Square icons from Circle ones. Compared to Circle however the shadow must be moved 1px to the left for Square and symbol+shadow together go 1px up in Square.

And of course the baseplate gradient colours need to be adjusted.

How did you do the links? Be sure it's symbolic links (to be created by ``ln -s``).

**Comment by ghost** [comment]
@palob Yeah, just `ln -s`

I uploaded the .svg in one of my previous comments if you wanted to take a look/merge it.
