### ISSUE TITLE
Icon Request for Any Desk

### ISSUE THREAD

**Issue by amjidbacker** [numixproject/numix-core#3509]
[Desktop Entry]
Name=AnyDesk
GenericName=AnyDesk
X-GNOME-FullName=AnyDesk
Exec=anydesk
Icon=anydesk
Terminal=false
TryExec=anydesk
Type=Application
Categories=Network;GTK;

**Comment by Foggalong** [comment]
@amju Do you have a screenshot of the original icon too so we know what to base it on?

**Comment by amju** [comment]
PFA 

http://anydesk.com 

On 2016-11-21 02:58 AM, Joshua H. Fogg wrote: 

> @amju [1] Do you have a screenshot of the original icon too so we know what to base it on? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/amju
[2]
https://github.com/numixproject/numix-core/issues/3509#issuecomment-261807115
[3]

**Comment by amjidbacker** [comment]
![anydesk](https://cloud.githubusercontent.com/assets/1375378/20479803/9f582a22-b005-11e6-8e14-f91f84244c28.png)

http://anydesk.com/

**Comment by Bundy01** [comment]
HI,
please icon for anydesk. 
New icon: https://framapic.org/9RKASN96VBo4/zAH0efPRzDoK.png
Tanks very much

**Comment by Bundy01** [comment]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Anydesk`| `anydesk.svg` | `DESKTOP FILE NAME` | [original](https://framapic.org/9RKASN96VBo4/zAH0efPRzDoK.png) |

Description: `Remote Desktop Software`

Website: `https://anydesk.com/remote-desktop`

Hi, 
please icon for anydesk.
Thank you very much.

**Comment by Baton4986** [comment]
Hi, i'm new but created svg icon. Cannot fix it via fix.sh, any ideas how to get forward with this?

[anydesk.svg.tar.gz](https://github.com/numixproject/numix-core/files/2643071/anydesk.svg.tar.gz)

**Comment by bilelmoussaoui** [comment]
You can open a PR and get it merged into Numix Icons :)

**Comment by palob** [comment]
Hi, can you please submit your icon proposal as pull request and look up the original icon name in the ``.desktop`` file?

**Comment by palob** [comment]
Looks like the icon has changed in the meantime compared to https://github.com/numixproject/numix-core/issues/3509#issuecomment-261903660

**Comment by Baton4986** [comment]
[Desktop Entry]
Type=Application
Name=AnyDesk
GenericName=AnyDesk
X-GNOME-FullName=AnyDesk
Exec=anydesk %u
Icon=anydesk
Terminal=false
TryExec=anydesk
Categories=Network;GTK;
MimeType=x-scheme-handler/anydesk;

**Comment by palob** [comment]
With ``Icon=anydesk`` the icon isn't hardcoded and supposed Numix-Circle/Square is your current theme it should be picked up when copied to ``/usr/share/icons/Numix-Circle/48/apps`` or wherever you installed the theme to.

**Comment by Baton4986** [comment]
This was already done. The SVG is ignored, icon must be fetched somewhere else.

**Comment by Baton4986** [comment]
Finally found the solution: i had to rebuild icon cache `update-icon-caches /usr/share/icons/*`

**Comment by ramon-kramer** [comment]
Finally found the solution: i had to rebuild the icon cache
`update-icon-caches /usr/share/icons/*`
