### ISSUE TITLE
[Request]: Gnu Octave icon (circle)

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-core#3518]
The current and only icon for Gnu Octave right now is:
https://www.gnu.org/software/octave/img/octave-logo.svg

I'm requesting an Octave circle icon be added. Cheers!

**Comment by palob** [comment]
We've got one but it is [hardcoded](https://github.com/numixproject/numix-core#hardcoded-icons) (fixed in Octave 4.2. or is that the version you're using?).

**Comment by brittyazel** [comment]
Arch still has 4.0 in the repos. Not sure when 4.2 will make it to stable (the maintainer seems to be neglecting a whole range of packages).

**Comment by bilelmoussaoui** [comment]
try installing https://aur.archlinux.org/packages/numix-circle-icon-theme-git

**Comment by brittyazel** [comment]
Yeah I have both numix-circle-icon-theme-git and numix-icon-theme-git installed. I think it must be the issue that palob stated in that in Octave 4.0 it hardcodes the icon. I'll just continue to wait for arch to update the octave package to 4.2.

**Comment by bilelmoussaoui** [comment]
Your issue can be fixed using https://github.com/numixproject/numix-core#hardcoded-icons
