### ISSUE TITLE
Icon for mongochef

### ISSUE THREAD

**Issue by patking02** [numixproject/numix-core#3520]
Desktop file `/usr/share/applications/mongochef.desktop`:

```
[Desktop Entry]
Exec=/usr/bin/mongochef
Type=Application
Terminal=false
Icon=mongochef
Categories=Development;

Name=MongoChef
GenericName=MongoDB Administration Tool
```

`/usr/share/pixmaps/mongochef.png`

![mongochef](https://cloud.githubusercontent.com/assets/4238956/20932860/1cdecce0-bba4-11e6-93d0-da4f5de13e3c.png)

**Comment by palob** [comment]
Now called 3T Studio, don't know if available for Linux.
