### ISSUE TITLE
Icon for Visual Studio Code

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#3523]
An numix-circle icon for Visual Studio Code is missing.
The Icon row says: "code", and the original icon is attached.
![code](https://cloud.githubusercontent.com/assets/15245298/21117915/f2f75dbc-c0bb-11e6-9d4b-dc08b4540a66.png)

**Comment by Foggalong** [comment]
We won't be providing a VSCode icon with the name `code.svg` it for the reasons mentioned in #2964
