### ISSUE TITLE
Missing icon for Visual Studio Code

### ISSUE THREAD

**Issue by talhakabakus** [numixproject/numix-core#3525]
Big fan of `numix-circle` icons, have been using it since day 1. Thanks for all your effort. Just figured out icon for **[Visual Studio Code](https://code.visualstudio.com)** is missing, showing the **Text Editor** (`gedit`) icon. Would like to see it to be included in future updates.

Thanks in advance.

**Comment by bilelmoussaoui** [comment]
Duplicate of #3266
