### ISSUE TITLE
Icons for 4chan.org and pr0gramm.com

### ISSUE THREAD

**Issue by 0b11001111** [numixproject/numix-core#3526]
I would like to request icons for two image boards, [4chan.org](http://www.4chan.org/) and [pr0gramm.com](http://pr0gramm.com/). To access these boards I use Chrome(ium) **application shortcuts** which have own `.desktop` files.

## 4chan.org
`chrome-http___www.4chan.org_.desktop`
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=4chan
Exec=/usr/bin/chromium-browser --app=http://www.4chan.org/
Icon=/home/USER/.local/share/applications/icons/4chan_128.png
StartupWMClass=www.4chan.org
```

![4chan_128](https://cloud.githubusercontent.com/assets/19192307/21282090/1555419c-c3f2-11e6-80b0-194aba852376.png)

## pr0gramm.com
`chrome-http___pr0gramm.com_.desktop`
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=pr0gramm.com
Exec=/usr/bin/chromium-browser --app=http://pr0gramm.com/
Icon=/home/USER/.local/share/applications/icons/pr0gramm_128.png
StartupWMClass=pr0gramm.com
```

![pr0gramm_128](https://cloud.githubusercontent.com/assets/19192307/21282094/1cac08fe-c3f2-11e6-8a4c-b3e10fa597b6.png)

SVG files: [icons.zip](https://github.com/numixproject/numix-core/files/658497/icons.zip)

**Comment by palob** [comment]
Hi, can you please open a pull request so we can review your drafts?
