### ISSUE TITLE
Icon for QNapi

### ISSUE THREAD

**Issue by M1sQ** [numixproject/numix-core#3527]
Desktop file:
`/usr/share/applications/qnapi.desktop`
```
[Desktop Entry]
Exec=qnapi
Name=QNapi
Icon=qnapi
Type=Application
Categories=AudioVideo;
Comment=Program do pobierania napisów do filmów
GenericName=Program do pobierania napisów do filmów
Terminal=false
X-KDE-StartupNotify=false
```

Original icon:
![qnapi](https://cloud.githubusercontent.com/assets/23002143/21294572/e603577c-c53f-11e6-95a2-1bce84350449.png)

About:

> QNapi is free software for automatic fetching subtitles for given movie file. It uses online databases such as NapiProjekt, OpenSubtitles and Napisy24. It is based on Qt5 library, so it can be launched on any supported operating system, including Windows, OSX and Linux.

https://github.com/QNapi/qnapi

**Comment by palob** [comment]
There's an additional icon name ``qnapi-48``.
https://github.com/QNapi/qnapi/search?utf8=%E2%9C%93&q=desktop
