### ISSUE TITLE
Icon for Intel XDK

### ISSUE THREAD

**Issue by arthurflor23** [numixproject/numix-core#3529]
Desktop file `intel-xdk.desktop`:

```
[Desktop Entry]
Name=Intel® XDK
Comment=Comprehensive, cross-platform HTML5 development environment
Icon=/opt/intel/XDK/xdk/public/images/xdk_icon.png
Type=Application
Categories=Development
Exec=/usr/bin/intel-xdk
Terminal=false
```

Original icon:
![xdk_icon](https://cloud.githubusercontent.com/assets/11759042/21361275/1def671a-c6c2-11e6-9247-a7a0cbae35a3.png)

**Comment by palob** [comment]
Why did you close this?

**Comment by arthurflor23** [comment]
Discontinued product ([link](https://software.intel.com/en-us/articles/intel-xdk))
