### ISSUE TITLE
Icon for Elinks

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-core#3533]
Name: ``Elinks``
Description: ``An advanced and well-established feature-rich text mode web browser.``
Website: ``http://elinks.or.cz``
Note: Current it uses the html icon (we can use the hardcode fixer)

Desktop file:
```
[Desktop Entry]
Name=ELinks
Categories=Application;Network
GenericName=Web Browser
Comment=Browse the World Wide Web in Text-Mode
Exec=/usr/bin/elinks %u
Terminal=1
Type=Application
Icon=html
MimeType=text/html
XClassHintResName=ELinks
```

Current situation:
![image](https://cloud.githubusercontent.com/assets/11244067/21591433/f677339c-d0ea-11e6-8b62-4261d282fc14.png)

---
There is no symbol/icon for the project, So, I do believe that we can symlink to some generic browser svg

**Comment by palob** [comment]
I'm afraid we can't. An app icon named ``html`` will probably interfere with mimetpe icons (even though there actually isn't any mimetype just called ``html``).

**Comment by hlechner** [comment]
It's possible to create a svg called ``elinks.svg``.

And the https://github.com/Foggalong/hardcode-fixer uses the name of launcher to find it and change it to ``elinks``, then will be ok.
