### ISSUE TITLE
numix square icon software manager missings

### ISSUE THREAD

**Issue by zboraon** [numixproject/numix-core#3536]
In linux mint, when ou open the software manager, you face with the categories. However, for numix square (which is a lovely theme), there is no corresponding icon for fonts and programming.

![screenshot from 2017-01-05 12-38-18](https://cloud.githubusercontent.com/assets/22004884/21675725/7d3f5cea-d33b-11e6-8fc0-0f30b4795e61.png)

**Comment by palob** [comment]
Yeah, alas Square lacks a lot of icons. Can you please check whether it works with Circle? If so this will be fixed in the course of #3481.

**Comment by zboraon** [comment]
Dear Palob, with circle it is ok, see below please
![screenshot from 2017-01-05 20-41-52](https://cloud.githubusercontent.com/assets/22004884/21690942/343c2232-d37f-11e6-911d-15c65df67a7f.png)

**Comment by palob** [comment]
Thanks, this means it will be fixed down the road. It may take quite a while though.

It may be a bug however that no icons are shown, i.e. no ``Mint-X`` icons as fallback, maybe we can change the inheritance line of our ``index.theme``.

**Comment by zboraon** [comment]
On the other hand palob, I am not sure if it is correct to continue from here, from linuxmint 18.1 the window borders and control selection of numix seem to not working properly. I think, numix selection get mixed with the Mint-Y theme. If you take a look at the screenshots below, the theme seems to be not working properly.
Thanks for all.

![screenshot from 2017-01-06 13-26-46](https://cloud.githubusercontent.com/assets/22004884/21715119/67bdb6b6-d40b-11e6-8c91-90858dbc2484.png)

![screenshot from 2017-01-06 13-25-47](https://cloud.githubusercontent.com/assets/22004884/21715097/48577320-d40b-11e6-9354-02e9659ba8ca.png)

**Comment by palob** [comment]
Hmm, I don't understad what your screenshots show. Why is it a light theme in the first and a dark theme in the second with the same themes selected in both?

I don't understand the issue but it's probably for https://github.com/numixproject/numix-gtk-theme.

**Comment by zboraon** [comment]
Dear palob,
In the first screenshot, when I apply numix to window borders, it doesn't get black. Yes it is numix border but it is white.
In the scond one, when I apply controls as numix, everything gets black (as in mint-y dark), which I remember it wasn't like that in numix.
It seems that, it is an issue of numix-gtk theme:(
Thanks in advance.
