### ISSUE TITLE
Gis Weather

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3539]
I would like an icon for the Gis Weather project. Fortunately its icon is a generic one: https://sourceforge.net/projects/gis-weather/ so a simlink for "indicator-weather" would do the trick just fine. Thank you!

File=gis-weather.desktop
Name=Gis Weather
Icon=gis-weather

**Comment by palob** [comment]
Is ``indicator-weather`` actually supposed to be an app icon?

**Comment by ghost** [comment]
I don't know, but that is the entry the hardoce icon fixer puts in the "My-Weather-Indicator" desktop file (a similar but inferior weather tray/widget) so I assume it is.

**Comment by palob** [comment]
It's an icon commited long time ago and the name sounds like a try icon.

**Comment by bilelmoussaoui** [comment]
@palob The icon name was chosen here https://github.com/numixproject/numix-core/issues/246#issuecomment-33382023 I think we should rename it to something else, and commit the fix upstream on hardcode-fixer
