### ISSUE TITLE
Icon Request : GNOME Shell integration

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3540]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| GNOME Shell integration | `org.gnome.ChromeGnomeShell` | `org.gnome.ChromeGnomeShell.desktop` | ![GNOME Shell integration](http://i.imgur.com/ePLWQfe.png)| Numix-Circle |

This issue was automatically created using IconRequsts.

**Comment by palob** [comment]
Do you think a symlink to ``desktop-environment-gnome`` will do it?

**Comment by bilelmoussaoui** [comment]
Perfect! didn't knew that we had such icon on Numix :p
