### ISSUE TITLE
Icon Request : Temps

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3541]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Temps | `Temps` | `Temps.desktop` | ![Temps](http://i.imgur.com/61fMqBe.png)| Numix-Circle |

This issue was automatically created using IconRequsts.

**Comment by palob** [comment]
Symlink to ``indicator-weather``, ``indicator-weather`` greyed out or a distinct one?

**Comment by bilelmoussaoui** [comment]
I would rather say a distinct one as we have already too many symlinks to `indicator-weather` :+1:

**Comment by palob** [comment]
Which one's the best?
![temps](https://cloud.githubusercontent.com/assets/7050624/21928958/33053998-d98e-11e6-9368-f7dca2659276.png)

**Comment by bilelmoussaoui** [comment]
The first one is perfect !
