### ISSUE TITLE
Icon Request : KDE Connect Indicator (tray icons)

### ISSUE THREAD

**Issue by AliKarami** [numixproject/numix-core#3543]
Icon name | Used Application | Numix Icon | Requested Icon for Theme 
----------------|-----------------------|-----------------|---------------------------------
smartphone|KDE Connect Indicator (in tray)|[![smartphone.png](https://s27.postimg.org/704u6ep4z/smartphone.png)](https://postimg.org/image/4vkh5bni7/)|Numix-circle
tablet|KDE Connect Indicator (in tray)|[![tablet.png](https://s27.postimg.org/9841c7ho3/tablet.png)](https://postimg.org/image/n1se19a9b/)|Numix-circle

**Comment by palob** [comment]
You're asking for monochrome icons, right? That's an issue for the [base theme](https://github.com/numixproject/numix-icon-theme). It's not easy to fix though as the icon names are the same like for the device icons which are supposed to look like they do now.

Maybe we can achieve this through https://github.com/bil-elmoussaoui/Hardcode-Tray, @bil-elmoussaoui ?

@AliKarami Can you show us how it looks with other themes?

**Comment by bilelmoussaoui** [comment]
@palob I don't think that we will need Hardcode-Tray, as the icon names are not correct, here's a list of the icons used by Kdeconnect Indicator https://github.com/Bajoja/indicator-kdeconnect/tree/master/data/icons/elementary/status/24

**Comment by palob** [comment]
Ah, so another case of icons with a shorter name being picked up.

**Comment by bilelmoussaoui** [comment]
@palob We had this issue with only Qt applications nop? if it's the case, i will open a PR upstream to change those names ;)

**Comment by andia89** [comment]
The Icons are just missing. If we add them they will be picked up

**Comment by bilelmoussaoui** [comment]
Anyway, this should be reported here instead https://github.com/numixproject/numix-icon-theme

**Comment by palob** [comment]
@bil-elmoussaoui No everything is fine, it's just that apparently Qt picks up an icon called ``icon`` for any icon called ``icon-xyz`` if there is no exact match.

**Comment by bilelmoussaoui** [comment]
Well, this is not the same situation as the indicator is wroten using Vala and Gtk+

**Comment by bilelmoussaoui** [comment]
Moved the issue to Numix icon theme https://github.com/numixproject/numix-icon-theme/issues/1178
