### ISSUE TITLE
Wrong cog (square)

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#3548]
`cog.svg` in square has messed up cog.

**Comment by palob** [comment]
Thanks for reporting but that's already covered by #3482.

**Comment by gregorydk** [comment]
Yeah, it appears so. Same for https://github.com/numixproject/numix-core/issues/3547 I think.
Didn't know about https://github.com/numixproject/numix-core/issues/3482.

Well, carry on then.
