### ISSUE TITLE
Symlink to org.gnome.Lollypop

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-core#3550]
Seems like lollypop have changed the theme file reflecting the icon too:

```
Icon=org.gnome.Lollypop
```
Here you can found the file on Lollypop's github: https://github.com/gnumdk/lollypop/blob/master/data/org.gnome.Lollypop.desktop.in

 This was changed on Dec 8: https://github.com/gnumdk/lollypop/commit/b867207e125fe2b6a7c0922d7a0dece15dc28dde

---

We should create a symlink ``org.gnome.Lollypop.svg`` to ``lollypop.svg``

**Comment by bilelmoussaoui** [comment]
Already done https://github.com/numixproject/numix-core/blob/master/data.json#L7783 by @palob. You either wait until @Foggalong create a new release. Or build the icons from git, the instructions are on the README.
And we don't create symlinks anymore, it's done automatically by the  :package:  we provide

**Comment by hlechner** [comment]
Oh Thanks!

I missed the creation of this ``data.json``, good to know!
