### ISSUE TITLE
System Settings icon

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-core#3553]
The system settings icon looks too much like an on/off switch. Something with either a gear or a wrench, as it is conventionally represented, would be a lot more intuitive.

**Comment by palob** [comment]
Actually, I think our icon implements a widely-used and established metaphor for *settings*. 
It looks like the switches you'll find in the system settings.

Anyway, I'm open to discussion. While we are at it - we've got quite a few icons designs involving switches, cogs or physical representation. Maybe it's not always a plausibe representation for the app in question

**Comment by pgera** [comment]
Perhaps more than one switch would make it more obvious ? It's the single switch that makes it look like an on-off switch, especially when it's on the launcher. See the last icon on the launcher, for instance. 

![screenshot from 2017-01-24 23 10 19](https://cloud.githubusercontent.com/assets/5542855/22277547/75921704-e28a-11e6-8fe6-fd891889fbae.png)

**Comment by bilelmoussaoui** [comment]
@pgera Just a small question, why aren't using Numix Circle and you're using Numix base instead?

**Comment by pgera** [comment]
@bil-elmoussaoui Just a matter of taste. I prefer the base icons over the circle ones. I find the circle icons to be over-simplified to the point that they convey less information.

**Comment by palob** [comment]
In this case it's an issue for https://github.com/numixproject/numix-icon-theme.
Since Numix is designed to be used combined with Numix Circle/Square the icon in question (it's the lowermost in your screenshot, light?) usually won't be picked for system settings.

**Comment by pgera** [comment]
That's where I had opened it originally. https://github.com/numixproject/numix-icon-theme/issues/1179

**Comment by bilelmoussaoui** [comment]
@pgera Sorry about that! I thought that you meant the Circle/Square icon. Can you please reopen the other one instead of this issue ? Thank you

**Comment by palob** [comment]
Closing because using just Numix base is an unsupported use case.
