### ISSUE TITLE
Icon Request : Abricotine

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3555]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Abricotine | `abricotine` | `abricotine.desktop` | ![Abricotine](http://i.imgur.com/aeZOnJ9.png)| Numix-Circle |

This issue was automatically created using IconRequsts.

**Comment by palob** [comment]
Have you got the original icon in higher res?
