### ISSUE TITLE
icon for gtk-lshw

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-core#3556]
Hard-coded icon

Project Page:

https://github.com/lyonel/lshw

Logo:

![](http://www.ezix.org/project/raw-attachment/wiki/HardwareLiSter/logo.png)

```
[Desktop Entry]
Name=LSHW
Comment=HardWare LiSter
Comment[fr]=Listeur de matériel
Comment[es]=Listar equipamiento
Categories=Application;System;X-Red-Hat-Base;X-Fedora;
Icon=/usr/share/lshw/artwork/logo.svg
Exec=/usr/sbin/gtk-lshw
Type=Application
Terminal=false
Encoding=UTF-8
X-Desktop-File-Install-Version=0.10
```

**Comment by mrmeszaros** [comment]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Hardware Lister`| `lshw-gtk` | `lshw-gtk.desktop` | ![lshw-gtk_lshw-gtk](https://user-images.githubusercontent.com/15245298/27680492-2f9dc7b4-5cbc-11e7-9b68-2aa5d3494734.png) |

Description: Graphical interface for the `lshw` hardware lister, a tool to provide hardware configuration information.

* Installed via `sudo apt install lshw-gtk`.
* Desktop entry created manually:
    * Created by Unity
    * Copied from `/usr/share/app-install/desktop/lshw-gtk\:lshw-gtk.desktop`

Website: http://www.ezix.org/project/wiki/HardwareLiSter/GUI

**Comment by palob** [comment]
@sljunkie Can you please report the hardcoded icon upstream?
