### ISSUE TITLE
lollypop needs a symlink

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-core#3557]
It seems lollypop music player is the new 'default' gnome music player, as the desktop file from version 0.9.224 is named `org.gnome.Lollypop.desktop` and asks for `Icon=org.gnome.Lollypop`

**Comment by bilelmoussaoui** [comment]
Already done on master https://github.com/numixproject/numix-core/blob/master/data.json#L7784. It will be included on the next update
