### ISSUE TITLE
'Files' icon appears missing in Fedora 25 - Gnome 3.22.2

### ISSUE THREAD

**Issue by benfairless** [numixproject/numix-core#3559]
There was a [similar issue](https://github.com/numixproject/numix-icon-theme-circle/issues/26) posted in numixproject/numix-icon-theme-circle

Within Fedora 25 the icon for the default Gnome file manager referred to as 'Files' is not automatically available. On Fedora 24 this icon was available but within a fresh install of Fedora 25 the icon for this application is not assigned to the application.

As Numix is now packaged in Fedora 25 I have tried the package from the Fedora repositories as well as
the Fedora 24 COPR repositories since a Fedora 25 COPR repository doesn't exist (although a 26 does). https://copr.fedorainfracloud.org/coprs/numix/numix/

Versions of Numix Icon Theme tested:
- COPR for Fedora 24
  - `numix-icon-theme-circle-1010-6.git101307f.fc24.noarch`
  - `numix-icon-theme-1010-6.git101307f.fc24.noarch`
- COPR for Fedora 26 (it seems this is mislabelled as packages are for Fedora 25)
  - `numix-icon-theme-circle-1010-6.git101307f.fc25.noarch`
  - `numix-icon-theme-1010-6.git101307f.fc25.noarch`
- Fedora official repositories
  - `numix-icon-theme-circle-0.1.0-11.gitc3aefdb.fc25`
  - `numix-icon-theme-0.1.0-12.git101307f.fc25`

To clarify, the icon simply does not seem to be assigned correctly to the 'Files' application. There are definitely the correct icons installed for example `/usr/share/icons/Numix-Circle/48/apps/file-manager.svg`. I do not know if this is simply due to some renaming in a later Gnome version or something?

**Comment by benfairless** [comment]
![Image of issue](http://i.imgur.com/U3UT1ij.png)

**Comment by palob** [comment]
This was fixed some months ago, meaning all three packages are outdated. You can get the icon by manually installing the latest release from here https://github.com/numixproject/numix-icon-theme-circle/releases.

**Comment by benfairless** [comment]
Thanks for that. Release 16-11-23 fixed this issue for me.

Since both the Fedora repositories as well as the COPR ones are out of date is there something we could do to improve the rate of COPR releases? I'm more than willing to help if there is something that you simply don't have time for.
