### ISSUE TITLE
Icon Request : Yaourt-Gui

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3565]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Yaourt-Gui | `yaourtgui` | `Yaourt-Gui.desktop` | ![Yaourt-Gui](http://i.imgur.com/i2DUAft.png)| Numix-Circle |

This issue was automatically created using IconRequsts.

**Comment by palob** [comment]
2 drafts:
![yaourtgui](https://cloud.githubusercontent.com/assets/7050624/22309655/6f74c3ae-e34c-11e6-8c46-1639af840c88.png)

**Comment by bilelmoussaoui** [comment]
The second draft is more representing the packaging stuff than the first one! 👍

**Comment by Foggalong** [comment]
It is but I'm gonna try and move us away from that symbol for packages (think it originated in aptik?) and toward the full colour one that we use elsewhere.

**Comment by palob** [comment]
Is this recognisable?

![yaourtgui2](https://cloud.githubusercontent.com/assets/7050624/22343070/fc816cf2-e3f6-11e6-860d-4dd9d72cd205.png)
