### ISSUE TITLE
Pix (Linux Mint X-App)

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3568]
Good day, Linux Mint 18 replaced its photo managing application with their ow fork simply called "Pix". This application does not yet have an icon so I would like to request, a simlink would probably do from something similar:

![pix](https://cloud.githubusercontent.com/assets/20751590/22373693/43549b20-e4a3-11e6-8a00-a2339c95f793.png)

Desktop file name is "pix.desktop."
Icon line is: "Icon=pix"

**Comment by palob** [comment]
Symlink to ``accessories-camera``, ``entangle``, ``fotowall`` or to ``digikam``?

Which exactly is this a fork of? Shotwell? GThumb? GNOME Photos? Or written from scratch?

**Comment by ghost** [comment]
Right, sorry forgot to mention that part its a GThumb fork.

**Comment by Foggalong** [comment]
Yeah, symlink would be fine.

**Comment by palob** [comment]
Will do a symlink to ``gthumb`` since I think it doesn't make sense to have both installed. Pix is probably just GThumb without headerbar/GNOME App Menu.
