### ISSUE TITLE
Numix Calendar issue

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3573]
There's a small issue in the Numix Calendar script, the issue is due to this line https://github.com/numixproject/numix-core/blob/master/data.json#L2016
On Numix Calendar we symlink the current day icon to https://github.com/numixproject/numix-calendar-icons/blob/master/calendar-script#L23 `office-calendar` which is already a symlink to the current day (31 of the month) we should replace the root to `office-calendar` and have the rest of the icons linked to it.

**Comment by Foggalong** [comment]
Ah damn, yeah. I understand why we did it the way we did, it keeps all the actual calendar icons together, but it breaks that script. Will push the switch now.
