### ISSUE TITLE
Icon Request - Writefull

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#3577]
https://writefullapp.com/

```
[Desktop Entry]
Version=3.0
Type=Application
Name=Writefull
Comment=Writefull helps you improve your writing
Exec=/usr/local/writefull/Writefull_3beta
Icon=/usr/local/writefull/Writefull.ico
MimeType=image/x-foo;
```

Original
![image](https://cloud.githubusercontent.com/assets/1277920/22595409/87dea2e8-ea0e-11e6-936f-edf53e01ffcd.png)

"My" idea from [here](https://writefullapp.com/tutorial.html). 
![writefull svg](https://cloud.githubusercontent.com/assets/1277920/22595312/1cc47960-ea0e-11e6-929b-3e729e4eef3e.png)

[My SVG source](https://www.dropbox.com/s/bwax3sx0s593eem/Writefull.svg?dl=0)

**Comment by Foggalong** [comment]
@flexiondotorg If you want to open a pull request then we can start a proper review of your icon proposal :)

**Comment by flexiondotorg** [comment]
Wha?

**Comment by Foggalong** [comment]
@flexiondotorg Sorry didn't mean to summon you there! Must have misclicked, should have been @leoheck

**Comment by leoheck** [comment]
Haha, ok I will do that @Foggalong

**Comment by leoheck** [comment]
Done, it is now related to PR https://github.com/numixproject/numix-core/pull/3580

**Comment by bilelmoussaoui** [comment]
ALready on master
