### ISSUE TITLE
Icon Request - CoolReader3

### ISSUE THREAD

**Issue by icasdri** [numixproject/numix-core#3586]
Missing icon for [CoolReader3](https://sourceforge.net/projects/crengine/), a cross-platform XML/CSS based eBook reader.

Name=CoolReader3
GenericName=E-book reader
Comment=A cross-platform XML/CSS based eBook reader
Icon=cr3

Icon it installs with
![cr3](https://cloud.githubusercontent.com/assets/9786418/22677857/0ad78a90-ecc4-11e6-955f-b301dcd4b2ed.png)

Icon from homepage
![cr3-homepage](https://a.fsdn.com/allura/p/crengine/icon?1480461704)

**Comment by palob** [comment]
Symlink present for some time.
