### ISSUE TITLE
Google Play Movies

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3587]
Good day, I would like to request an icon for the official Google Play Movies chrome application. The filename is:
"chrome-gdijeikdkaembjbdobgfkoidjkpbmlkd-Default.desktop" and the icon line is:
Icon=chrome-gdijeikdkaembjbdobgfkoidjkpbmlkd-Default

The icon looks like this:

![google play filmek](https://cloud.githubusercontent.com/assets/20751590/22699836/f2edde8a-ed58-11e6-8166-8f774089ef6c.png)

**Comment by theel0ja** [comment]
Is this correct icon?

https://github.com/numixproject/numix-core/blob/master/icons/circle/48/web-google-movies.svg

**Comment by ghost** [comment]
It is. :D
