### ISSUE TITLE
XAMPP

### ISSUE THREAD

**Issue by cromat** [numixproject/numix-core#3588]
Here is icon proposal for XAMPP (Dashboard)

[Desktop Entry]
Comment=xampp
Terminal=false
Name=XAMPP
Exec=sudo /opt/lampp/manager-linux-x64.run
Type=Application
Icon=xampp
Categories=Developer

![xampp](https://cloud.githubusercontent.com/assets/3780307/22806771/e299fb64-ef23-11e6-96b8-fefede4ea446.png)

**Comment by bilelmoussaoui** [comment]
We already have one https://github.com/numixproject/numix-core/blob/master/icons/circle/48/xampp.svg
