### ISSUE TITLE
Icons for libreoffice 5.3

### ISSUE THREAD

**Issue by AlexisSniffer** [numixproject/numix-core#3590]
In version 5.3 the icons are not reflected because I change to this form:
libreoffice5.3-"NAME"

**Comment by palob** [comment]
Can you please specify what the "NAME"s are?

**Comment by AlexisSniffer** [comment]
**Normally it would be**
Icon=libreoffice-writer
Icon=libreoffice-math
Icon=libreoffice-impress
Icon=libreoffice-draw
Icon=libreoffice-calc
Icon=libreoffice-base
Icon=libreoffice-startcenter

**But in version 5.3 they are this way and do not assign the icons**
- [x] Icon=libreoffice5.3-writer
- [x] Icon=libreoffice5.3-math
- [x] Icon=libreoffice5.3-impress
- [x] Icon=libreoffice5.3-draw
- [x] Icon=libreoffice5.3-calc
- [x] Icon=libreoffice5.3-base
- [x] Icon=libreoffice5.3-startcenter
