### ISSUE TITLE
New media icon

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-core#3595]
With gnome 3.22 and adwaita-icon-theme 3.22, there's a new icon which appears in the notification area when a music file is played and there's no album art for it. When this was the case a gray square with a musical note was displayed, but now there's an LP-like icon for it:

![screenshot from 2017-02-17 17-43-59](https://cloud.githubusercontent.com/assets/7532854/23080916/cd525aa0-f539-11e6-8d44-9983d0e3a6a9.png)

Unfortunately, I haven't been able to track down its name yet.

**Comment by palob** [comment]
Can you please reopen this in https://github.com/numixproject/numix-icon-theme?

I can't reprodrude this with Lollypop. What's your player?

**Comment by sljunkie** [comment]
Lollypop fetches album covers from the web if I'm not mistaken. I'm was using deadbeef with the mpris2 plugin

**Comment by palob** [comment]
I think deadbeef provides this icon, it's not from Adwaita.
