### ISSUE TITLE
Icon Request - mintinstall's Featured-icon

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3596]
Linux Mint's [mintinstall](https://github.com/linuxmint/mintinstall) **Featured**-category have its' default icon.
![image](https://cloud.githubusercontent.com/assets/5832930/23092909/ae6419d6-f5dd-11e6-8f82-88c9de19e80e.png)
(Finnish version in screenshot)

**Comment by bilelmoussaoui** [comment]
The icon is hardcoded on the source code. We have already looked at that. Can you please open an issue upstream?

**Comment by bilelmoussaoui** [comment]
@palob @Foggalong i think we should add this icon anyway, and let the Mint guys fix this upstream :)

**Comment by palob** [comment]
Ah OK, we haven't got it or do we?

**Comment by bilelmoussaoui** [comment]
@palob Not yet

**Comment by palob** [comment]
What's the name supposed to be?

**Comment by bilelmoussaoui** [comment]
Something like `applications-featured`

**Comment by theel0ja** [comment]
`applications-featured` is the name of icon in [pull request](https://github.com/linuxmint/mintinstall/pull/122) by me.

**Comment by theel0ja** [comment]
It's now on the upstream.

**Comment by palob** [comment]
Fixed
