### ISSUE TITLE
[Submission] Lollypop Icon

### ISSUE THREAD

**Issue by momoe** [numixproject/numix-core#3597]
hi hiii~
This is my first contribution to GitHub so please forgive my newbishness. 
![org gnome lollypop svg](https://cloud.githubusercontent.com/assets/19848666/23130419/2f5a138e-f73b-11e6-80de-284dec8d965a.png)

I offer a Numix Square icon for Lollypop. Please note that this is probably not formatted exactly to the Numix community standards; so I would welcome anyone to review any issues they come accross and offer insight to making the colors, style, and other advanced shading settings fit better. 

I am unsure of some of the color flags such as "unset paint" used in the shadow portions of the provided Numix Square icons. 

Furthermore, I was unsuccessful at getting the icon to override the default one once, I put it in the /usr/share/icons/Numix-Square/48/apps/org.gnome.lollypop.svg location. Not sure what else needs to be done there. 

Anywho, I hope this is a helpful contribution to the numix project, and if the feedback is positive I'm considering doing a few others, like Kodi. 

Enjoy, 
momoe

[org.gnome.Lollypop.zip](https://github.com/numixproject/numix-core/files/787826/org.gnome.Lollypop.zip)

**Comment by bilelmoussaoui** [comment]
Hey, 
Thanks for the contribution, can you please open a PR so we can easily review it? Thanks!

**Comment by palob** [comment]
Is this based on our current Circle design? If you open a PR please push the icon as ``lollypop.svg``. The symlinks will be taken care of by our script.

**Comment by momoe** [comment]
I just gathered the square and circle template svg files. I'm currently trying to learn how to do this PR. If nothing else I can still post the links to the source files if someone needs to make those quick changes.

**Comment by bilelmoussaoui** [comment]
@Momoe If you need any help figuring out how things works just ping me here and i will do my best :)
