### ISSUE TITLE
Icon Request: Citra Emulator

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3599]
https://citra-emu.org/
Open-source 3DS Emulator.
It's worth noting that the icon for this application could end up looking similar to that of Clementine, and there should probably be some way of distinguishing between the two.

**Comment by palob** [comment]
Please add the information asked for in the readme. Otherwise we can't add the icon.

**Comment by ghost** [comment]
The icon line reads "citra" (see here: https://github.com/citra-emu/citra/blob/master/dist/citra.desktop )
The original icon can be found at the below link.
https://github.com/citra-emu/citra/blob/master/dist/citra.svg
(Let me know if I missed anything!)

**Comment by palob** [comment]
A few drafts
![citra](https://cloud.githubusercontent.com/assets/7050624/23376804/cd4864b8-fd2d-11e6-8ab9-32562f9bf66a.png)

**Comment by bilelmoussaoui** [comment]
@palob  The first one looks nice :) but the second one is better even if it looks soo much like the Clementine icon

**Comment by heyhippari** [comment]
The first one looks the best, imho (It's also the closest to the original design, aside from the fourth one, but that one looks a bit weird due the baseplate being too visible, I think).

**Comment by ghost** [comment]
Given this is a 3DS emulator, it might be best to make an icon of the 3DS itself (much like the icons for DeSmuME, VisualBoyAdvance, etc.).
![3DS](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Nintendo-3DS-AquaOpen.png/1200px-Nintendo-3DS-AquaOpen.png)

**Comment by heyhippari** [comment]
For those emulators, though, the original system is part of the original icon and branding.

Here, much in the same case as Dolphin (IIRC, Citra was actually spun off of Dolphin by a few devs), it's  a completely separate branding and, imho, it makes more sense to respect that branding if it fits into the theme.

**Comment by palob** [comment]
@Foggalong What do you think? Something like the above drafts or an orangey controller icon?

**Comment by Foggalong** [comment]
Go with a 3DS design - we do already have a DS emulator icon which could easily be modified by just changing up the buttons :)

**Comment by palob** [comment]
This?
![citra](https://cloud.githubusercontent.com/assets/7050624/24981602/be4b953e-1fdd-11e7-8a56-8b2e07f4af1b.png)

**Comment by Foggalong** [comment]
@palob Maybe a more yellowy colour for the top half, otherwise all good :+1:
