### ISSUE TITLE
Icon Request - mintwelcome's icons

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3601]
mintwelcome is showing icons in default Mint icons, while I'm using Numix Circle.
![image](https://cloud.githubusercontent.com/assets/5832930/23329927/7f95f250-fb4b-11e6-9dc5-42ae74ea478c.png)

**Comment by theel0ja** [comment]
Icons seems to be hardcoded.
https://github.com/linuxmint/mintwelcome/blob/master/usr/lib/linuxmint/mintwelcome/mintwelcome.py#L166
https://github.com/linuxmint/mintwelcome/blob/master/usr/lib/linuxmint/mintwelcome/mintwelcome.py#L167

**Comment by bilelmoussaoui** [comment]
Wa can do anything about it, please report it upstream..
