### ISSUE TITLE
Numix-square Icon cleanup request Spotify

### ISSUE THREAD

**Issue by BurningSmile** [numixproject/numix-core#3602]
I've noticed that the spotify icon in my window list in Gnome shell looks pixelated. 

https://i.imgur.com/1ACwqET.png

**Comment by bilelmoussaoui** [comment]
@BurningSmile It doesn't look like the icon provided by Numix Square as it isn't Square :p It must be an issue with a missing StartupWMClass. Is that the official app? What's the output of `xprop WM_CLASS` (and then click on the Spotify Window). Also, can you paste the content of the desktop file? Thanks!
Anyway, this isn't a Numix bug, i will mark it as invalid. But i will try my best to help you fix it!

**Comment by BurningSmile** [comment]
@bil-elmoussaoui 

xprop WM_CLASS
WM_CLASS(STRING) = "spotify", "Spotify"

All the other icons work as well. I should note I am starting spotify via blockify in a tmux session. This launches spotify-ad killer-git. 

In the gnome app menu the icon is square.

I am assuming this issue is because of the fact that I'm using some other tools to launch spotify. A workaround is to just have the Spotify on its own workspace so I don't see the icon.

**Comment by bilelmoussaoui** [comment]
Maybe trying to add `StartupWMClass=spotify` in your desktop file of Spotify? and see what happens?
