### ISSUE TITLE
Icon request - Ghetto Skype

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3603]
Icon for [Ghetto Skype](https://github.com/stanfieldr/ghetto-skype).

```
[Desktop Entry]
Name=Ghetto Skype
Comment=Integrates Web Skype with the Linux desktop
Exec="/opt/Ghetto Skype/ghetto-skype"
Terminal=false
Type=Application
Icon=ghetto-skype
StartupWMClass="Ghetto Skype"
Categories=Network
```

**Comment by bilelmoussaoui** [comment]
@palob  A symlink to the original icon is enough ?

**Comment by palob** [comment]
Probably.
I don't use Skype but isn't the official desktop client to be phased out soon?
So this is will be the only desktop client in future anyway?

**Comment by bilelmoussaoui** [comment]
@palob Skype already has a new electron based client. And this one is just an attempt to do the same thing based on web.skype.com :) so, a symlink is more than enough for me (even if i don't use it)
