### ISSUE TITLE
Icon Request - Ramme

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3604]
Icon for [Ramme](https://github.com/terkelg/ramme).

```
[Desktop Entry]
Name=Ramme
Comment=Unofficial Instagram Desktop App
Exec="/opt/Ramme/ramme"
Terminal=false
Type=Application
Icon=ramme
```

**Comment by bilelmoussaoui** [comment]
@palob Maybe a symlink to unity-webapp-instagram and redesign it to follow the latest logo design of Instagram?

**Comment by palob** [comment]
I was actually thinking of doing a dedicated one for this.

**Comment by bilelmoussaoui** [comment]
@palob Alright, it just seem to use the original Instagram logo :)
