### ISSUE TITLE
Slack Improvement

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#3605]
There are some cool icons like the one used in google-chrome. This is not the case with slack. 
I would like to ask for improvements. Thanks.

**Comment by palob** [comment]
Sorry, can you please be more specific as to which kind of improvement you wish?

**Comment by bilelmoussaoui** [comment]
Duplicate of #2604

**Comment by leoheck** [comment]
Yeah, the same improvement in issue referenced by @bil-elmoussaoui. thanks.
