### ISSUE TITLE
Icon Request Code Composer Studio (IDE)

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#3609]
Hardcoded icon

![ccscube256](https://cloud.githubusercontent.com/assets/1277920/23534236/4d2279c6-ff95-11e6-9f50-b6012343475b.png)

.desktop content:
``
[Desktop Entry]
Icon=/repo/tools/TI/css/7.1.0/ccsv7/doc/eclipse-css-2.ico
``

Ref: http://www.ti.com/tool/CCSTUDIO

**Comment by palob** [comment]
Closing in favour of #4690

**Comment by leoheck** [comment]
lol

**Comment by leoheck** [comment]
> Closing in favour of #4690

![image](https://github.com/user-attachments/assets/87c99180-9bbe-4e36-8720-280a61404e97)

Githubshit is ridiculous.
