### ISSUE TITLE
Icon Request: discord-canary

### ISSUE THREAD

**Issue by aveao** [numixproject/numix-core#3611]
I can't really find the tool people use to request so meh, sorry.

[Here's the download for Discord Canary](https://www.reddit.com/r/discordapp/comments/4bu7lm/discord_linux_very_experimental_canary_release/).

Name in desktop entry is `discord-canary`

Application name is `Discord Canary`

Desktop File Name is `discord-canary.desktop`

Original icon (it took me a lot to find this. They hid it in /usr/share/discord-canary/discord.png apparently): ![](https://s.ave.zone/52f.png)

Theme is `numix-square`

**Comment by bilelmoussaoui** [comment]
The Numix Square theme is still not as complete as the Circle one see this issue https://github.com/numixproject/numix-core/issues/3482 (the icon you request is on the list)
And you can use this tool to request the missing icons easily.
https://github.com/bil-elmoussaoui/Icon-Requests

Thanks

**Comment by aveao** [comment]
Aha, I see. My bad, sorry. I've opened up gimp and just made the icon non-gradienty and honestly I can now live with it until someone decides to make the square one.

I've installed the tool. It seems great, thanks for pointing it out :)
