### ISSUE TITLE
Icon Request - Keybase

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3614]
Icon for [Keybase](https://github.com/keybase/client).

```
[Desktop Entry]
Name=Keybase
Exec=run_keybase
Icon=keybase
Terminal=false
Type=Application
Categories=Network;
StartupNotify=false
```

![image](https://cloud.githubusercontent.com/assets/5832930/23811988/1ae3ba18-05e1-11e7-920d-9f28a5390362.png)

**Comment by bilelmoussaoui** [comment]
Can you please include the original logo on the issue ?
