### ISSUE TITLE
Symlink request for PB Desktop

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3619]
Good day, I would like to request a symlink for PB Desktop: https://sidneys.github.io/pb-for-desktop/

There already is a 'web-pushbullet' icon in the Circle pack that would do just fine. The .desktop file is called: "pb-for-desktop.desktop" and the icon line is:

Icon=pb-for-desktop

Thank you!

**Comment by bilelmoussaoui** [comment]
It's already included see https://github.com/numixproject/numix-core/blob/master/data.json#L14315 we just need to release a new version. Please wait until it's done :)
