### ISSUE TITLE
Terminix -> Tilix

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#3620]
Apparently terminix becomes tilix from night to day. We have to fix it. What do you suggest? Creating a symlink for tilix or renaming the original terminix to icon a tilix and create a symlink to terminix?

**Comment by bilelmoussaoui** [comment]
Already done on master

**Comment by bilelmoussaoui** [comment]
see https://github.com/numixproject/numix-core/commit/0af521f7c825c4fd9560f877b839aac769e1c9f0

**Comment by brittyazel** [comment]
The switch to Tilix happened on Archlinux today. I am not seeing the numix icon being used though, and yes I am using an up to date pull of Numix icon themes

**Comment by leoheck** [comment]
Yeah. Me too on Ubuntu.

**Comment by palob** [comment]
Sorry guys, we need to get a new release out.
