### ISSUE TITLE
Icon Request : Vectr

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3621]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Vectr | `vectr` | `vectr.desktop` | ![Vectr](http://i.imgur.com/rqMm6Sy.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by really-need-an-api-key** [comment]
I believe this was fixed by #4731.

**Comment by palob** [comment]
It was indeed, thank you.
