### ISSUE TITLE
Icon request for Android Studio

### ISSUE THREAD

**Issue by scottmangiapane** [numixproject/numix-core#3622]
Hello! I found that the icon for Android Studio is missing. In the desktop entry, the icon line says "/opt/android-studio/bin/studio.png". This line will change between different users however; my path is this because that's where I chose to install it. The original icon is attached.

![studio](https://cloud.githubusercontent.com/assets/16295236/24128954/a975d9a6-0db5-11e7-9059-e717e8d86c6e.png)

**Comment by palob** [comment]
Hi, we already did the [icon](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/androidstudio.svg). In order to have it show up copy the ``.desktop`` file over to ``~/.local/share/applications/`` and change the icon line to ``Icon=androidstudio``
