### ISSUE TITLE
Numix Circle copr repo outdated

### ISSUE THREAD

**Issue by jrupinski** [numixproject/numix-core#3623]
A numix-circle icon for Nautilus is missing.
The icon line says "org.gnome.Nautilus", and the original icon is attached.

![image](https://cloud.githubusercontent.com/assets/9074800/24288668/94beb2d2-107e-11e7-9a70-ae6f3f53c3ee.png)

**Comment by bilelmoussaoui** [comment]
Please provide the needed information as described on the readme.

**Comment by jrupinski** [comment]
Changed the issue according to the readme video.

**Comment by palob** [comment]
We've already got an icon with that name. You must be using an outdated version of the theme.

**Comment by jrupinski** [comment]
I installed the theme yesterday, so I think I am using the latest version.
I installed it using Fedy first, then after I noticed the wrong icon I removed it and installed it from the repo, using instructions in the readme. 

![image](https://cloud.githubusercontent.com/assets/9074800/24289025/d15a6640-107f-11e7-953e-d6de70bd6618.png)

**Comment by palob** [comment]
So that means the copr repo is outdated. Is that the preferred way of installing it for Fedora. I know it's even in the official repos but last time I tried that was even more outdated.

**Comment by palob** [comment]
What you you can do right now to get a fix is to copy the desktop file over to ``~/.local/share/applications/`` and edit the icon line to ``Icon=file-manager``.

**Comment by jrupinski** [comment]
Thanks, this fix works! 
Also, it's probably because the copr is outdated, but updating repo info results in this error:

`jrupinski [~]$ sudo dnf update
`
`Failed to synchronize cache for repo 'numix-numix', disabling.
`

**Comment by heyhippari** [comment]
The official repository (The preferred installation method, usually) seems to ship [this commit from September](https://github.com/numixproject/numix-core/commit/c3aefdb).

The copr (Which has no link to the package in the official repositories) was last updated 11 months ago, so it probably started to fail auto-updates when the build system changed ?  

@rupek1995 You should install the package from the official repositories for now, as it's more recent and has half a year of icons that the COPR doesn't have.

**Comment by Foggalong** [comment]
The copr repo is now unsupported, we added a message to inform users of that a few months ago. It just need removing from the README files of the packaging repos now and replacing with the Fedora repos version :)
