### ISSUE TITLE
Icon Request: Tilix

### ISSUE THREAD

**Issue by orioltf** [numixproject/numix-core#3624]
A numix-circle icon for [Tilix](https://gnunn1.github.io/tilix-web/) is missing.

The icon line is:
```
Icon=com.gexperts.Tilix
```

The original icon is attached:
![logo](https://cloud.githubusercontent.com/assets/743894/24281306/cb3efece-1057-11e7-958d-e2969779615c.png)

**Comment by bilelmoussaoui** [comment]
Already fixed on master https://github.com/numixproject/numix-core/commit/0af521f7c825c4fd9560f877b839aac769e1c9f0

**Comment by orioltf** [comment]
Lovely! Thanks :)
