### ISSUE TITLE
Icon Request - mintupload's tray icon

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3625]
https://github.com/linuxmint/mintupload/pull/32 is going to remove mintupload's hardcoded icons, so the icon `mintupload-tray` could be themed.

Original icon: https://github.com/JosephMcc/mintupload/blob/icon-fixes2/usr/share/icons/hicolor/scalable/apps/mintupload-tray.svg

**Comment by palob** [comment]
Can you please reopen this here https://github.com/numixproject/numix-icon-theme? Tray icons are part of the base theme.
