### ISSUE TITLE
Icon for GNOME Recipes

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#3627]
`Icon=org.gnome.Recipes`

![org gnome recipes](https://cloud.githubusercontent.com/assets/7804464/24450320/c209c07e-147a-11e7-8147-a247eb49ba26.png)

**Comment by palob** [comment]
We've already got a [symlink](https://github.com/numixproject/numix-core/blob/2684aa6342b7a00aca7126dcf533a1628016acc2/data.json#L7300) for this. We need a new release for this to come into effect, however.

Are you OK with the symlink or are you looking for a dedicated icon?

**Comment by gregorydk** [comment]
My preference goes to a dedicated icon, Gourmet has one and GNOME Recipes is a GNOME app. But it's your decision.

Idea: Round brown base plate with knife and tomato icon.
