### ISSUE TITLE
Invalid use of "exit" function causes package compilation problems

### ISSUE THREAD

**Issue by TheAifam5** [numixproject/numix-core#3628]
Hey,
I am ArchLinux user and i wanted to pack this package: https://aur.archlinux.org/packages/numix-icon-theme-pack/
At the end of the "gen.py" script you using "exit" function with string parameter which returns 1 (error code).

Please change to "print" function.

Regards,
Mateusz.

**Comment by bilelmoussaoui** [comment]
Done on master!
