### ISSUE TITLE
Icon Request : Tilitin

### ISSUE THREAD

**Issue by theel0ja** [numixproject/numix-core#3629]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Tilitin | `tilitin` | `tilitin.desktop` | ![Tilitin](http://i.imgur.com/cxHk9Me.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
What kind of application is this?

**Comment by theel0ja** [comment]
It's an accounting program.

**Comment by palob** [comment]
How about a symlink to [buddi.svg](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/buddi.svg)?
