### ISSUE TITLE
Problems with librsvg 2.41

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#3632]
User reported in numixproject/numix-icon-theme-circle#34 that our linear gradients aren't showing up properly, completely breaking the icon theme. Has anyone been able to replicate this?

**Comment by bilelmoussaoui** [comment]
No idea what causes this...The latest librsvg available for me on Archlinux is 2.40 :(

**Comment by Foggalong** [comment]
From what it sounds like it's not a stable release which might be part of the problem tbh

**Comment by Foggalong** [comment]
Closing this due to lack of updates, reproducibility, and likely coming down to using unstable libraries.
