### ISSUE TITLE
Icon Request: Postman (Desktop Client)

### ISSUE THREAD

**Issue by jonasknobloch** [numixproject/numix-core#3633]
Application: Postman (Desktop Client)
Icon: https://www.getpostman.com/img-rebrand/logo.png

The application does not create a desktop entry.

"A powerful GUI platform to make your API development faster & easier, from building API requests through testing, documentation and sharing."

There is already an outdated icon for the Chrome Web App available.
https://github.com/numixproject/numix-core/blob/master/icons/circle/48/chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.svg

Request for updating the Chrome Web App icon:
https://github.com/numixproject/numix-core/issues/2443

**Comment by Foggalong** [comment]
Duplicate of #2443

**Comment by bilelmoussaoui** [comment]
Well in that case we just need to update the outdated chrome web app? which means this issue is a duplicate of #2443 as the application does not provide any desktop entry with a default icon name
