### ISSUE TITLE
Icons problems: PCSX2 and PlayOnLinux

### ISSUE THREAD

**Issue by Kierek** [numixproject/numix-core#3641]
Application name: PCSX2
Icon name: PCSX2
Desktop filename: PCSX2.desktop

Application name: PlayOnLinux
Icon name: PlayOnLinux
Desktop filename: playonlinux.desktop

It doesn't work ootb, since original icon name is PCSX2, and icon provided by numix is pcsx2. When I manually change the name in launcher to the latter it works fine, but I guess that it's not a desirable behaviour.

The same happens with PlayOnLinux, should be PlayOnLinux instead of playonlinux.

**Comment by palob** [comment]
Tanks for reporting, will be fixed in the next release.

**Comment by Kierek** [comment]
I'm not sure if you've seen it, but I was adding the second case of the same problem to the post while you were closing this issue.

Thanks for the fix anyway.

**Comment by palob** [comment]
Alright, will add the other symlink in a second.
