### ISSUE TITLE
Icon request for OBS Studio (Numix Square)

### ISSUE THREAD

**Issue by malysps** [numixproject/numix-core#3650]
Hello, I'm using Numix Square 1.0.1+8-201704052001-ubuntu16.10.1 from PPA on Xubuntu 16.10.

Icon for OBS Studio (Open Broadcaster Software - https://obsproject.com) is missing in Numix Square (it is present in Numix Circle).

Icon=obs

Thanks!

**Comment by palob** [comment]
Hi, we already intend to transfer all Circle designs to Square. Please see #3481.

Unfortunately it's not the most enjoyable task.

**Comment by malysps** [comment]
Oh I see, sorry for that, I thought OBS was just an isolated case. Keep up the great work! Hands down the greatest icon set available right now.

**Comment by palob** [comment]
Thanks for your support :smiley:
