### ISSUE TITLE
Icon Request: Airwave Manager

### ISSUE THREAD

**Issue by KevyGSus** [numixproject/numix-core#3658]
A numix-circle icon for airwave-manager is missing.
The icon line says "airwave-manager" and the original icon is attached.

![airwave](https://cloud.githubusercontent.com/assets/27501387/25048273/d3d3e8b6-213b-11e7-9285-b85e50f43620.png)

**Comment by palob** [comment]
Is it this one https://github.com/phantom-code/airwave?

**Comment by KevyGSus** [comment]
Yes. That's the one.
