### ISSUE TITLE
Icon Request: Cadence and related apps

### ISSUE THREAD

**Issue by KevyGSus** [numixproject/numix-core#3659]
The following numix-circle icons are missing for Cadence and its related apps:

'cadence' and 'cadence-gnome-settings' both use the icon: 'cadence'
![cadence](https://cloud.githubusercontent.com/assets/27501387/25046712/4d4f14c6-2133-11e7-82ab-e5800cc93fd7.png)

'caterina' uses the icon 'caterina'
![catarina](https://cloud.githubusercontent.com/assets/27501387/25046728/6a5ea400-2133-11e7-9578-7fe75570a0b5.png)

'carla' uses the icon 'carla'
![carla](https://cloud.githubusercontent.com/assets/27501387/25053767/a09057aa-2159-11e7-8e91-94a703a57d6b.png)

'carla-control' uses the icon 'carla-control'
![carla-control](https://cloud.githubusercontent.com/assets/27501387/25053771/a4c59984-2159-11e7-8321-a8e114438402.png)

'catia' uses the icon 'catia'
![catia](https://cloud.githubusercontent.com/assets/27501387/25046779/ac048230-2133-11e7-9a81-9053cb3cf6a5.png)

'claudia' uses the icon 'claudia'
![claudia](https://cloud.githubusercontent.com/assets/27501387/25046791/b8c86950-2133-11e7-9b5d-941d02902919.png)

'claudia-launcher' uses the icon 'claudia-launcher'
![claudia-launcher](https://cloud.githubusercontent.com/assets/27501387/25046799/be1f9fa4-2133-11e7-9ff0-915b2a34a950.png)

**Comment by palob** [comment]
Hi, can you please tell us what the apps are about?

**Comment by KevyGSus** [comment]
Sure. They all have to do with audio production. Cadence is a manager for the jack and ladish audio system and is the main control center for each of these apps. Carla is an audio plugin host. Catarina, Claudia, and Catia are different kinds of audio patchbays for Jack and Ladish.

They're developed by the team at KXStudio:
http://kxstudio.linuxaudio.org/Applications

**Comment by maxtron95** [comment]
@palob since those icons got pulled in, maybe this should be closed?

**Comment by palob** [comment]
Yes.
