### ISSUE TITLE
Missing Icons in PCManFM-Qt on LxQt

### ISSUE THREAD

**Issue by pestadieu** [numixproject/numix-core#3687]
Some Icons does not display on PCManFM-Qt on LxQt:

pcmanfm-qt with Adwaita Icon theme:
![pcmanfm-qt with Adwaita Icon theme](https://cloud.githubusercontent.com/assets/23661819/25246411/dc5edaec-2607-11e7-99f7-e319702d3adb.png)

pcmanfm-qt with Numix Circle Icon theme:
![pcmanfm-qt with Numix Circle Icon theme](https://cloud.githubusercontent.com/assets/23661819/25246426/ef318598-2607-11e7-892c-5aa70491f368.png)

These are the missing icons (from left to right):
| Application name | Icon name | Original icon |
| PCManFM-Qt |  tab-new.png | ![tab-new.png](https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/master/Adwaita/22x22/actions/tab-new.png)
| PCManFM-Qt |  go-previous.png | ![go-previous.png](https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/master/Adwaita/22x22/actions/go-previous.png)
| PCManFM-Qt |  go-next.png | ![go-next.png](https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/master/Adwaita/22x22/actions/go-next.png)
| PCManFM-Qt |  go-up.png | ![go-up.png](https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/master/Adwaita/22x22/actions/go-up.png)
| PCManFM-Qt |  view-refresh.png | ![view-refresh.png](https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/master/Adwaita/22x22/actions/view-refresh.png)

Description: File Manager for LxQt

Website: https://github.com/lxde/pcmanfm-qt

**Comment by palob** [comment]
Hi, can you please report this here? https://github.com/numixproject/numix-icon-theme.
numix-core is for app icons only.

That aside, we definitely have got those icons. Looks like the base theme *Numix* which Numix-Circle is dependent on isn't installed.

**Comment by palob** [comment]
@pestadieu Can you please check if the Numix base theme is installed?

**Comment by pestadieu** [comment]
Numix based theme wasn't installed, I installed it and it works. Thanks for your help :)
