### ISSUE TITLE
Icon Request: NewPipe (Android)

### ISSUE THREAD

**Issue by mueller-ma** [numixproject/numix-core#3697]
| Application name | Android Package | Original icon |
| --- | :-- | :-- |
| `NewPipe`| `org.schabi.newpipe`| ![original](https://raw.githubusercontent.com/TeamNewPipe/NewPipe/master/app/src/main/res/mipmap-xhdpi/ic_launcher.png) |

Description: `A free lightweight Youtube frontend for Android`

Website: `https://github.com/TeamNewPipe/NewPipe`

**Comment by theScrabi** [comment]
What do you think about this one here:
![https://cloud.githubusercontent.com/assets/16841860/21958404/a4a99c18-daad-11e6-9c8d-9dc2711bfc3b.png](https://cloud.githubusercontent.com/assets/16841860/21958404/a4a99c18-daad-11e6-9c8d-9dc2711bfc3b.png)
Its form @ponypower.

**Comment by mueller-ma** [comment]
@theScrabi This looks good, but I think we need it as svg in circle and square.

**Comment by palob** [comment]
@theScrabi It looks cool but it's considerably un-Numixy. Please take a look at existing numix core icons and our unpolished [guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines).

**Comment by ponypower** [comment]
I'll come up with something.
