### ISSUE TITLE
Icon Request: TORCS

### ISSUE THREAD

**Issue by thenanobel** [numixproject/numix-core#3698]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `TORCS`| `torcs` | `torcs.desktop` | ![TORCS Icon](https://cloud.githubusercontent.com/assets/9353047/25488557/2b353612-2b89-11e7-88df-65e0d87347ee.png) |

**Description:** TORCS is a 3D racing cars simulator game using OpenGL.
**Website:** [http://torcs.sourceforge.net/index.php](http://torcs.sourceforge.net/index.php)

**Comment by Foggalong** [comment]
@thenanobel If the icon line is `torcs` why did you put `TORCS` in the table? :P

**Comment by thenanobel** [comment]
I'm sorry! I couldn't understand what the **Icon name** column is, when I created this issue. I'm changing it. :-)
