### ISSUE TITLE
Cleaning icon names in this repository

### ISSUE THREAD

**Issue by heyhippari** [numixproject/numix-core#3701]
As this is a developement repository, it might make more sense to have verbose names for some icons.

I'm thinking specifically about stuff like steam_icon_xxx or chrome-xyz123somethingorother.  
Naming them using a verbose name (For example `steam_icon_281990` would be `stellaris`) and then adding the proper icon name in data.json as a symlink would make editing down the line a lot easier.  
For example, it makes it easier to find if a game already has an icon when GOG or whatever releases a Linux version with another icon name.

We would obviously need to be done with #3481 and #3482 before, to not have to redo these lists as well, but I think it could be useful.

Here is a list of those icons as of April 29 2017:

- [ ] chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.svg
- [ ] chrome-gebjgjhbjedcomcajgpodjgfjgkepgpl-Default.svg
- [ ] chrome-dkfhfaphfkopdgpbfkebjfcblcafcmpi-Default.svg
- [ ] chrome-epionbmgciknkbdibokmpmcfllkdfeeo-Default.svg
- [ ] chrome-koegeopamaoljbmhnfjbclbocehhgmkm-Default.svg
- [ ] chrome-mojepfklcankkmikonjlnidiooanmpbb-Default.svg
- [ ] chrome-cnciopoikihiagdjbjpnocolokfelagl-Default.svg
- [ ] chrome-ofbpedjdfkboehhknoohhenbpmgcjoik-Default.svg
- [ ] chrome-omimkinlomnncbmnceacpkmlbfaapojj-Default.svg
- [ ] chrome-pkbfakcphdokdnbdhlndlpcehebmplab-Default.svg
- [ ] chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.svg
- [ ] chrome-eempgbpnkjnacmilmobpbhbfpdjdcpgd-Default.svg
- [ ] chrome-aeellliejpiclijnghognjagifplmmij-Default.svg
- [ ] chrome-iggpfpnahkgpnindfkdncknoldgnccdg-Default.svg
- [ ] chrome-knpkfcpnjfbniadmfchjpcigfhookhaa-Default.svg
- [ ] chrome-fljalecfjciodhpcledpamjachpmelml-Default.svg
- [ ] chrome-njkkjobcechefaoknodniidfjapgfoco-Default.svg
- [ ] chrome-gbchcmhmhahfdphkhkmpfmihenigjmpp-Default.svg
- [ ] chrome-jfbadlndcminbkfojhlimnkgaackjmdo-Default.svg
- [ ] chrome-menkifleemblimdogmoihpfopnplikde-Default.svg
- [ ] chrome-jklljiahjgoglchglekebfljnmbaleig-Default.svg
- [ ] chrome-cijncchffkmlnfdbnkkfclcbnjcoegjc-Default.svg
- [ ] chrome-pnoffddplpippgcfjdhbmhkofpnaalpg-Default.svg
- [ ] chrome-ocgddccilgpeepgglnlpchkpgamkgmld-Default.svg
- [ ] chrome-fnibmbcdeepaahjmddiihohjanlimlmj-Default.svg
- [ ] chrome-cnocophcbjfiimmnhlhleaooedeheifb-Default.svg
- [ ] chrome-https___stackedit.io_editor.svg
- [ ] chrome-bhmicilclplefnflapjmnngmkkkkpfad-Default.svg
- [ ] chrome-mknafpnfcafklkflhenhaldedggpciao-Default.svg
- [ ] chrome-ijfecbiladpinddbjfodaaiahggomhaf-Default.svg
- [ ] chrome-hjkdhkejcnlmkfdodbkdkelefnkobfif-Default.svg
- [ ] chrome-efjnaogkjbogokcnohkmnjdojkikgobo-Default.svg
- [ ] chrome-https___prezi.com.svg
- [ ] chrome-cmnpffgfpcohhpoddjankjanolcekbni-Default.svg
- [ ] chrome-jeogkiiogjbmhklcnbgkdcjoioegiknm-Default.svg
- [ ] chrome-knkapnclbofjjgicpkfoagdjohlfjhpd-Default.svg
- [ ] chrome-kidnkfckhbdkfgbicccmdggmpgogehop-Default.svg
- [ ] chrome-ohmmkhmmmpcnpikjeljgnaoabkaalbgc-Default.svg
- [ ] chrome-efdcneeepllhjlbejkfnaolelbpdacai-Default.svg
- [ ] chrome-hjbljnpdahefgnopeohlaeohgkiidnoe-Default.svg
- [ ] chrome-fgbjpbdfegnodokpoejnbhnblcojccal-Default.svg
- [ ] chrome-ieicmdpibfnjbmjolkmohnelljmjomoj-Default.svg
- [ ] chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.svg
- [ ] chrome-jbdlaalbpgnopkpnmoppmccbgkjhfmgh-Default.svg
- [ ] chrome-gighmmpiobklfepjocnamgkkbiglidom-Default.svg
- [ ] chrome-ehjonnoogdmhhidjcldckckmfkpcfefh-Default.svg
- [ ] chrome-mlijpphckdfkmcjclnimmbknefojcaol-Default.svg
- [ ] chrome-clhhggbfdinjmjhajaheehoeibfljjno-Default.svg
- [ ] chrome-eknidjojcplfcgkoffboklcbfhmcdhip-Default.svg
- [ ] chrome-bfimiibpomebbdeomajcknhccgpkjmlh-Default.svg
- [ ] chrome-bnadbgmffcofipfljniafanjcafjlbom-Default.svg
- [ ] chrome-hkgndiocipalkpejnpafdbdlfdjihomd-Default.svg
- [ ] steam_icon_232790.svg
- [ ] steam_icon_252950.svg
- [ ] steam_icon_293780.svg
- [ ] steam_icon_221830.svg
- [ ] steam_icon_60.svg
- [ ] steam_icon_302610.svg
- [ ] steam_icon_275390.svg

**Comment by bilelmoussaoui** [comment]
This should really make it easier to merge the android icons with the linux ones (easier to see if an icon already exists or not)

**Comment by Foggalong** [comment]
I whole heatedly agree with this, and it's one of the reasons I wrote the program as I did so that the file name and the linux icon name don't have to be the same thing :smile:

**Comment by mrmeszaros** [comment]
I definitely agree with it. So a question emerges:
 * should we create PR-s to rename icons which we know of
 * or rather make (or wait for) a collaborative effort (create / contribute to some mapping file)

**Comment by Foggalong** [comment]
You can make a PR if you want, but the potential issue is loosing track of the files listed in #3482 which need fixing when stuff gets renamed.

**Comment by mrmeszaros** [comment]
You are right.
For now then, I created a gist to manage mappings.
https://gist.github.com/matemeszaros/755c5ac2ba8f1b1f8296f9a8cb1dc49a

I extracted names from Steam (from the `http://store.steampowered.com/app/<appid>/<name>/`) - but feel free to contribute to the chrome app part.

Later on, we could use some kind of python script to modify the issue (or issues) based on this `mapping.json` file.

**Comment by mrmeszaros** [comment]
The mapping is ready.
Except for 5 Steam and 13 Chrome icons, all have a mapping.

I will look into the issues  #3481 and #3482, and try to fix the ones I have mappings for.

Should I create separate PR-s for the 3 parts (`optimization -> square coverage -> rename`), or can they go into one (but probably iteratively)?

**Comment by bilelmoussaoui** [comment]
@matemeszaros The square coverage is already done thanks to @W-Floyd :1st_place_medal: 
The only thing we still need to do is to update the icons and optimize them. If the mapping is ready, i can update the data.json & the icons names and #3482 so it won't cause any problems :)

**Comment by mrmeszaros** [comment]
@bil-elmoussaoui Ok :+1:

I can write a python script for you that automatically updates the data.json and the icon names.

(Actually I have already written one so if you want, I may upload next to the [mapping.json](https://gist.github.com/matemeszaros/755c5ac2ba8f1b1f8296f9a8cb1dc49a#file-mapping-json))

**Comment by bilelmoussaoui** [comment]
@matemeszaros I have already created a PR using your mapping.json here https://github.com/numixproject/numix-core/pull/3892
Thanks!

**Comment by bilelmoussaoui** [comment]
I have updated this issue with only the not-renamed yet icons
