### ISSUE TITLE
Icon for KeePassXC

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#3707]
Icon name is `keepassxc`
Desktop file name is `keepassxc.desktop`

![logo](https://cloud.githubusercontent.com/assets/7804464/25566658/c0346db8-2ddd-11e7-8553-8cf642cd3f6d.png)

KeePass Cross-Platform Community Edition

Website: https://keepassxc.org/

**Comment by bilelmoussaoui** [comment]
We already have that one https://github.com/numixproject/numix-core/blob/master/data.json#L7061

**Comment by palob** [comment]
The current one is a symlink which is why I labelled this as 'enhancement'.

**Comment by Foggalong** [comment]
Oooh, sorry misunderstood that!
