### ISSUE TITLE
Haguichi icon improvement

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-core#3709]
It will be nice to match the icon with the new logo.

![image](https://cloud.githubusercontent.com/assets/1277920/25602073/2a88691e-2ec7-11e7-9dde-9108c2af155e.png)

Description: `Haguichi is free and open source software licensed under GPLv3+. Written in Vala and using GTK+ as widget toolkit, Haguichi provides a user friendly GUI to ...`

Website: `https://www.haguichi.net/news/release130/`

**Comment by really-need-an-api-key** [comment]
Something like this?
![haguichi2 svg](https://user-images.githubusercontent.com/11636003/56855018-24ef5980-6940-11e9-8bcc-e4b832759dd0.png)

**Comment by palob** [comment]
Yeah but I think the background could be more contrasting. Is the colour related to the app?

**Comment by really-need-an-api-key** [comment]
Not particularly, the UI looks pretty bare-bones GTK3 https://www.haguichi.net/screenshots/

Is this better?
![haguichi3 svg](https://user-images.githubusercontent.com/11636003/56860541-074dde80-6998-11e9-87d8-f99d26d99b29.png)

**Comment by Foggalong** [comment]
All I can think looking at the redesigned original icon is Plex :disappointed:

**Comment by ztefn** [comment]
> All I can think looking at the redesigned original icon is Plex

With simple shapes there will always be some resemblance with other icons or brands, unfortunately. 

The original icon had this problems as well. As it was very similar to the "share icon" many icon themes interchanged these two, including Numix:
<img src="https://raw.githubusercontent.com/numixproject/numix-core/408048b43b4ffc6c4b641a209ae851ec37a76f7e/Numix-Circle/48/applications/haguichi.svg?sanitize=true" width=256 height=256 />
Also, the round shapes were sub optimal for rendering at small sizes (like in the status/notification area).

If you want to have a fresh base for the new Numix icon, I would like to suggest grabbing the [updated GNOME style icon from master](https://github.com/ztefn/haguichi/blob/master/data/icons/hicolor/scalable/apps/haguichi.svg) (it will be shipped in version 1.4.2):
<img src="https://raw.githubusercontent.com/ztefn/haguichi/2bb511947574c61427675f2099b0b60167a77fa6/data/icons/hicolor/scalable/apps/haguichi.svg?sanitize=true" width=256 height=256 />

**Comment by ztefn** [comment]
On topic, I made a quick icon suggestion for Numix square with sufficient contrast while still using the original colors:
https://gist.github.com/ztefn/0bf8c145ed775e6ecbfaaf39eefe29c2

<img src="https://gist.githubusercontent.com/ztefn/0bf8c145ed775e6ecbfaaf39eefe29c2/raw/a782877cfbf0f07fe4cfa1765534131a4a001446/haguichi.svg?sanitize=true" width=256 height=256 />

**Comment by Foggalong** [comment]
Ooo that split is quite nice actually. Would like to see any submission to Numix make use of that, seems upstream uses it in their style guide also for monochromatic icons.

**Comment by ztefn** [comment]
@Foggalong I _am_ upstream! :)

**Comment by Foggalong** [comment]
oh hai! Thanks for checking out this issue and directing us to the above icon :D

**Comment by really-need-an-api-key** [comment]
> On topic, I made a quick icon suggestion for Numix square with sufficient contrast while still using the original colors:
> https://gist.github.com/ztefn/0bf8c145ed775e6ecbfaaf39eefe29c2
> 
> <img alt="" width="256" height="256" src="https://gist.githubusercontent.com/ztefn/0bf8c145ed775e6ecbfaaf39eefe29c2/raw/a782877cfbf0f07fe4cfa1765534131a4a001446/haguichi.svg?sanitize=true">

Oh that is nice!

**Comment by ztefn** [comment]
> Oh that is nice!

Thanks! Already made a pull request for it: https://github.com/numixproject/numix-core/pull/4857
