### ISSUE TITLE
Icon for The Final Station (Steam)

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#3713]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `The Final Station`| `steam_icon_435530` | `The Final Station.desktop` | ![the_final_station 48](https://cloud.githubusercontent.com/assets/15245298/25949600/5032b0fa-3658-11e7-8d90-0e0869390a26.png) |

Description: "Travel by train through a dying world. Look after your passengers, keep your train operational, and make sure you can always reach the next station."

Website: http://thefinalstation.com/

**Comment by mrmeszaros** [comment]
@palob I created a sketch that could work. Do you think it is worth a PR?

| Circle | Square |
|:-:|:-:|
|![the-final-station circle](https://user-images.githubusercontent.com/15245298/31501653-201dbbf8-af6b-11e7-95c0-ce62b4505a0e.png) | ![the-final-station square](https://user-images.githubusercontent.com/15245298/31501662-25a354e8-af6b-11e7-8b68-4e4a4bb153b8.png) |

**Comment by palob** [comment]
Sure thing, go ahead :+1:
