### ISSUE TITLE
Icon for dnfdragora

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3715]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `dnfdragora`| `dnfdragora` | `org.mageia.dnfdragora.desktop` | ![screenshot_2017-05-14_16-59-38](https://cloud.githubusercontent.com/assets/6264656/26035478/ccba5e7c-38cc-11e7-9bcf-8e0427ce454f.png)

Description:  A graphical front end for installing, removing and updating packages

Website: https://github.com/manatools/dnfdragora

**Comment by palob** [comment]
The ``yumex-dnf`` icon is a symlink to ``synaptic``.

**Comment by bilelmoussaoui** [comment]
Done on master, the two other desktop files uses the same icon name; We can't do anything about it.
