### ISSUE TITLE
Icon for dnfdragora Package Installer

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3716]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `dnfdragora Package Installer`| `dnfdragora` | `org.mageia.dnfdragora-localinstall.desktop` | ![screenshot_2017-05-14_17-06-28](https://cloud.githubusercontent.com/assets/6264656/26035506/8f443e18-38cd-11e7-8f3a-d3cd993b5f86.png)

Description: Install local packages on the system

Website: https://github.com/manatools/dnfdragora

**Comment by bilelmoussaoui** [comment]
A symlink to `system-software-install`?

**Comment by Foggalong** [comment]
I thought we had a fedora package icon somewhere but maybe I'm misremembering it. Otherwise yeah, symlink will suffice

**Comment by ghost** [comment]
You guys had a icon for Yum Extender on Fedora/Korora but YumEx isn't developed anymore and will be replaced with dnfdragora in Fedora and Korora 26. Maybe just use the YumEx icon instead? I'm no expert on this kind of thing so i'll leave that up to you.

**Comment by ghost** [comment]
I had a chat on IRC with one of our team members at Korora. He and i both agreed it would be nice to see a new numix circle icon which is more close to the original dnfdragora icon. So if it's possible we would appreciate it a lot if you guys could look into that. :)

**Comment by palob** [comment]
I'd however say you can't get any closer than a cardboard box like in the yumex icon.

The way I see it the original icon (which I don't think is particularly well designed) is a cardboard box with an arbitrary array of colours on it.

Maybe some colour variation or something based on ``yaourt-gui``?

**Comment by ghost** [comment]
You're right. If it's possible for you guys, could you please fix (symlink?) this so the yumex icon points to dnfdragora, dnfdragora-updater and dnfdragora Package Installer? We really would appreciate it.
Thanks in advance. :)

**Comment by bilelmoussaoui** [comment]
@DarkEra It's done on master, the 3 desktop files uses the same icon name so we can't have a different icon for each one. Can you report that upstream? And reopen this & #3717
