### ISSUE TITLE
Capslock/Numlock panel indicator (for indicator-keylock package)

### ISSUE THREAD

**Issue by ayushkamadji** [numixproject/numix-core#3725]
| Application Name | Icon name | Desktop File Name | Original icon |
| --- | :-- | :-- | :-- |
| `indicator-keylock`| `caps/num/scrolllock(on-off)` | `DESKTOP FILE NAME` | ![lock-icons-ubuntu-mono-dark.zip](https://github.com/numixproject/numix-core/files/1015063/lock-icons-ubuntu-mono-dark.zip) (just simple flat icons with an 'A', '1', {up-arrow}. With active and not-active colors |

Description: `indicator-keylock allows for caps/num/scrolllock indicator on panel. Useful for machines without lock key LEDs. The original above is from ubuntu-mono-dark icon theme.`

Website: `https://launchpad.net/~tsbarnes/+archive/ubuntu/indicator-keylock`

**Comment by bilelmoussaoui** [comment]
The tray icons should be reported here instead https://github.com/numixproject/numix-icon-theme
And please upload the icons right here in the issue. No zip files or any other links that point to other websites.

**Comment by ayushkamadji** [comment]
cool thanks.
