### ISSUE TITLE
Icon request: Panel icons for Exaile Music Player

### ISSUE THREAD

**Issue by malysps** [numixproject/numix-core#3731]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| Exaile| `exaile-play` | `-` | ![exaile-play](https://cloud.githubusercontent.com/assets/16068365/26477142/c918f9f4-41c3-11e7-8300-c9821ea6686a.png) |
| Exaile| `exaile-pause` | `-` | ![exaile-pause](https://cloud.githubusercontent.com/assets/16068365/26477169/0b40eb98-41c4-11e7-9f00-113c0ae1f139.png) |

Hello. I'm using Exaile 3.4.0 and Xfce 4.10. These icons are visible on my panel in the Notification Area when my music is playing or is paused. I know that these icons are changing properly in Faenza set for example. They should be located in 'status' folder (16, 22, 24, 32 and maybe more?). I suggest that icon to be monochromatic to match current Numix panel icons style.

Thanks in advance.

Website: http://www.exaile.org

**Comment by bilelmoussaoui** [comment]
Should be reported here instead https://github.com/numixproject/numix-icon-theme
