### ISSUE TITLE
Icon for Antichamber (Steam)

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#3732]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Antichamber`| `steam_icon_219890` | `Antichamber.desktop` | ![antichamber](https://cloud.githubusercontent.com/assets/15245298/26531550/c8e6e1ce-43eb-11e7-8440-e269574e87e2.png) |

Description: Antichamber is a mind-bending psychological exploration game where nothing can be taken for granted.

Website: http://www.antichamber-game.com/

Comment: The `Icon` line of the desktop file only says `steam`.

**Comment by palob** [comment]
I suppose we've got this. At least we've got an icon looking very similar.

**Comment by mrmeszaros** [comment]
Yeah, right i found it (the circle one - square is missing).

Then all I need is to change the **Icon** line from `steam` to `steam_icon_219890`, right?

**Comment by palob** [comment]
Exactly. For convenience copy the launcher to ``~/.local/share/applications/`` beforehand. This way it will not be overwritten in the course of updates and you don't need root privileges.

**Comment by mrmeszaros** [comment]
I would like to add the square icon (based on the circle) - but the source of the circle seems to be a bit messy (there are two backgrounds and a second symbol between them):

![bad antichamber circle](https://cloud.githubusercontent.com/assets/15245298/26546652/59ad61d6-446b-11e7-96cc-8676120e3b91.png)

Can I clean it up, or should I leave it for now?

**Comment by palob** [comment]
I haven't noticed that before but if it's true it's a bug for sure. A fix is welcome.

**Comment by mrmeszaros** [comment]
Created a fix - although the symbol would need some tweaking in my opinion (the circle is a bit off-grid)
