### ISSUE TITLE
Icon Request : Dino

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3739]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Dino | `dino` | `dino.desktop` | ![Dino](http://i.imgur.com/Gop0ONt.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Can anybody point me to the app's web page?

**Comment by bilelmoussaoui** [comment]
@palob https://github.com/dino/dino
