### ISSUE TITLE
Icon for GNOME Usage

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#3741]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `GNOME Usage`| `org.gnome.Usage` | `org.gnome.Usage.desktop` | ![original icon](https://wiki.gnome.org/Apps/Usage?action=AttachFile&do=get&target=appname-logo.png) |

Description: A nice way to view information about use of system resources, like memory and disk space.

Website: https://wiki.gnome.org/Apps/Usage

**Comment by palob** [comment]
AFAIK this is more or less slated to replace GNOME System Monitor at some time.
Given that the icon looks quite similar, do you think a symlink (or a recolour) will do it?

**Comment by bilelmoussaoui** [comment]
A recolour is better :)

**Comment by palob** [comment]
Or maybe something like the htop icon.

**Comment by palob** [comment]
Here are some drafts:
![gnome-usage-drafts](https://cloud.githubusercontent.com/assets/7050624/26752131/4ea49ad4-4849-11e7-8735-c4ee78a682b8.png)

**Comment by KSXGitHub** [comment]
I vote for gnome-usage4
