### ISSUE TITLE
I'm making a new icon for the Opera Browser in Numix Circle

### ISSUE THREAD

**Issue by onemenzel** [numixproject/numix-core#3742]
| Application name | Icon name | Desktop file name | Original icon | Theme 
| --- | :-- | :-- | :-- | :-- |
| Opera| `opera` | `opera.desktop` | ![opera](https://cloud.githubusercontent.com/assets/6469566/26738042/f80894ea-47cc-11e7-928d-8247df469385.png) | Numix-Circle |

Description: A well known web browser

Website: http://www.opera.com/

Hello folks!

The current Opera icon in Numix Circle is outdated because it is based on the old logo. So I thought I'm going to make a new one. Still struggling with the background color though. I have one draft with a "black" which I got from the background they set on their windows version and one with L249. Do you prefer one of the appended styles or would you suggest another color (or even scaling the "O" down)?
Or would you just like to keep the old icon?

Regards, onemenzel

![opera](https://cloud.githubusercontent.com/assets/6469566/26738369/22835d62-47ce-11e7-8a10-d0b9afe01dc1.png)  ![opera-dark](https://cloud.githubusercontent.com/assets/6469566/26738376/25492838-47ce-11e7-86c5-2f699d6c3577.png)

**Comment by palob** [comment]
Hi, thanks for your contribution. Please open a pull request so we can review your icon.
Can you please implement the icon as a symbol of max 30x30 size on a baseplate?
