### ISSUE TITLE
Slack icon not working

### ISSUE THREAD

**Issue by Siilwyn** [numixproject/numix-core#3758]
| Application name | Icon name | Desktop file name |
| --- | :-- | :-- |
| `Slack`| `/usr/share/pixmaps/slack.png` | `slack.desktop` |

Not sure if this is the correct repository.
I'm using the `numix-icon-theme-circle 2.0.3+14~201704051631~ubuntu16.04.1` package, all icons except from Slack are working. Any way to troubleshoot this?

**Comment by palob** [comment]
It's hardcoded but since we use SVGs it should work anyway. What do you mean by "not working". Do you see a blank spot or the original icon?

**Comment by Siilwyn** [comment]
@palob sorry for not being clear, it is showing the original icon.

**Comment by bilelmoussaoui** [comment]
Are you sure about the icon name?

**Comment by Siilwyn** [comment]
@bil-elmoussaoui no, I just assumed I should fill in the name of the [icon in the repo](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/slack.svg)?

**Comment by bilelmoussaoui** [comment]
Ah non, you should check the desktop file. it must be under /usr/share/applications/ the file name might be slack.desktop. we need the content of that file in order to fix your issue

**Comment by Siilwyn** [comment]
Oh my bad I didn't understand the purpose of the table, updated the main post to include the full path.

**Comment by bilelmoussaoui** [comment]
Thanks! The icon is hardcoded and uses an absolute path instead of the icon name. You can use hardcode-fixer to fix that (see README) or just edit that file and change the icon value to slack (without any extension)

**Comment by Siilwyn** [comment]
@bil-elmoussaoui thank you! I actually checked out the supported hardcoded application list before creating this issue and Slack is not there.

**Comment by bilelmoussaoui** [comment]
@Siilwyn It's already supported https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv#L361 The supported list might be outdated

**Comment by Siilwyn** [comment]
Oh I see, thanks again! It might be better to link the "supported application list" in the wiki to the CSV, it's searchable and understandable too. Just noticed that the wiki page is more about tracking upstream bugs but the naming of the page is a bit confusing.

**Comment by bilelmoussaoui** [comment]
@Foggalong What do you think about that?

**Comment by Foggalong** [comment]
@Siilwyn @bil-elmoussaoui I get what you're saying, but yeah: we still need that page because one of the big aims of the project is to fix as many of those issues as possible upstream. I even messaged GitHub to ask about markdown support in CSV and they said it's just not going to happen :cry:
