### ISSUE TITLE
Improve Rambox Icon

### ISSUE THREAD

**Issue by forivall** [numixproject/numix-core#3759]
| Application Name | Icon Name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Rambox`| `rambox` | `rambox.desktop` | ![original](https://rawgit.com/numixproject/numix-core/master/icons/circle/48/rambox.svg) |

Description: `Multi-client Messaging and Email web-app client`

Website: https://rambox.pro

The rambox icon, originally added in e13594a6e99891526d4c2058d85e95bda4bdd416
https://github.com/numixproject/numix-core/commits/e13594a6e99891526d4c2058d85e95bda4bdd416/Numix-Circle/48x48/apps/rambox.svg

IMO, the icon should fill the entire circle, rather than being a circle inside a circle.

**Comment by palob** [comment]
All of our full-baseplate symbol designs are exceptions to our design guidelines.
Please see #3291 where the current design was chosen over a full-baseplate design.

**Comment by Foggalong** [comment]
Sorry @forivall, but I'm gonna reject this enhancement. The circle within a circle was an inspired way to get both colours from the original into the icon in there while keeping the silhouette as was and sticking to the design guidelines. Plus it's bloody beautiful!

**Comment by forivall** [comment]
Aww. I might make a custom version and modify the PKGBUILD anyways, and see if you _might_ consider it. Thanks for pointing me to the original PR though!

**Comment by Foggalong** [comment]
I can't promise that it'll be merged in, but yeah if you want to try a redesign by all means go for it :)
