### ISSUE TITLE
JetBrains IDEs installed through JetBrains ToolBox not themed (hardcode-fixer not working)

### ISSUE THREAD

**Issue by gusandrianos** [numixproject/numix-core#3773]
Is it just me or this is a problem in general?
I am on Ubuntu Gnome with Numix Circle icon pack. 
No Android Studio icon either.

**Comment by bilelmoussaoui** [comment]
Those icons are hardcoded. See https://github.com/numixproject/numix-core#hardcoded-icons

**Comment by gusandrianos** [comment]
@bil-elmoussaoui What do you mean see https://github.com/numixproject/numix-core#hardcoded-icons
?
As I explained already, I have used the script but it didn't change anything.

**Comment by bilelmoussaoui** [comment]
It's an upstream issue, the icons already exists on the Circle Icon Pack

**Comment by gusandrianos** [comment]
And what do you suggest I do to fix it? I'm not really following.

**Comment by palob** [comment]
Please add the information asked for in the readme. We need the icon name from the ``.desktop`` launcher file in particular.

**Comment by gusandrianos** [comment]
@palob It's not an icon request. The icons are there, they just don't apply. I think I was clear.

**Comment by palob** [comment]
We need to know it if you want help.

**Comment by gusandrianos** [comment]
@palob Do you mean the following files?

jetbrains-idea.desktop
jetbrains-studio.desktop
jetbrains-rubymine.desktop

**Comment by palob** [comment]
Yes, probably.

**Comment by palob** [comment]
We need the ``Icon=`` lines from inside the files.

**Comment by gusandrianos** [comment]
How can you make those universal? I mean, since anyone can have different versions in different locations and all.

Icon=/home/gus/.jetbrains/RubyMine-2017.1.3/bin/RMlogo.svg
Icon=/home/gus/.jetbrains/idea-IU-163.12024.16/bin/idea.png
Icon=/home/gus/.jetbrains/android-studio/bin/studio.png

**Comment by gusandrianos** [comment]
@palob 
The netbeans icon is also not applying.
/home/gus/netbeans-8.2/nb/netbeans.png

**Comment by palob** [comment]
You can copy those files to ``~/.local/share/applications/`` and edit the icon lines to ``Icon=<file name of the respective Numix Circle icon without .svg at the end>``.

I can't look up the`Numix icon names for you currently, I'm not at my PC.
You'll probably find the Numix Circle icons somewhere below ``usr/share/icons/Numix-Circle/``

**Comment by palob** [comment]
Alright, found it anyway, it's gotta be:
``Icon=androidstudio``
``Icon=netbeans``
``Icon=rubymine``
``Icon=idea``

**Comment by gusandrianos** [comment]
I did it, thank you very much. I'll try to make a shell script to automatically do those changes, but oh well, it worked. Thanks again :)

**Comment by palob** [comment]
When using a different theme you'll probably have to edit the icon names accordingly.
In order to get the original icons back you need to delete the edited files.
