### ISSUE TITLE
Icon Request : Persepolis Download Manager

### ISSUE THREAD

**Issue by alireza-amirsamimi** [numixproject/numix-core#3774]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Persepolis Download Manager`| `persepolis` | `persepolis.desktop` | ![original](https://user-images.githubusercontent.com/7452500/27415805-6673a3c4-571e-11e7-86bc-9c91e338b0e2.png) |

Description: 
Hello
I am developer of [Persepolis Download Manager](https://github.com/persepolisdm/persepolis) project. Persepolis is a download manager application for GNU/Linux and BSD and Mac and Windows. Persepolis is Free Software. 
I add some additional description about our original icon, may it helps you :)
The white symbol in icons is [OLD PERSIAN SIGN PA](https://www.utf8icons.com/character/66481/old-persian-sign-pa) which stands for P in Persepolis and it is related to our project name.
*Where does the name of our project come from?*
 [Persepolis](https://en.wikipedia.org/wiki/Persepolis) exemplifies the Achaemenid style of architecture. UNESCO declared the ruins of Persepolis a World Heritage Site in 1979. Persepolis is situated 60 km northeast of the city of Shiraz in Fars Province, Iran. The earliest remains of Persepolis date back to 515 BC.
The old persian symbol( that we used in icon) is the first letter of Persepolis word in [old persian language](https://en.wikipedia.org/wiki/Old_Persian_language)  .

[perhaps this font helps you](http://www.fontspace.com/fereydoun/behistun)

[Link of Persepolis original icon in svg format on github](https://github.com/persepolisdm/persepolis/blob/master/icons/persepolis.svg)

[Link of persepolis icon file in papirus icon theme project on github in svg format](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/persepolis.svg)

Website: `http://persepolisdm.github.io/`
GitHub Page : `http://github.com/persepolisdm/persepolis`

Regards
AliReza AmirSamimi

**Comment by palob** [comment]
Hi, I had already proposed an icon which however is only a loose representation of the original design.

**Comment by alireza-amirsamimi** [comment]
@palob 
Thanks for this [#3754](https://github.com/numixproject/numix-core/pull/3754) 👍 

We (developers of persepolis) selected that old persian letter as symbol of our application and it's important for us. some thing like cone shape in VLC icon or fox in FireFox icon ,  ... :)

Do you can redesign it and add that symbol to the icon in your free time please ? :)

thank you
