### ISSUE TITLE
Icon for Arx Libertatis

### ISSUE THREAD

**Issue by terzag** [numixproject/numix-core#3775]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Arx Libertatis`| `arx-libertatis.png` | `arx-libertatis.desktop` | ![arx-libertatis](https://user-images.githubusercontent.com/3089759/27450939-a53f4350-578d-11e7-848f-da5c655f7f8c.png) |

Description: Arx Libertatis is a cross-platform, open source port of Arx Fatalis, a 2002 first-person role-playing game / dungeon crawler developed by Arkane Studios.

Website: [arx-libertatis.org](http://arx-libertatis.org/)

I've made a quick and dirty icon using Numix templates, not sure where/how to upload the SVG version if interested for inclusion.
![arx-libertatis_preview](https://user-images.githubusercontent.com/3089759/27451025-0a79fa94-578e-11e7-837a-8c9058caf6a5.png)

**Comment by palob** [comment]
@terzag Do  you have your drafts still around and do you fancy opening a pull request?

**Comment by terzag** [comment]
I still have both SVG icons but I'm not sure how to open a pull request / what to put in it. I'm not very GitHub-savvy. ;)

**Comment by Foggalong** [comment]
There's a good tutorial in the contributing file :)

**Comment by terzag** [comment]
Too complicated. If someone want to grab them, I've put an archive there: https://www.dropbox.com/s/nv6vuqdtid91i9f/numix_arx.tar.gz?dl=0

**Comment by palob** [comment]
Fixed in https://github.com/numixproject/numix-core/commit/eb65ef51088a7a57337287e8464c7d6d363c3030
