### ISSUE TITLE
Icon for StackApplet

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#3780]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `StackApplet`| `stackexchange` | `stackapplet.desktop` | ![stackexchange](https://user-images.githubusercontent.com/15245298/27512079-ac549484-5935-11e7-9447-c3a8586bb641.png) |

Description: An indicator for monitoring your Stack Exchange accounts.
Sadly, the project is no longer maintained.

Website: https://launchpad.net/stackapplet

**Comment by palob** [comment]
Last release dates back more than 10 years. Closing unless someone is still using this via Flatpak, Snap, appimage or something.
