### ISSUE TITLE
Icon for Linphone

### ISSUE THREAD

**Issue by xoxys** [numixproject/numix-core#3806]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Linphone`| `linphone` | `linphone.desktop` | ![linphone](https://user-images.githubusercontent.com/3391958/27827728-04272da4-60b9-11e7-8b47-75447a17f70e.png) |

Description: `Open source voip softphone`

Website: `http://www.linphone.org/`

**Comment by bilelmoussaoui** [comment]
we already have that icon on Circle https://github.com/numixproject/numix-core/blob/master/icons/circle/48/linphone.svg
The square theme is still not fully complete yet see #3481
