### ISSUE TITLE
Icon for Visual Studio Code

### ISSUE THREAD

**Issue by AmbulantRex** [numixproject/numix-core#3810]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Visual Studio Code`| `Visual Studio Code` | `/usr/share/code/resources/app/resources/linux/code.png` | ![code](https://user-images.githubusercontent.com/21176662/28019706-14c5361c-653f-11e7-81d6-6bdd3a1eef5d.png) |

Description: `Code Editing. Redefined.`

Website: https://code.visualstudio.com/

**Comment by palob** [comment]
duplicate of #3507 #2964 #3504

**Comment by bilelmoussaoui** [comment]
+ The content of the issue is invalid
