### ISSUE TITLE
Icon for MAT

### ISSUE THREAD

**Issue by go-jdiego** [numixproject/numix-core#3819]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `MAT`| `mat` | `mat.desktop` |![captura de pantalla de 2017-07-14 14-47-55](https://user-images.githubusercontent.com/28605562/28255306-83a54bac-6a72-11e7-9e48-46a00688c07c.png)|

Description: `Metadata Anonymisation Toolkit`

Website: `https://mat.boum.org`

**Comment by palob** [comment]
Here's some drafts I'm unsure about.
![mat](https://user-images.githubusercontent.com/7050624/28288956-45af45b2-6b41-11e7-8788-32b1dbdb4a6e.png)

**Comment by bilelmoussaoui** [comment]
mat6.svg looks nice :)

**Comment by go-jdiego** [comment]
mat2 ;)

**Comment by Foggalong** [comment]
Mat2 gets my vote, though would it be possible to tweak the size so the symbol is slightly smaller?
