### ISSUE TITLE
update kdenlive icon

### ISSUE THREAD

**Issue by ramzydoni** [numixproject/numix-core#3849]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `kdenlive`| `kdenlive` | `Kdenlive.desktop` | ![original](https://kdenlive.org/wp-content/uploads/2016/06/kdenlive-logo-hori.png) |

Description: `Kdenlive video editor..

The program icon has been changed for a long time and has been changed in the official website i hope to update in "numix icon" ! 
http://i.imgur.com/G9nrddT.png`

Website: `https://kdenlive.org`

**Comment by Foggalong** [comment]
As @bil-elmoussaoui [already mentioned](https://github.com/numixproject/numix-icon-theme/issues/1232), this was already reported in #3415

**Comment by ramzydoni** [comment]
Why i can t  make a request i dont know !?

**Comment by bilelmoussaoui** [comment]
It's already made.

**Comment by ramzydoni** [comment]
Thank you. This is the third time I have requested this request ! : (

**Comment by Foggalong** [comment]
@ramzydoni And that was the thid time you'd been told it'd already been made :P

**Comment by ramzydoni** [comment]
I'm sorry I have a bad english
I understand that the icon has been updated but I don t see it.

**Comment by Foggalong** [comment]
The icon hasn't been updated, it's just been reported to us already and is on out list of things to do

**Comment by ramzydoni** [comment]
Thank you team
Good luck
