### ISSUE TITLE
New Fritzing Design

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#3850]
The design for Fritzing looks fine for Circle but because of the shadow placement in Square it looks very off there. This could be a design specifically for Square or a redesign for both, I don't really mind which.

**Comment by W-Floyd** [comment]
I know the dark band is in the real icon, but I think the best route is to simply remove it entirely.

![iconified_fritzing_icon](https://user-images.githubusercontent.com/11786132/33935924-5c841ede-e049-11e7-9726-23060f080ddb.png)

**Comment by Foggalong** [comment]
I'll be honest, I'm down for that :+1:

**Comment by W-Floyd** [comment]
Can be closed, fixed as of #4010
