### ISSUE TITLE
New Openshot design

### ISSUE THREAD

**Issue by ramzydoni** [numixproject/numix-core#3858]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `openshot`| `openshot` | `openshot.desktop` | ![original](http://www.omgubuntu.co.uk/wp-content/uploads/2016/01/openshot-logo.png) |

Description: `Openshot video editor`

Website: `www.openshot.org`

**Comment by bilelmoussaoui** [comment]
Just to be sure, are you saying that is the new logo of OpenShot or the current icon should be redesigned to match the current one?

**Comment by ramzydoni** [comment]
bil-elmoussaoui I think you should design a new icon for the openshot similar to the new logo and thank you

**Comment by W-Floyd** [comment]
This may be closed as of #4009
