### ISSUE TITLE
Icon for muCommander

### ISSUE THREAD

**Issue by k-kirill** [numixproject/numix-core#3863]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| muCommander| `Icon=mucommander` | `mucommander.desktop` | ![original](https://user-images.githubusercontent.com/8539168/28766365-cc95cb32-75be-11e7-94f7-34fbbd9e9ac9.png) |

Description: a lightweight, cross-platform file manager with a dual-pane interface

Website: http://www.mucommander.com/

**Comment by k-kirill** [comment]
Thanks for the icon. It is nice. I hope you update numix-icon-theme-circle repository soon, so, I can grab it from there.

**Comment by Foggalong** [comment]
@k-kirill Updates there should now be happening roughly weekly again :)
