### ISSUE TITLE
Icon for RimWorld (Steam)

### ISSUE THREAD

**Issue by founderio** [numixproject/numix-core#3876]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `RimWorld`| `steam_icon_294100` | `RimWorld.desktop` | ![unityplayer](https://user-images.githubusercontent.com/6136865/29045239-1e85ce60-7bc3-11e7-9a29-40f10a07a02e.png) |

Description: `A 2D sci-fi colony simulation game. Top-Down view.`
Additional art ref:
![scenariopreview](https://user-images.githubusercontent.com/6136865/29045281-5551b666-7bc3-11e7-9e2b-7a66f2e2acfd.jpg)

Website: https://rimworldgame.com/ and http://store.steampowered.com/app/294100/RimWorld/

**Comment by bilelmoussaoui** [comment]
Fixed in https://github.com/numixproject/numix-core/commit/eea77c85021298e6e18c605f6e8e6143fdd5bb84
