### ISSUE TITLE
Icon for Slime Rancher (Steam)

### ISSUE THREAD

**Issue by founderio** [numixproject/numix-core#3877]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Slime Rancher`| `steam_icon_433340` (appid for the demo: `622050`) | `Slime Rancher.desktop` | ![unityplayer](https://user-images.githubusercontent.com/6136865/29045443-ec449f5c-7bc3-11e7-8912-6444c8fe27d0.png) ![96x96](https://user-images.githubusercontent.com/6136865/29045602-57620f2c-7bc4-11e7-9319-1e7e3467c80b.png)|

Description: `Slime Rancher is a life simulation game, primarily revolving around exploration, catching slimes and tending to them, selling their plorts, etc.`

Website: http://slimerancher.com/ and http://store.steampowered.com/app/433340/Slime_Rancher/

**Comment by bilelmoussaoui** [comment]
@palob @Foggalong Shouldn't we use a label for steam? that will make it much easier to find those icons instead of adding (Steam) in every icon report's title

**Comment by Foggalong** [comment]
@bil-elmoussaoui I'm not super clear why Steam needs a distinct label, title or otherwise? The route to fixing it isn't any different whether it's for Steam, Chrome, or any of the other similar groups because they (thankfully) follow the standards

**Comment by mrmeszaros** [comment]
@Foggalong I guess that creating a label for steam would help in filtering what has been requested, and what not.

**Comment by Foggalong** [comment]
@mrmeszaros Aye, but what does that do that [this doesn't](https://github.com/numixproject/numix-core/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Arequest+steam)?
