### ISSUE TITLE
Icon Request: Brackets-Electron

### ISSUE THREAD

**Issue by thenanobel** [numixproject/numix-core#3885]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Brackets-Electron`| `brackets-electron` | `brackets-electron.desktop` | ![brackets-electron](https://raw.githubusercontent.com/zaggino/brackets-electron/master/build/icons/128x128.png) |

Description: `Brackets-Electron is a derivative of Brackets, with Electron as it's underline shell. This fork of Brackets is being maintained by an official developer of Brackets, called Martin Zagora.`

Website: [`https://github.com/zaggino/brackets-electron`](https://github.com/zaggino/brackets-electron)

> **Note:** A SVG version of this icon is available [here](https://github.com/zaggino/brackets-electron/blob/master/build/icon.svg).

**Comment by Foggalong** [comment]
@thenanobel Is there any other distinction between the two pieces of software? i.e. are people likely to have both installed at once?

**Comment by thenanobel** [comment]
No. There's not any other distinction between these two, as far as I've seen since yesterday. No. As, `Brackets-Electron` provides you all the same features as `Brackets`. There's not any possible reason for installing both them on a system, at.

You may find it useless to install `Brackets-Electron`, as it doesn't have any special feature that `Brackets` lacks. But, it has a significance for Debian/Ubuntu users. `Brackets`' default installer for Debian/Ubuntu has a dependency issue, it depends on an obsoleted library called `libgcrypt11`, which has been superseded by `libgcrypt20` in the latest versions of Debian/Ubuntu. As `Brackets`' shell depends on that obsoleted library, `Brackets` developers couldn't switch from depending on that obsoleted library, probably because, they have to a lot of works for resolving this issue. For this reason [they have suggested](https://github.com/adobe/brackets/issues/10255#issuecomment-243854796) GNU/Linux user to use `Brackets-Electron` instead.

Anyway, I've modified the existing `Brackets` icon for [Numix Circle](https://my.owndrive.com/index.php/s/M4pDUTLkujLu43Z) and [Numix Square](https://my.owndrive.com/index.php/s/dYcOp3ZKL34bOv9) icon themes by applying the color schemes of `Brackets-Electron`. All the related files can be found [here](https://my.owndrive.com/index.php/s/9FPF9lXGTh0MFga). I don't know whether these will be helpful or not. But, they might.

| Original Icon | Circle Icon | Square Icon|
| --- | --- | --- |
| ![icon be svg](https://user-images.githubusercontent.com/9353047/29253218-0e34d8aa-8099-11e7-8046-59ee2b234c13.png) | ![brackets-electron-circle svg](https://user-images.githubusercontent.com/9353047/29253223-24b8af48-8099-11e7-8cd2-ae6996956667.png) | ![brackets-electron-square svg](https://user-images.githubusercontent.com/9353047/29253225-323f2df4-8099-11e7-8b80-fe82c6874501.png) |

**Comment by Foggalong** [comment]
Sure thing! If you fancy setting those up as a pull request that'd be awesome :)

**Comment by thenanobel** [comment]
Done! :smiley:
