### ISSUE TITLE
Icon for Piper

### ISSUE THREAD

**Issue by rautesamtr** [numixproject/numix-core#3889]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| Piper (exec: piper)| org.freedesktop.Piper | org.freedesktop.Piper.desktop | ![original](https://cdn.rawgit.com/libratbag/piper/master/data/org.freedesktop.Piper.svg) |

Description: Piper is a GTK+ application to configure gaming mice, using libratbag via ratbagd.

Website: https://github.com/libratbag/piper

**Comment by bilelmoussaoui** [comment]
Fixed
