### ISSUE TITLE
How to install Numix packages on Debian?

### ISSUE THREAD

**Issue by thenanobel** [numixproject/numix-core#3891]
I've make a move from Ubuntu 16.04 to Debian 9 for some days. I'm wishing to install Numix packages on my Debian system. How to install Numix packages on Debian?

I've found [this process](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#debian-and-derivatives) in Papirus Icon themes' repository. Is it okay, if I do the same for Numix?

**Comment by bilelmoussaoui** [comment]
I think you can use this installation method 
https://github.com/numixproject/numix-icon-theme#installation

**Comment by thenanobel** [comment]
Nothing happens. Watch here, [https://asciinema.org/a/irfBamaA2MRraaBfzQlIdLsdj](https://asciinema.org/a/irfBamaA2MRraaBfzQlIdLsdj).

Althought it creates a file `/etc/apt/sources.list.d/numix-ubuntu-ppa-artful.list` containing,

    deb http://ppa.launchpad.net/numix/ppa/ubuntu artful main
    # deb-src http://ppa.launchpad.net/numix/ppa/ubuntu artful main
    # deb-src http://ppa.launchpad.net/numix/ppa/ubuntu artful main

**Comment by Foggalong** [comment]
I honestly have no idea how using Ubuntu PPAs for Debian works. Might be wroth messaging the Papirus folks to see what they did to make it work

**Comment by bilelmoussaoui** [comment]
Hey @varlesh, is there anything we should do to make our PPA works with Debian like yours? You have much more knowledge about Debian packaging than me! Thanks

**Comment by Foggalong** [comment]
We now have themes [in the Debian repository](https://packages.debian.org/search?keywords=numix&searchon=names&suite=all&section=all), with more on the way :) If @varlesh ever gets back to use about Debian PPAs we'll enable that also
