### ISSUE TITLE
Icon for Visual Studio Code

### ISSUE THREAD

**Issue by adowdy** [numixproject/numix-core#3913]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Visual Studio Code`| `vsc.svg` | `visual-studio-code.desktop` | ![original](https://www.shareicon.net/data/128x128/2015/10/04/111667_microsoft_512x512.png) |

Description: `VSC - visual studio code is a text editor and pseudo-IDE from microsoft. cross-platform and open source`

Website: `https://code.visualstudio.com/`

I have a recolored SVG file that fits the color theme of VSC (distinct from the purple of visual studio on windows) that I made that looks pretty good already in numix-square. Here: http://svgshare.com/s/30f

**Comment by bilelmoussaoui** [comment]
We already have a vscode icon, the icon name is vscode. I will add a symlink to fix this
