### ISSUE TITLE
Icon for Spotify is wrong color in Square

### ISSUE THREAD

**Issue by tangram** [numixproject/numix-core#3915]
Spotify's icon is not "Spotify Green" (#1ED760) in Square.

![Spotify in Circle](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/spotify-client.svg)

![Spotify in Square](https://github.com/numixproject/numix-core/blob/master/icons/square/48/spotify-client.svg)

**Comment by tangram** [comment]
I see that you have quite the list to get through (#3482), so I guess you will get around to it eventually.

**Comment by bilelmoussaoui** [comment]
I have created a PR to fix this, so you should get it in the next update 👍

**Comment by tangram** [comment]
Wow, thanks! :+1:
