### ISSUE TITLE
Icon for Cryptomator

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#3926]
`Cryptomator`
`Icon=/opt/Cryptomator/Cryptomator.png`
 `Cryptomator.desktop`

![cryptomator-logo](https://user-images.githubusercontent.com/7804464/30772853-d1f2b9b6-a064-11e7-8707-c42bef3578d2.png)

Description: Free client-side encryption for your cloud files.

Website: https://cryptomator.org/

**Comment by mrmeszaros** [comment]
Hey @gregorydk, how do you like something like this?
![cryptomator 512](https://user-images.githubusercontent.com/15245298/32283656-4c1da41a-bf25-11e7-97de-e8dae0a4262d.png)

**Comment by gregorydk** [comment]
Looks good but it's missing a drop shadow.
