### ISSUE TITLE
Icon Request: Granite Demo

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#3935]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Granite Demo | `applications-interfacedesign` | `granite-demo.desktop` | ![Granite Demo](https://i.imgur.com/F9sDjnJ.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by bilelmoussaoui** [comment]
@palob What do you think about a link to gtk3-widget-factory?

**Comment by palob** [comment]
Recolour or symlink?

**Comment by bilelmoussaoui** [comment]
The icon name seems to be one of the applications-* icons.  The icon looks pretty fine. And I don't think it deserves it's own icon. Either a symlink or a recolour with a light green?

**Comment by palob** [comment]
I'd say a recolour since you are like to use both.
