### ISSUE TITLE
Update Visual Studio Code Icon

### ISSUE THREAD

**Issue by jose-a-sa** [numixproject/numix-core#3938]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Visual Studio Code`| `code` | `code.desktop` | ![original](https://code.visualstudio.com/images/1_17_mac-stable-orange.png) |

Description: `Code editing. Redefined.`

Website: `https://code.visualstudio.com/updates/v1_17`

**Comment by Foggalong** [comment]
See discussion in #3902 or #2964 depending what the intent of your report was.
