### ISSUE TITLE
Icon for Mailspring

### ISSUE THREAD

**Issue by Txarli** [numixproject/numix-core#3946]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Mailspring`| `mailspring` | `mailspring.desktop` | ![mailspring](https://user-images.githubusercontent.com/3373382/31491390-661a17ec-af47-11e7-8dbe-7824f501083c.png) |

Description: `An email app for people and teams at work`

Website: `http://www.getmailspring.com/`

**Comment by cerniusnet** [comment]
Created pull request for Mailspring icons. https://github.com/numixproject/numix-core/pull/3984

**Comment by l3lackcurtains** [comment]
How is this issue closed? I still get the ugly original icon.

**Comment by palob** [comment]
Either you've got an outdated Numix installation or your Mailspring installation comes with a different icon name. Could you please look up what's in the respective ``.desktop`` launcher file?

**Comment by l3lackcurtains** [comment]
Thanks, Worked after updating Numix and OS itself.
