### ISSUE TITLE
Icon for Meshlab

### ISSUE THREAD

**Issue by bkanuka** [numixproject/numix-core#3971]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
|Meshlab| `/usr/share/pixmaps/meshlab_32x32.xpm` | `meshlab.desktop` |![icon](http://www.meshlab.net/img/meshlabLogo.png)|

Description: the open source system for processing and editing 3D triangular meshes.
It provides a set of tools for editing, cleaning, healing, inspecting, rendering, texturing and converting meshes. It offers features for processing raw data produced by 3D digitization tools/devices and for preparing models for 3D printing.

Website: http://www.meshlab.net/

Yes, I know it's hardcoded, but it's not difficult to fix if an icon existed.

**Comment by bkanuka** [comment]
original icon svg is here: https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlab/images/eye.svg

I have done my best simplifying the icon. I think if this was put over a gray background, it would look nice and keep the "feeling" of the original icon. 
[drawing.svg.zip](https://github.com/numixproject/numix-core/files/1444174/drawing.svg.zip)

**Comment by bkanuka** [comment]
I took my best shot at an icon. It is very much based on the original icon svg. I'm really hoping someone can complete the last few steps. I'm *really* not sure what I'm doing!
[meshlab.svg.zip](https://github.com/numixproject/numix-core/files/1444366/meshlab.svg.zip)

**Comment by bilelmoussaoui** [comment]
Fixed
