### ISSUE TITLE
Icon for XnView

### ISSUE THREAD

**Issue by AdLef2595** [numixproject/numix-core#3980]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `XnView Multi Platform`| `xnview.png` | `XnView.desktop` | ![xnview](https://user-images.githubusercontent.com/33607200/32703877-a1fd7baa-c7fc-11e7-91a2-fbfbd7e80ca9.png)

Description: `XnView is a multimedia viewer, browser and converter.`

Website: `https://www.xnview.com/en/`

**Comment by bilelmoussaoui** [comment]
We do have that icon 
https://github.com/numixproject/numix-core/blob/master/icons/circle/48/xnview.svg

**Comment by bilelmoussaoui** [comment]
Please use https://github.com/numixproject/numix-core#hardcoded-icons
or just modify the destkop file, and set the icon name to `xnview`

**Comment by AdLef2595** [comment]
Thank you
