### ISSUE TITLE
Icon for Riot

### ISSUE THREAD

**Issue by idolgov** [numixproject/numix-core#3981]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Riot`| `riot` | `riot.desktop` | ![original](https://raw.githubusercontent.com/vector-im/riot-web/master/electron_app/img/riot.png) |

Description: `A glossy Matrix collaboration client for the web (desktop version).`

Website: `https://riot.im/desktop.html`

**Comment by palob** [comment]
We've already got one, this needs a symlink.
