### ISSUE TITLE
A few of icons on fedora/korora have been set back to default

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#3998]
A few icons on Korora have been set back to default, this happened months ago after a update. The icons of the apps we talk about include DeJa Dup, Login Window, Xfburn, Cura, Compiz Start so far. Those don't have the Numix Circle icon applied to them so i guess the symlinks need to be fixed.

**Comment by bilelmoussaoui** [comment]
Can you please follow the issue template? Otherwise we cant fix this..'

**Comment by ghost** [comment]
will do when i find the time

**Comment by Foggalong** [comment]
Closing this for now, will reopen when the information has been added.
