### ISSUE TITLE
Icon for Sourcetrail

### ISSUE THREAD

**Issue by AlexanderRevo** [numixproject/numix-core#4000]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Sourcetrail`| `/usr/share/icons/sourcetrail.png` | `/usr/share/applications/sourcetrail.desktop` | ![original](https://user-images.githubusercontent.com/11422776/33550359-a8bb1976-d8fe-11e7-96b9-de56bdf9ae3d.png) |

Description: `A cross-platform source explorer for C/C++ and Java.`

Website: `https://www.sourcetrail.com`

**Comment by maxtron95** [comment]
Should we close this since we have a Sourcetrail icon?

**Comment by palob** [comment]
Yes, thanks for noticing.
