### ISSUE TITLE
Icon Request : Icon Requests

### ISSUE THREAD

**Issue by founderio** [numixproject/numix-core#4004]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Icon Requests | `icon-requests` | `icon-requests.desktop` | ![Icon Requests](https://i.imgur.com/AbaWl44.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).
I hope you get the joke ;) https://github.com/bil-elmoussaoui/Icon-Requests/issues/9

**Comment by bilelmoussaoui** [comment]
I'm working on a new version which is a lot faster than the current one (see the beta branch). And it would be really nice to have an icon in the next version so I can push the app to flathub, elementary appstore and snapstore. Especially that i have added hardcode-fixer support :D 
I am going to also provide a deb, rpm package for Debian and Fedora.
