### ISSUE TITLE
Icon Request: Chromebook Recovery Utility

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4024]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Chromebook Recovery Utility | `chrome-jndclpdbaamdhonoechobihbbiimdgai-Default` | `chrome-jndclpdbaamdhonoechobihbbiimdgai-Default.desktop` | ![Chromebook Recovery Utility](https://i.imgur.com/26H5VWL.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).
The app is used to create a bootable recovery for chrome OS (chromebook)

**Comment by palob** [comment]
Does this even work on Linux? My old laptop was a Chromebook with a custom coreboot firmware. When I wanted to restore everything to original prior to selling it it didn't.

**Comment by bilelmoussaoui** [comment]
Oups, it doesn't work at all

**Comment by bilelmoussaoui** [comment]
But as we are going to generate the themes for osx and android too. We can keep this one open

**Comment by Foggalong** [comment]
Yeah but if it's a ChromeOS specific extension then it won't be working on macOS or Android either :P

**Comment by palob** [comment]
It does work on mac and Windows afaik and its used to create a Chrome OS recovery thumbdrive.

**Comment by Foggalong** [comment]
Ooooh, I'd misunderstood what was being said. For now a wontfix then until Linux support has been added or we seriously start work on the macOS theme.
