### ISSUE TITLE
Icon Request: Chromium-dev Web Browser

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4035]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Chromium-dev Web Browser | `chromium-dev` | `chromium-dev.desktop` | ![Chromium-dev Web Browser](https://i.imgur.com/OCSa9ek.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by bilelmoussaoui** [comment]
I think that chromium-dev deserves a different icon than just a link. The same think we did for Chrome/Firefox :+1:

**Comment by palob** [comment]
Lighter and less saturated like this?

![chromium](https://user-images.githubusercontent.com/7050624/34470651-7c3d0b72-ef36-11e7-9572-44b46b9c7688.png)

Original one:
![chromium](https://user-images.githubusercontent.com/7050624/34470661-b0dbf35c-ef36-11e7-907f-9b0d7dfaffde.png)

**Comment by bilelmoussaoui** [comment]
@palob Looks perfect for me!
