### ISSUE TITLE
Icon needed for Plex Media Manager

### ISSUE THREAD

**Issue by derekdickerson** [numixproject/numix-core#404]
Icon=plexmediamanager

![swdksd z copy](https://f.cloud.github.com/assets/2068774/2433305/f089c814-ad89-11e3-8316-e19a682aa29c.png)

**Comment by leoheck** [comment]
This works very well for me:

![plex](https://cloud.githubusercontent.com/assets/1277920/9400042/bc63d8fa-4792-11e5-8356-6bcbb83ec1d2.png)

**Comment by leoheck** [comment]
I don't know if you had updated the icon. Anyone know how long take to the updates reach ubuntu ppas?

**Comment by palob** [comment]
Concerning PPA updates there's the nasty launchpad issue described in #2430.
