### ISSUE TITLE
Netflix Icon Mismatch

### ISSUE THREAD

**Issue by W-Floyd** [numixproject/numix-core#4041]
I don't think they are supposed to be different, it's just that square got forgotten when resolving #1174

![iconified_netflix-desktop](https://user-images.githubusercontent.com/11786132/34290518-91dbab8c-e743-11e7-818e-6d57c33ca86b.png)

I can PR the update of square if that's what should be done.

**Comment by palob** [comment]
That's actually one of the less ugly ones of #3482 

There are other Square icons which are in really bad shape.

**Comment by W-Floyd** [comment]
Yeah, that list still needs to be updated from the square porting I did.

**Comment by bilelmoussaoui** [comment]
@W-Floyd Mind sharing that script you used to create the image? :+1:

**Comment by W-Floyd** [comment]
@bil-elmoussaoui https://github.com/W-Floyd/numix-tools/blob/master/iconify/iconify.sh

**Comment by W-Floyd** [comment]
Out of curiosity, I did some more visual diffing, came out with some interesting results. For correct icons, I get an image like this:

![distributor-logo-solus](https://user-images.githubusercontent.com/11786132/34315554-f66d29e8-e7cc-11e7-9949-3089c5a2eace.png)

For mismatched icons, I get:

![netflix-desktop](https://user-images.githubusercontent.com/11786132/34315560-053e47fe-e7cd-11e7-9856-dbbbb824d057.png)

Should be useful, no?

**Comment by W-Floyd** [comment]
Just passing through once, I see the following as being out of agreement:
* ~amarok~ (full baseplate on circle only, seems okay)
* billard-gl
* brasero
* chrome-dkfhfaphfkopdgpbfkebjfcblcafcmpi-Default
* chrome-gighmmpiobklfepjocnamgkkbiglidom-Default
* DC++
* deepin-software-center
* dia
* distributor-logo-ubuntu
* dragonplayer
* gnome-commander
* gnome-encfs-manager
* gnome-glines
* gnome-software
* gpk-log
* gufw
* gweled
* icedove
* iceweasel
* idea
* jabref
* jdownloader
* k9-copy
* kdenlive
* kicad
* krusader_root
* krusader_user
* liferea
* linuxdcpp
* lubuntu-software-center
* mansa
* marlin
* matlab
* mkvinfo
* mkvmergeGUI
* mongodb
* mupdf
* nemo
* netflix-desktop
* numix
* onboard
* onboard-settings
* palemoon
* panel
* pdfshuffler
* phpstorm
* plexmediamanager
* preferences-system-time
* pycharm
* qjackctl
* QMPlay2
* quiterss
* rubymine
* shares
* software-center
* softwarecenter-debian
* steam_icon_98800
* thunar
* turpial
* web-newsblur
* webstorm

**Comment by palob** [comment]
That visual diffing looks like a rad script but alas there's definitely more mismatches.

**Comment by W-Floyd** [comment]
I don't want to flood the comments here, but the script I used is [here](https://github.com/W-Floyd/numix-tools/blob/master/square-circle/square-circle.sh), and all the resulting images, [here](https://github.com/numixproject/numix-core/files/1584074/transdiff.zip).

**Comment by bilelmoussaoui** [comment]
It's a duplicate of this issue #3482

**Comment by Foggalong** [comment]
Huh, so it is. @W-Floyd could you add your information about the discrepancies between Circle & Square to that issue so we know which icons are the biggest problem and need fixing first.

**Comment by W-Floyd** [comment]
Sure, I'll do that later tonight.
