### ISSUE TITLE
Use docker with travis

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4047]
Currently, with each commit Travis runs the tests and installs all the dependencies all over again. Which takes a lot of time. In order to reduce this, I'm going to create a Docker container based on Ubuntu 14.04  and install all the dependencies on it. 

This way, whenever Travis has to run the tests, it can use the docker container. The time diff will be huge, as only tests will have to be done.  The container will be kept up to date by me. This more to reduce the time of tests and give to the reviewers an easy life before merging an icon, and to the contributors an easy and fast way to verify their PR

I can provide a PR this weekend improve this.

**Comment by Foggalong** [comment]
Made redundant by #5753

**Comment by Foggalong** [comment]
Made redundant by #5753
