### ISSUE TITLE
Icon Request: Date Countdown

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4087]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Date Countdown | `com.github.rickybas.date-countdown` | `com.github.rickybas.date-countdown.desktop` | ![Date Countdown](https://i.imgur.com/WONxybP.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by really-need-an-api-key** [comment]
The icon seems to have changed.
![com github rickybassom date-countdown svg](https://user-images.githubusercontent.com/11636003/112060554-a1573b00-8b5d-11eb-8e33-49003520c9fd.png)

**Comment by really-need-an-api-key** [comment]
Would this be acceptable?
![square](https://user-images.githubusercontent.com/11636003/112064382-2729b500-8b63-11eb-94d5-4f0e01362f78.png)

**Comment by palob** [comment]
The symbol looks too big. The circle this is based on should be 26x26 or 28x28 (instead of 30x30) to account for the dot and the arrow head.

**Comment by really-need-an-api-key** [comment]
I liked how chunky and proportionate it looked, it looks a little bit off to me when shrunk down, either with 2px and 3px circle width.
![square-1](https://user-images.githubusercontent.com/11636003/112509614-ed3df600-8d90-11eb-976d-eb5bc0d8e6c0.png)
![square-3](https://user-images.githubusercontent.com/11636003/112510263-8ec54780-8d91-11eb-9c1f-64925112f4f6.png)

**Comment by palob** [comment]
Could you please check how those 2 look on the Circle plate? That's the more critical one in this case.

**Comment by really-need-an-api-key** [comment]
Like so:
![circle-1](https://user-images.githubusercontent.com/11636003/112763670-b02e6980-9005-11eb-8178-b41293e080ee.png)
![circle-3](https://user-images.githubusercontent.com/11636003/112763676-b3295a00-9005-11eb-9716-6789e177c8b7.png)
I think I like the thicker one more.

**Comment by palob** [comment]
Yeah, the thicker one!
