### ISSUE TITLE
Icon Request: Desktop Folder

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4088]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Desktop Folder | `com.github.spheras.desktopfolder` | `com.github.spheras.desktopfolder.desktop` | ![Desktop Folder](https://i.imgur.com/jvnKzgy.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by GrbavaCigla** [comment]
+1
