### ISSUE TITLE
Icon Request: Exchange

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4090]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Exchange | `com.github.brandonlujan.exchange` | `com.github.brandonlujan.exchange.desktop` | ![Exchange](https://i.imgur.com/nBxHT46.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Fixed in https://github.com/numixproject/numix-core/pull/4114/commits/5d76aa9278c3cee5143c9c9cf3cff59112abf575
