### ISSUE TITLE
Icon Request: Formatter

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4091]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Formatter | `com.github.djaler.formatter` | `com.github.djaler.formatter.desktop` | ![Formatter](https://i.imgur.com/Rp2F6sb.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by bilelmoussaoui** [comment]
https://github.com/numixproject/numix-core/blob/master/icons/circle/48/multibootusb.svg
A variant of this?

**Comment by palob** [comment]
Yeah, maybe a recolour.
