### ISSUE TITLE
Icon Request: Image Burner

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4093]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Image Burner | `com.github.artemanufrij.imageburner` | `com.github.artemanufrij.imageburner.desktop` | ![Image Burner](https://i.imgur.com/EddBmje.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by bilelmoussaoui** [comment]
@palob Should we go with usb-creator with a blue symbol?

**Comment by palob** [comment]
Or just a symlink to ``usb-creator-kde``.
