### ISSUE TITLE
Icon Request: Image Optimizer

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4094]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Image Optimizer | `com.github.gijsgoudzwaard.image-optimizer` | `com.github.gijsgoudzwaard.image-optimizer.desktop` | ![Image Optimizer](https://i.imgur.com/wIVxJvL.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Fixed.
