### ISSUE TITLE
Icon Request: Lottery

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4095]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Lottery | `com.github.bartzaalberg.lottery` | `com.github.bartzaalberg.lottery.desktop` | ![Lottery](https://i.imgur.com/S3XMU47.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Fixed for quite some time.
