### ISSUE TITLE
Icon Request: Palaura

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4099]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Palaura | `com.github.lainsce.palaura` | `com.github.lainsce.palaura.desktop` | ![Palaura](https://i.imgur.com/q0OGYyR.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Fixed for quite some time.
