### ISSUE TITLE
Icon Request: QR Share

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4101]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| QR Share | `com.github.mubitosh.qrshare` | `com.github.mubitosh.qrshare.desktop` | ![QR Share](https://i.imgur.com/cVYyD1G.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by bilelmoussaoui** [comment]
A symlink to this maybe? https://github.com/numixproject/numix-core/blob/master/icons/circle/48/qreator.svg

**Comment by palob** [comment]
Yep, feel free to open another symlinking PR.
