### ISSUE TITLE
Icon Request: Sudoku

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4106]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Sudoku | `com.github.parnold-x.sudoku` | `com.github.parnold-x.sudoku.desktop` | ![Sudoku](https://i.imgur.com/XFfTxpr.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
We've got this as symlink. Do you think this justifies a dedicated icon?

**Comment by bilelmoussaoui** [comment]
Nop, just create a symlink will be more than enough i guess
