### ISSUE TITLE
Icon Request: Tranqil

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4109]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Tranqil | `tranquil` | `com.github.nick92.tranqil.desktop` | ![Tranqil](https://i.imgur.com/gHy2IXf.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
We've already got this. I'll do a prophylactic symlink.

**Comment by bilelmoussaoui** [comment]
The link is missing, before running icon-requests I generated the latest version from git :+1:
