### ISSUE TITLE
Icon Request: URM Simulator

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4111]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| URM Simulator | `com.github.aleksandar-stefanovic.urmsimulator` | `com.github.aleksandar-stefanovic.urmsimulator.desktop` | ![URM Simulator](https://i.imgur.com/zONNcSH.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Closing because upstream repo is gone.
