### ISSUE TITLE
Parental control

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4115]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Parental control`| `preferences-system-parental-controls` | `pantheon-parental-controls-client.desktop` | ![preferences-system-parental-controls](https://user-images.githubusercontent.com/7660997/34418531-e1831674-ebfe-11e7-85f2-09d9ddfa24a3.png)|

Description: `Parental control settings on elementary OS

**Comment by bilelmoussaoui** [comment]
With this one being added (and the recent issues i opened) we can say that we have a pretty good support for elementary OS. Except the huge tray icons :p

**Comment by Foggalong** [comment]
Is that still a thing? A base issue obvs but I thought that had be solved in Freya :(

**Comment by bilelmoussaoui** [comment]
@Foggalong Yeah it's and the solution is here https://github.com/numixproject/numix-icon-theme/issues/1154#issuecomment-341256977

**Comment by Foggalong** [comment]
@bil-elmoussaoui That's not so much a solution as a hacky workaroud. We shouldn't need to provide `*-symbolic` icons in any size except 16px :confused:

**Comment by bilelmoussaoui** [comment]
Yeah currently it's all we have... I might take a look at Wingpanel code after my finals and get the correct way of doing this! We should definitely work on supporting as much widely used distros as possible!
