### ISSUE TITLE
Add a CONTRUBTING.md file

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4132]
"To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, docs, or .github folder. Then, whenever someone opens a pull request or creates an issue, they will see a link to that file."

We should this file, to talk about the important stuff to contributue. Like the data.json file content, the design guidlines, the optimisation options on Inkscape.....

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by mrmeszaros** [comment]
Regarding the discussion on #4079 we need this!

**Comment by mymindstorm** [comment]
See: [wiki/Contributing](https://github.com/numixproject/numix-core/wiki/Contributing), [wiki/Guidelines](https://github.com/numixproject/numix-core/wiki/Guidelines), [wiki/Optimise-Options](https://github.com/numixproject/numix-core/wiki/Optimise-Options), and #2656 for older discussion / documents to use for this. 

On a somewhat related note, the guidelines page is very outdated and should probably have its own issue.
