### ISSUE TITLE
Improve data.json linux entry interaction

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#4151]
Currently we use a list of values in android, but separate a `root` value and `symlinks` for linux:

```json
"some-icon": {
  "android": [
    "entry-1",
    "entry-2"
  ],
  "linux": {
    "root": "some-name",
    "symlinks": [
      "other-name",
      "other-name-2"
    ]
  }
}
```

We should use a single list too for that, to simplify usage.

This would also need an update for the `gen.py` generator script.

**Comment by bilelmoussaoui** [comment]
That could work ;) don't know why we didn't do that this way at the beginning :p

**Comment by Foggalong** [comment]
@bil-elmoussaoui @mrmeszaros There are good reasons that's not the case:
1. If you mean just have all copies of the icon file, then we don't do that to save disk space. There's no point having multiple copies of the same icon in the theme when symlinks are a thing. The only reason we don't do that on Android is that it doesn't support symlinks.
2. If you mean just store Linux icon names in a list and then pick one arbitrarily (probably the top one) to be the root file others link to then there are two options:
    1. If the list is alphabetical, then the top icon name might not be the most logical one for the others to link to. For example, [Onenote](https://github.com/numixproject/numix-core/blob/master/data.json#L10006-L10017) would have the obfuscated Chrome name.
    2. If you mean move the desired root file to the top of the list then it would be crappy from a easy of use POV: the list would be un-alphabetical and there's no obvious label for the root.

So yeah. Unless I've misunderstood what you were referring to?

**Comment by mrmeszaros** [comment]
@Foggalong I was referring to your second point - restructuring only the `data.json` `linux` object to a list.

* I meant making the first (alphabetically) the file, and then linking others to it.
* What is the use-case of somebody creating links manually?
  * Or do we care which is the root in a _group_?
* anyway:
  * all links should be created by the script, shouldn't they?
  * linux systems support chained links
    * max chain depth is 40 (based on [this](https://unix.stackexchange.com/questions/53087/how-do-you-increase-maxsymlinks#53107)) but I doubt that this would be a limit in this use-case

@bil-elmoussaoui What is the **bfb** thing in `gen.py` **line 141**?
I have not found such a part anywhere in `data.json`

**Comment by Foggalong** [comment]
@mrmeszaros Poking around the theme repo itself (rather than any source repo from GitHub) is how most people get involved with contributing. For that reason I'd rather the output remain fairly logical in terms of which is the root and which are symlinks, especially when the overhead is basically zilch.

The bfb is to do with the Unity 7 "start" button; specifically the icon that filled it needed to meet very specific requirements in terms of size and filetype. I'm not sure how you searched for it but there are four entries for it in the file. The version of Unity 7 is supported until 2021 and there's talk of the community picking it up too so it's not going anywhere any time soon.

**Comment by mrmeszaros** [comment]
@Foggalong 
To have a **logical root** icon, we could be using the base name of the icon. This is actually the case with most of the entries, so not many entries would get a new **root**.
Those that would receive one, would be the ones that have a better base name, than the current root:
```json
 // data.json
 "imdb": {
  "android": [
   "com.imdb.mobile"
  ],
  "linux": {
   "root": "chrome-ciioilnaleldclnoaglmkejfikodhdai-Default"
  }
 },
```

Sorry for the **bfb** - of course there are entries - I was sleepy, and did not see them :sleeping:.
But the **bfb** must stay, so the linux format could only be:
```json
 "base-name": {
  "linux": {
   "bfb": "bfb-name",
   "symlinks": []
  }
 }
```

**Comment by Foggalong** [comment]
@mrmeszaros There's also a reason we don't do that; sometimes even the most logical root name is a bit shit and we need at least vaguely recognisable base name for development. At the same time there's no sense in adding a root icon for which no such launcher exists hence the need to differentiate the two.

**Comment by mrmeszaros** [comment]
Thanks for all the explanations @Foggalong!

**Comment by Foggalong** [comment]
No worries! And thanks for bringing this up as a point of discussion; as a result I've noticed an inefficiency and inconsistency with regard to BFB entries so made a fix for that 😄
