### ISSUE TITLE
Icon Request : gmsh

### ISSUE THREAD

**Issue by tkoyama010** [numixproject/numix-core#4156]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `gmsh`| `gmsh_32x32.xpm` | `gmsh.desktop` | ![gmsh_32x32](https://user-images.githubusercontent.com/7513610/34914177-76926fc2-f950-11e7-9d63-4ce0f68c1843.png) |

Description: `3-D finite element mesh generator`

Website: `http://gmsh.info/`

**Comment by palob** [comment]
We've already added this icon but it is hardcoded. You can fix this by using the hardcode fixer script (link in readme) or by copying the respective ``.desktop`` launcher file over to ``$HOME/.local/share/applications`` and editing the icon line inside to ``Icon=gmsh``.

**Comment by tkoyama010** [comment]
Thank you.
