### ISSUE TITLE
Update icons for JetBrains products - Square

### ISSUE THREAD

**Issue by bkanuka** [numixproject/numix-core#4157]
Many icons for jetbrains products have not been updated in Numix square. Issue #2730 is closed but solved the issue for Numix circle only. The following icons need to be updated in Numix square:

- intellij
- pycharm
- phpstorm
- webstorm
- rubymine

**Comment by palob** [comment]
This is part of #3482

**Comment by palob** [comment]
Regarding those icons we've got a pending design decision in #3706.
