### ISSUE TITLE
Spotify icon bug

### ISSUE THREAD

**Issue by lucaspessoapereira** [numixproject/numix-core#4160]
When added to dock favorites, Spotify won't open on its "own" icon, instead it opens a low-res second icon.

![captura de tela de 2018-01-19 09-00-28](https://user-images.githubusercontent.com/24278794/35148039-e7625528-fcf7-11e7-956b-d363d1604191.png)

**Comment by palob** [comment]
That is not our bug but I think there's somebody around who knows to fix it. What's that unthemed icon (2nd from left) in your dock? We could do something about it as well.

**Comment by bilelmoussaoui** [comment]
It's a missing StartupWMClass key in the desktop file. It's used by the desktop to match the running the application with the correct desktop file.

**Comment by lucaspessoapereira** [comment]
@palob thank you, it's the icon of All-In-One Messenger.

@bil-elmoussaoui ok so how can I fix it? thanks!

**Comment by bilelmoussaoui** [comment]
You can use https://github.com/bil-elmoussaoui/StartupWMClassFixer 
I don't think that It's already support Spotify. But everything is explained on the README. If it does work for you, can you please send a PR with the database entry for Spotify

**Comment by palob** [comment]
@lucaspessoapereira Feel free to open a new issue for it so we can do an icon for it.

**Comment by bilelmoussaoui** [comment]
Closing as it's not a Numix issue
