### ISSUE TITLE
Firefox quantumisation

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#4176]
Should we go for it?

Someone wished for it over here https://github.com/numixproject/numix-icon-theme/issues/1277, #4171
reminded me.

**Comment by Foggalong** [comment]
Mozilla have updated the design style of all their browser icons, but the design itself hasn't changed. It's still a fox around the globe like ours, but their globe and fox are just in a new style. Since our globe and fox style didn't match theirs in the first place there's not a reason to update it.

**Comment by mrmeszaros** [comment]
Sorry for the zombification, but I recolored firefox-focus #4171 icon - and it looks pretty decent:
![firefox 384-192-96-48-24](https://user-images.githubusercontent.com/15245298/35740758-2215dc46-0836-11e8-9b0b-6a271c97b505.png)

**Comment by palob** [comment]
If at all think the fox should only have a vertical 10L/48px gradient. And the colours should be less saturated.

**Comment by mrmeszaros** [comment]
I am trying to keep the radial gradient, experimenting a bit:

| A (Previous) | B (Desaturated) | C (Lightened) |
|:--:|:--:|:--:|
|![firefox circle 384 2a](https://user-images.githubusercontent.com/15245298/35771062-05517524-0927-11e8-9770-47c2e5f45661.png)|![firefox circle 384 2c](https://user-images.githubusercontent.com/15245298/35771064-05977cf4-0927-11e8-8408-9c20a017d8b0.png)|![firefox-quantum circle 384](https://user-images.githubusercontent.com/15245298/35777122-b1366bac-09a8-11e8-88d3-a63c5a2b1881.png)|

**Comment by palob** [comment]
Colours are still somewhat garish for Numix. Should be a bit brighter, too.

**Comment by Foggalong** [comment]
@mrmeszaros It makes use of symbol gradients though; symbol colours should be solid.

**Comment by dvorapa** [comment]
> Mozilla have updated the design style of all their browser icons, but the design itself hasn't changed. It's still a fox around the globe like ours, but their globe and fox are just in a new style. Since our globe and fox style didn't match theirs in the first place there's not a reason to update it.

I would say you are not correct as the design changed slightly. Yes, it is still a fox around the globe, but its tail points outwards now. I would leave the icon as is, I personally like the current Numix icon, but the tail end should be changed

**Comment by Foggalong** [comment]
@dvorapa Our icon didn't perfectly match the original logo in the first place though, it was again a distinct design. Possibly something we'll revisit at some point but definitely not a priority

**Comment by dvorapa** [comment]
I see. Btw Numix website looks down (offtopic, but maybe can be fixed even faster than to create a new issue on GitHub)

**Comment by Foggalong** [comment]
@dvorapa [There's a mirror GitHub page here](http://numixproject.github.io/). Working on getting the URL back up atm :)
