### ISSUE TITLE
Icon Request : Mailspring

### ISSUE THREAD

**Issue by l3lackcurtains** [numixproject/numix-core#4203]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Mailspring | `mailspring` | `mailspring.desktop` | ![Mailspring](https://i.imgur.com/YruuLCX.png)| Numix-Circle |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Duplicate of #3946
