### ISSUE TITLE
Tray Icons for KeepassXC

### ISSUE THREAD

**Issue by founderio** [numixproject/numix-core#4206]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `KeepassXC`| `keepassxc` | `keepassxc.desktop` | ![keepassxc](https://user-images.githubusercontent.com/6136865/36124387-1d28e346-1050-11e8-972d-83c012fba0c4.png) |
| `KeepassXC`| `keepassxc-locked` | `keepassxc.desktop` | ![keepassxc-locked](https://user-images.githubusercontent.com/6136865/36124274-bf367dac-104f-11e8-915b-f6a93286246c.png) |
| `KeepassXC`| `keepassxc-unlocked` | `keepassxc.desktop` | ![keepassxc-unlocked](https://user-images.githubusercontent.com/6136865/36124354-03160fba-1050-11e8-824e-390104e5c202.png) |
| `KeepassXC`| `keepassxc-dark` | `keepassxc.desktop` | ![keepassxc-dark](https://user-images.githubusercontent.com/6136865/36124373-1080778a-1050-11e8-9991-9b26f70952af.png) |

I'm not sure if these are hardcoded or use some other special logic.. As soon as I switch to Numix theme, only the application icon is used - not the specific icons.
Hicolor:
![2018-02-12-002-selection](https://user-images.githubusercontent.com/6136865/36124473-732175b0-1050-11e8-8b2f-c393e216683c.png)

Numix Square:
![2018-02-12-001-selection](https://user-images.githubusercontent.com/6136865/36124420-36c4ed90-1050-11e8-9d3f-6ec6847f496f.png)

**Comment by palob** [comment]
Hi, please reopen here numixproject/numix-icon-theme
