### ISSUE TITLE
Tray icon for Shutter broken

### ISSUE THREAD

**Issue by founderio** [numixproject/numix-core#4207]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Shutter`| `shutter-panel` | `shutter.desktop` | ![shutter-panel](https://user-images.githubusercontent.com/6136865/36124849-05c7c0f8-1052-11e8-92d6-55561d79e664.png) |

It seems that shutter-panel.png has been removed from numix some time ago (#1232), keeping only shutter-panel.svg. However, my install seems to prefer loading shutter-panel.png from hicolor instead of Numix' shutter-panel.svg. Hardcoded?
![2018-02-13-005-selection](https://user-images.githubusercontent.com/6136865/36125020-a6b01010-1052-11e8-9fd4-910abcf5a007.png) ![2018-02-12-001-selection](https://user-images.githubusercontent.com/6136865/36124816-d59fd690-1051-11e8-81a2-8bee572ee520.png)

I noticed, however, that shutter-panel.png in hicolor is in /apps, while shutter-panel.svg is in /panel - maybe that is the reason?

The icon for shutter itself works perfectly:
![2018-02-13-001-workspace 1](https://user-images.githubusercontent.com/6136865/36124953-5d3ab6ec-1052-11e8-93c0-26efd40d3f16.png)

**Comment by palob** [comment]
Hi, pleaae reopen here numixproject/numix-icon-theme
