### ISSUE TITLE
Icon Request: Basically every single JetBrains IDE

### ISSUE THREAD

**Issue by ereDaMeme** [numixproject/numix-core#4208]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `APPLICATION NAME`| `ICON NAME` | `DESKTOP FILE NAME` | ![original](https://cloud.githubusercontent.com/assets/5920259/25233502/e8d0afd4-25d6-11e7-9182-b4102e40ae5a.png) |

Description: `Very good progamming tools`

Website: `jetbrains.com`

I know this is not creative but I don't know how to make this like an acutal post so...
Anyway sorry for the lack of detail.
I use windows 10 pro.

**Comment by palob** [comment]
Windows is not amongst our supported platforms. If you are using a Numix theme on Windows this one hs got to be composed ny a 3rd party (which hopefully respects our copyleft licence).
