### ISSUE TITLE
Update to new QGIS icon

### ISSUE THREAD

**Issue by msevilla00** [numixproject/numix-core#4227]
| Aplication name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `QGIS`| `qgis` or `qgis-icon` | `qgis.desktop` | ![original](https://raw.githubusercontent.com/qgis/QGIS/master/images/icons/qgis-icon-60x60.png) |

Description: `A Free and Open Source Geographic Information System`

Website: `https://qgis.org/`

*Proposed idea for new QGIS icon (Numix-square style)*:
![QGIS icon - Numix-square style](https://i.imgur.com/tvikCB5.png)

**Comment by msevilla00** [comment]
Here it is my proposal in SVG format:
[qgis.svg.zip](https://github.com/numixproject/numix-core/files/1754441/qgis.svg.zip)

**Comment by W-Floyd** [comment]
Though an icon already exists, it has gradients where it shouldn't so I'd be inclined to update this.

**Comment by msevilla00** [comment]
Great! But I should maintain the green gradient within the "Q".

**Comment by W-Floyd** [comment]
Ah, I meant the old icon. My PR has no gradient on the symbol, as per Numix guidelines.

**Comment by msevilla00** [comment]
I see, but we could add two or three color steps instead. What do you think?

**Comment by msevilla00** [comment]
What about something like this:

![Imgur](https://i.imgur.com/C8wpkCC.png)

[qgis_no_gradients.svg.zip](https://github.com/numixproject/numix-core/files/1759115/qgis_no_gradients.svg.zip)

**Comment by palob** [comment]
Nah, that's worse than a gradient.

**Comment by msevilla00** [comment]
Then, I would use bottom green (darker one).

Anyway, in the official web page there is some monochrome options to use as logo/icon:

[Visual Style Guide - QGIS web](https://qgis.org/en/site/getinvolved/styleguide.html)

Example: 
![Monochrome QGIS logo](https://qgis.org/en/_downloads/qgis-icon-green128.png)

There they say to use Dark Green (HEX: #589632) color:

![Dark green](https://qgis.org/en/_images/dark_green.png)

**Comment by msevilla00** [comment]
Icon without gradients and "official" dark green as main color of the "Q"

![qgis_no_gradients2 svg](https://user-images.githubusercontent.com/1491985/36722675-742cac0e-1bae-11e8-9e0f-f801a2a0949b.png)

Or better: A "plain" icon (diferent of https://github.com/numixproject/numix-core/pull/4240)

![qgis_no_gradients2 svg](https://user-images.githubusercontent.com/1491985/36722740-aa76cad8-1bae-11e8-99b8-0c8c849e6e95.png)

Here the file:  [qgis_no_gradients2.svg.zip](https://github.com/numixproject/numix-core/files/1762134/qgis_no_gradients2.svg.zip)
