### ISSUE TITLE
Icon Request: Marker

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#4242]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Marker | `com.github.fabiocolacio.marker` | `com.github.fabiocolacio.marker.desktop` | ![Marker](https://i.imgur.com/Xkl7IrO.png)| Numix-Circle |

**Description:** Marker is a markdown editor for linux made with Gtk+-3.0

**Website:**
- https://github.com/fabiocolacio/Marker
- https://fabiocolacio.github.io/Marker

**Comment by palob** [comment]
Done, see #4188.
