### ISSUE TITLE
Icon Request: Fractal

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#4244]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Fractal | `org.gnome.Fractal` | `org.gnome.Fractal.desktop` | ![Fractal](https://i.imgur.com/x5siqLi.png)| Numix-Circle |

**Description:** Fractal is a GTK+ client for Matrix.org — a messaging app

**Website:** https://github.com/danigm/fractal 

---

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
duplicate of #4244
