### ISSUE TITLE
Icon Request: HydraPaper

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-core#4247]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| HydraPaper | `org.gabmus.hydrapaper` | `org.gabmus.hydrapaper.desktop` | ![HydraPaper](https://i.imgur.com/f9fuaKU.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by palob** [comment]
Fixed for quite some time.
