### ISSUE TITLE
Indistinguishable icons between GNOME characters and GNOME Fonts.

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#4296]
**DE:** GNOME 3 (Version 3.22.3)
**Distro:** Debian 9.4
**Icon package:** ![Numix-Icon-Square](https://github.com/numixproject/numix-icon-theme-square)
**Install Location:** ~/.local/share/icons

![Issue](https://user-images.githubusercontent.com/23306695/37462515-3d257606-2878-11e8-9ed2-754a65dc55ff.png)

Maintainer,
In GNOME shell 3.22, two app icons for "Font Viewer" and "Characters" respectively, look very similar, which can make recognizing correct application a bit harder. I hope you will take a look at this issue.

Thanks you for maintaining this project.

**Comment by palob** [comment]
Found some old drafts on my drive.
![characters-1](https://user-images.githubusercontent.com/7050624/37494715-6594d320-28aa-11e8-949e-baf6829e637b.png)
![characters-2](https://user-images.githubusercontent.com/7050624/37494716-65b8145c-28aa-11e8-8ec8-790e7e95ac2e.png)

**Comment by ghost** [comment]
@palob  Looks good, but they are circular :\

**Comment by Foggalong** [comment]
@fr0xk That doesn't matter, we make Circle & Square versions of every icon.
@palob That second one looks grand if you want to run with it :)
