### ISSUE TITLE
Gnome-Tweak-Tool was renamed to Gnome-Tweaks

### ISSUE THREAD

**Issue by colemickens** [numixproject/numix-core#4299]
In Gnome 3.28, `gnome-tweak-tool` was renamed to `gnome-tweaks`.

As a result, the nice Numix icon is no longer working.

**Comment by palob** [comment]
We should have the correct icon name in our latest release. How did you install the theme?

To be sure please add the icon name from the respective ``.desktop`` launcher file.

**Comment by colemickens** [comment]
Yeah, that's embarassing. I forgot I was on a `-git` AUR package and needed to update manually.

You're right, everything looks fine. Sorry for the noise.
