### ISSUE TITLE
Icon Request : Hiri

### ISSUE THREAD

**Issue by Chinney** [numixproject/numix-core#4300]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Hiri`| `hiri` | `hiri.desktop` | ![icon](https://user-images.githubusercontent.com/5702231/37763117-7c0d1694-2dbe-11e8-902c-b12c67fc2143.png) |

Description: Local mail client for Office 365 accounts 

Website: https://www.hiri.com/
 
If possible also add a panel/tray/indicator icon

**Comment by palob** [comment]
For tray icons please open an issue here https://github.com/numixproject/numix-icon-theme.

We need to know the icon names and a screenshot of the original iconsin order to fix it.

**Comment by palob** [comment]
upstream defunct.
