### ISSUE TITLE
Some icon's edge shows the inferior layer color instead of superior one

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#4306]
[This issue from December 2016](https://github.com/numixproject/numix-icon-theme-square/issues/7) was closed because it was submitted to the wrong issue tracker, but it doesn't seem to have been solved or reopened.

My LibreOffice icon still looks as per hlechner's screenshot (see top right corner):

![](https://cloud.githubusercontent.com/assets/11244067/21546282/f7989a46-cdc4-11e6-96da-b068aee10c59.png)

I observed the same problem with other icons, like firefox (bottom corners) and nvidia.

**Comment by palob** [comment]
This should be fixed. Please check if your installation is up to date.

**Comment by palob** [comment]
This is part of #3482.

**Comment by ghost** [comment]
I downloaded release 18-02-16, which I believe is the most recent version.

Had the same issue both with installating via pacman and manually downloading the recent release into ~/.local/share/icons

**Comment by palob** [comment]
Oh, that's over a year old...

**Comment by palob** [comment]
Worked on this here https://github.com/numixproject/numix-core/pull/4233, hasn't been released yet.

**Comment by ghost** [comment]
Additional info, just in case: I'm on Antergos with GNOME, Res: 1920x1080, GPU: Nvidia GTX 580

Image examples (`firefox`; `libreoffice-main`; `nvidia`), opened in EoG at 100% zoom:
![](https://i.imgur.com/qBMJkJB.png) ![](https://i.imgur.com/3ggac79.png) ![](https://i.imgur.com/CfXVcyY.png)

At 500% zoom:
https://i.imgur.com/VYlSEPB.png
https://i.imgur.com/Cqf7IK0.png
https://i.imgur.com/dKuFKux.png

**Comment by palob** [comment]
I know what causes tjis, lo and nvidia are fixed in master. Work on #3482 is ongoing.

**Comment by Foggalong** [comment]
Closing this as a subsidiary of #3482
