### ISSUE TITLE
 Minetest icon is unrecognisable and wrong 

### ISSUE THREAD

**Issue by rubenwardy** [numixproject/numix-core#4314]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `minetest`| `minetest.svg` | `minetest` | ![original](https://raw.githubusercontent.com/minetest/minetest/master/misc/minetest-xorg-icon-128.png) |

Description: Open source voxel game engine
Website: <minetest.net>

Hi, I'm a Minetest core developer. The Minetest icon is unrecognisable. It's fair enough to make a flat version, but it's completely unrecognisable as Minetest.

[Icon in numix](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/minetest.svg)
[Official Minetest Logo](https://github.com/minetest/minetest/blob/master/misc/minetest.svg)

Here's an example of a different Minetest icon that is a bit better, from papirus: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/minetest.svg
The ground cube is more important than the tree

**Comment by palob** [comment]
I'll leave this open as enhancement request as the icon could be a bit more spectacular indeed (looking at the white background for instance).
That said I don't think it is unrecognisable. We replicate the voxel tree 1:1.
Please keep in mind that the more details we add the less distinguishable the icon gets at smaller sizes.

As opposed to Papirus we need to account for the space taken up by our Circle/Square baseplates.

**Comment by maxtron95** [comment]
@palob I was creating a custom Minetest icon and I figured the symbol could be useful for the issue.

![minetest-144](https://user-images.githubusercontent.com/53346722/113735296-bbe2f580-96c1-11eb-8395-788a8f5f2f81.png)

The symbol looks like it is still recognizable at 16x16.

[minetest.zip](https://github.com/numixproject/numix-core/files/6265725/minetest.zip)

**Comment by palob** [comment]
Yeah, it's better because it doesn't use strokes. Centring the tree might help cranking up the size on a Numix baseplate.

**Comment by palob** [comment]
@rubenwardy Why did you close this? Is the proposed icon not to your liking?

**Comment by rubenwardy** [comment]
I no longer use this icon set, so I'm not invested in its outcome

That logo does look better though, to me

Edit: I suppose you can do what you want with this issue

**Comment by palob** [comment]
@creepertron95 Are you interested in implementing this? Otherwise I can give it a shot.

**Comment by maxtron95** [comment]
@palob Perhaps you can try to give this one a shot. I'm planning to clear out my backlog of PRs later today before I start adding new ones.

**Comment by palob** [comment]
This is my draft, too busy, too 3Dish?

![minetest-ci](https://user-images.githubusercontent.com/7050624/115265044-23c02400-a137-11eb-9f37-9060746fada2.png)

**Comment by Foggalong** [comment]
@palob Yeah something about it looks off. Think it might be that the design has a lot of implicit shadows through colouring? This is a bit of a wild card, but how does it look from a side on perspective?

**Comment by palob** [comment]
I was thinking about a simplified one with just tree+grass+soil but a 2D variant probably just makes more sense for Numix. The 3D one looks odd without the tree casting a shadow.

**Comment by palob** [comment]
Is something like this recognisable?

![minetest2](https://user-images.githubusercontent.com/7050624/117494551-c3bde000-af74-11eb-87fc-4c75e87a1eb8.png)

**Comment by Foggalong** [comment]
In my opinion yes!
