### ISSUE TITLE
Icon Request : MultiMC

### ISSUE THREAD

**Issue by founderio** [numixproject/numix-core#4323]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| MultiMC | `multimc` | `multimc.desktop` | ![MultiMC](https://i.imgur.com/Rha4tMK.png)| Numix-Square |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by maxtron95** [comment]
@palob Should this issue be closed?

**Comment by founderio** [comment]
I've updated and the icon is there now, so I'd say yes :)
