### ISSUE TITLE
Renamed icons in Ubuntu 18.04

### ISSUE THREAD

**Issue by ddnexus** [numixproject/numix-core#4330]
| Application name |
| --- | 
| `gnome-tweaks`|
| `dconf-editor`| 

These apps have been renamed and the icons are not found. The renaming should be reflected in the theme.

**Comment by mrmeszaros** [comment]
@ddnexus Are these the new icon names?

* `dconf-editor` is the current icon name - did it change?
* `gnome-tweak` is for [Tweaks (previously Gnome Tweak Tool)](https://wiki.gnome.org/action/show/Apps/Tweaks), right?

**Comment by ddnexus** [comment]
I don't know the right names (old and new). I just noticed that they are not found, while before 18.04 they were OK. I tried to report it [here](https://github.com/numixproject/numix-icon-theme-circle/issues/88#issuecomment-380896620), and @palob confirmed that is a renaming issue, and suggested to report it here.

**Comment by ddnexus** [comment]
Just found that the icon name in the desktop file of `dconf-editor` is `ca.desrt.dconf-editor`. WTF!? :)
And the one for `gnome-tweaks` is `org.gnome.tweaks`.
HTH

**Comment by mrmeszaros** [comment]
@ddnexus I checked out the master branch, and it seems to me, that the necessary changes have been implemented (around February).

Could You check if You have the latest release of the theme?

**Comment by bilelmoussaoui** [comment]
Those changes are already on master. It seems that somehow the packaging is outdated on the Ubuntu repositories. We have released at least one release since the modifications on this repository. How did you install the theme?

**Comment by ddnexus** [comment]
I am confused. I used the ppa:numix/ppa.
numix-icon-theme is already the newest version (0.3+931~201804050035~ubuntu18.04.1).
numix-icon-theme-circle is already the newest version (2.0.3+17~201803212054~ubuntu18.04.1).
Is it outdated?
What is the _right_  method to install and keep it updated?

**Comment by Foggalong** [comment]
@ddnexus If you want the most up to date version you have to clone this repo and build it using the script. If you want the latest packaged release see the themes [packaging repo](https://github.com/numixproject/numix-icon-theme-circle). The PPA should in theory build from the latest tagged version there but we're currently having issues with it.

@khurshid-alam Is currently switching the PPA from bzr to git which will hopefully fix the problem :)
