### ISSUE TITLE
Icon request - Update Wolfram Mathematica .wl mimetype 

### ISSUE THREAD

**Issue by jose-a-sa** [numixproject/numix-core#4331]
Build on the Numix .nb mimetype. 

| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `.wl mimetype`| `application-vnd.wolfram.wl.svg` | `n/a` | ![vnd wolfram wl-64](https://user-images.githubusercontent.com/13206784/39371308-3c5e16f0-4a39-11e8-9102-e5eb78321791.png) |
| `.cdf mimetype`| `application-vnd.wolfram.cdf.svg` | `n/a` | ![vnd wolfram cdf-64](https://user-images.githubusercontent.com/13206784/39371453-a82c6864-4a39-11e8-91ca-14b51bc7a072.png) |

Description: `Wolfram Mathematica`

Website: `https://www.wolfram.com/language/`

**Comment by bilelmoussaoui** [comment]
This should be reported here instead https://github.com/numixproject/numix-icon-theme
