### ISSUE TITLE
Gajim icon missing

### ISSUE THREAD

**Issue by manuel-uberti** [numixproject/numix-core#4354]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Gajim`| `gajim.svg` | `gajim.desktop` | ![original](https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Gajim.svg/120px-Gajim.svg.png) |

As requested [here](https://github.com/numixproject/numix-icon-theme-circle/issues/92#issuecomment-393265676), I am reporting the `Icon` line from my `/usr/share/applications/org.gajim.Gajim.desktop` file:
```
Icon=org.gajim.Gajim
```

**Comment by palob** [comment]
Actually our latest release includes a symlink for this. Looks like we've got a PPA problem again as indicated in https://github.com/numixproject/numix-icon-theme-circle/issues/84.

**Comment by manuel-uberti** [comment]
I see thanks, I guess we can close this one then.

**Comment by palob** [comment]
Until the PPA gets fixed you can copy the launcher file to ``~/.local/share/applications/`` and edit the icon line to ``Icon=gajim``.

**Comment by manuel-uberti** [comment]
Thanks, it worked.
