### ISSUE TITLE
Symlink-request: quodlibet to io.github.quodlibet.QuodLibet

### ISSUE THREAD

**Issue by jgandert** [numixproject/numix-core#4363]
[quodlibet](github.com/quodlibet/quodlibet) is working on flatpak support and as a result the icon [was renamed](https://github.com/quodlibet/quodlibet/pull/2842) to "io.github.quodlibet.QuodLibet". (to support older versions "quodlibet" as a name for the icon should stay)

**Comment by palob** [comment]
Thanks for reporting, it's included in #4345

**Comment by jgandert** [comment]
@palob Thanks!
