### ISSUE TITLE
Added 'online account' icon in Cinnamon settings.

### ISSUE THREAD

**Issue by Bundy01** [numixproject/numix-core#4375]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `numix-circle`| `cs-online-accounts.svg` | `Cinnamon` | `preferences-desktop-online-accounts.svg`

Description: `The " online account" icon in the Cinnamon settings.`

Website: `LINK TO THE APP`

Hi,
I tried to do a pull-request but couldn't: /
Simply add a 'preferences-desktop-online-accounts.svg' icon and rename it to 'cs-online-accounts.svg' to get the right icon in Cinnamon's system settings.

**Comment by palob** [comment]
Alright, I've submitted a fix and closed #4374.
