### ISSUE TITLE
Not related to this repository, but I would like tot alk with you.

### ISSUE THREAD

**Issue by gusbemacbe** [numixproject/numix-core#4423]
Hello developers, deisgners and @palob !

Would you like to take my repositories Suru++ Arrogin, Suru++ Dark and Suru++ Telinkrin?

I would maintain them, but the Germans Linux users and the Linux users do not accept I maintain these repositories and they want they be retorned to the original author (Paul) or to author of Suru++, but they refused to take ownership of these repositories. 

If you refuse, it is OK!

**Comment by palob** [comment]
Is it this https://github.com/Magog64/SURU-PLUS?

I don't think I understand what's the matter. Who doesn't accept which practice?
It's all freely licensed, right?

Anyway, personally I'm in favour of contributing upstream instead of forking if possible if that's the bone of contention.

**Comment by gusbemacbe** [comment]
Yes, he is already the new owner of Suru++, but I am owner of all other projects as Suru++ Arrogin, Suru++ Dark and Suru++Telinkrin.

The problem is that, the polls result show that Linux users do not accept I own these repositories and want they be returned to Magog64 or Paul, but they do not want to maintain these repositories. I am looking for someone to take ownership of my repositories. I indicate you and the Numix team becaue the Linux community supports fully you. 

> It's all freely licensed, right?

Yes, all my repositories are under GPL3.

> Anyway, personally I'm in favour of contributing upstream instead of forking if possible if that's the bone of contention.

In the polls, they do not accept I be a contributor or a collaborator. Better transferring the ownership of these repositories to you instead of forking. 

If you refuse, no problems.

**Comment by palob** [comment]
Why do people take issue with you?

**Comment by gusbemacbe** [comment]
The history is long. Only two of all the reasons: because I am not the original author of these repositories and ones of stargazers do not like me, boycott me and downvote my comments. When the original author no longer wants to maintain the projects, he transfers the ownership to me, but the Linux users see, unstar and flee to other unofficial and testing repositories of the same original author

**Comment by Foggalong** [comment]
@gusbemacbe Numix doesn't really have the resources right now to maintain an extra set of themes. Looking through a few of the issues I'd advise you sort out the disagreements between yourselves because it doesn't look like there's many, if any, people actually objecting.
