### ISSUE TITLE
Icon Request: Crow Translate

### ISSUE THREAD

**Issue by Shatur** [numixproject/numix-core#4439]
| Application name | Icon name | Desktop file name | Original icons |
| --- | :-- | :-- | :-- |
| `Crow Translate`| ` crow-translate` | `crow-translate.desktop` | ![crow-translate](https://raw.githubusercontent.com/Shatur95/crow-translate/master/dist/unix/generic/hicolor/72x72/apps/crow-translate.png) |

**Description:** A simple and lightweight translator that allows to translate and say selected text using the Google Translate API and much more.

**Links**: [Link](https://github.com/Shatur95/crow-translate) to the program GitHub repository. [Link](https://github.com/Shatur95/crow-translate/tree/master/dist/unix/generic/hicolor) to the icons that are copied to the hicolor folder during package installation.

I also [submitted](https://github.com/numixproject/numix-core/issues/4439) a request for the application tray icon

**Comment by palob** [comment]
Hi, the tray icons won't be covered here. Can you please report those here https://github.com/numixproject/numix-icon-theme so nothing goes by the board?

**Comment by Shatur** [comment]
@palob Oh, sorry, of course!
