### ISSUE TITLE
Shaky Wesnoth icons

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#4458]
Currently looking like this:

Main icon
![before1](https://user-images.githubusercontent.com/7050624/42543107-9fb67f70-84aa-11e8-87db-457d44ef5d74.png)

Editor icon (which is only there for legacy distros since the latest release has got it integrated in them main app)
![before2](https://user-images.githubusercontent.com/7050624/42543184-f1163554-84aa-11e8-9eea-440a06bb2bc1.png)

This is what a slight reproportioning looks like for both
![after1](https://user-images.githubusercontent.com/7050624/42543177-ec59c4b8-84aa-11e8-91f2-b5dcfe46b5fb.png)
![after2](https://user-images.githubusercontent.com/7050624/42543178-ec792484-84aa-11e8-8c5c-795033d97dd6.png)

Based on the original icon 
![wesnoth-icon](https://user-images.githubusercontent.com/7050624/42543343-c1364c88-84ab-11e8-9fd1-a4f78b8b2217.png)

I've come up with this draft (colours/contrast to be tweaked)
![wesnoth-new](https://user-images.githubusercontent.com/7050624/42543242-21787482-84ab-11e8-942c-8b4e815c87fd.png)

So far however no better idea than this for a matching editor icon has occured to me:
![wesnoth-editor-new](https://user-images.githubusercontent.com/7050624/42543277-5b21096a-84ab-11e8-9d9c-65f55fd00dac.png)

Maybe something like ``solarus-quest-editor`` rearranged/recoloured would be close enough?

**Comment by Foggalong** [comment]
That flaw is a left over from what is now called Numix Shine, the first ever app theme that Numix did. We had a whole series of icons which used that sword symbol and all were misaligned. I *think* this is now the last one left in Circle & Square.

I strongly approve of your new designs. For the second one maybe the shields but yeah with an extra symbol on the shield or something instead of swords? Anything would be an improvement tbh though

**Comment by palob** [comment]
Got this for the editor, maybe a bit busy.

![wesnoth-editor-new](https://user-images.githubusercontent.com/7050624/42605224-14b0e85c-8577-11e8-897e-0adc96cd6d4c.png)

**Comment by Foggalong** [comment]
Is there a reason for using tools both on the shield and the background, rather than just one or the other? Might look less busy and more consistent with just one of the two

**Comment by palob** [comment]
Yeah, could use just the standard shield here as well.

**Comment by palob** [comment]
![wesnoth-new](https://user-images.githubusercontent.com/7050624/42778865-cb938f50-893e-11e8-9756-059e483212ef.png)
![wesnoth-editor-new](https://user-images.githubusercontent.com/7050624/42778868-cf13a296-893e-11e8-8ece-7dd038c152c1.png)

**Comment by Foggalong** [comment]
Those look good to me, great job :+1:
