### ISSUE TITLE
Icon Request: Hyper

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#4462]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Hyper`| `hyper` | `Hyper.desktop` | ![original](https://user-images.githubusercontent.com/37634063/42580670-0651560e-8566-11e8-9d51-c69eacab3c22.png) |

Description: `JS/HTML/CSS Terminal`

Website: https://hyper.is

**Comment by palob** [comment]
We've got this for a long time. Your installation must be quite outdated. How did you get the theme?

**Comment by ghost** [comment]
I got the theme from here.
https://aur.archlinux.org/packages/numix-circle-icon-theme-git

**Comment by palob** [comment]
Alas, the AUR package is seriously outdated https://github.com/numixproject/numix-icon-theme-circle/issues/97

**Comment by ghost** [comment]
Ah... I know how old it is.
Does the latest version include the Jetbrains IDE icon?

**Comment by palob** [comment]
Depends on what the icon name it. Can you look for it?

**Comment by ghost** [comment]
This's Desktop Entry file
![image](https://user-images.githubusercontent.com/37634063/42608540-1ebb9a4e-85c3-11e8-9b4b-fadd7a3c4b01.png)
I think its name is Jetbrains-toolbox.

**Comment by palob** [comment]
Thanks. If there's a path after the ``Icon=`` this means the icon is hardcoded and a themed icon won't be picked automatically without editing the file.

This icon isn't done yet, see #3468

**Comment by ghost** [comment]
Thank you for your kind answers!

**Comment by scratchyone** [comment]
I just updated using the official repo, but I still don't have a hyper icon. Am I missing something?

**Comment by palob** [comment]
Please report the icon line from inside the respective .desktop launcher file. Maybe the icon is hardcoded or needs a symlink.

**Comment by scratchyone** [comment]
The icon is called "hyper".

**Comment by palob** [comment]
If ``sudo gtk-update-icon-cache /usr/share/icons/*`` or ``sudo update-icon-caches /usr/share/icons/*`` is of no avail you probably haven't got the latest release. How exactly did you install?

**Comment by scratchyone** [comment]
I'm not able to try those commands yet, but I just completely removed and
installed again with the official ppa

**Comment by scratchyone** [comment]
Those commands didn't help either

**Comment by palob** [comment]
It looks like Numix circle only got updated for 18.10 in the PPA. https://launchpad.net/~numix/+archive/ubuntu/ppa

We will investigate.

Can you however search for ``hyper`` in ``/usr/share/icons/Numix-Circle``?

**Comment by scratchyone** [comment]
Hyper.svg exists, and I also did a reboot.

**Comment by palob** [comment]
Only ``Hyper`` or ``hyper`` as well?

Maybe it's a case where this needs to be applied. https://github.com/bilelmoussaoui/StartupWMClassFixer

**Comment by scratchyone** [comment]
Oops, it's "hyper.svg" and "hyperterm.svg". I'll run that script and see if
that fixes it

**Comment by scratchyone** [comment]
Script didn't do anything

**Comment by palob** [comment]
Well, then I don't see any reason why the icon wouldn't show up. Weird.

**Comment by palob** [comment]
I've found a package where the icon line reads ``Icon=/usr/share/pixmaps/hyper.png`` which means that the icon path is hardcoded. Are you sure your line reads ``Icon=hyper`` or is it ``Icon=Hyper``?

**Comment by scratchyone** [comment]
It says `Icon=hyper`. Maybe there's another desktop file? I also moved it to my local .desktop location and that didn't help

**Comment by palob** [comment]
Are you sure there is no old Numix installation lingering somewhere in your home folder?

**Comment by scratchyone** [comment]
There could be. How would I remove it?

**Comment by scratchyone** [comment]
I removed numix with apt get, did a search for it and deleted every folder
that had numix in the name. I'm going to try to install from github

**Comment by scratchyone** [comment]
That didn't fix it...

**Comment by scratchyone** [comment]
Wait, hyper is installed with AppImage... Could that be it?

**Comment by scratchyone** [comment]
I got it! Apparently appimage creates a hardcoded icon inside the appimage
file, and the desktop file I found wasn't the real one. It creates a
different desktop file. I deleted it, and made my own that specified the
numix icon path

**Comment by scratchyone** [comment]
Nvm, it's not hardcoded. Just make a symlink for "appimagekit-hyper" and
it'll work fine.

**Comment by scratchyone** [comment]
Wait, that changes the launcher I on but not the icon that shows up when
you actually open it

**Comment by scratchyone** [comment]
STEPS TO FIX: Don't install the appimage.
Make your own desktop file
EDIT: nope, once you launch it, it still has the old icon

**Comment by scratchyone** [comment]
You can also install it and find the desktop file and change the icon name
and remove the %U from Exec and it'll work as well.

**Comment by palob** [comment]
Yep, all Snap icons are hardcoded.
The unthemed icon for the running might be fixeable with the explanation here: https://github.com/bilelmoussaoui/StartupWMClassFixer#how-to-contribute

**Comment by scratchyone** [comment]
It works!!! Thanks
