### ISSUE TITLE
Icon Request: BOOLR

### ISSUE THREAD

**Issue by TalviT** [numixproject/numix-core#4484]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `BOOLR`| `/opt/boolr/resources/app/build/icon.png` | `/opt/boolr/boolr.desktop` | ![icon](https://user-images.githubusercontent.com/18188251/43023323-ba7d13ba-8c6a-11e8-9e44-d5d796e0ca93.png) |

Description: `BOOLR is a digital logic simulator`

Website: `http://boolr.me/`

**Comment by really-need-an-api-key** [comment]
Is the symbol size acceptable, or does it look to big?

| | |
| :-- | :-- |
| ![circle](https://user-images.githubusercontent.com/11636003/51867970-1eefd980-234d-11e9-8dd1-92390a587509.png) | ![square](https://user-images.githubusercontent.com/11636003/51867963-1ac3bc00-234d-11e9-8b66-4136122510a6.png) |

**Comment by palob** [comment]
Looks a tad big from distance.

**Comment by really-need-an-api-key** [comment]
Shrunk it up a bit.

| | |
| :-- | :-- |
| ![circle](https://user-images.githubusercontent.com/11636003/51938408-4b6b2a80-240d-11e9-87a6-d97a4b6cefea.png) | ![square](https://user-images.githubusercontent.com/11636003/51938421-4f974800-240d-11e9-8bae-cfc3987e5df7.png) |

Fits just so in the template:

![circle_guides](https://user-images.githubusercontent.com/11636003/51938459-7190ca80-240d-11e9-8ef0-4987c998e4d5.png)
