### ISSUE TITLE
Icon Request: Pritunl Client

### ISSUE THREAD

**Issue by lllmio** [numixproject/numix-core#4553]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Pritunl Client`| `pritunl_client_electron` | `pritunl-client-electron.desktop` | ![original](https://user-images.githubusercontent.com/1689966/44103206-43aa0728-9ff4-11e8-90ab-d9669c7d7d6f.png) |

Description: `Free and open source cross platform OpenVPN client`

Website: `https://client.pritunl.com/`

**Comment by palob** [comment]
Fixed for quite some time.
