### ISSUE TITLE
Icon Request: FreeCAD

### ISSUE THREAD

**Issue by kAoi97** [numixproject/numix-core#4565]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `FreeCAD`| `freecad` | `freecad.xpm` | ![original](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/FreeCAD-logo.svg/64px-FreeCAD-logo.svg.png) |

Description: `FreeCAD is an open-source parametric 3D modeler made primarily to design`

Website: `https://www.freecadweb.org/`

**Comment by palob** [comment]
Are you sure on the icon name? We've got this for years.

**Comment by palob** [comment]
Ah OK, ``freecad.xpm`` is the icon name. You need to copy the launcher to ``~/.local/share/applications/`` and edit the icon line to simply ``Icon=freecad`` in order to fix it.
