### ISSUE TITLE
Icon Request: MinerGate

### ISSUE THREAD

**Issue by kAoi97** [numixproject/numix-core#4566]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `MinerGate`| `minergate` | `minergate` | ![original](https://www.ebavs.net/wp-content/uploads/2017/10/minergate_logo_5-818x423.png) |

Description: `Cryptocurrency GUI miner 8.3 & Mining Pool`

Website: `https://minergate.com/`

**Comment by palob** [comment]
upstream defunct.
