### ISSUE TITLE
Update Godot Engine icon

### ISSUE THREAD

**Issue by YeldhamDev** [numixproject/numix-core#4584]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Godot Engine`| `godot` | `godot` | ![original](https://www.3dminfographie.com/images/logos/logiciels/godot.png) |

Description: `Multi-platform 2D and 3D game engine.`

Website: `https://godotengine.org`

The current icon is outdated, using the old Godot Engine logo.

**Comment by palob** [comment]
Is it just the smaller jaw?

**Comment by YeldhamDev** [comment]
@palob Pretty much.
