### ISSUE TITLE
Huge icon for menu in Terminal 

### ISSUE THREAD

**Issue by GreatNewHope** [numixproject/numix-core#4611]
Hi there. Probably this bug has already been reported.

I'm using Ubuntu 18.04 and numix-circle.

![imagen](https://user-images.githubusercontent.com/23639693/46956364-7071a280-d095-11e8-8417-593199149525.png)

Probably this link is of use: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/453

**Comment by bilelmoussaoui** [comment]
It's an upstream issue.

**Comment by GreatNewHope** [comment]
@bilelmoussaoui Could you reference where the issue is located? Or at least some more info on the issue.
Thank you very much
