### ISSUE TITLE
Icon Request: Spectral

### ISSUE THREAD

**Issue by PureTryOut** [numixproject/numix-core#4616]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Spectral`| `org.eu.encom.spectral.png` | `org.eu.encom.spectral.desktop` | ![original](https://gitlab.com/b0/spectral/raw/master/assets/img/icon.png) |

Description: `A glossy client for Matrix, written in QtQuick Controls 2 and C++`

Website: [`https://gitlab.com/b0/spectral`](https://gitlab.com/b0/spectral)

**Comment by palob** [comment]
Isn't that the simplenote logo recoloured?

**Comment by PureTryOut** [comment]
I don't know that app, but after searching it: yes it does. Interesting, I'll ask about this upstream.

**Comment by PureTryOut** [comment]
I asked about it, it's a coincidence. If you inspect both the logos closely, you'll see they're not curved the same so it's not literally a copy. I guess it does make making a Numix icon easier though, just take the same approach as was doen with the SimpleNote one.
