### ISSUE TITLE
Icon Request: IRCCloud

### ISSUE THREAD

**Issue by lutzke** [numixproject/numix-core#4634]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| IRCCloud| irccloud | irccloud.desktop | ![original](https://user-images.githubusercontent.com/20097150/48136293-89b4db80-e25c-11e8-9dd5-daf574fee21d.png) |

Description: "Chat on IRC from anywhere, and never miss a message." Seamlessly cross-platform IRC client (desktop, mobile, web) featuring a built-in bouncer service.

Website: https://www.irccloud.com/

**Comment by really-need-an-api-key** [comment]
Not sure if symbol position isn't a tad high but when I move it down a pixel it starts to get blurry at lower resolutions:
![square](https://user-images.githubusercontent.com/11636003/52066887-afaafd00-2579-11e9-9be3-866c8a47f371.png)

**Comment by Foggalong** [comment]
@really-need-an-api-key Like the design and positioning looks okay, but the colours chosen are bit gloomy. Try more vibrant shades of blue for the baseplate and a slightly whiter colour for the cloud

**Comment by really-need-an-api-key** [comment]
![square2](https://user-images.githubusercontent.com/11636003/52087487-e3058000-25a9-11e9-9d3a-119ebfadeb17.png)
