### ISSUE TITLE
Change this icon (I can't find the name)

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#4637]
This picture is a screenshot of pamac 7.x in Numix Circle icon theme

![pamac in numix circle](https://user-images.githubusercontent.com/11488886/49055086-eaff1780-f228-11e8-9f05-bb62a8bd7dba.png)

This picure is screenshot of the same app in Adwaita icon theme

![pamac in adwaita](https://user-images.githubusercontent.com/11488886/49055113-05d18c00-f229-11e8-874c-1156a3e45f12.png)

The Adwaita version has the icons (checkboxes) distinguishable whilst the Numix version has not.

**Comment by palob** [comment]
Why are there still Numix icons on the right side with Adwaite?

**Comment by palob** [comment]
Cn you please file the issue here? https://github.com/numixproject/numix-icon-theme

**Comment by palob** [comment]
By the way, I use pamac 6.4 on Arch and I don't see this issue.
Are you running Manjaro? If so, do you use Numix or do you use their own hacked Numix theme?

**Comment by KSXGitHub** [comment]
> Why are there still Numix icons on the right side with Adwaite?

Application's error? I don't know! But this is after I restart pamac:

![image](https://user-images.githubusercontent.com/11488886/49082381-3393f080-f27c-11e8-9c0c-e5a595c52179.png)

> By the way, I use pamac 6.4 on Arch and I don't see this issue.
> Are you running Manjaro? If so, do you use Numix or do you use their own hacked Numix theme?

I use Antergos, but I install pamac from AUR/pamac-aur (7.3.1-1).
Regarding numix, I use Numix-Circle AUR/numix-icon-theme-pack-git

**Comment by KSXGitHub** [comment]
> Cn you please file the issue here? https://github.com/numixproject/numix-icon-theme

https://github.com/numixproject/numix-icon-theme/issues/1319

**Comment by palob** [comment]
Thank you.
