### ISSUE TITLE
Duplicate Icons

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#4654]
cs-user should be a symlink of mugshot, duplicative design

**Comment by palob** [comment]
Or even better both should be a symlink of ``preferences-desktop-user``.

**Comment by palob** [comment]
Another pair of identical designs: ``pyrenamer`` and ``rename``

**Comment by palob** [comment]
Should we even keep ``rename``? Sounds much like an action.

**Comment by bilelmoussaoui** [comment]
I think it's okay to remove `rename`. We should avoid those kinds of icons.  If someone reports an issue about it, we should ask them to report that upstream so they can RDNN their icon name :+1:

**Comment by Foggalong** [comment]
Rename isn't actually an action icon; the related action seems to be exclusively [edit-rename](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/48/actions/edit-rename.svg). However `rename.svg` was added as part of one of the commits to bring it on par with another icon theme¹, so I don't know which application will actually be using it.

¹ - that series of commits was made just under 5 years ago now which has made me realise just how long I've been doing this.

**Comment by palob** [comment]
So let's go forward and do away with it?

**Comment by Foggalong** [comment]
That's good with me :)
