### ISSUE TITLE
System monitor icon theme in Ubuntu 18.04

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [numixproject/numix-core#4669]
| System Monitor in Ubuntu 18.04 |

![screenshot from 2018-12-29 08-15-13](https://user-images.githubusercontent.com/16388948/50532618-ec7e7100-0b41-11e9-860d-2bf0c3966620.png)

Description: Used for System Monitoring in Ubuntu 18.04 

Website: `LINK TO THE APP`

**Comment by palob** [comment]
Can you please look up the ``*.desktop`` file for the icon name?
