### ISSUE TITLE
Icon Request: Slack (update)

### ISSUE THREAD

**Issue by ngc7293** [numixproject/numix-core#4714]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Slack`| `slack` | `slack.desktop` | ![original](https://slackhq.com/wp-content/uploads/2019/01/2019-01_BrandRefresh_slack-brand-refresh_04-harmonized-logos.png) |

Description: `Slack is a collaboration hub for work`

Website: `https://slack.com/`

Slack recently updated their Logo

**Comment by mrmeszaros** [comment]
Hey,
Here, I made a draft:
![slack-new circle](https://user-images.githubusercontent.com/15245298/53646769-4bdd2800-3c3c-11e9-8e1a-2f3877206776.png)
* I used the colors from the old icon - but maybe the colors of the dark variant might be better.
* Also the symbol might be a tad bit too small - again did not try to make it bigger

**Comment by palob** [comment]
I think for a redesign you should use the colours from the new icon. The baseplate looks a bit dark/dull here.
Symbol size could be up to 30x30 I think, since it is a somewaht circular shape.
