### ISSUE TITLE
Icon Request: PICO-8

### ISSUE THREAD

**Issue by really-need-an-api-key** [numixproject/numix-core#4761]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `PICO-8`| `pico-8` | `pico-8.desktop` | ![pico-8](https://user-images.githubusercontent.com/11636003/52351439-0d808e80-2a2b-11e9-8963-3d2af5080ea3.png) |

Description: PICO-8 is a fantasy console for making, sharing and playing tiny games and other computer programs.

Website: https://www.lexaloffle.com/pico-8.php

**Comment by really-need-an-api-key** [comment]
I was thinking about making PRs for either of those:
![pico-8 2 svg](https://user-images.githubusercontent.com/11636003/52351883-e5455f80-2a2b-11e9-9695-e7bb17dac361.png)
![pico-8 svg](https://user-images.githubusercontent.com/11636003/52351879-e37b9c00-2a2b-11e9-8bcb-72c3608c8698.png)

The 8 is from the logotype:
![pico8](https://user-images.githubusercontent.com/11636003/52352043-2c335500-2a2c-11e9-9ced-9c19678eca3d.png)

**Comment by palob** [comment]
I'd prefer the first one but i'm not sure on the combination of the dark baseplate with the white cross in the middle. The symbol could be larger. For this shape 28x28 or even 30x30 should be OK as it is basically an approximation of a circle.

**Comment by really-need-an-api-key** [comment]
Decided to try the logotype background.
![pico-8 3 svg](https://user-images.githubusercontent.com/11636003/52438049-ac36e900-2b18-11e9-972d-8bb4181d800a.png)
or a cross-less version:
![pico-8 4 svg](https://user-images.githubusercontent.com/11636003/52438068-b822ab00-2b18-11e9-8189-3e1643df657e.png)

**Comment by palob** [comment]
How does it look with a white or cream/bright grey/colour from PICO 8 logotype baseplate?

Colourful symbols work best with a neutral coloured, intensely bright or dark baseplate.

**Comment by really-need-an-api-key** [comment]
Kinda dull-ish in my opinion.
![pico-8 5 svg](https://user-images.githubusercontent.com/11636003/52439502-f372a900-2b1b-11e9-9e59-e9979eaeff0f.png)

The logo there has a dark blue shadow, the contrast is much better imo.
![pico-8 6 svg](https://user-images.githubusercontent.com/11636003/52439665-6c720080-2b1c-11e9-8df6-fbd4fe79f936.png)

**Comment by palob** [comment]
The blue one looks cool but is it recognisable? Do you know if there is something in particular which the "pixel rhombus" is a symbol for? Is there even something you could recognise?

**Comment by really-need-an-api-key** [comment]
I don't think it's a symbol for anything, really. It's just some of the colours of the palette available for use in the program.

![pico-8 7 svg](https://user-images.githubusercontent.com/11636003/52592268-3eefc480-2e46-11e9-8a94-abf114ed4577.png)

**Comment by palob** [comment]
Now with both blue ones on one page I'm not sure anyore which one is the better. What do you think, @Foggalong?

**Comment by Foggalong** [comment]
The blue one without the white centre I think:)

**Comment by really-need-an-api-key** [comment]
Shall i open a PR?

**Comment by palob** [comment]
You're welcome to :-)
