### ISSUE TITLE
PacmanXG Redesign

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#4766]
The problem here is two fold: the [original icon](https://github.com/mesjetiu/PacmanXG/blob/master/icon.png) is pretty awful, but also our icon is just the meshing together of two Numix symbols (way back in #125). The symbols doesn't really go together well so some adjustments are needed.

**Comment by really-need-an-api-key** [comment]
What about making it firefox-like?
![pacmanxg 1 svg](https://user-images.githubusercontent.com/11636003/57184393-33e38800-6ebb-11e9-907c-fbc2c9bae9fa.png)

Or something like this, which extends slighty beyond the symbol area (red)?
![pacmanxg 2 svg](https://user-images.githubusercontent.com/11636003/57184433-bcfabf00-6ebb-11e9-95cb-955faa855dd3.png)

Looks kinda like a sheriff's badge though, so maybe with a different cog symbol.

**Comment by palob** [comment]
For me the first one doesn't work at all. It would look even more weird on a Circle baseplate.
Moreover I'm all for ditching this strangely shaped object and creating (or taking one from existing icons) a more classical, recognisable cogwheel like the one in the orininal icon.

**Comment by really-need-an-api-key** [comment]
Like this?
![pacmanxg2 1 svg](https://user-images.githubusercontent.com/11636003/57559710-7c031e80-7383-11e9-8148-9cbd54348dad.png)
But maybe with a lighter blue, or a different base shape colour.

**Comment by palob** [comment]
Spot-on for me! :rocket:

**Comment by Foggalong** [comment]
@really-need-an-api-key Please submit a pull request for this when you can, would be great to get it in :)

**Comment by really-need-an-api-key** [comment]
Whoops time sure flies.
I'll get on it this weekend!
