### ISSUE TITLE
Unity Monodevelop

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#4767]
There's just too much going on [in this icon](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/unity-monodevelop.svg). The base layer symbol doesn't have a shadow, the top layer symbol has weird edge strokes, and generally the whole thing could be done much better.

**Comment by palob** [comment]
This is probably fixed now, simplified it a good deal, what do you think @Foggalong?

That arrow thing is still a bit concealed maybe.

**Comment by Foggalong** [comment]
No 100% agree, this is so much better :heart:
