### ISSUE TITLE
Duplicated Entry Test

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#4786]
Currently it doesn't look like we do Travis tests for duplicate entries. We probably should to avoid cases [such as this](https://github.com/numixproject/numix-core/pull/4783#issuecomment-464513399) in #4783.

**Comment by Foggalong** [comment]
@palob I just implemented a test to do this and was shocked at how many fails came back! I was expecting a couple given the size of the database but 18 :grimacing: 

```log
Found the following Linux icon names duplicated:
- accessories-thesaurus (2 times)
- azpainter (2 times)
- com.github.jeromerobert.pdfarranger (2 times)
- com.github.lainsce.notejot (2 times)
- com.github.manexim.typewriter (2 times)
- com.github.muriloventuroso.pdftricks (2 times)
- cs-desktop (2 times)
- deepin-deb-installer (2 times)
- freac (2 times)
- freedv (2 times)
- gnome-settings-default-applications (2 times)
- kmail2 (2 times)
- kylin-video (2 times)
- org.tordini.flavio.Minitube (2 times)
- pdfarranger (2 times)
- pdftricks (2 times)
- popsicle (2 times)
- textadept (2 times)
```

Will submit a fix for that as part of the PR but just thought I'd share

**Comment by palob** [comment]
I'm a bit snowed under atm, thanks for keeping Numix future-proof, @barelyhuman, @Foggalong , @satya164.

**Comment by Foggalong** [comment]
That's all good! Hope things are okay :)

**Comment by palob** [comment]
Thank you for fixing the duplicates up. Did you run into cases of ambiguity or could you make up where the entries belong to (as far as I read the diff you could)?

**Comment by Foggalong** [comment]
Yeah most cases were pretty unambiguous, clearly apps we'd had generic symlinks for which were later replaced by specific icons.
