### ISSUE TITLE
code-oss

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#4809]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Code - OSS` | `code-oss` | `code-oss.desktop` |  |

Description: Visual Studio Code, but open source variant

Website: https://github.com/Microsoft/vscode

**TL;DR** Please create a symlink from `vscode` to `code-oss`

BTW, I installed `code-oss` from official Arch Linux repository using `pacman` and this is content of `/usr/share/applications/code-oss.desktop`:

```desktop
[Desktop Entry]
Name=Code - OSS
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=code-oss --unity-launch %F
Icon=code-oss
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=code-oss --new-window %F
Icon=code-oss
```

**Comment by palob** [comment]
We've got this symlink for some time already. Looks like your installation is outdated.
