### ISSUE TITLE
GNOME Books Design

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#4810]
In hindsight, the use of gradients and 3D perspective in the icon for GNOME Books (sketched in #1800, added in #1858) really doesn't fit in with the Numix guidelines. It's a nice icon but needs tweaking for consistent.

**Comment by palob** [comment]
I'm working on an icon for [Foliate](https://github.com/johnfactotum/foliate). I came up with these 3 designs options which could be candidates for the GNOME Books redesign.

![gnome-books1](https://user-images.githubusercontent.com/7050624/58725967-c7d44100-83e0-11e9-8d9c-3e5ad0434d1e.png)
![gnome-books2](https://user-images.githubusercontent.com/7050624/58725974-cc005e80-83e0-11e9-8e33-dea4df0bc6be.png)
![gnome-books3](https://user-images.githubusercontent.com/7050624/58726202-6bbdec80-83e1-11e9-8ba2-464bbd2624d4.png)

**Comment by Foggalong** [comment]
Loving the third one, happy to go with that :)
