### ISSUE TITLE
[Suggestion] Provide a separated icons theme for GIMP and Inkscape

### ISSUE THREAD

**Issue by gusbemacbe** [numixproject/numix-core#4837]
Hello Numix team!

I suggest you provide a small separated icons packs for GIMP and Inkscape. Some users will use their favourite icons theme for the system, but want to stay with Numix icons for Inkscape and for GIMP. You can check:

1. https://www.opendesktop.org/p/1168331/ (Inkscape colourful icons pack)
2. https://www.opendesktop.org/p/1011952/ (GIMP icons pack)
3. https://www.opendesktop.org/p/1108406/ (GIMP icons pack)

**Comment by palob** [comment]
We've got no GIMP icons (I for one can't see any in 2.10 with symbolic icons used) AFAIK.

If I understand correctly, soon to be released Inkscape 1.0 will ship with new symbolic icons. This will make our colourful icons disappear but one the other hand cater for a homogeneously designed UI.
I don't see a big point in Numix-re-theming symbolic icons as there simply isn't much material to carve a Numix style into.

Before releasing packages of non-symbolic GIMP or Inkscape we would need to do a lot of icons. Right now we're quite incomplete.

**Comment by palob** [comment]
Labelled this as *invalid* because https://github.com/numixproject/numix-icon-theme is our repo for in-UI icons.

**Comment by gusbemacbe** [comment]
> This will make our colourful icons disappear but one the other hand cater for a homogeneously designed UI.

It is why you need to create a `icons.svg` and put in `~/.config/inkscape/share/icons/`, that Inkscape will find and reload and use Numix icons. 

> I don't see a big point in Numix-re-theming symbolic icons as there simply isn't much material to carve a Numix style into.

You do not need to re-theme them, nobody will want to use monochromantic symbolic icons. 

> Labelled this as invalid because https://github.com/numixproject/numix-icon-theme is our repo for in-UI icons.

Your icons theme has already all Inkscape icons, but an user who asked me, wanted to use an icons theme for the system, but another icons theme for Inkscape, like I said you you need to create only a file `icons.svg` which will be reloaded by Inkscape of both version 0.92 and 1.0.1. 

If you decide not to create it and still think it is invalid, too bad, no problems, I will explain to the user that he has to choose one of two icons theme – the mine or yours. As he wants the coliurful icons in Inkscape, he should pick Numix icons theme up. Thank you for your answer and your information!

**Comment by gusbemacbe** [comment]
@palob, I do not know which decision of yours, but if you decide not to provide for Inkscape and GIMP, I ask your authorisation to fork your projects and create a small separated icons set for Inkscape, or also to add to another new icons theme Suru++, "numixising", i.e., to colourise the monochromatic 16px, 22px and 24px icons. 

If you authorise, do you have colours palette?

**Comment by palob** [comment]
You're of course free to fork as per the GPL terms. I won't probably have the resources to maintain separate themes, don't know about other team members. So far we did not define a palette, we composed the colours somewhat intuitively.
