### ISSUE TITLE
Seahorse icon looks like "open source initiative"

### ISSUE THREAD

**Issue by mueller-ma** [numixproject/numix-core#4843]
The icon for Seahorse (https://github.com/numixproject/numix-core/blob/master/icons/circle/48/seahorse.svg) looks like the icon from the Open Source Initiative (https://en.wikipedia.org/wiki/Open_Source_Initiative).

Here's the current default icon of Seahorse: https://wiki.gnome.org/Apps/Seahorse?action=AttachFile&do=get&target=seahorse-icon.png

**Comment by Foggalong** [comment]
The icon used to be a key but it looks like @me4oslav changed to this way back in 13f6ce1ec98b5db8344d8ba09a172857f7a3d39d over 5 years ago. There doesn't look to be any note as to why it was changed but I'd hazard a guess that it's supposed to be a keyhole. You're right though definitely needs redesigning.

**Comment by palob** [comment]
Two drafts
![seahorse-1](https://user-images.githubusercontent.com/7050624/77705850-0c107d80-6fc1-11ea-89ae-4cea4c9104b1.png)
![seahorse-2](https://user-images.githubusercontent.com/7050624/77705851-0d41aa80-6fc1-11ea-8443-c820bb6baf6e.png)

Maybe just some password entry stuff or a keyhole better recognisable as such?

**Comment by Foggalong** [comment]
@palob Those would be good with me!

**Comment by palob** [comment]
So which is the better one? Right now I prefer the first but I could swear that if asked yesterday I'd preferred the other one.

**Comment by Foggalong** [comment]
Oh sorry I thought these were variations for two different icons; I'd prefer the second one :)
