### ISSUE TITLE
Enhancement Request: Brave Browser

### ISSUE THREAD

**Issue by modelmat** [numixproject/numix-core#4847]
| Application name | Icon name | Desktop file name | Original icon | Current Icon | 
| --- | :-- | :-- | :-- | :-- |
| Brave| brave| brave-bin.desktop| ![original](https://cloud.githubusercontent.com/assets/7050624/12705179/744acac8-c86c-11e5-9902-fd9b31487111.png) | ![current](https://cloud.githubusercontent.com/assets/7050624/12790042/be4ee5a6-caa0-11e5-8f02-66b448f099ed.png)

Description: A Private and Secure Web Browser

Website: https://brave.com/

-----

The current icon does not have good contrast on my system.
![mine](https://user-images.githubusercontent.com/25718989/55949377-ca929f80-5c95-11e9-9d7f-e0fd4ac51fd6.png)
An icon which increases the contrast between the orange and yellow would be great.
@palob [agrees](https://github.com/numixproject/numix-core/issues/2818#issuecomment-482314698): 
> I for one find it quite stark even in the screenshot but we could darken the orange and tone down the yellow.

**Comment by Foggalong** [comment]
Speaking for @palob here, that's very much not an agreement :P The contrast between the yellow and orange _is_ already quite stark and I'm not really sure that making them darker would do much good. What I will do though is remove the symbol gradient from the mane to make the colour one of the darker orange tones from the bottom.

**Comment by raknerak** [comment]
Can you please make a copy of brave.svg to brave-browser.svg?

**Comment by palob** [comment]
We've got this for a long time so your Numix installation is probably outdated.

**Comment by raknerak** [comment]
ii  numix-icon-theme                             0.3+949~202003201747~ubuntu18.04.1                                          all          Numix icon theme
ii  numix-icon-theme-circle                      2.0.3+21~201806080916~ubuntu18.04.1                                         all          Numix Circle icons


PPA is already added however latest release from 2018

(base) ahmety@ahmety-HP-ZBook:~/anaconda3/bin$ sudo apt-get upgrade numix-icon-theme-circle
Reading package lists... Done
Building dependency tree       
Reading state information... Done
numix-icon-theme-circle is already the newest version (2.0.3+21~201806080916~ubuntu18.04.1).
Calculating upgrade... Done

I will try manual upgrade

**Comment by palob** [comment]
OK sorry, looks like the PPA is severely outdated.

You can manually fetch the latest releases here:
https://github.com/numixproject/numix-icon-theme-circle/releases
https://github.com/numixproject/numix-icon-theme-square/releases
