### ISSUE TITLE
Requesting several icons that are missing

### ISSUE THREAD

**Issue by dylanmtaylor** [numixproject/numix-core#4852]
I'd love to see these added. Names are from Arch/AUR packages.

| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Slic3r Prusa Edition`| `slic3r-prusa3d` | `slic3r-prusa3d.desktop` | ![original](https://www.prusa3d.com/wp-content/uploads/2017/06/Slic3r_128px-1.png) |
| `Shadow`| `shadow-beta,shadow-dev,shadow-preprod (depending on distro)` | `shadow-dev/shadow-beta.desktop` | ![original](https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2018/02/shadow-796x498.jpg) |
| `DBeaver (CE/EE)`| `dbeaver-ce/dbeaver-ee` | `dbeaver-ce.desktop/dbeaver-ee.desktop` | ![original](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/DBeaver_logo.svg/128px-DBeaver_logo.svg.png) |
| `PIA VPN`| `pia` | `piavpn.desktop` | ![Screenshot from 2019-04-14 17-50-12](https://user-images.githubusercontent.com/277927/56099664-cf499480-5edd-11e9-85ec-e397bd17c4bf.png) |
| `YubiKey Personalization GUI`| `yubikey-personalization-gui` | `yubikey-personalization-gui.desktop` | ![Screenshot from 2019-04-14 17-49-03](https://user-images.githubusercontent.com/277927/56099653-b345f300-5edd-11e9-83ce-8df83ddacd67.png) |
| `balenaEtcher` | `balena-etcher-electron` | `balena-etcher-electron.desktop` | ![Screenshot from 2019-04-14 17-52-11](https://user-images.githubusercontent.com/277927/56099702-37987600-5ede-11e9-802e-88ebb3b7a6d3.png) |
| `Simple Scan` | `org.gnome.SimpleScan` | `simple-scan.desktop` | ![Screenshot from 2019-04-14 17-54-36](https://user-images.githubusercontent.com/277927/56099714-6282ca00-5ede-11e9-8843-7a484affa303.png)

**Comment by palob** [comment]
The first and the last two ones as well as pia and dbeaver will be fixed once my PRs get merged.

**Comment by dylanmtaylor** [comment]
I see DBeaver and PIA merged. Cool. The Slic3r and Slic3r Prusa Edition have different color schemes and shouldn't have the same icon FYI

**Comment by palob** [comment]
Both are different in colours. Other than that the original icons look the same, that's why do ours.

**Comment by palob** [comment]
Closing because the only one left, yubikey-personalization-gui was retired in favour of yubioath-flutter
