### ISSUE TITLE
Path for icon for LibreOffice flatpaks have changed

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-core#4853]
Starting recently (around the GNOME 3.32 release) the LibreOffice flatpak icons are no longer showing the Numix theme. I believe it is because the name of the requested icon in the flatpak is different that what Numix has right now.

The new ones are:
org.libreoffice.LibreOffice.base
org.libreoffice.LibreOffice.calc
org.libreoffice.LibreOffice.startcenter
org.libreoffice.LibreOffice.draw
org.libreoffice.LibreOffice.impress
org.libreoffice.LibreOffice.math
org.libreoffice.LibreOffice.writer

What we currently have is symlinks named:
org.libreoffice.LibreOffice-base.svg
org.libreoffice.LibreOffice-calc.svg
org.libreoffice.LibreOffice-startcenter.svg
org.libreoffice.LibreOffice-draw.svg
org.libreoffice.LibreOffice-impress.svg
org.libreoffice.LibreOffice-math.svg
org.libreoffice.LibreOffice-writer.svg

**Comment by Foggalong** [comment]
Should the math one start with org as the others?

**Comment by brittyazel** [comment]
oh yes, sorry I mistyped. Corrected

**Comment by brittyazel** [comment]
@Foggalong 

This recent commit seems to contain the fix 

https://github.com/numixproject/numix-core/commit/dd136b6dfc579a9d5271fab5bffa93456260448a

**Comment by Foggalong** [comment]
In which case never mind! It's in the latest update so will be rolling out soon to a package manager near you :)
