### ISSUE TITLE
Goland Icon

### ISSUE THREAD

**Issue by alrightjulian** [numixproject/numix-core#4969]
| Application Name | Icon Name | Desktop File Name | Original icon |
| --- | :-- | :-- | :-- |
| `goland`| `goland` | `goland` | ![original](https://pbs.twimg.com/profile_images/809358866442055680/CZjD2GYK_400x400.jpg) |

Description: `Jetbrain IDE for golang, goland`

Website: `https://www.jetbrains.com/go/`

**Comment by palob** [comment]
duplicate of #4198
