### ISSUE TITLE
Blender 3D

### ISSUE THREAD

**Issue by alanrme** [numixproject/numix-core#4970]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Blender` | `/usr/snap/blender/current/blender.svg` | `/usr/snap/blender/current/blender.desktop` | ![original](https://svgur.com/i/EhH.svg) |

Description: `Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, video editing and 2D animation pipeline.`

Website: `https://blender.org`

**Comment by palob** [comment]
We've already got an icon for Blender. It doesn't however show up when it's installed via Snap because Snap hardcodes the icon paths.

You can fix this by copying the ``.desktop`` file to ``~/.local/share/applications`` and editing the icon line to ``Icon=blender``.
