### ISSUE TITLE
Icon Request: Microsoft Teams

### ISSUE THREAD

**Issue by azorng** [numixproject/numix-core#4971]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Microsoft Teams`| `teams` | `teams.desktop` | ![original](https://www.logolynx.com/images/logolynx/46/4699e4d0504d6ed4e249d6109d89238a.png) |

Description: `Microsoft Teams is the hub for team collaboration in Office 365 that integrates the people, content, and tools your team needs to be more engaged and effective.`

Website: [`Microsoft Teams`](https://products.office.com/en-us/microsoft-teams/group-chat-software)

**Comment by TiZ-HugLife** [comment]
The Flatpak wrapper from Flathub has the icon name `com.microsoft.Teams` and desktop file name `com.microsoft.Teams.desktop`.

**Comment by raknerak** [comment]
Is there any update about teams.svg in latest package?
