### ISSUE TITLE
Inconsistent Settings Icon In System Menu

### ISSUE THREAD

**Issue by ccrisan** [numixproject/numix-core#4985]
I find the Settings icon that appears in the Gnome system menu a bit inconsistent. It's next to the *Lock* and *Power* icons which are simply white monochrome icons, while the Settings icon is colored:

![colored-settings-icon](https://user-images.githubusercontent.com/76639/65796341-043c6180-e175-11e9-9d22-5574c5a3a82f.png)

Is this by design, is it something that you guys are willing to change or is it a misconfiguration on my side?

I'm running Gnome 3.34 on Arch Linux and I use the *Numix Circle Light* icon theme.

**Comment by palob** [comment]
It's not intended but I can't reproduce it (Arch, 3.34).

However Numix Circle Light exposes some other serious brokenness (symbolic icons for folders).

Is there a specific reason you use the Light theme? Does it occur with the non-Light theme selected as well?

**Comment by ccrisan** [comment]
@palob thanks for your quick answer. The non-Light theme behaves similarly, except for the fact that the icon is different (the green horizontal on/off switch).

**Comment by palob** [comment]
That's strange. Could you please provide a screenshot?

**Comment by ccrisan** [comment]
Sure, here is a screenshot of my entire desktop when using Numix icon set:

![Screenshot from 2019-09-28 11-20-14](https://user-images.githubusercontent.com/76639/65813772-1dc7c280-e1e2-11e9-88ae-a4e9c280149e.png)

The thing I find very strange though is now that I selected plain Numix theme (as opposed to Light one), my application icons (visible in the Dock) also don't look much like Numix. The third one from the left is supposed to be Chrome.

I'm starting to believe that there's something strange about my setup. Any help in identifying this particular problem will be highly appreciated.

**Comment by ccrisan** [comment]
I mention that I have the following Arch packages installed:

    $ pacman -Qs numix
    local/numix-circle-icon-theme-git 0.r51.74295b4-1
        Circle icon theme from the Numix project
    local/numix-icon-theme-git 0.r1987.cfef86f11-1
        Base icon theme from the Numix project

**Comment by palob** [comment]
The plain Numix theme doesn't provide app icons. It is meant to be used with one of our app icon themes (Circle, Square) for the full "Numix experience".

**Comment by ccrisan** [comment]
> The plain Numix theme doesn't provide app icons. It is meant to be used with one of our app icon themes (Circle, Square) for the full "Numix experience".

Oh, that makes sense. In any case, I am using the Circle variant and app icons are just fine. The Settings icon that shows up in the menu is still a problem though.

**Comment by ccrisan** [comment]
I found the source of my issue: I had a `~/.local/share/applications/gnome-control-center.desktop` customized for some reasons and it contained `Icon=gnome-control-center` which was the source of this issue.

**Comment by palob** [comment]
That's comforting to hear. I was afraid that GNOME could have changed the icon name which could have been impossible to work around.
