### ISSUE TITLE
Icon Request: Celluloid

### ISSUE THREAD

**Issue by Latesil** [numixproject/numix-core#4986]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Celluloid`| `celluloid` | `celluloid.desktop` | ![original](https://avatars2.githubusercontent.com/u/42234840?s=200&v=4) |

Description: `GTK+ frontend for mpv`

Website: `https://github.com/celluloid-player`

**Comment by palob** [comment]
Fixed (but not released yet). See #4979.
