### ISSUE TITLE
New firefox icon

### ISSUE THREAD

**Issue by msevilla00** [numixproject/numix-core#4998]
I was wondering if you are planning to change Firefox icon to show last changes as you could see in [mozilla's web page](https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/).
It would be great to see new Firefox's look in my favourite icons pack.
There is a svg version of the new logo in [wikimedia](https://en.wikipedia.org/wiki/Firefox#/media/File:Firefox_logo,_2019.svg)
Cheers
Miguel

**Comment by Foggalong** [comment]
@msevilla00 For future reference when reporting, your original issue was in the wrong repo. I've transferred it across this time though so all good.

@palob There's been a new-new icon since that other issue was posted and it's enough of a design departure (in particular the ditching of the globe) that we're going to have to comeback and potentially redesign these icons.

**Comment by msevilla00** [comment]
Great  to hear it! I will open issue in right place next time, sorry.
I'm looking forward to see new icon.
Cheers

**Comment by maxtron95** [comment]
@palob I created some new firefox icons but, I am not sure if there are mistakes with the icons. Or should I make a full baseplate icon instead like the current firefox icon?

![firefox-ci svg](https://user-images.githubusercontent.com/53346722/77718516-22aed880-6fb1-11ea-92d1-fcd541fa8949.png)
![firefox-sq svg](https://user-images.githubusercontent.com/53346722/77718526-25a9c900-6fb1-11ea-8efa-dcd247307d3e.png)

[firefox-icons-redesign.tar.gz](https://github.com/numixproject/numix-core/files/4391313/firefox-icons-redesign.tar.gz)

**Comment by palob** [comment]
These are definitely cool. The colours should be a bit brighter and less saturated for Numix. Full-baseplate designs are somewhat set to be phased out but this cries for one so yes, it would be great if you could give this a shot for comparison.

**Comment by palob** [comment]
@Foggalong So symbol-on-baseplate is the way to go?
In addition to numixier colours I think this could use a fox shadow on the marble.

While we can't take over the gradients seen in the original icons's fox I'd love to see the the rose-red from the bottom kept.

**Comment by palob** [comment]
Should we have a slight radial gradient for the marble? We've got this in some icons.

Maybe a darker background as seen in the About dialogue (but not quite as dark)?
![about](https://user-images.githubusercontent.com/7050624/77965230-e0eb9e00-72e0-11ea-9868-599a51148502.png)

**Comment by Foggalong** [comment]
Yes to being a symbol on baseplate and yes to the general proposed design (thought saturation does need reducing slightly). I'd sooner avoid gradients on the marble because it works alright without them here, but yeah a shadow from the fox onto it would work well :+1:

**Comment by dvorapa** [comment]
Any news?
