### ISSUE TITLE
Icon Request: LazyMan

### ISSUE THREAD

**Issue by mattyrc** [numixproject/numix-core#5003]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `LazyMan`| `lazyman` | `lazyman.desktop` | ![original](https://raw.githubusercontent.com/StevensNJD4/LazyMan/master/resources/Logos/LM.png) |

Description: `A simple program that lets you stream every NHL and MLB game from your favorite media player for free.`

Website: `https://github.com/StevensNJD4/LazyMan`

**Comment by palob** [comment]
Upstream project vanished it appears.
