### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by Gabb1995** [numixproject/numix-core#5005]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Zoom`| `Zoom.png` | `Zoom.desktop` |![Original](https://user-images.githubusercontent.com/20728259/69229684-315e2c80-0b86-11ea-8f71-73fa64368a3b.png)|

Description: `Video Calling`

Website: `https://zoom.us/`

**Comment by TiZ-HugLife** [comment]
The Flatpak wrapper from Flathub has the icon name `us.zoom.Zoom` and desktop file name `us.zoom.Zoom.desktop`.
