### ISSUE TITLE
Panel icon for sirikali.

### ISSUE THREAD

**Issue by arun54321** [numixproject/numix-core#5037]
Monochromatic panel/status icon for Sirikali.

**Comment by palob** [comment]
Hi, could you please tell us the icon names and attach a screenshot of the original icons?
We need this to fix the issue.

**Comment by palob** [comment]
Could you please reopen the updated report here https://github.com/numixproject/numix-icon-theme?

**Comment by arun54321** [comment]
> Could you please reopen the updated report here https://github.com/numixproject/numix-icon-theme?

The icon is already in numix icon pack. It just needs monochrome panel icons [link](https://github.com/numixproject/numix-core/commit/0893cc96b30ada841597d25ae3d8379bbd51838c#diff-02e40af74e43bc5ec6766936ae17bc75)

**Comment by palob** [comment]
Alright, but how do they look like? A monochrome representation of the app icon or representation of states/actions? How many are there and what are the icons names?
