### ISSUE TITLE
[Icon Request] New GNOME Extensions app

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-core#5070]
I am requesting an icon be made for the brand-new GNOME 3.36 Extensions app that is debuting.

From the .desktop:
```
[Desktop Entry]
Type=Application
Name=Extensions
Icon=org.gnome.Extensions
Comment=Configure GNOME Shell Extensions
Exec=/usr/bin/gnome-shell-extension-prefs %u
Categories=GNOME;GTK;
OnlyShowIn=GNOME;

```

Attached is the upstream icon for reference.

![org gnome Extensions](https://user-images.githubusercontent.com/3747347/76178728-95c4ec00-6175-11ea-94ff-e138622c2dee.png)

**Comment by palob** [comment]
Will be fixed by #5025.
