### ISSUE TITLE
Icon request: Cataclysm: Dark Days Ahead

### ISSUE THREAD

**Issue by superDuperCyberTechno** [numixproject/numix-core#5147]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Cataclysm: Dark Days Ahead`| `cataicon.ico` | `cataclysm` | ![original](https://i.imgur.com/DlMDY3Z.png) |

Description: `Cataclysm: Dark Days Ahead is a turn-based survival game set in a post-apocalyptic world.`

Website: `https://cataclysmdda.org/`

**Comment by palob** [comment]
We've got an icon for this with other non-hardcoded icon names.
