### ISSUE TITLE
Gender & Race Options for People Icons

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#5320]
As mentioned in #5075, an idea I've had during hiatus is to provide race/gender options a la emojis for generic icons which use a person with visible features (i.e. not just a blob person) in their design. That doesn't mean redesigning every icon which has a face, just the generic ones like preferences-desktop-user.

This issue is to keep track of that and also discuss potential design changes which can happen along side that since the current one is also due an update.

**Comment by palob** [comment]
The lazy solution would be one skin/gender-agnostic pictogram-like design.

The problem with optional icons is how can the user select those?

**Comment by Foggalong** [comment]
I'd also be good with a pictogram design, and yeah that would also avoid complications with how to make it obvious to users that options were available :+1:

**Comment by palob** [comment]
Here comes a very simplistic approach with a multitude of colour options
![user-0](https://user-images.githubusercontent.com/7050624/83978222-4de56a80-a906-11ea-9d45-e929cc235b09.png)
![user-1](https://user-images.githubusercontent.com/7050624/83978223-4e7e0100-a906-11ea-9588-778c317454b6.png)
![user-2](https://user-images.githubusercontent.com/7050624/83978224-4f169780-a906-11ea-8c78-427a6dee9e64.png)
![user-3](https://user-images.githubusercontent.com/7050624/83978226-4f169780-a906-11ea-8023-21e40cda053c.png)
![user-4](https://user-images.githubusercontent.com/7050624/83978227-4faf2e00-a906-11ea-8b65-f57bffea4cb8.png)
![user-6](https://user-images.githubusercontent.com/7050624/83978228-4faf2e00-a906-11ea-8e31-0b1b1f428699.png)
![user-7](https://user-images.githubusercontent.com/7050624/83978229-5047c480-a906-11ea-9724-988434ecf7af.png)
![user-8](https://user-images.githubusercontent.com/7050624/83978230-5047c480-a906-11ea-8455-4e6016e3bca3.png)
![user-9](https://user-images.githubusercontent.com/7050624/83978231-50e05b00-a906-11ea-86c7-73b43b2002b3.png)
![user-10](https://user-images.githubusercontent.com/7050624/83978232-50e05b00-a906-11ea-8d80-e74202a2fe6c.png)
![user-11](https://user-images.githubusercontent.com/7050624/83978233-5178f180-a906-11ea-9e3f-09e6ccb8282f.png)
![user-12](https://user-images.githubusercontent.com/7050624/83978234-52118800-a906-11ea-8f35-690077cb59e5.png)

**Comment by palob** [comment]
design options
![user-20](https://user-images.githubusercontent.com/7050624/83978874-b898a500-a90a-11ea-814c-ba7a52a03c57.png)
![user-30](https://user-images.githubusercontent.com/7050624/83978875-b9c9d200-a90a-11ea-8d06-6da166397bcc.png)
![user-40](https://user-images.githubusercontent.com/7050624/83978876-ba626880-a90a-11ea-8c95-98e5c68ed32d.png)

**Comment by palob** [comment]
Alternatively maybe a combination with an emoji-like head as seen in the ``gnome-social`` icon.

**Comment by palob** [comment]
Or maybe a contour design as seen in the Suru Plus theme?
![user](https://user-images.githubusercontent.com/7050624/86283359-36399300-bbe1-11ea-9e72-5b2f50b7ab08.png)

**Comment by palob** [comment]
Revisiting this I think those pictogram style icon look somewhat un-Numixy.
The tough task is to get the existing icon gender-/race-agnostic.

![preferences-desktop-user-11](https://user-images.githubusercontent.com/7050624/138927607-c1bd104b-f481-47ab-b6a1-7839daee9522.png)
![preferences-desktop-user-12](https://user-images.githubusercontent.com/7050624/138927612-b9cd478d-c454-47d3-9176-62d67bde191f.png)
![preferences-desktop-user-13](https://user-images.githubusercontent.com/7050624/138927615-4d931d13-1fe2-41c8-803b-eaeb0e6ed3a8.png)

**Comment by palob** [comment]
The emoji idea miiiight be viable, what do you think @Foggalong, way to go or dead end?

![preferences-desktop-user-emoji](https://user-images.githubusercontent.com/7050624/138930084-459e647b-a26f-4d81-b70b-129a7744e835.png)

**Comment by palob** [comment]
Or maybe a even more simple smiley face (dot, dot, line), looking less like a real person, @Foggalong ?

**Comment by palob** [comment]
Another very lazy way of "solving" this is using a recolour of ``cs-user-accounts``.

**Comment by palob** [comment]
Maybe grey @Foggalong so it looks even less like a real person?

![preferences-desktop-user-emoji-grey](https://user-images.githubusercontent.com/7050624/152011738-d8ff45f3-0ac5-4028-bcc8-bbb2f6daae04.png)
