### ISSUE TITLE
Icon Request: Fallout Shelter

### ISSUE THREAD

**Issue by hmlendea** [numixproject/numix-core#5378]
| Game | Steam AppID | Icon name | Original icon |
| --- | :-- | :-- | :-- |
| `Fallout Shelter` | `588430` | `steam_icon_588430` | ![original](https://upload.wikimedia.org/wikipedia/en/9/90/Fallout_Shelter_Icon.jpeg) |

Description: `A colony management type game available for PC (Steam Play whitelisted) and mobiles`

Website: `https://store.steampowered.com/app/588430/Fallout_Shelter/`

**_Note: It's also available on Android_**

**Comment by maxtron95** [comment]
There is an Android port of this game as well.

**Comment by hmlendea** [comment]
Yes there is. It's literally the same game. I just can't seem to be able to add the Android tag to this issue.

**Comment by palob** [comment]
We'd need to know the Android icon name for that.

**Comment by maxtron95** [comment]
The icon name is `com.bethsoft.falloutshelter/com.bhvr.Prime31MainActivityWithMemoryWarning`
