### ISSUE TITLE
Icon Request: LYNE

### ISSUE THREAD

**Issue by hmlendea** [numixproject/numix-core#5383]
| Game | Steam AppID | Icon name | Original icon |
| --- | :-- | :-- | :-- |
| `LYNE` | `266010` | `steam_icon_266010` | ![original](https://user-images.githubusercontent.com/10261133/85958605-6265d180-b99f-11ea-892a-2d05fc789bde.png) |

Description: `A small puzzle game for PC (Steam Play whitelisted) and mobile`

Website: `https://store.steampowered.com/app/266010`

**_Note: It's also available on Android_**

**Comment by maxtron95** [comment]
I can't get the android icon name at the moment because I have to pay $1.99 for it.

**Comment by hmlendea** [comment]
I installed Applications Info.
What value should I be looking for?

Also, please note that I own the Android version on the Humble Store, not the Play Store.

**Comment by maxtron95** [comment]
On the Applications Info app, go to the app you are getting names from. Then on that screen, tap Activities. I am using the [Fancade](https://play.google.com/store/apps/details?id=com.martinmagni.fancade) game as an example, take note of all the names found above `Task affinity:` on each Activity entry that does not have a grayed out launch button. I don't think it matters where you got the app from. (Google Play, F-Droid, Humble Store)

![Screenshot_2020-06-29-06-26-03 1](https://user-images.githubusercontent.com/53346722/86000221-dec5d800-b9d2-11ea-8f54-5861af00a2fc.jpg)

**Comment by hmlendea** [comment]
`com.unity3d.player.UnityPlayerActivity`

That seems pretty generic...

![Screenshot_20200630-003729](https://user-images.githubusercontent.com/10261133/86058759-103db280-ba6a-11ea-966b-9ca3837e9636.png)

**Comment by maxtron95** [comment]
That must be the main activity name I am looking for. Thanks for looking into it.

Then the android icon name is:

`com.thomasbowker.lynerelease/com.unity3d.player.UnityPlayerActivity`

That generic name is pretty much used on "most" Unity games that are on Android.
