### ISSUE TITLE
Icon Request: Rise & Shadow of the Tomb Raider

### ISSUE THREAD

**Issue by BlueManCZ** [numixproject/numix-core#5404]
| Game | Steam AppID | Icon name | Original icon |
| --- | :-- | :-- | :-- |
| `Rise of the Tomb Raider` | [`391220`](https://store.steampowered.com/app/391220/Rise_of_the_Tomb_Raider/) | `steam_icon_391220` | <img src="https://user-images.githubusercontent.com/17854950/86138784-2ccffe00-baef-11ea-82d5-6262ad8faa54.png" width="200"> |
| `Shadow of the Tomb Raider` | [`750920`](https://store.steampowered.com/app/750920/Shadow_of_the_Tomb_Raider_Definitive_Edition/) | `steam_icon_750920` | <img src="https://user-images.githubusercontent.com/17854950/86139831-79680900-baf0-11ea-9e22-6b8b3c4e5bd8.jpg" width="200"> |

Note: Maybe the recolouring or linking to `Tomb Raider` icon could be enough? https://github.com/numixproject/numix-core/pull/4037

**Comment by maxtron95** [comment]
@Foggalong Can you reopen this? We haven't completed the icon for Shadow of the Tomb Raider yet.

**Comment by Foggalong** [comment]
My bad, missed that! I think a recolour of Rise to orange/black/white should be fine?
