### ISSUE TITLE
Icon for Moon Hunters

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#5427]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Moon Hunters`| `steam_icon_320040` | `Moon Hunters.desktop` | ![steam_icon_320040](https://user-images.githubusercontent.com/15245298/86280038-5cf4cb00-bbdb-11ea-9bf9-6658f425fa25.png)* |

Description: `Coop mythology storytelling game`

Website: http://www.moonhuntersgame.com/

*: The game only installs this 32x32 icon

**Comment by mrmeszaros** [comment]
Thought of something like this (based on a banner):
![moon-hunters-test](https://user-images.githubusercontent.com/15245298/192821269-78165e07-3691-4c43-8e42-f6e77b0c3355.png)

It's work in progress - there will be no contours, just the parts with different shades (also not final).

Not sure about the size - might be a bit too small?

**Comment by palob** [comment]
Yeah, size can be increased by a good deal. That horn/feather? thingprobably can exceed the 30x30 circle a bit.
And with a bigger symbol there is less risk of overly fine-grained structures.

**Comment by mrmeszaros** [comment]
How about this?
![moon-hunters-large-symbol-test](https://user-images.githubusercontent.com/15245298/192907803-5b07ed88-2fe4-4224-a822-acf068548640.png)

I kind of like it and and don't at the same time.
Feel like the "hair ornament" exceeds the 30x30 circle too much...

This other one is one pixel smaller (moon-circle), and seems to line up decently too:

![moon-hunters-large-2](https://user-images.githubusercontent.com/15245298/192910624-bb89ba69-2f03-4d22-a047-809eb4878fc7.png)

The ornament does not stand out that much in this - it's bound by a 17px radius circle (first one exceeds the 18px circle).

Not sure how much it can exceed - should I go even smaller?

**Comment by palob** [comment]
2nd is definitely fine, no need to go smaller. Alternatively you could bend the hair lock a bit more inwards so the "symbol body" can be slightly bigger.

**Comment by mrmeszaros** [comment]
Went with the second - seemed to line up better with the grid.
Here are renders in 384, 192, 96, 48:
![moon-hunters circle 384 1](https://user-images.githubusercontent.com/15245298/193103090-25668e79-44ca-49dc-9e9b-c92e09e81719.png) ![moon-hunters circle 384 2](https://user-images.githubusercontent.com/15245298/193103109-9cac8c5b-15f6-45cd-8656-075d58739814.png)
![moon-hunters circle 384 4](https://user-images.githubusercontent.com/15245298/193103135-d9d6fe41-068d-49f5-ad42-c6f170b91a81.png) ![moon-hunters circle 384 8](https://user-images.githubusercontent.com/15245298/193103153-6a27151b-9ed8-43e5-a2df-a9cd68259ef2.png)

Working on colors - then shadows, then I'll do a PR.
