### ISSUE TITLE
Icon for Lovers in a Dangerous Spacetime

### ISSUE THREAD

**Issue by mrmeszaros** [numixproject/numix-core#5465]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Lovers in a Dangerous Spacetime`| `steam_icon_252110` | `Lovers in a Dangerous Spacetime.desktop` | ![steam_icon_252110](https://user-images.githubusercontent.com/15245298/86522289-e1558100-be5b-11ea-927b-323cb65cc182.png) |

Description: Cute co-op 2D spaceship shooter

Website: https://www.loversinadangerousspacetime.com/

**Comment by really-need-an-api-key** [comment]
Something like this, perhaps?
![lovers](https://user-images.githubusercontent.com/11636003/111923372-1ca5e780-8a9f-11eb-8afe-4432cc9b3298.png)

**Comment by palob** [comment]
Yes, with a bit brighter background though.

**Comment by mrmeszaros** [comment]
Yes, I love it <3

Ain't sure if it works, but maybe a pink hue for the heart would be more in line with the original, and the game's color theme.

**Comment by really-need-an-api-key** [comment]
Here it is, brighter and pinkier

![lovers](https://user-images.githubusercontent.com/11636003/115611001-dd5ef680-a2e9-11eb-8d76-a01ad24ced97.png)

**Comment by palob** [comment]
Yes, looking forward to it! From distance, the gradient looks like 10L(new). I prefer the old colours for the lovers and maybe they should cast a shadow onto the heart.

**Comment by really-need-an-api-key** [comment]
Ah, yes, I forgot to adjust the gradient. I'll fix that for the PR.
