### ISSUE TITLE
VSCodium icon renders poorely

### ISSUE THREAD

**Issue by ixxie** [numixproject/numix-core#5485]
Hello folks,

It seems the VSCodium icon does not render well with Numix circle (see https://github.com/VSCodium/vscodium/issues/396 for details). I'm not sure what goes wrong, but I get a different icon for the launcher and the window, and the window icon renders poorly (however, it also renders poorly in Adwaita).

![Screenshot from 2020-07-08 01-16-37](https://user-images.githubusercontent.com/20320695/86850049-45c14c00-c0b9-11ea-87ba-8a9edf7918be.png)

**Comment by Foggalong** [comment]
Closing due to lack of information from reporter. @ixxie if you can provide the information we'll look into this further :+1:
