### ISSUE TITLE
preferences-desktop-icons shouldn't be a symlink to numix

### ISSUE THREAD

**Issue by mueller-ma** [numixproject/numix-core#5490]
Screenshot from KeePassXC:
![keepassxc](https://user-images.githubusercontent.com/22525368/56286032-f049f980-6118-11e9-8ef1-dfe0e9b87153.png)

The icon used for "Icon" shouldn't be the numix icon, but instead an "icon" icon.
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/preferences-desktop-icons.svg

Here's the request for a proper "preferences-desktop-icons" icon: https://github.com/numixproject/numix-core/issues/2908#issuecomment-484052740

**Comment by Foggalong** [comment]
@palob Didn't you recently make a new icon to do with icon themes? That might be a more suitable destination for that symlink

**Comment by Foggalong** [comment]
@mueller-ma For future reference, you submitted your request against the packaging repo (numix-icon-theme-circle) not against the development repo. Please consult the READMEs of repositories when submitting issues.

**Comment by palob** [comment]
Yeah, that was in #5119, the db icon name is ``icon-preview-app``.

**Comment by Foggalong** [comment]
Aye I reckon that one works here too!
