### ISSUE TITLE
Icon Request: Lords of Waterdeep

### ISSUE THREAD

**Issue by hmlendea** [numixproject/numix-core#5508]
| Game | Steam AppID | Icon name | Original icon | Banner |
| --- | :-- | :-- | :-- | :-- |
| `D&D Lords of Waterdeep` | `644390` | `steam_icon_644390` | ![original](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/644390/3d4f35c136ae57449ccf4eadb8ef7efc39fa3be9.jpg) | ![banner](https://cdn.cloudflare.steamstatic.com/steam/apps/644390/header.jpg?t=1594736414) |

Description: `PC/Mobile adaptation for the board game with the same name (Steam Play compatible)`

Website: `https://store.steampowered.com/app/644390`

**Comment by hmlendea** [comment]
There's an Android version of this game as well, but I don't own it so I cannot provide any info for it

**Comment by really-need-an-api-key** [comment]
Perhaps something like this?
![circle-lords-of-waterdeep](https://user-images.githubusercontent.com/11636003/111865587-427ca080-8968-11eb-8d19-c28670e15010.png)
![square-lords-of-waterdeep](https://user-images.githubusercontent.com/11636003/111865589-43adcd80-8968-11eb-94c3-37ad9b632724.png)

**Comment by palob** [comment]
Yep, looking forward to the PR.
