### ISSUE TITLE
Fall Guys (Proton)

### ISSUE THREAD

**Issue by furtabs** [numixproject/numix-core#5566]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Fall Guys`| `steam_icon_1097150` | `Fall Guys.desktop` | ![image](https://user-images.githubusercontent.com/48419040/90903366-d4ed9f00-e39b-11ea-9986-fb8044a18cda.png) |

** Note its not the original icon but its the mascot for Fall Guys** OG Icon is just text

Description: `Fall Guys: Ultimate Knockout flings hordes of contestants together online in a mad dash through round after round of escalating chaos until one victor remains!`

Website: `https://fallguys.com/`

**Comment by maxtron95** [comment]
![fall-guys-ci](https://user-images.githubusercontent.com/53346722/90908364-e7ff6f80-e399-11ea-9527-b24a4685b21c.png)

**Comment by furtabs** [comment]
that was quick nice
