### ISSUE TITLE
Wrong OpenERP symlink

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#5585]
We've got a symlink ``openerp-client`` to the root ``opera``.
Does this make a sense I fail to see?

**Comment by Foggalong** [comment]
This is definitely a bug, looking at the commit where it was added it will have been put there intending for it to be an app with a similar name, though not clear what :confused:

**Comment by Foggalong** [comment]
Actually perhaps it wasn't a bug - the OpenERP icon is almost identical to what Opera's icon used to be.

| OpenERP | Opera (pre-2015) | Opera (post-2015) | Numix Opera (2014) |
| :----: | :-----: | :-----: | :-----: |
| ![ap_resize php](https://user-images.githubusercontent.com/5920259/92919036-e4568a00-f427-11ea-827b-3736225281e2.png) | ![external-content duckduckgo com](https://user-images.githubusercontent.com/5920259/92919039-e4ef2080-f427-11ea-8d97-109d8cc197fd.png) | ![external-content duckduckgo com](https://user-images.githubusercontent.com/5920259/92919092-f0dae280-f427-11ea-8870-e097c45c6835.jpeg) |  ![Screenshot from 2020-09-11 12-17-43](https://user-images.githubusercontent.com/5920259/92919695-dce3b080-f428-11ea-9293-a37bea8de684.png) |

When you compare it to what our Opera icon was in 2014 at the time OpenERP was introduced by yours truly in adc6a87dd152f02a931e80d39836a1f474aa9de1, it's not hard to imagine that I might have cut that corner and just made it a symlink instead. In the spirit of that laziness, I'm actually just gonna reintroduce the old opera icon with a colour switch be the new (old) OpenERP icon.

**Comment by Foggalong** [comment]
Fixed in #5587
