### ISSUE TITLE
Zotero Refresh

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#5586]
Current icon for Zotero is [very old](https://github.com/numixproject/numix-core/commit/925a821f6de0f146b2146cc9cf7a012342692142?short_path=9ccc7a6) and could do with a new lick of paint. This is an app I use every day so will get that sorted myself.

**Comment by Foggalong** [comment]
As an aside, I would love to know if there are any icons which are still using their original symbol design (allowing for resizing but nothing else) from [8 years ago](https://github.com/cldx/numix/tree/ba7eab1e512031f879f50e25c7bcc00ffa76cac2/apps/48). The theme has changed a lot since then but I'd bet money on there being at least one such app.

**Comment by palob** [comment]
You mean those monochrome designs?

**Comment by Foggalong** [comment]
I mean specifically if there are any icons still in the theme which are still using the original white monochrome symbol from the initial commit for Numix.

They'd all monochrome because the original Numix app theme (which was since renamed Shine) had monochrome symbols. There are some monochrome icons though (like Zotero) which were added _after_ that initial commit.
