### ISSUE TITLE
Software centre icon redesign

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#5601]
The current symbl design looks like this (I take it it is a shopping bag, or is it a tag?)

![center-before](https://user-images.githubusercontent.com/7050624/95128920-723d4080-075a-11eb-8c1d-bcc401e01ad1.png)

It has the sides bent inwards by less than 1px, hence looks blurry and the symbol size is a bit big.

Now before I go through all our icons using this design, do you like something like this any better?
![center-later1](https://user-images.githubusercontent.com/7050624/95129224-fee7fe80-075a-11eb-9d89-3c2292bf0f92.png)

![center-later2](https://user-images.githubusercontent.com/7050624/95129184-ed9ef200-075a-11eb-95e2-912e6a8b7e62.png)

**Comment by palob** [comment]
@Foggalong Any inclination?

**Comment by Foggalong** [comment]
Design 2 is brilliant, I love the paper bag design!
