### ISSUE TITLE
New xfce4-screensaver icon name.

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-core#5623]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `xfce4-screensaver`| `org.xfce.ScreenSaver` | `xfce4-screensaver-preferences.desktop` | ![original](https://raw.githubusercontent.com/xfce-mirror/xfce4-screensaver/master/data/icons/48x48/org.xfce.ScreenSaver.png) |

Description: `Screensaver application for Xfce Desktop`

Website: `https://xfce.org`

Version 0.1.11 uses new icons with rDNS icon name: org.xfce.ScreenSaver

**Comment by palob** [comment]
Thank you, browsing through their git instance I noticed a few more Xfce apps will have their icon names renamed.

**Comment by darkshram** [comment]
Most (if not all) of their apps will use rDNS for the future 1.16 release. As today, xfce4-screensaver and xfce4-dict are the only applications for current stable release that use rDNS for icon names.

Should I fill a new issue for **org.xfce.Dictionary.png** or it's enough with the info mentioned here?

**Comment by palob** [comment]
Enough, I don't think we'll need to do new icons, it's just a matter of symlinks I'm preparing right now.
