### ISSUE TITLE
TexStudio Icon not distinguishable

### ISSUE THREAD

**Issue by gilbertohasnofb** [numixproject/numix-core#5635]
TeXStudio icon has a light background with white text, which is not so discernible.

texiconissue
![image](https://user-images.githubusercontent.com/5700795/99812833-d4050e80-2b3e-11eb-8529-8c7e50c22a6b.png)

The TeXStudio icon between InkScape and GIMP on a unity launcher

(this is a repost of https://github.com/numixproject/numix-icon-theme-circle/issues/29 which the original author posed in the Numix Circle repository but was asked to post it here instead and never followed through)

**Comment by palob** [comment]
After revisiting #5341 earlier this week, I think I'll look into redesigning all existing icons featuring the TEX letters. The pixel grid non-alignment is really bad.
