### ISSUE TITLE
Redshift

### ISSUE THREAD

**Issue by fleamour** [numixproject/numix-core#5641]
|Night Colour Control| Redshift | redshift-status-on.svg | file:///usr/share/icons/breeze/status/24/redshift-status-on.svg |
| --- | :-- | :-- | :-- |
| `APPLICATION NAME`| `ICON NAME` | `DESKTOP FILE NAME` | ![original](https://cloud.githubusercontent.com/assets/5920259/25233502/e8d0afd4-25d6-11e7-9182-b4102e40ae5a.png) |

Description: KDE Night Colour Control

Bear with the janky report, I am **_VERY_** trying. The dark style icon has been missing forever from openSUSE Tumbleweed, finally reported!

![Screenshot_20201129_152323](https://user-images.githubusercontent.com/2966405/100546365-f0006280-3258-11eb-83ea-3427aa152401.png)

**Comment by palob** [comment]
So this is about a status icon? Could you please report this in our base theme repo? https://github.com/numixproject/numix-icon-theme

**Comment by fleamour** [comment]
Hi
You may close this bug, I believe I just needed to install numix-icon-theme under experimental Tumbleweed repo. Not sure if this always been available, but I was point blank told this yonks ago & did not grok.

**Comment by palob** [comment]
So the issue is about that bulb icon being white instead of black? And it's solved now?

**Comment by fleamour** [comment]
Copying icon from Breeze to Numix Circle in usr/share/icons folder solved issue. But I think installing numix-icon-theme (base theme?) from repo would also solve. So this may be not a bug.

**Comment by palob** [comment]
Yeah, numix-icon-theme (it is the base theme indeed, Circle/Square only contain app icons) is a hard prerequisite for a functional theme.
