### ISSUE TITLE
Recommendation: VS Code

### ISSUE THREAD

**Issue by Mortadelas** [numixproject/numix-core#5647]
| Visual Studio Code | Icon is [here]( https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F9%2F9a%2FVisual_Studio_Code_1.35_icon.svg%2F1200px-Visual_Studio_Code_1.35_icon.svg.png&f=1&nofb=1) |
Description: Open-source text editor made by Microsoft

Website: https://code.visualstudio.com/

**Comment by palob** [comment]
Hi, we need to know the exact icon name found in the respective ``.desktop`` file in order to help you.

**Comment by palob** [comment]
Closed due to missing information.
