### ISSUE TITLE
Icon Request: Lens

### ISSUE THREAD

**Issue by ogarcia** [numixproject/numix-core#5664]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Lens`| `kontena-lens` | `lens.desktop` | ![original](https://github.com/lensapp/lens/raw/master/build/icons/512x512.png) |

Description: The Kubernetes IDE. Lens provides the full situational awareness for everything that runs in Kubernetes. It's lowering the barrier of entry for people just getting started and radically improving productivity for people with more experience.

Website: https://k8slens.dev/

GitHub: https://github.com/lensapp/lens

SVG Icon: https://github.com/lensapp/lens/blob/3bc45218c19fe67fbfb50f70c841bf09c3bee78f/docs/img/lens-logo-icon.svg

**Comment by palob** [comment]
Fixed.
