### ISSUE TITLE
 Icon Request: Steam Link

### ISSUE THREAD

**Issue by solbero** [numixproject/numix-core#5706]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Steam Link`| `com.valvesoftware.SteamLink` | `com.valvesoftware.SteamLink.desktop` | ![original](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/com.valvesoftware.SteamLink.png) |

Description: Steam Link is a solution for extending your Steam games library to any room of the house via your home network.

Website: [About Steam Link](https://store.steampowered.com/steamlink/about/) and [Steam Link Flathub](https://flathub.org/apps/details/com.valvesoftware.SteamLink)

**Comment by really-need-an-api-key** [comment]
Is something like this okay, or should I remove the inner circle?
![circle-com valvesoftware SteamLink](https://user-images.githubusercontent.com/11636003/111864835-96d15180-8963-11eb-99a6-b561cede6009.png)
![square-com valvesoftware SteamLink](https://user-images.githubusercontent.com/11636003/111864800-64275900-8963-11eb-92b0-987bdeee74fd.png)

**Comment by palob** [comment]
It's alright.
