### ISSUE TITLE
Dialect

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#5717]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Dialect`| `com.github.gi_lom.dialect` | `com.github.gi_lom.dialect` | ![com github gi_lom dialect](https://user-images.githubusercontent.com/7804464/113912951-06589500-97dc-11eb-9853-846c543e6f8b.png) |

https://github.com/gi-lom/dialect/blob/main/data/com.github.gi_lom.dialect.svg

Description: A translation app for GTK environments based on Google Translate.

Website: https://github.com/gi-lom/dialect/

**Comment by palob** [comment]
Hi, I implemented a lazy fix via symlink to our google-translate icon (which this app is a frontend to) in #5595.
