### ISSUE TITLE
Element

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-core#5719]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Element`| `element-desktop` `im.riot.Riot` | `element-desktop` `im.riot.Riot` | ![im riot Riot](https://user-images.githubusercontent.com/7804464/113999998-dc928300-985a-11eb-8517-549170fb7f9d.png) |

https://github.com/vector-im/element-web/blob/develop/res/welcome/images/logo.svg

Description: Create, share, communicate, chat and call securely, and bridge to other apps.

Website: https://element.io/

**Comment by palob** [comment]
Should be fixed in master (not released yet). ``im.riot.Riot`` is linked to the old Riot icon though.

**Comment by gregorydk** [comment]
Please make `im.riot.Riot` a symlink to `element-desktop` because that name and icon name is still used by the flatpak-app.

```
Element - Create, share, communicate, chat and call securely, and bridge to
other apps

          ID: im.riot.Riot
         Ref: app/im.riot.Riot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.7.24
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 255,2 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: ab6de650f31cf6b9a3548c960f8f661c19bf33a6f1bcd65a4c4797246edbd8e7
      Parent: 8cfc6c787dcd4b324e4aaa162d3c0c09355b1a1f2f3e44137d750f716861a87a
     Subject: Update element-desktop_1.7.23_amd64.deb to 1.7.24 (cb13b3df)
        Date: 2021-03-29 15:03:59 +0000
```
