### ISSUE TITLE
Flatpak version of Joplin is not themed

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-core#5733]
All my Flatpak apps are themed except Joplin; even though Numix has that icon available.

**Comment by ghost** [comment]
Sure! It is `net.cozic.joplin_desktop`

Sorry for the trouble!

**Comment by palob** [comment]
Could you please look up the ``Icon=`` line inside this file?

**Comment by Foggalong** [comment]
@palob [That would seem to be it!](https://github.com/flathub/net.cozic.joplin_desktop/blob/084e37fe74cd533245af793e21595c1754aae819/net.cozic.joplin_desktop.desktop#L6)

**Comment by palob** [comment]
We've got this as well so the outdated Ubuntu package is the culprit again, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/139#.
Must have forgotten that we are in the Debian/Ubuntu repos btw.
