### ISSUE TITLE
Icon change proposal: circle: qalculate

### ISSUE THREAD

**Issue by gruenfron** [numixproject/numix-core#5734]
| Application name | Original icon | Current circle icon | Proposed circle icon |
| --- | :-- | :-- | :-- |
| `Qalculate!`| <img src="https://raw.githubusercontent.com/Qalculate/qalculate-gtk/67700021653ab72e5c3867eeea990fc91feb80af/data/icons/scalable/qalculate.svg" width=120 height=120> | <img src="https://raw.githubusercontent.com/numixproject/numix-core/3a6e68ac455726fd49227a595fed75add62ad910/icons/circle/48/qalculate.svg" width=120 height=120> | <img src="https://raw.githubusercontent.com/gruenfron/numix-icon-proposals/5d5aa052fbaa63d40f724a746045c447884e1f8f/circle/qalculate.svg" width=120 height=120> |

Description: The current Qalculate! circle icon is IMHO a bit far away from the original design. Is there a chance to get this replaced by this proposal and is a fork and pull request required then?

Thanks for the awesome circle theme.

**Comment by palob** [comment]
Yes, fork and PR is the way to go for contributions. I'm looking forward to it.
In general we are more and more departing from full-baseplate designs like this one(preferring symbol-on-baseplate designs), however this looks in line with the current generic calculator icon.

To mtch the styling of the generic icon the font used for the **x** and omega should probably be simpler, composed of primitive circle parts and rectangles.

**Comment by palob** [comment]
Fixed quite some time ago.
