### ISSUE TITLE
Nemo icon changed last week

### ISSUE THREAD

**Issue by lapega** [numixproject/numix-core#5743]
Since last week, the Nemo icon change to the square one.
I made a symbolic link to Nautilus one, but nothing change (icon cache cleared, machine rebooted, etc.)

![Captura de pantalla de 2021-07-19 09-42-41](https://user-images.githubusercontent.com/572502/126161414-5c5c37eb-c33b-422b-a5c2-faf6bf9c5193.png)

**Comment by Foggalong** [comment]
This isn't the "square" Numix icon, this is the folder icon from the [base theme](https://github.com/numixproject/numix-icon-theme). Can you tell us the icon name from Nemo's `.desktop` file? It'll probably be in `/usr/share/applications/`

**Comment by lapega** [comment]
Hi, thanks for the response.
The nemo.desktop puts
Icon=folder

**Comment by lapega** [comment]
Changed that line to Icon=nemo and works.

Thank you!!!!
