### ISSUE TITLE
Automated Travis build stopped working

### ISSUE THREAD

**Issue by palob** [numixproject/numix-core#5744]
According to
https://travis-ci.org/github/numixproject/numix-core
migration to travis-ci.com is needed.

**Comment by Foggalong** [comment]
Completed the migration just now! Ran the first test build [failed](https://travis-ci.com/github/numixproject/numix-core/jobs/531249962) because fbab23fe5928a6d14c216c7e166cf969d47b720c inadvertently added the old Skype keys back (but didn't remove the new ones which is why it probably didn't get caught). Triggered a new build which [passed](https://travis-ci.com/github/numixproject/numix-core/builds/235285273) so I think we're all good :+1:

**Comment by Foggalong** [comment]
As a side note though, we _maaaaay_ need to either change how Travis builds work or find another provider long term. Under Travis' new free plan we only get 1,000 free builds before we have to start paying which given Numix no longer has an income is a no :eyes:

**Comment by palob** [comment]
Is it an absolute limit or time-based, like1000 per week/month/year or something?

For Numic I think a big selling point of automated builds is those per-commit builds in unmerged PRs.

If we had to change to builds on a daily/weekly schedule (ideally no builds in time without repo activity) or to manually triggered builds would this leave us with any big advantages compared to just getting the same output by running ``gen.py`` locally from time to time?

**Comment by Foggalong** [comment]
It's an absolute limit (needing to purchase more when used) with a bunch of weird [caveat](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source) that I'd not noticed.

![Screenshot from 2021-08-13 19-34-05](https://user-images.githubusercontent.com/5920259/129403918-e17a7615-832b-4053-8558-c7716f347998.png)

The TLDR is that the paid plans come with a set amount of "bonus credits" which can be used on OSS projects, but it's also possible for anyone on any plan to request a "credit allowance" for use on OSS projects on an as-needed basis. With that in mind it might be worth us leaving it as is until there's ~100 builds left and using that to work out how frequently we're getting through "credits" and then request an amount accordingly.

I agree with your latter two points too; if the "allowance" doesn't work out and we can't find a replacement service, I'd be happy to just leave it as doing the tests manually periodically.

**Comment by palob** [comment]
Looks like we've run out of free builds right now.
