### ISSUE TITLE
Icon for MultiMC?

### ISSUE THREAD

**Issue by someones-alt** [numixproject/numix-core#5749]
It looks ugly by default, and I think enough people use it to make an icon

**Comment by Foggalong** [comment]
Please add the information set out in the readme and issue template, we can't fix otherwise :)

**Comment by Foggalong** [comment]
We do already have [MultiMC covered](https://github.com/numixproject/numix-core/blob/master/data.json#L15507-L15514) so this'll probably just be a missing symlink. If you let us know the icon name we'll reopen the issue and get that covered
