### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-core#5751]
- **Name:** Microsoft Edge
- **Description:**: Web browser by Microsoft
- **Website:** https://www.microsoftedgeinsider.com/en-us/
- **Icon Name:** `ms-edge`
- **Symlinks:** `Edge`,`microsoft-edge`, `microsoft-edge-beta`,`com.microsoft.Edge`
- **Desktop File:** `microsoft-edge-beta.desktop`
- **Original Icon:**

![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Microsoft_Edge_logo_%282019%29.svg/240px-Microsoft_Edge_logo_%282019%29.svg.png)

Credit to [Arjun](mailto:arjun6280414@gmail.com) for reporting this issue via email.

**Comment by Foggalong** [comment]
There's technically a separate icon for the beta release (the only one currently supporting Linux), but it's just this with "beta" written in the bottom left. For now at least I think we can just use the same icon for all three.

**Comment by palob** [comment]
``com.microsoft.Edge`` is the Flatpak icon name.
