### ISSUE TITLE
Numix Square - Asymmetric Discord Logo

### ISSUE THREAD

**Issue by MV525** [numixproject/numix-core#5754]
The Discord and Discord Canary logos are asymmetric. I noticed this when comparing the logos with the icons present in the circle set of themes.

**Comment by MV525** [comment]
Changed the title just so it's easier to understand what this issue is for at a glance.

**Comment by mrmeszaros** [comment]
To be fair, the circle logos aren't symmetric either, but at least the look convincing:

![discord circle 960](https://user-images.githubusercontent.com/15245298/196817396-ca114e7c-660d-432f-8157-3e7f40133e10.png)

The black outline is mirrored and so You can see that is is a tad bit asymmetric.
Question is, is it necessary to make the symbol fully symmetric (and fix circle too)?

**Comment by palob** [comment]
It's worthwhile in case there are other design shortcomings to fix like misalignments. I've just checked and found their logo doesn't look like this no more.

**Comment by mrmeszaros** [comment]
Okay, so I found the new logo svg path on the web-page (red) - scaled it to the size of the current one (white) and created an aligned half (blue).

![discord-update](https://user-images.githubusercontent.com/15245298/196957961-11b7e5c6-2ec0-4416-aafe-9b331e6a4f88.png)

Might need some more work, so please feel free to make comments and express your remarks!
(like the eyes might need to go 1 px higher)

Also, if You think I can do a PR in this state and then You can play with it on Your end too.

**Comment by palob** [comment]
I don't see anything left to be desired :+1: 
Eyes can be 1px wider and/or moved 1px up but that's up to you, what you think looks best.
