### ISSUE TITLE
Dropbox update request

### ISSUE THREAD

**Issue by MarvinDjd** [numixproject/numix-core#5769]
App name: `DROPBOX`, `https://www.dropbox.com/`

 Icon name: `com.dropbox.Client`

![original](https://cloud.githubusercontent.com/assets/5920259/25233502/e8d0afd4-25d6-11e7-9182-b4102e40ae5a.png)

Description: `PROVIDE A FILES MANAGER PLUGIN FOR FILES SAVED ON DROPBOX`
![Bildschirmfoto vom 2021-11-28 00-34-58](https://user-images.githubusercontent.com/95150565/143723442-a0cb9adf-4594-4ac2-987b-d2f165f7c39e.png)

The old icon is the light one which is terribly outdated, therefor asking for an update
![Bildschirmfoto vom 2021-11-28 00-39-58](https://user-images.githubusercontent.com/95150565/143723531-cd4972da-4a98-4556-9f3d-971d0e962468.png).

**Comment by mrmeszaros** [comment]
Hey, here are two candidates (couldn't decide between the two sizes :|):

![dropbox circle 192 a](https://user-images.githubusercontent.com/15245298/196217315-1d791560-6d14-4a7b-bda1-d7c7d4ffc5bd.png) ![dropbox circle 192 b](https://user-images.githubusercontent.com/15245298/196217367-e9317a26-9c3d-42a2-abee-b7db6ae5ca60.png)

What do You think design wise?

**Comment by palob** [comment]
"From distance" without comparing it with existing icons the right one looks big to me but if it fits well into a 26x26 square it might be fine.

**Comment by mrmeszaros** [comment]
The first (A) fits into 24x24,
the second (B) into 26x26.

I prefer A, but B is more similar in size to the "old".
Also A aligns better in tiny (24x24) render:

| A | B |
|--|--|
| ![dropbox circle 24 a](https://user-images.githubusercontent.com/15245298/196444978-b66a7dc3-17a2-4c80-9bcd-f8b294207aa1.png) | ![dropbox circle 24 b](https://user-images.githubusercontent.com/15245298/196445014-11fc9966-3383-4d8d-907d-d0037bd72a63.png) |
| ![dropbox circle 48 a](https://user-images.githubusercontent.com/15245298/196446364-dc089a20-5be2-4079-9180-6140bcfaa56e.png) | ![dropbox circle 48 b](https://user-images.githubusercontent.com/15245298/196446695-0c115624-3227-47df-866d-5562c840f6fb.png) |

In 48 and up there is no difference, maybe even B is better.

**Comment by palob** [comment]
In the upper row I think B is actually more recognisable at the cost of the more pronounced (actually non-existant) " rhomb connectors" in the bottom row. Both seems perfectly mergeable though.
