### ISSUE TITLE
Zoom Icon?

### ISSUE THREAD

**Issue by MintMain21** [numixproject/numix-core#5772]
Only now realizing that (on Linux Mint 20.3) there's no icon for Zoom. Not that the default Zoom Icon is bad, but it's square shaped, which contrasts hard with similar programs like Discord and Whatsapp that DO have icons in the Numix Circle Collection.

Edit: After using some Duck-Fu, I found this: https://cae.appstate.edu/sites/default/files/styles/asu_news_full/public/asu_news/zoom-logo_0.png?itok=A25Jffoo A png of the Zoom Logo as a circular icon.

I can manually change the menu entry to use this icon, yes, but the absence of this by default in the collection seems even more goofy knowing that a variant of the logo appropriate for the theme already exists.

**Comment by Foggalong** [comment]
I can't seem to replicate this issue, @MintMain21 where did you install Zoom from?

**Comment by MintMain21** [comment]
The Deb Package on the official Zoom Website. https://zoom.us/download

**Comment by Foggalong** [comment]
@MintMain21 Could you provide the details @palob asked for? Will help us work out what's going on :slightly_smiling_face:

**Comment by MintMain21** [comment]
Sorry. I should've done that before, but I didn't. 

Okay, in usr/share/applications, I found the Zoom Launcher. It was created December 23rd, which I believe was when I uninstalled the flatpak and installed the .deb package from the Zoom website. Opening that launcher in a text editor, I see the following:

[Desktop Entry]
Name=Zoom
Comment=Zoom Video Conference
Exec=/usr/bin/zoom %U
Icon=Zoom
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Network;Application;
StartupWMClass=zoom
MimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;application/x-zoom
X-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall;
Name[en_US]=Zoom

I followed the trail to usr/bin/zoom, which in turn led me to /opt/zoom/ZoomLauncher. I hope this is helpful.

**Comment by MintMain21** [comment]
![image](https://user-images.githubusercontent.com/91362684/149577777-e7aeb910-4393-42f5-a8d3-2206a26aeaa9.png)


As you can see, the image seems to be the default Zoom Icon. If there is a Zoom Icon in the Numix Circle Theme Pack, it is not overriding the default.

**Comment by MintMain21** [comment]
And again, for the record, I'm using the version in the Mint Repo. I can try this PPA: https://launchpad.net/~numix/+archive/ubuntu/ppa , which I understand is one version ahead.

**Comment by palob** [comment]
That's strange. When I download that ``19.12.27+202201101933`` package, a ``Zoom.svg``is included.
Are you sure you've got the latest version of Numix Circle?

What happens when you click on the icon in that *Edit Launcher* dialog box? Any path shown?

**Comment by MintMain21** [comment]
On Linux Mint, the icon is classified as "uncatagorized". When I search for a Zoom icon, without opening the file-system itself, what I get is the following: 
![image](https://user-images.githubusercontent.com/91362684/149603675-5958a21a-24ed-4131-9d59-69e3675ad198.png)

**Comment by MintMain21** [comment]
Like I said, I'm using the latest version of the Circle theme in the Mint Repo. I can upgrade to the version in the PPA if necessary.

**Comment by palob** [comment]
Can you please search for ``Zoom`` inside ``usr/share/icons/Numix-Circle``?

**Comment by MintMain21** [comment]
![image](https://user-images.githubusercontent.com/91362684/149603816-ffb6906f-1818-4d51-bf0b-749e17f4d013.png)

**Comment by palob** [comment]
So you are probably using an ancient version of Numix Circle.

**Comment by palob** [comment]
Ah OK, Mint repo. So this is not surprising given that Mint is a "sta(b)le" / LTS / frozen repo distro. Packages aren't updated apart from security backports.
I' definitely recommend the PPA.
