### ISSUE TITLE
Icon Request: Lens IDE for Kubernetes

### ISSUE THREAD

**Issue by lud0v1c** [numixproject/numix-core#5773]
App name: `Lens`, ![Official Github Repo](https://github.com/lensapp/lens)

Icon name: `lens`

Desktop filename: `lens.desktop`

Original icon:

![original](https://user-images.githubusercontent.com/9108633/150690972-eba0adc2-b722-424b-acd0-75e6ccbc4fb1.png)

Description: An IDE just for Kubernetes, with automatic detection of kubeconfig files, multiple cluster management and even remote/team features.

**Comment by lud0v1c** [comment]
Looks like it already exists, but it's not properly detected by Ubuntu 20/Gnome.

**Comment by palob** [comment]
Are you using the package from the Ubuntu repos? It's severely outdated so I'd recommend using the PPA.

**Comment by lud0v1c** [comment]
Yes @palob that was it, thank you.
