### ISSUE TITLE
intelliJ icon is not rounded

### ISSUE THREAD

**Issue by dipanshparmar** [numixproject/numix-core#5776]
![image](https://user-images.githubusercontent.com/49204837/152895358-caf1778b-6e84-4729-8aae-a31742b26aac.png)

**Comment by palob** [comment]
Hi, please add the ``Icon=`` line from the respective ``.desktop`` launcher file. Otherwise we can't help you.

**Comment by dipanshparmar** [comment]
App name: `intelliJ Idea`, `https://www.jetbrains.com/idea/`


Icon name: `/home/dipansh/Softwares/intelliJ/bin/idea.svg`


Desktop filename: `jetbrains-idea-ce.desktop`


Original icon:
![image](https://user-images.githubusercontent.com/49204837/152900645-0e294a31-81e4-4664-bc90-ddbc63de6be8.png)



Description: `It's a Java IDE`

**Comment by palob** [comment]
That mean the icon file is hardcoded. You need to edit the ``.desktop`` file manually in order for the Numix icon to show up.

Copy the launcher file to ``~/.local/share/applications`` (if not already there) and edit the icon line to ``Icon=intellij``.

**Comment by dipanshparmar** [comment]
@palob Thank you :)
