### ISSUE TITLE
Icon request: Outline Client 

### ISSUE THREAD

**Issue by ingria** [numixproject/numix-core#5781]
**App name:**
`Outline`, [wiki](https://en.wikipedia.org/wiki/Outline_VPN), [website](https://getoutline.org/), [github](https://github.com/Jigsaw-Code/outline-client)

**Icon name:**
`outline-client`

**Desktop filename:**
`outline-client.desktop`

**Original icon:**

|  Manager | Client |
| ------------- | ------------- |
|  <img src="https://user-images.githubusercontent.com/2178368/158916442-fa8531f2-9505-4572-9faf-7a14a36347c8.png" width="128"> | <img src="https://user-images.githubusercontent.com/2178368/158916440-5ed5b487-87d3-4a9f-8820-8ff081952a5f.png" width="128"> |

**Description:**
The Outline Client is a cross-platform VPN or proxy client for Windows, macOS, iOS, Android, and ChromeOS.

**Comment by ingria** [comment]
There's already an [icon for outline-manager](https://github.com/numixproject/numix-core/blob/ab4ee0870d145652f80a0d4df19ac950b35a2cfd/icons/circle/48/outline-manager.svg). I've made a draft so that they are both in the same style:

<img src="https://user-images.githubusercontent.com/2178368/158917130-defb7247-eed1-41c2-ac70-8094abde5848.svg" width="512"/>

**Comment by palob** [comment]
@ingria Can you please open a pull request for review? We don't do gradients on symbols anymore so these need to go I'm afraid. What is more there are no gradients on the original icons as far as I can see. The left symbol looks a bit too big.
