### ISSUE TITLE
Amberol not applying 

### ISSUE THREAD

**Issue by astro-ray** [numixproject/numix-core#5799]
The icon theme doesn't apply the icon for amberol
![Screenshot from 2022-10-04 18-33-18](https://user-images.githubusercontent.com/69363775/194024881-829773cd-890b-4782-8149-aefe9d0c002e.png)
I know there is an amberol icon as I have seen it, but it's not present here
![Screenshot from 2022-10-04 18-55-57](https://user-images.githubusercontent.com/69363775/194024785-bbf96439-62a9-457f-b073-66b399b44bc8.png)

**Comment by Foggalong** [comment]
@ritamsaha00 Can you give us the information set out in the readme, it's probably just a package which uses a different icon name

**Comment by palob** [comment]
Our latest release (same for a few releases back) definitely has got an icon named ``amberol`` (and also an icon for Black Box) so you probably are using an older version.

**Comment by palob** [comment]
@ritamsaha00 Noticed you gave a :+1: . Does the issue persist with the latest release?

**Comment by astro-ray** [comment]
I installed the icon theme from the ubuntu repository, so it might be that the repo is still not up to date. But the problem isn't exactly gone.

**Comment by palob** [comment]
On Ubuntu you can use the PPA https://launchpad.net/~numix/+archive/ubuntu/ppa for regular updates or install manually.
