### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by saltedcoffii** [numixproject/numix-core#5818]
App name: `Snapchat` `web.snapchat.com`

Icon name: `snapchat`, `snapchat-nativefier`

Desktop filename: `snapchat-nativefier.desktop`

Original icon: https://en.wikipedia.org/wiki/File:Snapchat_logo.svg

Description: Snapchat now offers a web service on web.snapchat.com. I've put together a `nativefier` app for arch linux and others at https://aur.archlinux.org/packages/snapchat-nativefier.

**Comment by saltedcoffii** [comment]
@palob you added a symlink from `snapchat` to `snapchat-nativefier`, but there's no actual `snapchat` icon in the first place. Reopen?

**Comment by palob** [comment]
There will be (once the next release is out). Otherwise it wouldn't have passed the CI tests.
