### ISSUE TITLE
Lichess icon doesn't look like the official lichess icon at all

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#5831]
## Info

Platform: web

Related Software: lichess.org

## Affected Icons

- [x] lichess
- [x] lichesslogowhite

## Problem

The official lichess logo looks like this:

[![official lichess logo](https://user-images.githubusercontent.com/11488886/222875325-5ff41a81-6ded-47a0-ac39-1f1cbdd38b2b.png)](https://images.prismic.io/lichess/5cfd2630-2a8f-4fa9-8f78-04c2d9f0e5fe_lichess-box-1024.png?auto=compress,format)

Whilst the current numix `lichess` icon looks like this:

![numix lichess](https://user-images.githubusercontent.com/11488886/222875417-97ba423a-9992-4659-975c-110a92c7f39e.png)

## To Reproduce

1. DO THIS
2. THEN THAT
3. ???
4. BUG

**Comment by palob** [comment]
Maybe linking to ``knights.svg`` instead?

**Comment by KSXGitHub** [comment]
The lichess icon is inspired by the knight piece, but it's not literally the knight. I think the proper thing to do is to adopt Lichess's official logo in the icon, but adapted to Numix style. Something like this (but with better color scheme and shading, ofc):

![lichess-template](https://user-images.githubusercontent.com/11488886/222894440-e46356eb-8d4b-40c2-8582-00cda6053c75.png)
