### ISSUE TITLE
[Icon Request] Add cs-gesture icon.

### ISSUE THREAD

**Issue by Initu-Castilhos** [numixproject/numix-core#5835]
App Name: cs-gesture
Icon Name: Gesture
Description: New function in Cinnamon 5.8 of gesture configuration.
Webpage (optional): https://github.com/linuxmint
Original Icon:
![248632947-609f43c4-68e0-42ab-be67-f936bf1b4ff6](https://github.com/numixproject/numix-core/assets/59381215/f9ee75d8-043c-4d93-a6fa-fca8b58574a1)

**Comment by palob** [comment]
As far as I can see the icon name is ``cs-gestures``, see https://github.com/linuxmint/cinnamon/blob/ae4523dd7d88b764bcaa0753389be6f91d964e6d/files/usr/share/applications/cinnamon-settings-gestures.desktop#L4

This is already present in the latest release. Which Numix Core/Square version are you using?

**Comment by Initu-Castilhos** [comment]
> Tanto quanto posso ver, o nome do ícone é `cs-gestures`, consulte [ https://github.com/linuxmint/cinnamon/blob/ae4523dd7d88b764bcaa0753389be6f91d964e6d/files/usr/share/applications/cinnamon-settings-gestures.desktop#L4 ](https://github.com/linuxmint/cinnamon/blob/ae4523dd7d88b764bcaa0753389be6f91d964e6d/files/usr/share/applications/cinnamon-settings-gestures.desktop#L4)
> 
> Isso já está presente na versão mais recente. Qual versão do Numix Core/Square você está usando?

Sorry! Had not checked.
