### ISSUE TITLE
Change icons: cs-tiling and preferences-dektop.

### ISSUE THREAD

**Issue by Initu-Castilhos** [numixproject/numix-core#5837]
The icon for preferences-desktop is the same as for preferences-system.
![Captura de tela de 2023-07-14 22-25-16](https://github.com/numixproject/numix-core/assets/59381215/e653aecd-d99f-4965-a787-ae5ce92ddcb9)
![Captura de tela de 2023-07-14 22-25-32](https://github.com/numixproject/numix-core/assets/59381215/ad75ef99-0ac5-4b97-ae65-a905879df69d)
![Captura de tela de 2023-07-14 22-26-10](https://github.com/numixproject/numix-core/assets/59381215/bfc0a50c-5b1c-4752-afdb-531faea490ea)

The icon for cs-tiling is the same as for cs-window.
![Captura de tela de 2023-07-14 22-26-43](https://github.com/numixproject/numix-core/assets/59381215/5e5a3494-507d-48ae-8549-b41d2511014a)
![Captura de tela de 2023-07-14 22-26-59](https://github.com/numixproject/numix-core/assets/59381215/56f6fa14-7e68-47d3-b425-ecc700d9e281)
 
In the base theme the preferences-desktop icon can be the same icon it has in the size of 32px as shown in the image below:
![Captura de tela de 2023-07-14 22-42-27](https://github.com/numixproject/numix-core/assets/59381215/869c7664-07db-40ab-bd72-8eb54bb7e47d)

**Comment by palob** [comment]
Could you please help me out as to what would be a fitting alternative?
What kind of settings is "Preferências" and "Administração" respectively?
What kind of settings is behind the icons ``cs-tiling`` and ``cs-window``?

Can you show the original icons?


I probably won't change anything in the base theme because it isn't meant to be used without Circle/Square.

**Comment by Initu-Castilhos** [comment]
> Could you please help me out as to what would be a fitting alternative? What kind of settings is "Preferências" and "Administração" respectively? What kind of settings is behind the icons `cs-tiling` and `cs-window`?
> 
> Can you show the original icons?
> 
> I probably won't change anything in the base theme because it isn't meant to be used without Circle/Square.

![preferences-desktop](https://github.com/numixproject/numix-core/assets/59381215/f046e3ef-93d4-4a4c-a62e-b1f7d7606903)
preferences-system

![preferences-system](https://github.com/numixproject/numix-core/assets/59381215/314e93f0-e5ec-485d-99e4-13f7c031e712)
preferences-desktop

![preferences-desktop](https://github.com/numixproject/numix-core/assets/59381215/a7eab5b4-21c9-48bb-b7e0-1abcf2dc9548)
Suggestion for preferences-desktop icon

![preferences-system](https://github.com/numixproject/numix-core/assets/59381215/ac1e6da9-a989-4879-8349-a71847cbe0b1)
preferences-system-circle

![preferences-desktop](https://github.com/numixproject/numix-core/assets/59381215/7e170878-cd5a-4335-a574-ff42c31e576e)
preferences-desktop-circle

![preferences-desktop](https://github.com/numixproject/numix-core/assets/59381215/b6df05b9-bd3e-4d60-8450-ab6b12c3031d)
Suggestion for preferences-desktop icon

![preferences-system](https://github.com/numixproject/numix-core/assets/59381215/e64b75f4-67ff-4323-85bd-f6e10f3375be)
preferences-system-square

![preferences-desktop](https://github.com/numixproject/numix-core/assets/59381215/d6f4021a-46ad-479b-b331-044b1214575e)
preferences-desktop-square

![preferences-desktop](https://github.com/numixproject/numix-core/assets/59381215/7a57557d-3f03-4715-b2df-c65bac709a44)
Suggestion for preferences-desktop icon

![cs-window](https://github.com/numixproject/numix-core/assets/59381215/7a46aef3-6c5b-41db-8f4c-cf31cfa06b1c)
cs-window-circle

![cs-tiling](https://github.com/numixproject/numix-core/assets/59381215/41bba77e-0d54-4b80-9755-e545dd02988c)
cs-tiling-circle

![cs-tiling](https://github.com/numixproject/numix-core/assets/59381215/2d519fed-8867-4d86-91b1-54450067d2be)
Suggestion for the cs-tiling icon

![cs-window](https://github.com/numixproject/numix-core/assets/59381215/b0f98676-427b-4fd4-8395-ed8e9eb4fa4e)
cs-window-square

![cs-tiling](https://github.com/numixproject/numix-core/assets/59381215/5bb54aba-c775-4b63-a979-18a63aa4de5e)
cs-tiling-square

![cs-tiling](https://github.com/numixproject/numix-core/assets/59381215/7aaf1ed4-f9cf-4852-95f4-c43aaeb187dd)
Suggestion for the cs-tiling icon

On top of the base icon, the subject icon is already used at a size of 32px as shown in the image below:
![Captura de tela de 2023-07-16 15-32-21](https://github.com/numixproject/numix-core/assets/59381215/d2f65daf-f97a-4942-986d-182e0b5be76d)

**Comment by palob** [comment]
Changed some symlinks. If I'm understanding the issue correctly there shouldn't be any duplicative preferences icons anymore in the next Numix Circle/Square release.

**Comment by palob** [comment]
The icons of the same name in the base theme should be removed maybe.

**Comment by palob** [comment]
New releases are out. Please check again.

**Comment by Initu-Castilhos** [comment]
> Saiu novos lançamentos. Por favor cheque novamente.

It's OK! Thanks!
