### ISSUE TITLE
Requesting icon

### ISSUE THREAD

**Issue by BaiqingL** [numixproject/numix-core#5839]
Not sure if this is the right place to submit requests? But it would be nice to add in an icon for lark suite, or feishu. I use it a lot on Linux and it would be a lot nicer if I can get a circle icon for it :)

**Comment by palob** [comment]
Hi, please add the original icon, the ``Icon=...`` line from the respective ``.desktop`` file and a link to the website/source code repo of the application.

**Comment by palob** [comment]
@BaiqingL Contributors or myself can't do anything here without information as pointed out above.

**Comment by palob** [comment]
Closed because not actionable. Feel free to reopen with additional information.

**Comment by BaiqingL** [comment]
> Hi, please add the original icon, the `Icon=...` line from the respective `.desktop` file and a link to the website/source code repo of the application.

Where should I place these files? Are there any templates I can follow? Thanks.

**Comment by palob** [comment]
You can find ``.desktop`` launcher files in either ``/usr/share/applications/``, ``~/.local/share/applications/`` or ``/var/lib/flatpak/exports/share/applications`` for Flatpaks.

Look up for the ``.desktop`` file belonging to the app in question, open it in a text editor and tell us the ``Icon=...`` line inside.

Assuming you found the file in ``/usr/share/applications/`` you can navigate back to ``/usr/share/`` and search for what comes behind ``Icon=`` in the file to find the icon.
