### ISSUE TITLE
[Icon request] Resources

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-core#5843]
App name: `Resources`, `https://github.com/nokyan/resources`

Icon name: `net.nokyan.Resources`

Desktop filename: `net.nokyan.Resources.desktop`

Original icon:

![original](https://raw.githubusercontent.com/nokyan/resources/bde509dccedf01b29d06622fa7c5c0cd96c9a284/data/icons/net.nokyan.Resources.svg)

Description: `Monitor your system resources and processes`

**Comment by palob** [comment]
There's a symlink in place already (unreleased) but leaving this open as enhancement request for a dedicated design.
