### ISSUE TITLE
Broken new Snap Store icon on Ubuntu 23.10

### ISSUE THREAD

**Issue by kaualandi** [numixproject/numix-core#5844]
After new Ubuntu update, the Snap Store was rewriter in Flutter and changed it's name to Applications Center.

The old icon is broken and now is:
![image](https://github.com/numixproject/numix-icon-theme-circle/assets/58404392/fdc65e85-b710-48ee-8ca7-754a042b2f6f)

![image](https://github.com/numixproject/numix-icon-theme-circle/assets/58404392/07acc957-9a2b-420b-88ad-139b35c79395)

**Comment by palob** [comment]
Hi, can you please look for the respective ``.desktop`` launcher file and the ``Icon=...`` line inside. We can't do anything without knowing the icon name.
What's your Numix Circle version? Maybe it's outdated.
