### ISSUE TITLE
No icons for snap applications and for Ubuntu 23.10 App Center

### ISSUE THREAD

**Issue by saveriob** [numixproject/numix-core#5848]
I installed Ubuntu 23.10 on a new machine, and Numix icons via the official ubuntu repository.
The icons of snap applications seem not to be affected: Firefox, Thunderbird, Morgen.
Also the icon of the App Center is not the correct one.

**Comment by palob** [comment]
Hi, we need the ``Icon=...`` lines from inside the respective ``.desktop`` launcher files in order for this to be actionable.
AFAIK, don't know if this has changed, snap apps have the icon path hardcoded in the launcher file which means the icons can't be themed without editing the launcher files.

**Comment by palob** [comment]
Closing because not actionable.
