### ISSUE TITLE
Icon Request: Mission Center

### ISSUE THREAD

**Issue by detherminal** [numixproject/numix-core#5852]
App name: `Mission Center`, [missioncenter.io](https://missioncenter.io)

Icon name: `io.missioncenter.MissionCenter`

Desktop filename: `io.missioncenter.MissionCenter.desktop`

Original icon:

![original](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/io.missioncenter.MissionCenter.png)

Description: `CPU, GPU, RAM, Disk etc. monitoring app. Looks awesome and is very fast. UI looks similar to Windows so it's handy.`

**Comment by palob** [comment]
I added a symlink for this, so this is somewhat fixed. The icon just doesn't look very similar. Changing this to "enhancement" for a dedicated icon.
