### ISSUE TITLE
Icon for lierolibre

### ISSUE THREAD

**Issue by KR4U7H3R** [numixproject/numix-core#5853]
App name: `lierolibre`, `(http://www.liero.be/)`

Icon name: `lierolibre`

Description: `Worms-like action game in real time`

Icon which is used on my system. It seems to be of the "hicolor" Icon pack
![lierolibre](https://github.com/numixproject/numix-core/assets/117851447/5c027204-f823-47e1-b76a-39eb45cad94b)

**Comment by Foggalong** [comment]
![Screenshot from 2024-02-13 19-21-36](https://github.com/numixproject/numix-core/assets/5920259/cfc9a92a-fa0f-47e8-99fc-81d2dd095d3a)
