### ISSUE TITLE
Surge XT Icon

### ISSUE THREAD

**Issue by Manunyo** [numixproject/numix-core#5855]
App name: `Surge XT`, `https://surge-synthesizer.github.io/`

Icon name: `surge-xt`

Desktop filename: `Surge-XT.desktop`

Original icon:
![surge-xt](https://github.com/numixproject/numix-core/assets/154324064/24d280f8-7eef-4a9c-921b-3d9c92ac2c5a)

Description: `Free Open Source Hybrid Synthesizer`

**Comment by palob** [comment]
Hi, this was added quite some time ago so your installation must be outdated. What's your distro and how did you install?

**Comment by Manunyo** [comment]
Thank you for getting back.
I 've just downloaded the latest Numix icon theme from github . Looking for the icons in the pack I realised that they have been misspelled as sturge-xt and sturge-xt-fx instead of surge-st. The icon for the flatpak ones seemed to be OK.
Kind regards

**Comment by Manunyo** [comment]
I realise i also misspelled....I meant surge-xt;;;lol

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by palob** [comment]
Oopsie, fixed in the repo, correct icons will be in the next release. Thanks for reporting and investigating.
