### ISSUE TITLE
S.T.A.L.K.E.R. trilogy icons

### ISSUE THREAD

**Issue by Supchik22** [numixproject/numix-core#5859]
Game names: 
S.T.A.L.K.E.R.: Shadow of Chornobyl
S.T.A.L.K.E.R.: Clear Sky
S.T.A.L.K.E.R.: Call of Pripyat

AppID: `4500` `20510` `41700`

Original icons:

S.T.A.L.K.E.R.: Shadow of Chornobyl
![original](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/4500/c57f5fdde74464aed0a09c2e5dd41f8973cbee8d.jpg)
S.T.A.L.K.E.R.: Clear Sky
![original](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/20510/82713e11a93dcbdbb0e1158b2e289720000bed3c.jpg)
S.T.A.L.K.E.R.: Call of Pripyat
![original](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/41700/60b32d190ebcaac8d2b2aaf16db2b07015616eb2.jpg)

Description: S.T.A.L.K.E.R. is a first-person-shooter survival horror video game franchise developed by Ukrainian game developer GSC Game World. The series is set in an alternate version of the present-day Chernobyl Exclusion Zone in Ukraine, where, according to the series' backstory, a mysterious second Chernobyl disaster took place in 2006. As a result, the physical, chemical, and biological processes in the area were altered, spawning numerous nature-defying anomalies, artifacts, and mutants. The player takes the role of a "stalker" - a name given to trespassers and adventurers who have come to explore the exclusion zone and its strange phenomena.

Icons I made:
![image](https://github.com/numixproject/numix-core/assets/71217534/c8f9db86-bc57-49d0-928c-1b566246ea40)
[stalker.zip](https://github.com/user-attachments/files/15538746/stalker.zip)

**Comment by palob** [comment]
Hi, thanks for your icon proposals. It is only now that I noticed them. I had to simplify them a bit to make them fit into the existing icons.
