### ISSUE TITLE
Weird message when updating numix-icon-theme-circle package

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-core#639]
Hey, guys.

I've noticed this weird message every time Numix Circle is updated from PPA:

Unpacking numix-icon-theme-circle (0.2+201404230017~417~ubuntu14.04.1) over (0.2+201404212146~416~ubuntu14.04.1) ...
gtk-update-icon-cache-3.0: The generated cache was invalid.
WARNING: icon cache generation failed for /usr/share/icons/Numix-Circle
Setting up numix-icon-theme-circle (0.2+201404230017~417~ubuntu14.04.1) ...

Is anything wrong here? Do I have to worry about it? Am I supposed to do anything here? If so, please, let me know what to do.

Thanks, guys.

brunces

**Comment by 3vi1** [comment]
Just an FYI that this is still present:

```
Unpacking numix-icon-theme-circle (1.0.2+3~201502071452~ubuntu15.04.1) over (1.0.2+2~201501241939~ubuntu15.04.1) ...
gtk-update-icon-cache-3.0: The generated cache was invalid.
```

**Comment by inizan-yannick** [comment]
still present:

```
Paramétrage de numix-icon-theme (0.3+403~201506012031~ubuntu15.04.1) ...
gtk-update-icon-cache: Cache file created successfully.
Paramétrage de numix-icon-theme-circle (1.0.2+3~201502071452~ubuntu15.04.1) ...
gtk-update-icon-cache: The generated cache was invalid.
```

**Comment by Foggalong** [comment]
Did you run apt-get update before installing? This issue was fixed months ago now :(

**Comment by inizan-yannick** [comment]
yes, packages installed from the PPA : https://launchpad.net/~numix/+archive/ubuntu/ppa

**Comment by Foggalong** [comment]
^ @PaoloRotolo @satya164 ^

**Comment by satya164** [comment]
This happens when icon names have spaces.  'i don't think we can do anything about that. It's safe to ignore.

**Comment by Foggalong** [comment]
We don't have any more icon names with spaces though :/

**Comment by Lippdo** [comment]
Also having this, after a fresh download from the PPA. (Running Ubuntu 15.04 & Gnome 3.16)

Problem appeared after I updated my Shell from 3.14. 

AND (maybe it's related) the wrong Google Chrome Icon is displayed for the running application. As a favorite in the dash and search it shows the correct icon.
