### ISSUE TITLE
Icon for Postman (Chrome Web App)

### ISSUE THREAD

**Issue by JesseFarebro** [numixproject/numix-core#682]
An icon for Postman is missing.

Web Store link: https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en

Icon: chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default
Image: ![screenshot from 2014-05-04 17 51 51](https://cloud.githubusercontent.com/assets/1377567/2874412/147135c2-d3e7-11e3-9a84-8d2f98fccccd.png)

**Comment by GuilhermeGoncalves** [comment]
That is old. The new official icon is 
![image](https://cloud.githubusercontent.com/assets/5985312/14820003/07e20c4e-0b9b-11e6-9a0e-95308a7ec0c2.png)
