### ISSUE TITLE
Icon for JDownloader

### ISSUE THREAD

**Issue by drazgo** [numixproject/numix-core#693]
A numix-circle icon for Jdownloader is missing
Icon line says "/home/user/.jdownloader/.install4j/JDownloader2.png"
Original icon is attached.

![i4j_extf_4_69g5ss_yklgyb](https://cloud.githubusercontent.com/assets/7521739/2913718/5c458e92-d690-11e3-9a98-2b87ff258b97.png)

**Comment by elridion** [comment]
Ive installed numix recently and have the same issue.
Tried this fixed but no changes.

Is there some way to get this to work?

**Comment by Foggalong** [comment]
It's just a case of either using the hardcode fixer (mentioned in the README) or changing the name on the icon line :)

**Comment by elridion** [comment]
Okay, so I’ve checked the supported applications for the hardcode fixer.
Since the JDownloader2 eg the 1 aren’t listed i figure i have to change the icon line.
Now i have altered it to "Icon=jdownloader" but it seems to have no effect.
Am I doing something wrong?

**Comment by ChuckDaniels87** [comment]
If you copy **.desktop** file to *$HOME/.local/share/applications/* and modify it you will override system configuration. Remember to refresh your desktop or log again into your session.

**Comment by elridion** [comment]
Thanks. Worked for me.
