### ISSUE TITLE
Icon for TeamViewer 9

### ISSUE THREAD

**Issue by cybre** [numixproject/numix-core#778]
Never have I liked reporting hardcoded icons but things must be done.
Icon = /opt/teamviewer9/tv_bin/desktop/teamviewer.png
Original icon:
![teamviewer](https://cloud.githubusercontent.com/assets/3101505/3029272/7a936eb2-e033-11e3-83ae-9994409f566e.png)

**Comment by erikdubois** [comment]
Hi 
just installed your theme
teamviewer-teamviewer10.desktop
this is the only icon that is now not in a circle.
i see it happened in the past with version 9

**Comment by zSTiK** [comment]
I can confirm.. TeamViewer icon does not work with TeamViewer 10 unfortunately.

**Comment by SimpleAnecdote** [comment]
@erikdubois @zSTiK : You must change TeamViewer's .desktop file in order to get the Numix icon (hence the 'hardcoded' label - see my earlier post on this thread for the exact line of code.

**Comment by zSTiK** [comment]
unfortunately that is not working.. I have to go to work though.. I'll tinker with it later.

**Comment by zSTiK** [comment]
OK I got it working.. TY :)

**Comment by Anaeijon** [comment]
Dear zSTiK,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icon for TeamViewer 9 (#778)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
